### ISSUE TITLE
Unhandled promise rejections and obscure deploy error message

### ISSUE THREAD

**Issue by mhartington** [firebase/firebase-tools#1012]
### Version info

```
$ firebase --version
6.0.1
```

### Platform Information

macOS 10.14

### Steps to reproduce

Attempt to deploy to hosting when the public folder does not exist. 

### Expected behavior

The unhandled promise rejection should be properly handled and a more better error message should be displayed.

### Actual behavior

```
$ firebase deploy

=== Deploying to 'startrack-ng'...

i  deploying hosting
i  hosting[startrack-ng]: beginning deploy...
i  hosting[startrack-ng]: found 0 files in www
✔  hosting[startrack-ng]: file upload complete
i  hosting[startrack-ng]: finalizing version...
(node:90935) UnhandledPromiseRejectionWarning: Error
    at new FirebaseError (/Users/mhartington/n/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Object.reject (/Users/mhartington/n/lib/node_modules/firebase-tools/lib/utils.js:67:31)
    at /Users/mhartington/n/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:48:26
    at arrayEach (/Users/mhartington/n/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/mhartington/n/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9344:14)
    at module.exports (/Users/mhartington/n/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:29:7)
    at _chain (/Users/mhartington/n/lib/node_modules/firebase-tools/lib/deploy/index.js:22:40)
    at /Users/mhartington/n/lib/node_modules/firebase-tools/lib/deploy/index.js:63:16
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:90935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:90935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bkendall** [comment]
If you have one, can you provide the contents of `firebase-debug.log`? I see some information here that should help us track it down, but it'll be more helpful if you can provide that file as well.

**Comment by bkendall** [comment]
I see where the error is coming from: https://github.com/firebase/firebase-tools/blob/v6.0.1/src/deploy/hosting/prepare.js#L60

The rejected promise is being returned inside a synchronous function `_.each`, so it's not really doing anything. I'll pass this along to the appropriate folks.

**Comment by bkendall** [comment]
Internal tracking number: 119425087

**Comment by jaysoncatacutan** [comment]
got the same issue, setup script on pipelines.

![screen shot 2018-11-15 at 1 12 44 am](https://user-images.githubusercontent.com/2920879/48499669-eb380400-e873-11e8-928f-eb097a064013.png)
