### ISSUE TITLE
Unable to "firebase deploy" version stuck on 3.17.7...

### ISSUE THREAD

**Issue by masonmahaffey** [firebase/firebase-tools#1033]
Just want to say up front thanks for the help! Not sure what's going on here but basically I believe my version is stuck on 3.17.7... and I'm not sure why. I'm unable to upgrade to >= 4.1.1 no matter what is tried. Thanks again!
 

### Version info
3.17.7

### Platform Information
MacOS - Mojave

### Steps to reproduce
npm uninstall -g firebase-tools
npm uninstall firebase-tools
npm install -g firebase-tools
firebase init
firebase deploy

### Expected behavior
(web app to be deployed to firebase hosting)

### Actual behavior

```
 Fri Nov 23 2018 22:27:16 GMT-0500 (Eastern Standard Time)
[2018-11-24T03:27:17.196Z] <<< HTTP RESPONSE 410 server=nginx, date=Sat, 24 Nov 2018 03:27:20 GMT, content-type=application/json; charset=utf-8, content-length=240, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, strict-transport-security=max-age=31556926; includeSubDomains; preload
[2018-11-24T03:27:17.197Z] <<< HTTP RESPONSE BODY undefined
[2018-11-24T03:27:17.198Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:45:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)

Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
`which firebase` will tell you at least where the `firebase-tools` you are using is located. Could you provide that? Or, you can look at the top of `firebase-debug.log` and it should have more information as well.

**Comment by masonmahaffey** [comment]
Ok, thanks! Yeah it says it's located in: /usr/local/bin/firebase

**Comment by bkendall** [comment]
@masonmahaffey I'm not sure of your setup, but you can use `which` and other tools to always track down where it's installed. `/usr/local/bin/firebase` will likely be a symbolic link somewhere - you can figure out where by using `ls -l /usr/local/bin/firebase`. That should help you figure how how it got installed (or, you can delete it manually). Hope that helps!

**Comment by Domiii** [comment]
Same issue here.

> OS: Mac v10.11.6
> Node v8.*

So this is what brought me here:

```
$ firebase --version
> 3.18.4
```

---

I tried @bkendall l's advice:

```
$ ls -l /usr/local/bin/firebase
> lrwxr-xr-x  1 domi  admin  47 May  3  2018 /usr/local/bin/firebase -> ../lib/node_modules/firebase-tools/bin/firebase
```

Then I kept going:
1. googled a bit and found [this NPM issue](https://github.com/npm/npm/issues/13956).
1. `rm -rf  /usr/local/lib/node_modules`
    * Turns out, this folder contains `npm` itself, and it only deleted some files including that version of `firebase-tools`. NPM seemed to survive. I would recommend just deleting the `firebase`-related sub folders instead: `rm -rf /usr/local/lib/node_modules/firebase*`
1. Either way: `firebase --version` finally stopped working.
1. `npm install -g firebase-tools`
1. IT STILL DID NOT WORK! 😖
1. Restarted Terminal
1. All good. :)
