### ISSUE TITLE
Can't use firebase cli serve and functions:shell at the same time.

### ISSUE THREAD

**Issue by sbadame** [firebase/firebase-tools#1035]
### Version info
6.1.1
### Platform Information
Linux
### Steps to reproduce
$ firebase serve
# In another shell..
$ firebase -p 7777 functions:shell --debug # Notice that the port isn't the same as serve!

### Expected behavior
firebase functions:shell to work or an error message telling me that you can't run `serve` and `functions:shell` at the same time. 

### Actual behavior
[2018-11-24T17:45:02.536Z] Command:       /usr/bin/node /home/sandro/.node/bin/firebase -p 7777 functions:shell --debug
[2018-11-24T17:45:02.540Z] CLI Version:   6.1.1
[2018-11-24T17:45:02.541Z] Platform:      linux
[2018-11-24T17:45:02.542Z] Node Version:  v8.11.1
[2018-11-24T17:45:02.543Z] Time:          Sat Nov 24 2018 12:45:02 GMT-0500 (EST)
[2018-11-24T17:45:02.544Z] ----------------------------------------------------------------------

[2018-11-24T17:45:02.629Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-11-24T17:45:02.632Z] > authorizing via signed-in user
[2018-11-24T17:45:02.634Z] [iam] checking project fermenter-220118 for permissions ["firebase.projects.get"]
[2018-11-24T17:45:02.654Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/fermenter-220118:testIamPermissions
 permissions=[firebase.projects.get]
[2018-11-24T17:45:03.313Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Sat, 24 Nov 2018 17:45:03 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
i  functions: Preparing to emulate functions.
[2018-11-24T17:45:07.602Z] Fetching environment
[2018-11-24T17:45:07.616Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/fermenter-220118

[2018-11-24T17:45:08.135Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Sat, 24 Nov 2018 17:45:08 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-24T17:45:08.140Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/90102997315:getServerAppConfig

[2018-11-24T17:45:08.439Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Sat, 24 Nov 2018 17:45:08 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-24T17:45:08.442Z] Starting @google-cloud/functions-emulator
Warning: You're using Node.js v8.11.1 but Google Cloud Functions only supports v6.11.5.
[2018-11-24T17:45:22.648Z] Parsing function triggers
[2018-11-24T17:45:28.746Z] Deploying functions locally
[2018-11-24T17:45:28.804Z] Error while deploying to emulator: Error: connect ECONNREFUSED 127.0.0.1:7778
Error: connect ECONNREFUSED 127.0.0.1:7778
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by rilian** [comment]
@sbadame sometimes node processes are stuck and take the port. You should try to run `ps aux|grep node` in Terminal and kill (`kill -9 PID`) everything related to node and your project and try again...

**Comment by bkendall** [comment]
+1 to @rilian's comment. Check to make sure no other processes are running. I tested this locally and can run both commands simultaneously as described. If you still have problems, feel free to re-open this issue.
