### ISSUE TITLE
Reduce firestore deletion batch size if we hit TRANSACTION_TOO_BIG

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1036]
Sometimes deleting a batch of documents can produce this error:

```
[2018-11-15T15:42:47.055Z] <<< HTTP RESPONSE BODY code=400, message=Transaction too big. Decrease transaction size., status=INVALID_ARGUMENT
[2018-11-15T15:42:47.056Z] Server error deleting doc batch Error
    at FirebaseError (/Users/phlipmode/.nvm/versions/node/v8.3.0/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at module.exports (/Users/phlipmode/.nvm/versions/node/v8.3.0/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/phlipmode/.nvm/versions/node/v8.3.0/lib/node_modules/firebase-tools/lib/api.js:37:35)
    at Request.self.callback (/Users/phlipmode/.nvm/versions/node/v8.3.0/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/phlipmode/.nvm/versions/node/v8.3.0/lib/node_modules/firebase-tools/node_modules/request/request.js:1161:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
```

Even if the batch contains less than 500 document IDs, if the total doc size and index entries are over 10MB this could happen.

In the short term we might want to add a batch_size flag to `firestore:delete` to allow developers to reduce this themselves.

In the long term we probably need to iteratively reduce the batch size and retry these requests.

**Comment by samtstern** [comment]
This is fixed by this PR:
https://github.com/firebase/firebase-tools/pull/2938

**Comment by jakeleventhal** [comment]
I'm getting this as well

**Comment by bkendall** [comment]
Could you open a new bug with the relavent details? It helps since this is new and closed - our triaging process won't re-surface the issue. Thanks!
