### ISSUE TITLE
Emulator cannot compare timestamp to request.time when testing security rules

### ISSUE THREAD

**Issue by morgs32** [firebase/firebase-tools#1041]
### Version info
@firebase/testing: 0.3.3
(and firebase: v3.9.1)

### Platform Information
OS X

### Steps to reproduce
1. Set up firestore emulator for testing locally
2. Load rules:
```
service cloud.firestore {
  match /databases/{database}/documents {
     match /{document=**} {
       allow update: requestData().attributes.updatedOn == request.time
     }
  }
}
```

In your test:
```
app.firestore().collection('stacks').doc('stack1').update({
    'id': 'LPLPbfueMqDyMJLxen7W',
    'type': 'stacks',
    'attributes': {
      'updatedOn': firebase.firestore.FieldValue.serverTimestamp()
    },
})
``` 
1. Then test an update.

### Expected behavior
The test should pass, the update should work

### Actual behavior
The update does not work.

**Comment by ryanpbrewster** [comment]
What version of `firebase-tools` are you using?

**Comment by ryanpbrewster** [comment]
These rules are improperly formed. Each "allow" expression must be preceded with an "if". `requestData()` is not a built-in function. `update` will only work if the provided document already exists. I _think_ the rules you want here are:

```
service cloud.firestore {
  match /databases/{database}/documents {
     match /{document=**} {
       allow write: if request.resource.data.attributes.updatedOn == request.time
     }
  }
}
```


[failing.js.txt](https://github.com/firebase/firebase-tools/files/2622516/failing.js.txt)
[passing.js.txt](https://github.com/firebase/firebase-tools/files/2622517/passing.js.txt)

**Comment by ryanpbrewster** [comment]
Please re-open this issue if this does not resolve the problems you're running into.

**Comment by morgs32** [comment]
@ryanpbrewster Sorry about that. Mine was a clumsy copy and paste from my own rules. `requestData()` was just a (pointless) function to return `request.resource.data` and yes I forgot the `if` at the start.

Anyway I'd be happy anyway if I could get your `passing.js` to work. It doesn't for me.
I'm using firebase-tools@6.1.1

```
(node:17130) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
{ FirebaseError: 7 PERMISSION_DENIED:
evaluation error at L5:30 for 'create' @ L5, evaluation error at L5:30 for 'update' @ L5, false for 'create' @ L5
    at new FirestoreError (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/@firebase/firestore/dist/index.node.cjs.js:348:28)
    at ClientDuplexStream.<anonymous> (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/@firebase/firestore/dist/index.node.cjs.js:6880:19)
    at ClientDuplexStream.emit (events.js:180:13)
    at ClientDuplexStream._emitStatusIfDone (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client.js:236:12)
    at ClientDuplexStream._receiveStatus (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client_interceptors.js:614:8)
    at /Users/morganintrator/GitHub/stackshirts/node_modules/@firebase/testing/node_modules/grpc/src/client_interceptors.js:1110:18
  code: 'permission-denied',
  name: 'FirebaseError',
  toString: [Function] }
```

Anything else I can tell you? Thanks!!

**Comment by ryanpbrewster** [comment]
Let me test this on my macbook to make sure this isn't a platform difference.

**Comment by ryanpbrewster** [comment]
It works on my macbook. Do me a favor and try changing the rules to `allow write;`, with no qualifications. That should _definitely_ pass. If it doesn't, that tells us something else is going on.

I expanded my example a bit to make sure it was working, I'll attach it below, along with my `package.json`.

[passing.js.txt](https://github.com/firebase/firebase-tools/files/2622813/passing.js.txt)
[package.json.txt](https://github.com/firebase/firebase-tools/files/2622816/package.json.txt)

**Comment by morgs32** [comment]
And you are running `firebase serve --only firestore` for an emulator? I know I'm asking you to hold my hand! But just to be sure.

**Comment by ryanpbrewster** [comment]
Correct. On my macbook I have
 - `firebase --version == 6.1.1`
 - `node --version` == 9.8.0

I've attached a screenshot with a bit more info.
![screen shot 2018-11-27 at 8 30 12 pm](https://user-images.githubusercontent.com/1649989/49129156-68577600-f283-11e8-96b1-0563d19d48e8.png)

**Comment by morgs32** [comment]
Well I'm stumped! Same everything?!

![image](https://user-images.githubusercontent.com/1364795/49129771-ed438f00-f285-11e8-9980-11681977f1c9.png)

**Comment by ryanpbrewster** [comment]
Very interesting, there must be something subtle happening here. I hope you don't mind if I ask a few follow-up questions, I'm curious about the root cause.

What version of java are you running (`java -version`)?

If you change `updatedOn == request.time` to `updatedOn < request.time` or `updatedOn > request.time`, does it pass?

**Comment by morgs32** [comment]
No problem!

For java:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

And this passes:
```
allow write: if request.resource.data.attributes.updatedOn > request.time
```

Not this:
```
allow write: if request.resource.data.attributes.updatedOn < request.time
```

**Comment by ryanpbrewster** [comment]
Interesting. My working hypothesis is that this is a Java issue. I'm running java 8 on my macbook, and we've had another report of Java 10 incompatibilities (https://github.com/firebase/firebase-tools/issues/1010). For now you may want to try downgrading to java 8 or java 9.

**Comment by ryanpbrewster** [comment]
Confirmed, if I run the emulator with openjdk 11 I get the same behavior you're reporting.

**Comment by morgs32** [comment]
I see! I'll do that and sleep a little better tonight. Thanks a lot for sleuthing that out!

**Comment by ryanpbrewster** [comment]
Traced it down and found a fix. Should have a new release later this week. Thanks for raising this issue!
