### ISSUE TITLE
Set environment variables during firebase deploy (and possibly in runtime)

### ISSUE THREAD

**Issue by dwatrous** [firebase/firebase-tools#1046]
### Version info
root@fc19e6bca144:/appfiles# firebase --version
6.1.1

### Platform Information
Linux

### Steps to reproduce
Create a function that uses node-config (possibly many other modules) and that requires resource files in order to function (in this case node-config also allows an environment variable to indicate where resource files are).

Assuming a file `config/default.json`
```
{"emoji": ":-)"}
```

Assuming a file `index.js`
```
const config = require('config');

exports.helloWorld = functions.https.onRequest((req, res) => {
  res.status(200).send('Hello, World!' + config.get('emoji'));
});
```

Run the command `firebase deploy --only functions`

### Expected behavior

I expect it to deploy the function.

### Actual behavior

```
root@fc19e6bca144:/appfiles# firebase --debug deploy --only functions
[2018-11-29T15:58:19.802Z] ----------------------------------------------------------------------
[2018-11-29T15:58:19.809Z] Command:       /usr/local/bin/node /usr/local/bin/firebase --debug deploy --only functions
[2018-11-29T15:58:19.809Z] CLI Version:   6.1.1
[2018-11-29T15:58:19.809Z] Platform:      linux
[2018-11-29T15:58:19.810Z] Node Version:  v11.1.0
[2018-11-29T15:58:19.810Z] Time:          Thu Nov 29 2018 15:58:19 GMT+0000 (Coordinated Universal Time)
[2018-11-29T15:58:19.811Z] ----------------------------------------------------------------------

[2018-11-29T15:58:19.828Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-11-29T15:58:19.829Z] > authorizing via signed-in user
[2018-11-29T15:58:19.829Z] [iam] checking project familybank-51a57 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2018-11-29T15:58:19.832Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/familybank-51a57:testIamPermissions  
 permissions=[cloudfunctions.functions.create, cloudfunctions.functions.delete, cloudfunctions.functions.get, cloudfunctions.functions.list, cloudfunctions.functions.update, cloudfunctions.operations.get, firebase.projects.get]
[2018-11-29T15:58:20.100Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:17 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close

=== Deploying to 'familybank-51a57'...

i  deploying functions
[2018-11-29T15:58:24.097Z] > [functions] package.json contents: {
  "name": "familybank",
  "description": "Familiy Bank Cloud Functions for Firebase",
  "author": "Daniel Watrous",
  "version": "0.0.1",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "test": "mocha --reporter spec"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "actions-on-google": "^2.4.1",
    "auth0": "^2.13.0",
    "firebase-admin": "^6.1.0",
    "firebase-functions": "^2.1.0",
    "format-currency": "^1.0.0",
    "chai": "^4.2.0",
    "sinon": "^7.1.1",
    "config": "^3.0.0"
  },
  "private": true,
  "devDependencies": {
    "firebase-functions-test": "^0.1.4",
    "mocha": "^5.2.0"
  }
}
i  functions: ensuring necessary APIs are enabled...
[2018-11-29T15:58:24.098Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/familybank-51a57?view=CONSUMER_VIEW  
 
[2018-11-29T15:58:24.100Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/familybank-51a57?view=CONSUMER_VIEW  
 
[2018-11-29T15:58:24.808Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-29T15:58:25.031Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
✔  functions: all necessary APIs are enabled
[2018-11-29T15:58:25.033Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/familybank-51a57  
 
[2018-11-29T15:58:25.232Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-29T15:58:25.233Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/470104770445:getServerAppConfig  
 
[2018-11-29T15:58:25.406Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:22 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
i  functions: preparing functions directory for uploading...
[2018-11-29T15:58:25.418Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/familybank-51a57/configs  
 
[2018-11-29T15:58:25.595Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:23 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-29T15:58:25.596Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/familybank-51a57/configs/familybank/variables  
 
[2018-11-29T15:58:26.098Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:23 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-29T15:58:26.099Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/familybank-51a57/configs/familybank/variables/auth0/clientid  
 
[2018-11-29T15:58:26.100Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/familybank-51a57/configs/familybank/variables/auth0/domain  
 
[2018-11-29T15:58:26.256Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:23 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-29T15:58:26.258Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 29 Nov 2018 15:58:23 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close

Error: Error occurred while parsing your function triggers.

Error: Configuration property "dialogflow.intents.welcome_user" is not defined
    at Config.get (/appfiles/functions/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/appfiles/functions/index.js:39:19)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:20:15
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:58:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

### Analysis

I found that the failure occurred in triggerParser.js at the point where it `require`d the functions directory. The root cause appears to be due to node-config using the current directory to find the config folder, which is actually in the functions folder. 

#### Workaround attempt 1
The node-config library does provide a way to modify this behavior by setting the `NODE_CONFIG_DIR` environment variable. I set this environment variable and tried the build again, but I found that the firebase CLI modifies `process.env`, so the environment variable I set was never seen by the script and the Deploy still failed.

#### Workaround attempt 2
I can duplicate the config directory in the root folder, which allows the Deploy to succeed. The duplicate config folder and file(s) is only needed for the `require` step in triggerParser.js.

#### Workaround attempt 3
I modified triggerParser.js so that it set `process.env.NODE_CONFIG_DIR="./functions/config"`, and the build worked as expected. This suggests that if the firebase CLI retained environment variables in `process.env`, the Deploy would work by just setting the node-config environment variable.

### Conclusion

I still don't have a working solution for my automated build/deploy pipeline, other than committing a duplicate config folder in my repository.

**Comment by dwatrous** [comment]
I have found that this is where we lose environment variables
https://github.com/firebase/firebase-tools/blob/78f11b62ab658a5a59b291daad7ea5ee08b2bc34/src/parseTriggers.js#L30

When fork creates a new process, all it receives are the environment variables built into `env`. So it's not modifying them, it just doesn't carry them over to the new forked process.

**Comment by dwatrous** [comment]
This could be fixed by https://github.com/dwatrous/firebase-tools/commit/3cfe473561cf53e8c4dd4a5fc252e6e5ddd14d8d

**Comment by bkendall** [comment]
As mentioned in Slack - would you mind making a PR for this? 😄

**Comment by SantiMA10** [comment]
One question, can this environment variable copy make that all the env vars are available in the Firebase Cloud Functions env?

**Comment by RaviH** [comment]
Any update on this? This has been open since 2018!

**Comment by taeold** [comment]
This should now be possible via [parametrized config](https://firebase.google.com/docs/functions/config-env)
