### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by muthugit** [firebase/firebase-tools#1076]
### Steps to reproduce

1. deploy the firebase
2. Got the successful message
3. Re-deploy the firebase
4. Got this error

firebase
/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:13504
        path = castPath(path, object!;
                              ^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)

### Expected behavior
Firebase hosting to be deployed

### Actual behavior

firebase
/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:13504
        path = castPath(path, object!;
                              ^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by muthugit** [comment]
Resolved the issue by changed the symbol `!` to `)` in `/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js` line number: 13504

**Comment by samtstern** [comment]
Sounds like you resolved it yourself @muthugit , so closing this.
