### ISSUE TITLE
firebase use --add and firebase list not showing any project

### ISSUE THREAD

**Issue by micksatana** [firebase/firebase-tools#1098]
### Version info
6.2.2

### Platform Information
OS X

### Steps to reproduce
firebase use --add

### Expected behavior
Expected to display `? Which project do you want to add?` and see some projects

### Actual behavior
Display `? Which project do you want to add?` without any projects

Here is the log
```
[2019-01-10T05:14:42.513Z] ----------------------------------------------------------------------
[2019-01-10T05:14:42.516Z] Command:       /Users/mick/.nvm/versions/node/v10.4.0/bin/node /Users/mick/.nvm/versions/node/v10.4.0/bin/firebase use --add --debug
[2019-01-10T05:14:42.516Z] CLI Version:   6.2.2
[2019-01-10T05:14:42.516Z] Platform:      darwin
[2019-01-10T05:14:42.517Z] Node Version:  v10.4.0
[2019-01-10T05:14:42.517Z] Time:          Thu Jan 10 2019 12:14:42 GMT+0700 (Indochina Time)
[2019-01-10T05:14:42.518Z] ----------------------------------------------------------------------

[2019-01-10T05:14:42.526Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-01-10T05:14:42.528Z] > authorizing via signed-in user
[2019-01-10T05:14:42.531Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects

[2019-01-10T05:14:43.621Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 10 Jan 2019 05:14:43 GMT, content-type=application/json; charset=utf-8, content-length=15, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
```

Note:
- This problem just happen this morning. Yesterday still deploy without any problem.
- `firebase use --add` not showing any project but in my firebase console can see all projects
- Already cleared `firebase use --clear` and tried `firebase login`
- Already tried `firebase login --reauth` and confirmed the correct account being selected.
- Already tried change Node.js to v8.9.4, no luck
- After run `firebase use --add` if I hit arrow down and enter. I'll get the following error. (Should not be a root cause though. Just hope it helps scope down problem)
- Possibly the same problem as #529 
```
[2019-01-10T05:38:28.643Z] TypeError: Cannot read property 'short' of undefined
    at Prompt.render (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/inquirer/lib/prompts/list.js:94:69)
    at Prompt.onSubmit (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/inquirer/lib/prompts/list.js:116:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver._onNext (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:4234:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/mick/.nvm/versions/node/v8.9.4/lib/node_modules/firebase-tools/node_modules/rx-lite/rx.lite.js:1469:31)
```
![project-listing-issue](https://user-images.githubusercontent.com/1315909/50959306-375e9800-14f5-11e9-9baa-488eea159f6b.jpg)

**Comment by micksatana** [comment]
Seem `firebase use` getting projects from [getProjects method in api.js](https://github.com/firebase/firebase-tools/blob/1386ad74737ac59a6ce780efe80964bc44c20e6a/src/api.js#L235)

Already submitted the support form in Firebase Console just in case it's an issue in the API. I also notice even the project listing field in the support form also not listing my projects. If I can confirm, it's not `firebase-tools` issue, I'll close this.

![project-listing-issue-1](https://user-images.githubusercontent.com/1315909/50959675-121e5980-14f6-11e9-944b-ef629fbc3f13.jpg)

**Comment by bkendall** [comment]
To be sure, you don't have something like `GOOGLE_APPLICATION_CREDENTIALS` or anything else set in your environment that could accidentally be authenticating your request?

**Comment by micksatana** [comment]
Hi @bkendall Thank you for suggestion. I don't use any environment variable that Google or Firebase might be using.

**Comment by micksatana** [comment]
To summarize, in case other people facing this issue, `firebase use --add` and `firebase list` not showing projects BUT there are projects in Firebase Console.

First, try `firebase login` and make sure correct account being selected, just to be sure it's not a simple mistake.
Second, you should make sure you're not using environment variables that `firebase-tools` using for example `GOOGLE_APPLICATION_CREDENTIALS` and `FIREBASE_TOKEN` as suggested by bkendall  and mbleigh.

If both points checked and not the root cause, you may want to directly [contact Firebase support via the Firebase Console](https://firebase.google.com/support/contact/?category=troubleshooting). They will help check on their side whether anything goes wrong.

![fixed-firebase-issue](https://user-images.githubusercontent.com/1315909/51010985-337c5580-1589-11e9-87c3-0fb3ac346b44.jpg)

In my case, I can confirm the issue not in `firebase-tools` code but happened on API side as I did not change anything on my local since last deployment (2 days ago before problem appeared) until now (after problem solved). Similarly other cases found on StackOverflow, reported they wait until problem solved itself, [some took a day](https://stackoverflow.com/questions/50381048/new-project-not-showing-up-firebase-cli/50385251), some took a week.
