### ISSUE TITLE
Error launching Realtime Database Emulator

### ISSUE THREAD

**Issue by brianchirls** [firebase/firebase-tools#1105]
### Version info
firebase: 6.2.2
node: v11.6.0
java version: 1.7.0_76
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

### Platform Information

OS X

### Steps to reproduce

I'm trying to run the [Realtime Database Emulator](https://firebase.google.com/docs/database/security/test-rules-emulator) with the following command:

`firebase serve --only database`

I have already installed the emulator with this command:

`firebase setup:emulators:database`

### Expected behavior

Emulator should run.

### Actual behavior

The following error message displays in the terminal:

```
[2019-01-13T23:16:50.143Z] ----------------------------------------------------------------------
[2019-01-13T23:16:50.147Z] Command:       /usr/local/Cellar/node/11.6.0/bin/node /usr/local/bin/firebase serve --debug --only database
[2019-01-13T23:16:50.147Z] CLI Version:   6.2.2
[2019-01-13T23:16:50.147Z] Platform:      darwin
[2019-01-13T23:16:50.147Z] Node Version:  v11.6.0
[2019-01-13T23:16:50.148Z] Time:          Sun Jan 13 2019 18:16:50 GMT-0500 (Eastern Standard Time)
[2019-01-13T23:16:50.148Z] ----------------------------------------------------------------------

⚠  database: Exception in thread "main" 
⚠  database: java.lang.UnsupportedClassVersionError: com/firebase/server/forge/App : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)


Error: database: emulator has exited with code: 1
```

**Comment by brianchirls** [comment]
Yeah, I think so, since that's where the installation instructions are.

Might not hurt to present a warning after installation if the detected java version isn't right. Or even at run time instead of throwing that error.

**Comment by ryanpbrewster** [comment]
I submitted a documentation update, it should be released sometime this week. Thanks for your help 👍

**Comment by brianchirls** [comment]
Great. Thanks!

**Comment by nicosemp** [comment]
@ryanpbrewster was it updated? I couldn't find any mention of it at your link:

> Where do you think the best place for a note like this would be? [This documentation](https://firebase.google.com/docs/database/security/test-rules-emulator)?

**Comment by samtstern** [comment]
@ryanpbrewster you can leave Firebase but you can never leave the Emulator Suite on GitHub!!!!!
