### ISSUE TITLE
need sudo permission for firebase deploy, even if npm package is installed with normal user permissions

### ISSUE THREAD

**Issue by neerajyadav** [firebase/firebase-tools#1136]
Even though I installed `firebase-tools` without `sudo`, I need to use `sudo` permission while running `firebase serve`. Earlier it used to work without `sudo`, but now not. I'm using `nvm`. Here are the environment config.
- `nvm` - `0.33.11`
- `node` - `v10.11.0`
- `firebase-tools` - `6.3.0`
- I recently updated my os. os version is `macOS Mojave 10.14.4 Beta`. I don't know file permission read issue arise due to os upgrade.

Here is the error from `firebase-debug.log`.
``` log
[info] i  functions: Preparing to emulate functions.
[debug] [2019-01-30T09:54:05.574Z] Fetching environment
[debug] [2019-01-30T09:54:05.975Z] Error: EACCES: permission denied, open '/Users/a/.config/gcloud/application_default_credentials.json'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1168:35)
    at module.exports (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/ensureDefaultCredentials.js:28:8)
    at FunctionsEmulator.start (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/functionsEmulator.js:106:5)
    at Object.start (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/serve/index.js:15:23
    at arrayMap (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/serve/index.js:13:26)
    at Command.module.exports.Command.description.option.option.option.option.before.action [as _action] (/Users/a/.nvm/versions/node/v10.11.0/lib/node_modules/firebase-tools/lib/commands/serve.js:55:12)
[error] 
[error] Error: An unexpected error has occurred.
```
Here is the output of `ls -al`. 

`-rw-r--r--  1 root  staff  258 Jan 31 13:12 /Users/a/.config/gcloud/application_default_credentials.json`

**Comment by neerajyadav** [comment]
I tried to delete the file `application_default_credentials.json`. Did `firebase logout` and then again did `firebase login`, hoping the file will be created with `staff` permissions this time.

But still it is created with `root` access and not able to `deploy` without `sudo`.

**Comment by mbleigh** [comment]
The Firebase CLI does create `application_default_credentials.json`, but only as the current user. Are you running the Firebase CLI as root? If so, you should try to fix your NPM permissions so that you can run it as your own user.

Have you tried `chown` on the file to make it owned by yourself instead?

**Comment by jnorkus** [comment]
I am experiencing the same issue.

**Comment by ilorez** [comment]
this link fix my problem:
https://betterstack.com/community/questions/how-to-fix-npm-sudo-error/
