### ISSUE TITLE
Error when deploying the project without the "database.rules.json" file

### ISSUE THREAD

**Issue by pablomargareto** [firebase/firebase-tools#1153]
### [REQUIRED] Environment info

**firebase-tools:**
6.0.1

**Platform:**
macOS

### [REQUIRED] Test case

Deploy your firebase app without the file database.rules.json

### [REQUIRED] Steps to reproduce
firebase deploy

### [REQUIRED] Expected behavior
It should throw an error like: "database.rules.json must be present in order to deploy your app"
...or, it should not crash at all and deploy the app. NOTE: Some apps do not use "Realtime database", and they use "Firestore" instead

### [REQUIRED] Actual behavior
```
[info] i  deploying database, storage, firestore, functions, hosting
[debug] [2019-02-22T12:32:51.763Z] Error: ENOENT: no such file or directory, open '/Users/pablo/webs/hvaskjer/database.rules.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Config.readProjectFile (/usr/local/lib/node_modules/firebase-tools/lib/config.js:143:26)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/database/prepare.js:42:50
    at /usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:2996:24)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9344:14)
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/deploy/database/prepare.js:39:7)
    at _chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:22:40)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
Thanks for the report. Fix submitted in the PR above.
