### ISSUE TITLE
NPM install failed, continuing with Firebase initialization...

### ISSUE THREAD

**Issue by ricardolousada** [firebase/firebase-tools#1183]
**firebase-tools: instalation did not finnish but it's 3.13.1 

**Platform: macOS High Sierra 

### [REQUIRED] Test case
```
WARN deprecated joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

> grpc@1.6.6 install /Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.6.6/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.6.6 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.6.6/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.6.6 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/src/core/lib/surface/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64"
gyp ERR! cwd /Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node --module_name=grpc_node --module_path=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64' (1)
node-pre-gyp   CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_args.o
ERR! stack     at ChildProcess.<anonymous> (/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node --module_name=grpc_node --module_path=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64' (1)
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack.o to exec install script
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack_builder.o install script
In file included from ../src/core/lib/channel/channel_stack_builder.c:19: to exec install script
In file included from .././src/core/lib/channel/channel_stack_builder.h:24:
In file included from .././src/core/lib/channel/channel_args.h:22:
../include/grpc/compression.h:27:10: fatal error: 'grpc/slice.h' file not found
#include <grpc/slice.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/src/core/lib/channel/channel_stack_builder.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64"
gyp ERR! cwd /Users/rlousada/Documents/Developer/react-native/BNDEV/functions/node_modules/firebase-admin/node_modules/grpc
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN firebase-functions@0.7.5 requires a peer of firebase-admin@~5.5.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.6.6 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rlousada/.npm/_logs/2019-04-06T16_08_44_753Z-debug.log

NPM install failed, continuing with Firebase initialization...

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```

**Comment by bkendall** [comment]
`3.13.1` is a _very_ old version. Please upgrade your version of [`firebase-tools`](http://npmjs.com/package/firebase-tools) as recent versions have included many fixes.
