### ISSUE TITLE
Error deploying function in Cloud Build

### ISSUE THREAD

**Issue by cdock1029** [firebase/firebase-tools#1201]
### Environment info

**firebase-tools:**
6.6.0

**Platform:**
macOS, Google Cloud Build

### Test case

`firebase.json`
```json
  "functions": {
    "source": "packages/functions",
    "predeploy": [
      "yarn --cwd \"$RESOURCE_DIR\" run lint",
      "yarn --cwd \"$RESOURCE_DIR\" run build"
    ]
  }
```

`index.ts`
```ts
import * as functions from 'firebase-functions'
import { admin } from './deps'

export const preventAuth = functions.auth.user().onCreate(async (user, _) => {
  await admin.auth().deleteUser(user.uid)
  console.log(`deleted user=[${user.uid}], email=[${user.email}]`)
})
```

### Steps to reproduce

Deploying locally works fine.

When a build trigger on Cloud Build tries to deploy exact same code, I get an error.

### Expected behavior

Deploy result same locally as on cloud build.

### Actual behavior

```
Step #1: 
Step #1: Error: Error occurred while parsing your function triggers.
Step #1: 
Step #1: /workspace/packages/functions/lib/index.js:13
Step #1: exports.preventAuth = functions.auth.user().onCreate(async (user, _) => {
Step #1: ^
Step #1: 
Step #1: SyntaxError: Unexpected token (
Step #1: at createScript (vm.js:56:10)
Step #1: at Object.runInThisContext (vm.js:97:10)
Step #1: at Module._compile (module.js:549:28)
Step #1: at Object.Module._extensions..js (module.js:586:10)
Step #1: at Module.load (module.js:494:32)
Step #1: at tryModuleLoad (module.js:453:12)
Step #1: at Function.Module._load (module.js:445:3)
Step #1: at Module.require (module.js:504:17)
Step #1: at require (internal/module.js:20:19)
Step #1: at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
Finished Step #1
```

**Comment by cdock1029** [comment]
The Dockerfile used to build `firebase-tools` container had listed the improper version of node (6) instead of 8, so deploying node-8 functions would error.

Fixed Docker file for `firebase-tools` submitted to Google Container Registry:

```dockerfile
FROM node:carbon
RUN npm install -g firebase-tools

ENTRYPOINT ["/usr/local/bin/firebase"]
```
