### ISSUE TITLE
`firebase init` fails on latest version of Node / npm

### ISSUE THREAD

**Issue by myspivey** [firebase/firebase-tools#122]
On running 'firebase init' on the latest node/npm receive the following error. This can be resolved by stepping back versions. I was able to step back to node 4.2.3 and npm 2.14.7 and get it to run. Failed on Node 5.4.1, npm 3.5.3.

module.js:327
    throw err;
    ^

Error: Cannot find module 'wcwidth'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/Data/.nvm/versions/node/v5.4.1/lib/node_modules/firebase-tools/node_modules/cli-table/lib/utils.js:10:15)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by jwngr** [comment]
Thanks for alerting us of this issue. We probably need to update our dependencies here. We will take a look. For the time being, you'll probably just have to use an older version of Node / npm. Sorry for the inconvenience!

**Comment by Pohaki** [comment]
Hello,
I fix this error,
install the npm modules wcwidth directly in this folder : 
`cd  /Volumes/Data/.nvm/versions/node/v5.4.1/lib/node_modules/firebase-tools/node_modules/`
with :
`sudo npm install wcwidth --save `
It's working for me.
