### ISSUE TITLE
emulator:start crashes without error when firestore.rules is not found

### ISSUE THREAD

**Issue by JakeHedman** [firebase/firebase-tools#1254]
### [REQUIRED] Environment info

**firebase-tools:** 6.9.0

**Platform:** Arch Linux

### [REQUIRED] Test case
```sh
mv firestore.rules firestores.rules.notfound
firebase setup:emulators:firestore
firebase emulators:start --only firestore
```

### [REQUIRED] Steps to reproduce
0. Set an incorrect firestore.rules path in `firebase.json`
1. Install the firestore emulator
2. Start the firestore emulator using `emulators:start` or `emulators:exec`

### [REQUIRED] Expected behavior
Should show helpful error message

### [REQUIRED] Actual behavior
Command crashes, the log file is empty.
Output:
```
i  Starting emulators: ["firestore"]
i  firestore: Logging to firestore-debug.log

Error: firestore: emulator has exited with code: 1
```

```
2019-05-08T05:08:50.712Z] ----------------------------------------------------------------------
[2019-05-08T05:08:50.714Z] Command:       /usr/bin/node /usr/bin/firebase emulators:start --only firestore --debug
[2019-05-08T05:08:50.714Z] CLI Version:   6.9.0
[2019-05-08T05:08:50.714Z] Platform:      linux
[2019-05-08T05:08:50.714Z] Node Version:  v11.15.0
[2019-05-08T05:08:50.715Z] Time:          Wed May 08 2019 07:08:50 GMT+0200 (Central European Summer Time)
[2019-05-08T05:08:50.715Z] ----------------------------------------------------------------------

[2019-05-08T05:08:50.721Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-08T05:08:50.721Z] > authorizing via signed-in user
[2019-05-08T05:08:50.723Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/xxx  
 
i  Starting emulators: ["firestore"]
[2019-05-08T05:08:51.676Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Wed, 08 May 2019 05:08:51 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=877, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-08T05:08:51.689Z] Starting emulator firestore with args {"host":"localhost","port":5002,"rules":"firestore/firestore.rules"}
i  firestore: Logging to firestore-debug.log
[2019-05-08T05:08:51.873Z] Exception in thread "main" 
[2019-05-08T05:08:51.874Z] java.io.FileNotFoundException: firestore/firestore.rules (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:131)
	at com.google.common.io.Files$FileByteSource.read(Files.java:161)

[2019-05-08T05:08:51.874Z] 	at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:512)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:64)


Error: firestore: emulator has exited with code: 1

Having trouble? Try firebase emulators:start --help

```

**Comment by samtstern** [comment]
Thanks for the report @JakeHedman we should make that crash with a better error and make sure it's not using the default values when it shouldn't.

**Comment by samtstern** [comment]
A fix for this has been merged and will be included in the next release.
