### ISSUE TITLE
verifyDeveloperNodeModules() fails due to package.json resolution issue on Windows

### ISSUE THREAD

**Issue by rmkl** [firebase/firebase-tools#1258]
### [REQUIRED] Environment info
Firebase-tools 6.9.0

**firebase-tools: 6.9.0**

**Platform: Windows 10 Pro**

### [REQUIRED] Test case
https://stackoverflow.com/questions/56030342/firebase-unable-to-serve-local-function-after-upgrading-to-6-9-0/56040351#56040351

### [REQUIRED] Steps to reproduce
I followed the steps to set up Cloud Functions: https://firebase.google.com/docs/functions/get-started
Then I wanted to test locally: https://firebase.google.com/docs/functions/local-emulator
When I try to run: firebase emulators:start there is a crash

### [REQUIRED] Expected behavior
A firebase prompt to run functions locally
A URL to run functions locally in the browser

### [REQUIRED] Actual behavior
A crash occurs. Note that 'firebase functions:shell' doesn't work either, same problem as reported in https://github.com/firebase/firebase-tools/issues/1243

λ firebase.cmd serve --only functions:upload
+  functions: Using node@12 from host.
+  functions: Emulator running at http://localhost:5001
i  functions: Beginning execution of "upload"
!  Error: Cannot find module 'package.json'
Require stack:
- C:\Users\MyLocalUsername\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at verifyDeveloperNodeModules (C:\Users\MyLocalUsername\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:125:32)
    at C:\Users\MyLocalUsername\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:457:26
    at Generator.next (<anonymous>)
    at C:\Users\MyLocalUsername\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\MyLocalUsername\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
!  Your function was killed because it raised an unhandled error.

**Comment by seven-dev** [comment]
It works on MacOS but not on windows. This line fails to find the package.json's path.
`
const modPackageJSON = require(path.join(functionsEmulatorShared_1.findModuleRoot(modBundle.name, modResolution), "package.json"));
// functionsEmulatorShared_1.findModuleRoot(modBundle.name, modResolution) <-- this part
`

**Comment by Ciberusps** [comment]
#1242

**Comment by samtstern** [comment]
Thanks @seven-dev that's a very interesting observation!

cc @abehaskins looks like a Windows path problem with our resolver

**Comment by abehaskins** [comment]
`findModuleRoot` splits on [`"/"`](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulatorShared.ts#L149), this does not work cross platform and will break `package.json` resolution on Windows.

**Comment by shaji-Dev** [comment]
This happens to me as well, please fix, I can't run my functions locally.

**Comment by abeisgoat** [comment]
@shaji-Dev feel free to downgrade to `6.8.0` until the fix is released.

**Comment by shaji-Dev** [comment]
> @shaji-Dev feel free to downgrade to `6.8.0` until the fix is released.

Thank you, that's what I've done eventually and it worked.

**Comment by samtstern** [comment]
Fixed by #1263

**Comment by samtstern** [comment]
Version `6.9.2` has been released with this fix.

**Comment by shaji-Dev** [comment]
With 6.9.2 I'm getting this error:

!  Error: Cannot find module '..\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64\grpc_node.node'
Require stack:
- ..\node_modules\grpc\src\grpc_extension.js
- ..\node_modules\grpc\src\client.js
- ..\node_modules\grpc\index.js
- ..\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Shaji\node_modules\grpc\src\grpc_extension.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
!  Your function was killed because it raised an unhandled error.
