### ISSUE TITLE
Cloud Functions requires the module "firebase-functions-set"

### ISSUE THREAD

**Issue by jefrydco** [firebase/firebase-tools#1266]
### [REQUIRED] Environment info

**firebase-tools:** 6.9.1

**Platform:** Fedora 30

### [REQUIRED] Test case

Work on default project from `firebase init` command

### [REQUIRED] Steps to reproduce

1. Run `firebase serve --only functions` with `index.js` containing user on create event.
2. `firebase-functions-test` is installed.

### [REQUIRED] Expected behavior

Warning
```
The Cloud Functions emulator requires the module "firebase-functions-test" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory.
```
shouldn't appear.

### [REQUIRED] Actual behavior

```
[2019-05-10T06:48:30.966Z] ----------------------------------------------------------------------
[2019-05-10T06:48:30.974Z] Command:       /home/jefrydco/.nvm/versions/node/v10.15.3/bin/node /home/jefrydco/.yarn/bin/firebase serve --only functions --debug
[2019-05-10T06:48:30.974Z] CLI Version:   6.9.1
[2019-05-10T06:48:30.975Z] Platform:      linux
[2019-05-10T06:48:30.975Z] Node Version:  v10.15.3
[2019-05-10T06:48:30.975Z] Time:          Fri May 10 2019 13:48:30 GMT+0700 (Western Indonesia Time)
[2019-05-10T06:48:30.975Z] ----------------------------------------------------------------------

[2019-05-10T06:48:30.989Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-10T06:48:30.990Z] > authorizing via signed-in user
[2019-05-10T06:48:30.990Z] [iam] checking project reblood-pwa for permissions ["firebase.projects.get"]
[2019-05-10T06:48:30.993Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/reblood-pwa:testIamPermissions  
 permissions=[firebase.projects.get]
[2019-05-10T06:48:32.357Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 06:48:32 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=1090, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-10T06:48:32.360Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/reblood-pwa  
 
[2019-05-10T06:48:33.670Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 06:48:33 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=1153, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
⚠  Your requested "node" version "8" doesn't match your global version "10"
[2019-05-10T06:48:33.682Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/366013164330:getServerAppConfig  
 
[2019-05-10T06:48:34.076Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 06:48:34 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/mnt/Data/Projects/Reblood/reblood-pwa-v2/functions" for Cloud Functions...
[2019-05-10T06:48:34.878Z] Functions runtime initialized.
[2019-05-10T06:48:34.879Z] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"protect_env":true,"admin_stubs":true}
⚠  The Cloud Functions emulator requires the module "firebase-functions-test" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)
```

**Comment by abeisgoat** [comment]
This is the same issue as #1262 and will be fixed once #1263 is merged and released.

**Comment by samtstern** [comment]
Version `6.9.2` has been released with this fix.

**Comment by KcPele** [comment]
!  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
!  External network resource requested!
   - URL: "http://169.254.169.254/computeMetadata/v1/instance"
 - Be careful, this may be a production service.
!  External network resource requested!
   - URL: "http://metadata.google.internal./computeMetadata/v1/instance"
 - Be careful, this may be a production service.
>  Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
>      at GoogleAuth.getApplicationDefaultAsync (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
>      at processTicksAndRejections (internal/process/task_queues.js:93:5)
>      at async GoogleAuth.getClient (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
>      at async GrpcClient._getCredentials (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-gax\build\src\grpc.js:92:24)
>      at async GrpcClient.createStub (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-gax\build\src\grpc.js:213:23)
i  functions: Finished "createScream" in ~1s

**Comment by KcPele** [comment]
please i need help. how do i fix these
!  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
!  External network resource requested!
   - URL: "http://169.254.169.254/computeMetadata/v1/instance"
 - Be careful, this may be a production service.
!  External network resource requested!
   - URL: "http://metadata.google.internal./computeMetadata/v1/instance"
 - Be careful, this may be a production service.
>  Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
>      at GoogleAuth.getApplicationDefaultAsync (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
>      at processTicksAndRejections (internal/process/task_queues.js:93:5)
>      at async GoogleAuth.getClient (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
>      at async GrpcClient._getCredentials (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-gax\build\src\grpc.js:92:24)
>      at async GrpcClient.createStub (C:\Users\userpc\Desktop\Oriamo-Function\functions\node_modules\google-gax\build\src\grpc.js:213:23)
i  functions: Finished "createScream" in ~1s
