### ISSUE TITLE
Emulator hot-reloading doesn't ignore "node_modules"

### ISSUE THREAD

**Issue by ItangSanjana** [firebase/firebase-tools#1274]
### Environment info
Command:       `/usr/bin/node /home/[user]/.npm-global/bin/firebase serve`
CLI Version:   `6.9.2`
Platform:      `linux`
Node Version:  `v10.15.3`
Time:          `Sat May 11 2019 12:15:20 GMT+0700 (Western Indonesia Time)`

### Test case
Run command `firebase serve`

### Steps to reproduce
Update firebase tools `npm i -g firebase-tools`
Run command `firebase serve`

### Expected behavior
`Emulator started at http://localhost:5001`
`Serving hosting files from: [public]`

### Actual behavior
        Error: An unexpected error has occurred.

        [debug] [2019-05-11T05:15:26.539Z] Error: ENOSPC: System limit for number of file watchers reached, watch '/home/[user]/FirebaseProjects/[project-id]/functions/node_modules/google-proto-files/google/ads/googleads/v1/resources/ad_group_criterion_label.proto'
            at FSWatcher.start (internal/fs/watchers.js:165:26)
            at Object.watch (fs.js:1253:11)
            at createFsWatchInstance (/home/[user]/.npm-global/lib/node_modules/firebase-tools/node_modules/chokidar/lib/nodefs-handler.js:38:15)
            at setFsWatchListener (/home/[user]/.npm-global/lib/node_modules/firebase-tools/node_modules/chokidar/lib/nodefs-handler.js:81:15)
            at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/[user]/.npm-global/lib/node_modules/firebase-tools/node_modules/chokidar/lib/nodefs-handler.js:233:14)
            at FSWatcher.NodeFsHandler._handleFile (/home/[user]/.npm-global/lib/node_modules/firebase-tools/node_modules/chokidar/lib/nodefs-handler.js:262:21)
            at FSWatcher.<anonymous> (/home/[user]/.npm-global/lib/node_modules/firebase-tools/node_modules/chokidar/lib/nodefs-handler.js:495:21)
            at FSReqWrap.oncomplete (fs.js:154:5)

**Comment by abeisgoat** [comment]
This appears to be an issue with accidentally watching `node_modules` when hot-reloading. Should be a quick fix.
