### ISSUE TITLE
Cannot deploy functions with git dependencies

### ISSUE THREAD

**Issue by billyjs** [firebase/firebase-tools#1301]
### [REQUIRED] Environment info

**firebase-tools:** v6.9.2

**Platform:** Windows

### [REQUIRED] Test case

```
"dependencies": {
    "@slack/interactive-messages": "github:ErwinLengkeek/node-slack-interactive-messages#feature/issue-91"
}
```

### [REQUIRED] Steps to reproduce

with git dependencies in functions/package.json run `firebase deploy` or `firebase deploy --only functions`

### [REQUIRED] Expected behavior

project is deployed successfully

### [REQUIRED] Actual behavior

```
functions[endpoints(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '@slack/interactive-messages'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:65:34)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getUserFunction (/worker/worker.js:439:24)
    at loadUserCode (/worker/worker.js:495:18)
    at /worker/worker.js:720:31
    at Layer.handle [as handle_request] (/worker/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by bkendall** [comment]
I am unable to replicate this behavior.

Have you run `npm install` in your `functions` directory? When the deployment runs, it has to parse the code in that directory and it will break if you've not run `npm install` there.

**Comment by bkendall** [comment]
Oop - I guess my machine changed its mind. Now I can replicate this pretty reliably. I see the error message which is coming all the way from GCF. I think @thechenky will be the best person to help triage this.

**Comment by thechenky** [comment]
Hi @billyjs your git dependency definition looks off - can you follow the guide here https://docs.npmjs.com/files/package.json#git-urls-as-dependencies? The URL should start with a `<protocol>`.
