### ISSUE TITLE
Emulator does not provide a good error when Typescript is not compiled

### ISSUE THREAD

**Issue by mitjans** [firebase/firebase-tools#1304]
### [REQUIRED] Environment info

**firebase-tools:** 6.9.2

**Platform:** macOS/Windows

### [REQUIRED] Test case

`firebase serve` seems broken when using Typescript. 
When executing `firebase serve` for the first time after a new empty project has been initialized, it gives the following warning:
`The Cloud Functions emulator requires the module "firebase-functions-test" to be installed as a development dependency. To fix this, run "npm install --save-dev firebase-functions-test" in your functions directory.
`

After installing `firebase-functions-test` inside the functions directory, the command `firebase serve` returns de following output:

```
Error: Cannot find module '/path/to/functions'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:482:29
    at Generator.next (<anonymous>)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:444:12)
⚠  Your function was killed because it raised an unhandled error.
```

### [REQUIRED] Steps to reproduce

1. `firebase init functions`
2. Select Typescript
3. `firebase serve` (it asks to install `firebase-functions-test`  inside functions dir)
4. `cd functions && npm install --save-dev firebase-functions-test`
5. `firebase serve`

### [REQUIRED] Expected behavior

Serve the functions locally.

### [REQUIRED] Actual behavior
```
Error: Cannot find module '/path/to/functions'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:482:29
    at Generator.next (<anonymous>)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:444:12)
⚠  Your function was killed because it raised an unhandled error.
```

[2019-05-16T15:23:38.511Z] ----------------------------------------------------------------------
[2019-05-16T15:23:38.514Z] Command:       /Users/carlesm/.nvm/versions/node/v8.16.0/bin/node /Users/carlesm/.nvm/versions/node/v8.16.0/bin/firebase serve --debug
[2019-05-16T15:23:38.514Z] CLI Version:   6.9.2
[2019-05-16T15:23:38.514Z] Platform:      darwin
[2019-05-16T15:23:38.515Z] Node Version:  v8.16.0
[2019-05-16T15:23:38.515Z] Time:          Thu May 16 2019 17:23:38 GMT+0200 (CEST)
[2019-05-16T15:23:38.515Z] ----------------------------------------------------------------------

[2019-05-16T15:23:38.524Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-16T15:23:38.524Z] > authorizing via signed-in user
[2019-05-16T15:23:38.524Z] [iam] checking project circles-9fb9c for permissions ["firebase.projects.get"]
[2019-05-16T15:23:38.526Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/circles-9fb9c:testIamPermissions
 permissions=[firebase.projects.get]
[2019-05-16T15:23:39.439Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 16 May 2019 15:23:39 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=800, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-16T15:23:39.441Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/circles-9fb9c

[2019-05-16T15:23:40.311Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 16 May 2019 15:23:40 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=823, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked

=== Serving from '/Users/carlesm/SocialCircles/firebase'...

✔  functions: Using node@8 from host.
[2019-05-16T15:23:40.321Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/977491340356:getServerAppConfig

[2019-05-16T15:23:40.527Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 16 May 2019 15:23:40 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
✔  functions: Emulator started at http://localhost:5000
i  functions: Watching "/Users/carlesm/SocialCircles/firebase/functions" for Cloud Functions...
[2019-05-16T15:23:40.829Z] Functions runtime initialized.
[2019-05-16T15:23:40.830Z] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"protect_env":true,"admin_stubs":true}
[2019-05-16T15:23:41.299Z] firebase-admin has been stubbed.
⚠  Error: Cannot find module '/Users/carlesm/SocialCircles/firebase/functions'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:482:29
    at Generator.next (<anonymous>)
    at /Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/carlesm/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:444:12)
⚠  Your function was killed because it raised an unhandled error.

**Comment by abeisgoat** [comment]
Hi, it appears you never actually compiled the Typescript which would result in this issue, can you try running the typescript compiler in your functions directory and let me know if it's still not working?

The emulator doesn't attempt to take care of compiling your code (due to the many caveats and particular settings a dev might want), but we could potentially improve error messages here and be more helpful.

**Comment by mitjans** [comment]
Hi, I run the compiler inside `functions/src`:
`tsc index.ts`
which generated the js.

After that, the output is the same when running `firebase serve` in the root dir of the project.

**Comment by mitjans** [comment]
This are the dirs/files inside root/functions:
```
firebase-debug.log
package-lock.json   
package.json        
src/                
tsconfig.json       
tslint.json
```

**Comment by mitjans** [comment]
Ok got it working! I had to compile the source code from the `functions` folder, not `functions/src`!
Thanks for your help!

**Comment by mitjans** [comment]
A more explicit error could be very helpful in this particular error!

**Comment by samtstern** [comment]
@abeisgoat is there anything we can do to improve the error message or is this totally opaque to us?

**Comment by abeisgoat** [comment]
I think we could make a helpful guess. We know where the user's `firebase.json` is and we know if they're using any language that compiles to JavaScript, it's probably Typescript. If they're using TS, they probably have a `tsconfig.json`, so in that situation, we can try to import their code, if it fails we can look for a `tsconfig.json` and if it exists, let them know that maybe it's failing because they forgot to build their Typescript. I bet this would be helpful like... 50% of the time issues like this come up and just invisible the rest of the time.

Personally I'm inclined to do this because there's no downside 🤷‍♂

**Comment by abeisgoat** [comment]
Closing this in favor of tracking error improvements in #1310
