### ISSUE TITLE
Firestore emulator logging about tokens is very noisy

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#1308]
### [REQUIRED] Environment info

**firebase-tools:** 6.9.2

**Platform:** All

### [REQUIRED] Test case

Run an Android app with auth against the Firestore emulator

### [REQUIRED] Steps to reproduce

Any query

### [REQUIRED] Expected behavior

Maybe a small warning in the logs

### [REQUIRED] Actual behavior

In the `--debug` logs we get this on every request:

```
[2019-05-16T20:15:37.355Z] May 16, 2019 1:15:37 PM com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization warnAboutSecuredJwt
WARNING: expected an unsecured JWT, the emulator does not validate JWTs and IS NOT SECURE
com.google.cloud.datastore.core.exception.ValidationException: expected JWT alg to be 'none' but got 'RS256'
	at com.google.cloud.datastore.core.exception.ValidationException.validatePrecondition(ValidationException.java:56)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.validateUnsecuredJwt(EmulatorAuthorization.java:119)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.warnAboutSecuredJwt(EmulatorAuthorization.java:138)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:93)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.constructRequestContext(CloudFirestoreV1Router.java:211)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.listenStream(CloudFirestoreV1Router.java:163)
	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter.bidi(FirestoreV1GrpcAdapter.java:88)
	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter.access$300(FirestoreV1GrpcAdapter.java:38)
	at com.google.cloud.datastore.emulator.firestore.v1.FirestoreV1GrpcAdapter$1.listen(FirestoreV1GrpcAdapter.java:182)
	at com.google.firestore.v1.FirestoreGrpc$MethodHandlers.invoke(FirestoreGrpc.java:1721)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler.startCall(ServerCalls.java:221)
	at io.grpc.Contexts.interceptCall(Contexts.java:52)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore$FirebaseAuthInterceptor.interceptCall(CloudFirestore.java:188)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
	at io.grpc.Contexts.interceptCall(Contexts.java:52)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore$FirebaseDatabaseRefInterceptor.interceptCall(CloudFirestore.java:203)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:610)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:590)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:410)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:526)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ryanpbrewster** [comment]
This is much quieter with Firestore emulator v1.4.6
