### ISSUE TITLE
verifyDeveloperNodeModules() should selectively disable trigger types based on available SDKs

### ISSUE THREAD

**Issue by bobbydreamer** [firebase/firebase-tools#1337]
### [REQUIRED] Environment info

**firebase :** 6.10.0
**firebase-tools :**  6.9.0
**firebase-admin :**  8.0.0
**firebase-functions :**  2.3.1
**firebase-functions-test :**  0.1.6

firebase-functions-test is the new one which i had installed yesterday only due to a message when running serve command.

**Platform:** Windows

### [REQUIRED] Test case

Executed the steps as mentioned in "Steps to reproduce"

### [REQUIRED] Steps to reproduce

Getting below error message after issuing command "firebase serve --only functions,hosting"

```
!  AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:594:3)
    at require (internal/module.js:11:18)
    at InitializeFirebaseAdminStubs (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:231:18)
    at C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:451:9
    at Generator.next (<anonymous>)
    at C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at main (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:511:5)
!  Your function was killed because it raised an unhandled error.
^CTerminate batch job (Y/N)? Y

```
Below are the commands i executed

1. firebase serve --only functions,hosting
   Got a message that i need to update from 6.4.0 -> 6.9.2 "Run npm i -g firebase-tools to update"

1. After updating again did ran serve and got message "Update available 6.9.2 → 6.10.0" and i again did ran the update.

1. Updated firebase-admin as well "npm i -g firebase-admin@latest"

1. Again ran "firebase serve --only functions,hosting" started seeing below message on firebase-functions-test. Ran the mentioned command in functions folder.

```
+  functions: Using node@8 from host.
+  functions: Emulator started at http://localhost:5001
i  functions: Watching "D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions" for Cloud Functions...
i  hosting: Serving hosting files from: public
+  hosting: Local server: http://localhost:5000
!  The Cloud Functions emulator requires the module "firebase-functions-test" to be installed as a development dependency. To fix this, run "npm install --save-dev firebase-functions-test" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)
[hosting] Rewriting / to http://localhost:5001/btd-in2-20180718/us-central1/app for local Function app
i  functions: Beginning execution of "app"
!  The Cloud Functions emulator requires the module "firebase-functions-test" to be installed as a development dependency. To fix this, run "npm install --save-dev firebase-functions-test" in your functions directory.
```
5. Next time i run firebase serve, i am getting above error message.

Due to this i am not able to test locally the web nodejs firebase code.

### [REQUIRED] Expected behavior

Firebase hosting should run successfully and i should be able to see the website in localhost:5000

### [REQUIRED] Actual behavior

**Debug Logs**
```
[debug] [2019-05-24T01:58:03.699Z] ----------------------------------------------------------------------
[debug] [2019-05-24T01:58:03.699Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve --debug --only functions,hosting
[debug] [2019-05-24T01:58:03.715Z] CLI Version:   6.10.0
[debug] [2019-05-24T01:58:03.715Z] Platform:      win32
[debug] [2019-05-24T01:58:03.717Z] Node Version:  v8.10.0
[debug] [2019-05-24T01:58:03.719Z] Time:          Fri May 24 2019 07:28:03 GMT+0530 (India Standard Time)
[debug] [2019-05-24T01:58:03.720Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-05-24T01:58:03.747Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-05-24T01:58:03.750Z] > authorizing via signed-in user
[debug] [2019-05-24T01:58:03.751Z] [iam] checking project btd-in2-20180718 for permissions ["firebase.projects.get"]
[debug] [2019-05-24T01:58:03.757Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/btd-in2-20180718:testIamPermissions  

[debug] [2019-05-24T01:58:05.270Z] <<< HTTP RESPONSE 200
[debug] [2019-05-24T01:58:05.275Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/btd-in2-20180718  
 
[debug] [2019-05-24T01:58:06.665Z] <<< HTTP RESPONSE 200
[info] +  functions: Using node@8 from host.
[debug] [2019-05-24T01:58:06.795Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/25491243517/clients/_:getWebAppConfig  
 
[debug] [2019-05-24T01:58:06.800Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/25491243517:getServerAppConfig  
 
[debug] [2019-05-24T01:58:07.153Z] <<< HTTP RESPONSE 200
[info] +  functions: Emulator started at http://localhost:5001
[debug] [2019-05-24T01:58:07.199Z] <<< HTTP RESPONSE 200
[info] i  functions: Watching "D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions" for Cloud Functions...
[info] i  hosting: Serving hosting files from: public
[info] +  hosting: Local server: http://localhost:5000
[debug] [2019-05-24T01:58:08.528Z] Functions runtime initialized.
[debug] [2019-05-24T01:58:08.528Z] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"protect_env":true,"admin_stubs":true}
[warn] !  AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:594:3)
    at require (internal/module.js:11:18)
    at InitializeFirebaseAdminStubs (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:231:18)
    at C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:451:9
    at Generator.next (<anonymous>)
    at C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at main (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (C:\Users\Sushanth\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:511:5)
[warn] !  Your function was killed because it raised an unhandled error.
```

**Comment by thechenky** [comment]
Hi @bobbydreamer sorry you're having these issues! To help us debug, if you downgrade firebase-tools to 6.8.0, are you able to successfully emulate? Going to also pass this over to the folks that are working on the emulator.

**Comment by samtstern** [comment]
I hate to give up an issue with such a great number, but @abeisgoat should look at this one.

Thanks for the detailed report!  I hope downgrading to 6.8.0 unblocks you for now.

**Comment by bobbydreamer** [comment]
Thank you very very much. Downgrading to 6.8.0 worked!
npm i firebase-tools@6.8.0

**Comment by abeisgoat** [comment]
Hi Bobby, you're experiencing the same issue as was reported in #1316  where importing the `grpc` module fails for an unknown reason. 

This is, sadly, hard for me to reproduce, but I suspect it's because of `node-gyp` failing to build the native extensions which `grpc` relies on. If you could, I'd appreciate if you could run...

```
node -e "console.log(require.resolve('grpc'))"
```

In your functions directory and let me know the result!

Thanks!

**Comment by bobbydreamer** [comment]
Hi @abeisgoat , Please find the below,
1. I didn't have grpc installed in the first place in the functions directory, so i had installed it via command
```
PS D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions> npm i grpc --save

> grpc@1.21.1 install D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node" is installed via remotenpm WARN firebase-functions@2.3.1 requires a peer of firebase-admin@^7.0.0 but none is installed. You must install peer dependencies yourself.

+ grpc@1.21.1
added 89 packages from 49 contributors and audited 1299 packages in 61.147s
found 0 vulnerabilities
```

2. Executed the command you requested
```
PS D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions> node -e "console.log(require.resolve('grpc'))"
D:\BigData\13. Firebase\FB-BTD\FB-BTD\functions\node_modules\grpc\index.js
```

**Comment by abeisgoat** [comment]
Thanks for the info, after installing does `serve` run successfully?

**Comment by bobbydreamer** [comment]
Yes. Now the serve works

**Comment by imkane** [comment]
This is also happening to me :(

I tried:
`npm i firebase-tools@6.8.0`

But that didn't help. Is there another solution?

**Comment by bkendall** [comment]
@imkane to downgrade the CLI, you probably need to install it globally:

`npm i -g firebase-tools@6.8.0`

**Comment by abeisgoat** [comment]
I think the real issue here is that we're assuming to emulate functions you need `grpc` which is only true for Firestore triggers, so if you don't care about Firestore, this should just be a warning.

In order to fix this, we need to change how we're implementing `verifyDeveloperNodeModules()` to allow for non-blocking messages about specific SDKs. I think if we did that, then this issue would have never came up and in situations like @imkane where his system is failing to compile the GRPC module, we could selectively disable Firestore triggers instead of failing out.

**Comment by abeisgoat** [comment]
I'm going to close this in favor of tracking the issue in #1341 1341
