### ISSUE TITLE
verifyDeveloperNodeModules() should selectively warn and selectively disable trigger types based on available SDKs

### ISSUE THREAD

**Issue by jaschaio** [firebase/firebase-tools#1341]
### Related issues

#1262 seems to be related although I am not sure if this has to do with firebase-admin. Subsequent comments in #1316 seem spot on but I decided to open a new issue as the initial one was resolved differently.

### Environment info

**firebase-tools:** 6.10.0
**Platform:** macOSX 10.14.5
**Node:** 10.15.3
**firebase-functions:** 2.3.1
**firebase-admin:** 8.0.0

### Test case

A freshly generated firebase project using firebase init with functions. Use Node `10.15.3` and change the `package.json` engines node to `10`. Install `firebase-admin@8.0.0` and `firebase-functions@2.3.1` 

### Steps to reproduce

Just run `firebase serve` within the newly created project as described above.

### Expected behavior

Functions emulator should run.

### Actual behavior

Seeing this error with `firebase-tools: 6.10.0` and node `8.14.0`. Firebase admin is `8.0.0` and firebase functions `6.10.0`:

```
AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:595:3)
    at require (internal/module.js:11:18)
    at InitializeFirebaseAdminStubs (/Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:231:18)
    at /Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:451:9
    at Generator.next (<anonymous>)
    at /Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (/Users/Jascha/.nvm/versions/node/v8.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:511:5)
```

If I change node to version `10.15.3` (and as well udpate the `engine` to `10` within the package.json) the error changes to this one:

```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'id' must be a non-empty string. Received ''
    at Module.require (internal/modules/cjs/loader.js:634:11)
    at require (internal/modules/cjs/helpers.js:22:18)
    at InitializeFirebaseAdminStubs (/Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:231:18)
    at /Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:451:9
    at Generator.next (<anonymous>)
    at /Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (/Users/Jascha/.nvm/versions/node/v10.15.3/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:511:5)
```

Somebody said on the other issue that its the same error but with different error messages between node 8 and 10.

If I downgrade back to firebase-tools `6.8.0` it works.

When running `node -e "console.log(require.resolve('grpc'))"` the output is:

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'grpc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at [eval]:1:21
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### Steps to resolve

After running `npm install --save grpc` it works.

**Comment by samtstern** [comment]
@jaschaio thanks for such a well-researched issue!  This will be very helpful.

**Comment by abeisgoat** [comment]
This is related to both improvement in `verifyDeveloperNodeModules()` and the fact that `firebase-admin@8.0.0` dropped `grpc` as a dependency so it no longer exists. I'll work on both those as one fix.

**Comment by abeisgoat** [comment]
Fix has been merged into `next` branch so it'll go out with the `firebase-tools@7.0.0` release

**Comment by Nilegfx** [comment]
for now, I installed `grpc` module into functions directory and it worked!
