### ISSUE TITLE
Specify public directory on deploy

### ISSUE THREAD

**Issue by jschr** [firebase/firebase-tools#138]
Same error mentioned in https://github.com/firebase/firebase-tools/issues/136. 

I currently have a build folder for each environment. Prior to upgrading I deployed with `firebase deploy -p dist/staging -f db-staging`. After upgrading I'm trying to deploy with `firebase use staging && firebase deploy -p dist/staging` but its failing.

error in firebase-debug.log
```
[info] i  deploying database, hosting
[debug] TypeError: options.config.importLegacyKeys is not a function
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:19:20)
    at _chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:21:45)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:24:14
    at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
[error]
[error] Error: An unexpected error has occurred.
```

**Comment by mbleigh** [comment]
Because `firebase deploy` is expanding beyond just hosting, we're trying to re-evaluate how we manage configuration differences between environments. I think this is a totally valid use case, but I don't have an immediate solution (I don't think we'll be bringing `--public` back to deploy but taking a holistic approach).

In the meantime, you could perform a copy-before-deploy as an NPM script, something like:

```
{
  "scripts": {
    "deploy:staging": "cp -r dist/staging deploy && firebase deploy -f db-staging && rm -rf deploy",
    "deploy:prod": "cp -r dist/prod deploy && firebase deploy -f db-prod && rm -rf deploy"
  }  
}
```

Again, I think we can do better here but we're approaching it holistically.

**Comment by jschr** [comment]
Thanks for the response, the workaround seems pretty reasonable to me! You are welcome to close the issue if you'd like to.
