### ISSUE TITLE
Running firebase tools:migrate fails

### ISSUE THREAD

**Issue by israelidanny** [firebase/firebase-tools#139]
I'm following the fresh migration guide here:
https://firebase.google.com/support/guides/firebase-web

And getting an error every time.

```
[error]
[error] Error: An unexpected error has occurred.
[debug] ----------------------------------------------------------------------
[debug] Command:      /Users/danny/.nvm/versions/node/v5.6.0/bin/node /Users/danny/.nvm/versions/node/v5.6.0/bin/firebase tools:migrate
[debug] CLI Version:  3.0.0
[debug] Platform:     darwin
[debug] Node Version: v5.6.0
[debug] Time:         Thu May 19 2016 10:26:08 GMT+0300 (EEST)
[debug] ----------------------------------------------------------------------
[debug]
[info] i  Checking feature configuration...
[debug] TypeError: Cannot read property '_src' of undefined
    at null._action (/Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/commands/tools-migrate.js:25:41)
    at /Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/lib/command.js:168:29
    at lib$rsvp$$internal$$tryCatch (/Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/danny/.nvm/versions/node/v5.6.0/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
[error]
[error] Error: An unexpected error has occurred.
```

**Comment by pho3nixf1re** [comment]
I too am seeing this exact same error.

**Comment by mbleigh** [comment]
Can you please run with --debug and paste the results here?

**Comment by pho3nixf1re** [comment]
It is the exact same error that @israelidanny is seeing.

```
➤  node_modules/.bin/firebase tools:migrate --debug                                                                                                     
----------------------------------------------------------------------
Command:      /Users/mturney/.nvm/versions/node/v5.11.1/bin/node /Users/mturney/Workspace/reservationator/node_modules/.bin/firebase tools:migrate --debug
CLI Version:  3.0.0
Platform:     darwin
Node Version: v5.11.1
Time:         Sun May 22 2016 13:06:53 GMT-0500 (CDT)
----------------------------------------------------------------------

i  Checking feature configuration...
TypeError: Cannot read property '_src' of undefined
    at null._action (/Users/mturney/Workspace/reservationator/node_modules/firebase-tools/commands/tools-migrate.js:25:41)
    at /Users/mturney/Workspace/reservationator/node_modules/firebase-tools/lib/command.js:168:29
    at lib$rsvp$$internal$$tryCatch (/Users/mturney/Workspace/reservationator/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mturney/Workspace/reservationator/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/mturney/Workspace/reservationator/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/mturney/Workspace/reservationator/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)

Error: An unexpected error has occurred.
```

**Comment by pho3nixf1re** [comment]
As a side note, I was able to manually translate the rules myself.

**Comment by jwngr** [comment]
Thanks to everyone for reporting this. It looks like [this is the line at fault](https://github.com/firebase/firebase-tools/blob/40e4622d266226adc4d9beb6e4f62a8ed7d39e05/commands/tools-migrate.js#L25). I unfortunately don't know enough about this particular file to help out right away. We might just need to change that line to `var out = _.cloneDeep(_.get(options, 'config._src'));` but I'm not sure if that will just make something fail later on.

Michael should be able to look at this soon though.

**Comment by kierandes** [comment]
Hey guys, is this sorted? Still getting that bug..

**Comment by mbleigh** [comment]
A fix has been merged but not released to npm yet. Make sure you're in a directory with a `firebase.json` before running the command.
