### ISSUE TITLE
database:profile: Cannot read property 'millis' of undefined

### ISSUE THREAD

**Issue by alixaxel** [firebase/firebase-tools#1407]
### [REQUIRED] Environment info

**firebase-tools:** 7.0.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Using the `database:profile` command for a long duration (180 seconds or more).

### [REQUIRED] Steps to reproduce

```
firebase database:profile -d 180 -o profile.rtdb.txt
```

### [REQUIRED] Expected behavior

Should have a file listing all the profiled operations for the active running time.

### [REQUIRED] Actual behavior

If the command runs for more than 120 or so, no output is present and fails with:

> Error: An unexpected error has occurred.

```
[2019-06-17T11:37:05.364Z] ----------------------------------------------------------------------
[2019-06-17T11:37:05.366Z] Command:       /usr/bin/node /usr/bin/firebase database:profile -d 180 -o profile.rtdb.txt --debug
[2019-06-17T11:37:05.367Z] CLI Version:   7.0.0
[2019-06-17T11:37:05.367Z] Platform:      linux
[2019-06-17T11:37:05.367Z] Node Version:  v12.4.0
[2019-06-17T11:37:05.367Z] Time:          Mon Jun 17 2019 12:37:05 GMT+0100 (Western European Summer Time)
[2019-06-17T11:37:05.367Z] ----------------------------------------------------------------------

[2019-06-17T11:37:05.373Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-06-17T11:37:05.373Z] > authorizing via signed-in user
[2019-06-17T11:37:05.373Z] [iam] checking project X for permissions ["firebase.projects.get","firebasedatabase.instances.update"]
[2019-06-17T11:37:05.374Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2019-06-17T11:37:05.375Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2019-06-17T11:37:05.623Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 17 Jun 2019 11:37:05 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-06-17T11:37:05.631Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/X:testIamPermissions  
 permissions=[firebase.projects.get, firebasedatabase.instances.update]
[2019-06-17T11:37:06.487Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 17 Jun 2019 11:37:06 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=764, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-06-17T11:37:06.490Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/X  
 
[2019-06-17T11:37:06.847Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 17 Jun 2019 11:37:06 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-06-17T11:40:07.076Z] TypeError: Cannot read property 'millis' of undefined
    at /usr/lib/node_modules/firebase-tools/lib/profileReport.js:361:22
    at /usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:3733:18
    at arrayMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at /usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:3732:24
    at /usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:3549:27
    at /usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:4887:15
    at baseMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:3548:7)
    at baseOrderBy (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:3731:20)
    at Function.orderBy (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9599:14)
    at ProfileReport.renderOperationSpeed (/usr/lib/node_modules/firebase-tools/lib/profileReport.js:359:15)

Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
Huh, I can replicate this (though, I have to make sure my database has some activity - in the console is fine). I will see if someone will take a closer look...

**Comment by IanWyszynski** [comment]
This problem doesn't seem to come up when I write paths with just one component at the root of the database. It did come up when I tried writing deeper paths (1 level of hierarchy seems to be enough). I need to investigate more though, because writing a single deep path during a short profiler run doesn't seem to trigger this bug (time - or potentially the number of datapoints recorded seems to be a factor).

**Comment by IanWyszynski** [comment]
I was also able to tease out this:
```
[debug] [2019-06-17T19:19:35.258Z] ----------------------------------------------------------------------
[debug] [2019-06-17T19:19:35.260Z] Command:       /usr/local/google/home/wyszynski/.nvm/versions/node/v10.15.3/bin/node /usr/local/google/home/wyszynski/firebase-tools/lib/bin/firebase.js database:profile -d 240 -o rtdb.out
[debug] [2019-06-17T19:19:35.260Z] CLI Version:   7.0.0
[debug] [2019-06-17T19:19:35.260Z] Platform:      linux
[debug] [2019-06-17T19:19:35.260Z] Node Version:  v10.15.3
[debug] [2019-06-17T19:19:35.260Z] Time:          Mon Jun 17 2019 12:19:35 GMT-0700 (Pacific Daylight Time)
[debug] [2019-06-17T19:19:35.260Z] Env Overrides: FIREBASE_REALTIME_URL
[debug] [2019-06-17T19:19:35.260Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-06-17T19:19:35.267Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-06-17T19:19:35.267Z] > authorizing via signed-in user
[debug] [2019-06-17T19:19:35.267Z] [iam] checking project wyszynski-test for permissions ["firebase.projects.get","firebasedatabase.instances.update"]
[debug] [2019-06-17T19:19:35.268Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/wyszynski-test:testIamPermissions  

[debug] [2019-06-17T19:19:35.548Z] <<< HTTP RESPONSE 200
[debug] [2019-06-17T19:19:35.552Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/wyszynski-test  
 
[debug] [2019-06-17T19:19:35.764Z] <<< HTTP RESPONSE 200
[debug] [2019-06-17T19:23:35.805Z] TypeError: Cannot read property 'bytes' of undefined
    at /usr/local/google/home/wyszynski/firebase-tools/lib/profileReport.js:316:26
    at /usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:3733:18
    at arrayMap (/usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at /usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:3732:24
    at /usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:3549:27
    at /usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:4887:15
    at baseMap (/usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:3548:7)
    at baseOrderBy (/usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:3731:20)
    at Function.orderBy (/usr/local/google/home/wyszynski/firebase-tools/node_modules/lodash/lodash.js:9599:14)
    at ProfileReport.renderBandwidth (/usr/local/google/home/wyszynski/firebase-tools/lib/profileReport.js:314:15)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by IanWyszynski** [comment]
The problem here is that some operations introduced in https://github.com/firebase/firebase-tools/pull/1226 (e.g. listener-unlisten, listener-listen) do not have `path`s defined in their profiler record. The root cause of this problem is that lodash's `keys` function behaves as follows:
```
wyszynski@wyszynski:~/firebase-tools$ node
> var lodash = require('lodash');
undefined
> lodash.keys({ null: 1})
[ 'null' ]
```
Here is the sequence of events:
-  The null key, becomes the string 'null' on this line: https://github.com/firebase/firebase-tools/blob/master/src/profileReport.js#L261
- Since the null path has no leading `/`, it is added to `otherSegments` and the `'null'` (string) is turned into `'/null'` here:  https://github.com/firebase/firebase-tools/blob/master/src/profileReport.js#L302.
- The value for the `'/null'` key in the result object is set to `undefined` because the original stats object has no `'/null'` key, just a `null` (actual null) key.

This is how we end up with an `undefined` datapoint here: https://github.com/firebase/firebase-tools/blob/master/src/profileReport.js#L410.

There are a few ways we could fix this issue:
- We could set treat all operations with no defined paths as if they took place on the `/`. This may be confusing to developers in the case of unlistens. 
- We could treat all operations with no defined paths as if they took place some hardcoded special paths.

I prefer the latter approach because it doesn't conflict with the RTDB keyspace.

**Comment by IanWyszynski** [comment]
The profiler also appears to be emitting some 'rest-read' events without any `path` fields:
```
processOperation = { querySet: [ { orderBy: '$priority' } ],
  millis: 0,
  pendingTime: 0,
  bytes: 0,
  client:
   { remoteAddress: { address: '2620:0:1002:12:d6d3:cec4:69c0:1ca9' },
     userAgent:
      { browser: 'chrome',
        os: 'linux',
        platform: 'desktop',
        userAgentString:
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36',
        version: '75' } },
  allowed: true,
  name: 'rest-read',
  timestamp: 1560916122625 }
processOperation = { unIndexed: false,
  millis: 228,
  pendingTime: 0,
  bytes: 0,
  client:
   { remoteAddress: { address: '2620:0:1002:12:d6d3:cec4:69c0:1ca9' },
     userAgent:
      { browser: 'chrome',
        os: 'linux',
        platform: 'desktop',
        userAgentString:
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36',
        version: '75' } },
  allowed: true,
  name: 'listener-listen',
  timestamp: 1560916123445 }
processOperation = { querySet: [ { orderBy: '$priority' } ],
  millis: 1,
  pendingTime: 0,
  bytes: 0,
  client:
   { remoteAddress: { address: '2620:0:1002:12:d6d3:cec4:69c0:1ca9' },
     userAgent:
      { browser: 'chrome',
        os: 'linux',
        platform: 'desktop',
        userAgentString:
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36',
        version: '75' } },
  allowed: true,
  name: 'rest-read',
  timestamp: 1560916124928 }
processOperation = { unIndexed: false,
  millis: 236,
  pendingTime: 0,
  bytes: 0,
  client:
   { remoteAddress: { address: '2620:0:1002:12:d6d3:cec4:69c0:1ca9' },
     userAgent:
      { browser: 'chrome',
        os: 'linux',
        platform: 'desktop',
        userAgentString:
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36',
        version: '75' } },
  allowed: true,
  name: 'listener-listen',
  timestamp: 1560916125296 }
processOperation = { querySet: [ { orderBy: '$priority' } ],
  millis: 1,
  pendingTime: 0,
  bytes: 0,
  client:
   { remoteAddress: { address: '2620:0:1002:12:d6d3:cec4:69c0:1ca9' },
     userAgent:
      { browser: 'chrome',
        os: 'linux',
        platform: 'desktop',
        userAgentString:
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36',
        version: '75' } },
  allowed: true,
  name: 'rest-read',
  timestamp: 1560916127299 }
```

**Comment by simonbengtsson** [comment]
Also seeing this on mac. And we don't have to wait for 180 seconds. Usually it happens after only 50-100 operations. Based on above comment I guess it is that if there is a unlisten event during the profiler run?

**Comment by alixaxel** [comment]
We recently migrated over to Firestore so all of our RTDB usage is residual. I guess that would explain why we need ~200 seconds while a heavier usage might yield the same error after only a few operations. This only became clear after monitoring this behavior for a while.
