### ISSUE TITLE
firebase deploy unexpected error EPIPE

### ISSUE THREAD

**Issue by michalwa** [firebase/firebase-tools#1431]
Same issue: #1236 but I thought I'd reopen this with my info.

### [REQUIRED] Environment info

**firebase-tools:** 7.0.1

**Platform:** Windows

### [REQUIRED] Test case

`firebase init` with default settings and an existing Firebase project

### [REQUIRED] Steps to reproduce

1. `$ firebase init` in an empty directory; choose an existing Firebase project, leave all settings at default
2. `$ firebase deploy`

### [REQUIRED] Expected behavior

Should successfully deploy.

### [REQUIRED] Actual behavior
Run with `--debug`
```
[2019-06-22T13:16:14.655Z] ----------------------------------------------------------------------[2019-06-22T13:16:14.660Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js deploy --debug
[2019-06-22T13:16:14.661Z] CLI Version:   7.0.1
[2019-06-22T13:16:14.661Z] Platform:      win32
[2019-06-22T13:16:14.661Z] Node Version:  v10.16.0
[2019-06-22T13:16:14.663Z] Time:          Sat Jun 22 2019 15:16:14 GMT+0200 (GMT+02:00)
[2019-06-22T13:16:14.664Z] ----------------------------------------------------------------------
[2019-06-22T13:16:14.677Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-06-22T13:16:14.680Z] > authorizing via signed-in user[2019-06-22T13:16:14.681Z] [iam] checking project (project name) for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"][2019-06-22T13:16:14.684Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2019-06-22T13:16:14.685Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>[2019-06-22T13:16:14.903Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Sat, 22 Jun 2019 13:16:13 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked        
[2019-06-22T13:16:14.910Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/(project name):testIamPermissions     permissions=[cloudfunctions.functions.create, cloudfunctions.functions.delete, cloudfunctions.functions.get, cloudfunctions.functions.list, cloudfunctions.functions.update, cloudfunctions.operations.get, firebase.projects.get][2019-06-22T13:16:15.874Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Sat, 22 Jun 2019 13:16:14 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=823, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-06-22T13:16:15.935Z] SyntaxError: Unexpected token  in JSON at position 0 
    at JSON.parse (<anonymous>)                           in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (C:\nvm\v10.16.0\node_modules\firebase-tools\lib\checkFirebaseSDKVersion.js:24:31)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

Error: An unexpected error has occurred.
/d/temp/firebase-bug $ npm ERR! code EPIPE 
npm ERR! errno EPIPE
npm ERR! syscall write
npm ERR! EPIPE: broken pipe, write

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(my username)\AppData\Roaming\npm-cache\_logs\2019-06-22T13_16_16_548Z-debug.log
```

**Comment by bkendall** [comment]
This is a strange error that I am unable to replicate.

Can you confirm that you have the appropriate permissions on the project you are trying to run the CLI on? Are you an owner of that project?

**Comment by michalwa** [comment]
Yes, it's a clean project I created.

**Comment by abeisgoat** [comment]
@bkendall There's only one reference to `JSON.parse` in `checkFirebaseSDKVersion.ts` and it's attempting to parse the result from `npm outdated`. I wonder if there isn't some failure condition where `npm` returns a non-json result which causes us to implode.

**Comment by michalwa** [comment]
I tried running `npm outdated firebase-tools` in the `/functions` subdirectory as well as `npm outdated -g` with and without `--json=true` and all output nothing. That might be the source of the problem.

**Comment by michalwa** [comment]
I've also set the `engines.node` property in `functions/package.json` to `10`, as I'm using Node 10, but nothing seems to be different.

**Comment by Ale-Digitale** [comment]
Same IDENTICAL error here. I'm stuck and can't deploy anything :-(

Node version: 10.16.0
npm version: 6.9.0

This is my **debug.log** :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'prefix',
1 verbose cli   '-g' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose exit [ 0, true ]
5 verbose stack Error: EPIPE: broken pipe, write
5 verbose stack     at Socket._write (internal/net.js:58:25)
5 verbose stack     at doWrite (_stream_writable.js:415:12)
5 verbose stack     at writeOrBuffer (_stream_writable.js:399:5)
5 verbose stack     at Socket.Writable.write (_stream_writable.js:299:11)
5 verbose stack     at reallyExit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:138:20)
5 verbose stack     at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:125:5)
5 verbose stack     at EventEmitter.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:157:19)
5 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:149:20)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:61:11)
6 verbose cwd C:\Users\aledi\Desktop\firebase-demo\functions
7 verbose Windows_NT 10.0.17134
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
9 verbose node v10.16.0
10 verbose npm  v6.9.0
11 error code EPIPE
12 error errno EPIPE
13 error syscall write
14 error EPIPE: broken pipe, write
15 verbose exit [ 1, true ]

Please help, i'm stuck and can't deploy anything :-(

**Comment by michalwa** [comment]
Nope, can't fix it, can't deploy anything sadly.

**Comment by michalwa** [comment]
Updated to **npm** v6.9.2 and **firebase-tools** v7.0.2, nothing changed.

**Comment by Ale-Digitale** [comment]
Yeah, same here. I also updated them both, but this damn error keeps going on.

I'm really desperate since i'm completely stuck with my Firebase development.

I also tried to ask help here:
https://stackoverflow.com/questions/56818852/deploy-firebase-functions-with-node-js-console-error-epipe

**Comment by Ale-Digitale** [comment]
as a temporary "workaround", for the desperation, I installed UBUNTU with VMWare under my Windows 10, and i execute Node.js from the Linux terminal. It worms like a charm !

Therefore, this bug has something to do with the Windows version...

**Comment by michalwa** [comment]
Also works on Ubuntu 18.04 in WSL, so that's also a plausible workaround.

**Comment by E01T** [comment]
Same error as above. Any ideas?
CMD: 
Error: An unexpected error has occurred.

C:\Users\E01T\socialapp-functions>npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write
npm ERR! EPIPE: broken pipe, write
------------------------------------------------------------------------------------------------------------
Error Log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'prefix',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose exit [ 0, true ]
5 verbose stack Error: EPIPE: broken pipe, write
5 verbose stack     at Socket._write (internal/net.js:58:25)
5 verbose stack     at doWrite (_stream_writable.js:410:12)
5 verbose stack     at writeOrBuffer (_stream_writable.js:394:5)
5 verbose stack     at Socket.Writable.write (_stream_writable.js:294:11)
5 verbose stack     at reallyExit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:138:20)
5 verbose stack     at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:125:5)
5 verbose stack     at EventEmitter.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:157:19)
5 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:150:20)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:61:11)
6 verbose cwd C:\Users\E01T\socialapp-functions\functions
7 verbose Windows_NT 6.1.7601
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
9 verbose node v10.14.2
10 verbose npm  v6.4.1
11 error code EPIPE
12 error errno EPIPE
13 error syscall write
14 error EPIPE: broken pipe, write
15 verbose exit [ 1, true ]

**Comment by ChristineShaffer** [comment]
Hey not sure if it helps anyone but I was able to solve this issue by switching to node 8 using nvm rather than node 10 and was able to deploy.

**Comment by rotemrevivo91** [comment]
How is there still no solution for this problem?

**Comment by mbleigh** [comment]
So far I don't believe any Firebase engineers have been able to reproduce the issue. If you have debug logs, please post so we can continue to gather evidence!

**Comment by ebellumat** [comment]
This ticket still open in 2022?

**Comment by joehan** [comment]
@ebellumat We've never been able to repro this issue, and it seems very out of date at this point. Closing - feel free to open a new issue if you are facing something similar.
