### ISSUE TITLE
firebase use --alias is in conflict with commander

### ISSUE THREAD

**Issue by sferencik** [firebase/firebase-tools#1457]
Running `firebase use --alias`, I get an error:
```
$ firebase use --alias myAlias myProjectId

Error: An unexpected error has occurred.
```

I believe the `--alias` option is in conflict with [commander](https://github.com/tj/commander.js), which firebase uses for parsing the command-line. Commander has a feature called command aliases (so you could alias e.g. `firebase set` to `firebase use`) and as it tries to evaluate the aliases, it gets confused by the `--alias` option. If my assessment is correct, it's **not possible to have an option named `--alias`** (without a change in commander).

I briefly looked at the commander code, and what happens is this:
1. commander constructs a list of all the known firebase commands (`init`, `deploy`, etc.), each represented by a `Command` object
    * as it happens, the `Command` class has a method called `alias()` - more on that later
2. given the commandline `firebase use --alias myAlias --debug myProjectId`, the commander will
    1. parse the "command" (`use`) and create a `Command` object, setting `._name = "use"`
    2. parse the options, setting `.alias = "myAlias"` and `.debug = true`
3. notice how setting the `.alias` field above has overwritten the `.alias()` method
4. when commander tries to evaluate the aliases for the `Command("use")`, it tries to invoke its `.alias()` method but it's gone - there's now an `.alias` field instead, courtesy to us using the `--alias` option
5. crash

It makes me wonder why no-one else has encountered this before?

Is there an alternative to using `--alias`? I would be OK with `--add`, but I need to run this on the CI.

### Environment info
**firebase-tools:** 7.0.2
**commander:** 2.20.0
**Platform:** Windows 10

### Debug stack-trace
```
$ firebase use --alias myAlias --debug myProjectId
[2019-07-02T09:38:47.880Z] ----------------------------------------------------------------------
[2019-07-02T09:38:47.885Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\e10110549\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js use --alias myAlias --debug myProjectId
[2019-07-02T09:38:47.886Z] CLI Version:   7.0.2
[2019-07-02T09:38:47.886Z] Platform:      win32
[2019-07-02T09:38:47.887Z] Node Version:  v10.14.1
[2019-07-02T09:38:47.888Z] Time:          Tue Jul 02 2019 11:38:47 GMT+0200 (Central European Summer Time)
[2019-07-02T09:38:47.888Z] ----------------------------------------------------------------------

[2019-07-02T09:38:48.382Z] TypeError: command.alias is not a function
    at C:\Users\e10110549\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\commander\index.js:490:22
    at Array.filter (<anonymous>)
    at Command.parse (C:\Users\e10110549\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\commander\index.js:485:34)
    at Object.<anonymous> (C:\Users\e10110549\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js:98:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)

Error: An unexpected error has occurred.
...
```

**Comment by samtstern** [comment]
@sferencik thanks for the detailed report!

**Comment by bkendall** [comment]
Huh. I am making a note to myself to take a look. Thanks

b/137017467

**Comment by petarGitNik** [comment]
@samedson I have the same problem. It seems that the bug is not resolved yet.

**Comment by lahiru-tennakoon** [comment]
@samtstern It's been more than a year since this issue has been opened but seems like this bug still exists.

**Comment by TimonSotiropoulos** [comment]
@samtstern 

+1 also having this issue. Is there another way to create aliases using the CLI that don't involve using the interactive tool? Basically I want to be able to script this alias creation in my firebase project.

**Comment by samtstern** [comment]
Seems like this is:
https://github.com/tj/commander.js/issues/592

It was fixed in Commander 7, as described here:
https://github.com/tj/commander.js#legacy-options-as-properties

Right now we're only using Commander 4 so we'd have to upgrade 3 major versions to get the fix. Not too hard, but also a bit scary.

**Comment by aalej** [comment]
Hey folks, this issue seems to be fixed in the newer versions of the Firebase CLI. I tried reproducing this using the latest version, currently 15.18.0, and no errors are raised when running `firebase use --alias myAlias myProjectId`
```
$ firebase use --alias prod aalej-6162-2
Created alias prod for aalej-6162-2.
Now using project aalej-6162-2
```

I'll go ahead and close this issue as this seems to be resolved. If anyone is still encountering this error, please open up a new report.
