### ISSUE TITLE
Failed to exec server:local script

### ISSUE THREAD

**Issue by itPiligrim** [firebase/firebase-tools#1473]
### Related issues

May be https://github.com/firebase/firebase-functions/issues/399

### [REQUIRED] Version info

```
 "dependencies": {
    "uuid": "^3.3.2",
    "firebase-admin": "^8.2.0",
    "firebase-functions": "^3.0.2",
    "firebase-tools": "^7.0.2",
    "@google-cloud/pubsub": "^0.30.1"
  },
  "devDependencies": {
    "typescript": "~3.3.1",
    "@types/uuid": "^3.4.4",
    "del-cli": "^2.0.0",
    "webpack": "^4.35.2",
    "webpack-cli": "^3.3.5",
    "webpack-node-externals": "^1.7.2",
    "ts-loader": "^6.0.4",
    "tsconfig-paths-webpack-plugin": "^3.2.0"
  },
  "engines": {
    "node": "8"
  },
```

**node:**
8.9.0, 8.16.0 and 10.14.2

### [REQUIRED] Test case

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server:local' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'preserver:local', 'server:local', 'postserver:local' ]
5 info lifecycle homework.cloud-site@1.0.0~preserver:local: homework.cloud-site@1.0.0
6 info lifecycle homework.cloud-site@1.0.0~server:local: homework.cloud-site@1.0.0
7 verbose lifecycle homework.cloud-site@1.0.0~server:local: unsafe-perm in lifecycle true
8 verbose lifecycle homework.cloud-site@1.0.0~server:local: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/administrator/Work/HOMEWORK.CLOUD/site/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Andrei/android-sdk:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/administrator/go/bin
9 verbose lifecycle homework.cloud-site@1.0.0~server:local: CWD: /Users/administrator/Work/HOMEWORK.CLOUD/site
10 silly lifecycle homework.cloud-site@1.0.0~server:local: Args: [ '-c',
10 silly lifecycle   'cd hosting/local/ && firebase serve --project homework-cloud-check' ]
11 silly lifecycle homework.cloud-site@1.0.0~server:local: Returned: code: 2  signal: null
12 info lifecycle homework.cloud-site@1.0.0~server:local: Failed to exec server:local script
13 verbose stack Error: homework.cloud-site@1.0.0 server:local: `cd hosting/local/ && firebase serve --project homework-cloud-check`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid homework.cloud-site@1.0.0
15 verbose cwd /Users/administrator/Work/HOMEWORK.CLOUD/site
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:local"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error homework.cloud-site@1.0.0 server:local: `cd hosting/local/ && firebase serve --project homework-cloud-check`
22 error Exit status 2
23 error Failed at the homework.cloud-site@1.0.0 server:local script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

### [REQUIRED] Steps to reproduce

This is reproduce from helloworld
example:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
exports.addMessage = functions.https.onRequest(async (req, res) => {
  return 123;
});
```

### [REQUIRED] Expected behavior

Not worked after global firebase-tools update

### Were you able to successfully deploy your functions?

Deploy is correct

**Comment by bkendall** [comment]
I see that your logs are failing to run `firebase serve --project [project]` in a folder named `hosting/local/`. Can you run that `firebase serve` command in that directory and let us know what the error is? Run it with `--debug` as well for more information.

The error messages here are coming from `npm`'s code, though it may still be an issue with `firebase`. But, we need more information.
