### ISSUE TITLE
firebase serve - TypeError: _onRequestWithOpts is not a function

### ISSUE THREAD

**Issue by KaranHotwani** [firebase/firebase-tools#1524]
### Version info

**node:**

8.16.0

**firebase-functions:**

affected : 3.0.0,3.1.0 
not afftected : 3.0.2

**firebase-tools:**

7.0.1

Run firebase --version and print the output here

**firebase-admin:**

8.2.0

### Test case

in index.js:

    const functions = require('firebase-functions');
    const express = require('express');
    const admin = require('firebase-admin');
    admin.initializeApp();
    const app = express();
    const moment = require('moment');
    var now=moment().format();
    app.get('/', (req, res)=>res.send({timeStamp: now}));
    exports.devDashApi = functions.https.onRequest(app);

### Steps to reproduce

1: Configure cloud functions. 
2: Run npm i in the functions directory. 
3: Run firebase deploy. 
4: Run firebase serve 

### Expected behavior

Api gets served locally.

### Actual behavior

⚠  TypeError: _onRequestWithOpts is not a function
    at Object.httpsProvider._onRequestWithOpts (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:231:24)
    at Object.httpsProvider.onRequest (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:236:34)
    at Object.<anonymous> (/home/karan/projects/devDashBackend/functions/index.js:132:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
⚠  We were unable to load your functions code. (see above)

### Were you able to successfully deploy your functions?

Yes.

**Comment by thechenky** [comment]
Have you tried updating your firebase tools to the latest version? This bug may ready be fixed.

**Comment by samtstern** [comment]
This was fixed in `firebase-tools` version `7.1.0`
