### ISSUE TITLE
invalid JSON crashes without response

### ISSUE THREAD

**Issue by dgobaud** [firebase/firebase-tools#1531]
send HTTP request to emulator with invalid JSON it crashes without sending response even though it appears to form the response it doesn't get sent - curl left hanging

```
error: { SyntaxError: Unexpected token } in JSON at position 90
    at JSON.parse (<anonymous>)
    at parse (.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/json.js:89:19)
    at .nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:224:16)
    at done (.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (.nvm/versions/node/v8.15.0/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  expose: true,
  statusCode: 400,
  status: 400,
  body: '{MY_BAD_JSON_HERE}',
  type: 'entity.parse.failed' }
info: Execution took 541429 ms, finished with status: 'timeout'
```

**Comment by bkendall** [comment]
Please follow the issue template and provide a bit more context and a case to reproduce the issue. Thank you.
