### ISSUE TITLE
Unable to login behind a proxy

### ISSUE THREAD

**Issue by brekov** [firebase/firebase-tools#1592]
I am trying to login while being behind proxy, and I'm tried almost solutions in #155.
Is there a way to login and deploy behind a proxy ?

### [REQUIRED] Environment info

**firebase-tools: 7.2.2**

**Platform:macOS**

### [REQUIRED] Actual behavior

run:  ```firebase login --no-localhost --debug```
output:
```
[2019-08-10T14:27:19.288Z] ----------------------------------------------------------------------
[2019-08-10T14:27:19.290Z] Command:       /usr/local/bin/node /Users/brekov/.npm-global/bin/firebase login --no-localhost --debug
[2019-08-10T14:27:19.291Z] CLI Version:   7.2.2
[2019-08-10T14:27:19.291Z] Platform:      darwin
[2019-08-10T14:27:19.291Z] Node Version:  v10.16.2
[2019-08-10T14:27:19.291Z] Time:          Sat Aug 10 2019 22:27:19 GMT+0800 (GMT+08:00)
[2019-08-10T14:27:19.291Z] ----------------------------------------------------------------------

? Allow Firebase to collect anonymous CLI usage and error reporting information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=850872306&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

? Paste authorization code here: 4/nQGEcTl1E90JoDL3PLrdZtBZkyLRNyPCRDRntoWykvX7NhU3lTNg2wE
[2019-08-10T14:27:35.436Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 code=4/nQGEcTl1E90JoDL3PLrdZtBZkyLRNyPCRDRntoWykvX7NhU3lTNg2wE, client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com, client_secret=j9iVZfS8kkCEFUPaAeJV0sAi, redirect_uri=urn:ietf:wg:oauth:2.0:oob, grant_type=authorization_code
[2019-08-10T14:27:35.442Z] Token Fetch Error: FirebaseError: Server Error. tunneling socket could not be established, cause=socket hang up
    at Request._callback (/Users/brekov/.npm-global/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/Users/brekov/.npm-global/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.onRequestError (/Users/brekov/.npm-global/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at ClientRequest.onError (/Users/brekov/.npm-global/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
```

**Comment by mbleigh** [comment]
The solutions described in #155 cover pretty much all of the known supported proxy workarounds. One option might be to download a service account key for your project and use `GOOGLE_APPLICATION_CREDENTIALS` as described [here](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable). The Firebase CLI will automatically pick up those credentials and use them.

Unfortunately we don't have a good way to debug specific proxy setups. Check that you're setting HTTP/HTTPS proxy environment variables appropriately or try the workaround I suggested, but there's not much else I can suggest that isn't already in #155.

**Comment by galihif** [comment]
Hi @mbleigh , I already set my `GOOGLE_APPLICATION_CREDENTIALS` on my environment but when I try to login firebase CLI, it still not authenticated. Do you know how to solve this?
