### ISSUE TITLE
Local cloudfunctions cannot read from Firestore

### ISSUE THREAD

**Issue by jameskeiger** [firebase/firebase-tools#1613]
### Related issues

Related to firebase/firebase-functions#536 
Differences:
- This happens every time.
- It just started happening today. I upgraded firebase-tools to 7.2.4. I have since downgraded to 7.2.2 and then back again with no effect.
- I also loaded the latest emulator. I believe it was 1.8.0; however since then `firebase setup:emulators:firestore` downloads 1.6.2.
- I cannot downgrade firebase-admin to 7 because ```The Cloud Functions emulator requires the module "firebase-admin" to be version >8.0.0 so your version is too old. You can probably fix this by running "npm install firebase-admin@latest" in your functions directory.```.

### [REQUIRED] Version info

**node:** 
10.16.3

**firebase-functions:** 
3.2.0

**firebase-tools:** 
7.2.2, 7.2.4

**firebase-admin:**
7.4.0, 8.3.0

### [REQUIRED] Test case

```
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import { HttpsError } from "firebase-functions/lib/providers/https";

const firebaseApp = admin.initializeApp({
  credential: admin.credential.applicationDefault()
});

export const broken = functions.https.onRequest(async (request, response) => {
  try {
    console.log(`Looking up doc from firebase...`);
    const doc = await firebaseApp
      .firestore()
      .collection("stuff")
      .doc("somedoc")
      .get();
    console.log(`Got something ${doc}`);
    response.status(200).send(`${doc.exists}`);
    return true;
  } catch (ex) {
    throw new HttpsError("internal", ex);
  }
});


export const brokenPromises = functions.https.onRequest(
  async (request, response) => {
    firebaseApp
      .firestore()
      .collection("stuff")
      .doc("somedoc")
      .get()
      .then(doc => response.status(200).send(`${doc.exists}`))
      .catch(ex => {
        console.error(ex);
        response.status(500).send("Internal server error!");
      });
  }
);

export const working = functions.https.onRequest(async (request, response) => {
  response.status(200).send(`This is working`);
});
```

### [REQUIRED] Steps to reproduce

```
firebase init
# write above code
curl http://localhost:5000/<myproject>/us-central1/broken
curl http://localhost:5000/<myproject>/us-central1/brokenPromises
```

### [REQUIRED] Expected behavior

Returns 200 and doc status. Or at least provides a useful error.

### [REQUIRED] Actual behavior

when calling `/broken`:
```
functions: Error: Error
    at exports.broken.functions.https.onRequest (/Users/jameskeiger/code/reallydoesntwork/functions/lib/index.js:22:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

when calling `/brokenPromises`:
```
 { Error
>      at Http2CallStream.call.on (/Users/jameskeiger/code/reallydoesntwork/functions/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
>      at Http2CallStream.emit (events.js:203:15)
>      at process.nextTick (/Users/jameskeiger/code/reallydoesntwork/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
>      at process._tickCallback (internal/process/next_tick.js:61:11)
>    code: 13,
>    details: '',
>    metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

On my "real app" it looks like this:
```
  Unhandled error { Error
      at Http2CallStream.call.on (/Users/jameskeiger/code/cloudfunctions/functions/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
      at Http2CallStream.emit (events.js:203:15)
      at process.nextTick (/Users/jameskeiger/code/cloudfunctions/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
      at process._tickCallback (internal/process/next_tick.js:61:11)
    code: 13,
    details: '',
    metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

### Were you able to successfully deploy your functions?

Yes, it has worked on the server.

**Comment by jameskeiger** [comment]
Solution:
```unset FIRESTORE_EMULATOR_HOST```

Which is embarrassing because I set that variable. I figured this out by debugging deep into the code and noticing that the http2 session was attempting to connect to `localhost:8080`. This was  because I had set `FIRESTORE_EMULATOR_HOST` while trying to work on something else and neglected to unset it. Leaving this comment for posterity.
