### ISSUE TITLE
ReferenceError: d3 is not defined

### ISSUE THREAD

**Issue by codetraveler3000** [firebase/firebase-tools#1638]
Hello,

I am trying to deploy my React and Firebase app that has D3. I'm using "firebase-functions": "^3.1.0".

I'm getting **ReferenceError: d3 is not defined** and **Error: Error occurred while parsing your function triggers**. I get this same error when I both run firebase serve and firebase deploy.

- I've tried importing D3 at the top of the functions/index.js file, but that didn't work.

- I've tried installing D3 in the functions folder package.json, but that didn't work either.

The full terminal error that I'm getting is:

```
Mac:my-dashboard name$ firebase deploy

=== Deploying to 'my-dashboard-521629'...

i  deploying firestore, functions, hosting
i  firestore: checking firestore.rules for compilation errors...
i  firestore: reading indexes from firestore.indexes.json...
✔  firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  firestore: uploading rules firestore.rules...
✔  firestore: deployed indexes in firestore.indexes.json successfully
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

ReferenceError: d3 is not defined
    at Object.<anonymous> (/Users/name/Desktop/my-dashboard/functions/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/myname/.nvm/versions/node/v12.7.0/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
    at Object.<anonymous> (/Users/myname/.nvm/versions/node/v12.7.0/lib/node_modules/firebase-tools/lib/triggerParser.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)

```

**My functions/index.js is:**

```
//import * as d3 from "d3";  doesn't work

const functions = require('firebase-functions');

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello, Testing 3!");
 });

const svg = d3.select('.canvas')
  .append('svg')
    .attr('width', 600)
    .attr('height', 600);

const graph = svg.append('g')
  .attr('width', graphWidth)
  .attr('height', graphHeight)
  .attr('transform', `translate(${margin.left}, ${margin.top})`);

db.collection('revenue').get().then(res => {

    console.log(res);

 let data = [];
  res.docs.forEach(doc => {
    data.push(doc.data());
  });

});
```

I'm all out of ideas. What do I do? Thank you for your help!

**Comment by codetraveler3000** [comment]
This error is no longer an issue and went away later. Sorry!
