### ISSUE TITLE
UnhandledPromiseRejectionWarning: when the user initializes a Cloud Functions project and does not have enough permissions to enable required APIs 

### ISSUE THREAD

**Issue by Elgarni** [firebase/firebase-tools#1668]
### [REQUIRED] Environment info

**firebase-tools:** 7.3.2

**Platform:** MacOS

### [REQUIRED] Steps to reproduce
```bash
- firebase login # with a user that has the role `Viewer`
- firebase init # choose cloud functions
```
When prompted for the language, just wait a few seconds. Then you will see an UnhandledPromiseRejectionWarning stacktrace.

### [REQUIRED] Expected behavior
The user is notified about lack of permissions, and the rejected promise is handled so that no stacktrace is printed out .

### [REQUIRED] Actual behavior

```bash
? What language would you like to use to write Cloud Functions? (Use arrow keys)
❯ JavaScript 
  TypeScript (node:4901) UnhandledPromiseRejectionWarning: FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (/Users/algarni/repos/open source/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/algarni/repos/open source/firebase-tools/lib/api.js:39:35)
    at Request.self.callback (/Users/algarni/repos/open source/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/algarni/repos/open source/firebase-tools/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/algarni/repos/open source/firebase-tools/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
```
The following two HTTP requests to enable required APIs return 403, and they are not handled in the code.
```bash
[2019-09-22T01:22:24.963Z] >>> HTTP REQUEST POST https://serviceusage.googleapis.com/v1/projects/outdoor-culture/services/cloudfunctions.googleapis.com:enable  
 
[2019-09-22T01:22:24.964Z] >>> HTTP REQUEST POST https://serviceusage.googleapis.com/v1/projects/outdoor-culture/services/runtimeconfig.googleapis.com:enable 

..
..

[2019-09-22T01:22:26.928Z] <<< HTTP RESPONSE BODY code=403, message=The caller does not have permission, status=PERMISSION_DENIED
[2019-09-22T01:22:27.028Z] <<< HTTP RESPONSE BODY code=403, message=The caller does not have permission, status=PERMISSION_DENIED
```

**Comment by bkendall** [comment]
Thanks for the PR. I [fixed](https://github.com/firebase/firebase-tools/commit/92cdaf9a6645f715d4bb445bb72db1ce48fe67a1#diff-afa1f559219191ab5828cc94bf0f6d50) the unhandled promise in #1790.
