### ISSUE TITLE
UnhandledPromiseRejectionWarning: FirebaseError: Task

### ISSUE THREAD

**Issue by ivalsaraj** [firebase/firebase-tools#1670]
### Environment info

**firebase-tools:**
Version: 7.3.2

**Platform:**
macOS: 10.14.6
### Test case
I tried to upload files to firebase hosting with `firebase deploy --only hosting` which throws error.

### Steps to reproduce

I tried to upload files to firebase hosting with `firebase deploy --only hosting`. In my files I have symlinks, **one of the symlink points to a file that doesn't exist**. This causes error.
###  Expected behavior

Upload files without any issues.

### Actual behavior
Throws UnhandledPromiseRejectionWarning: FirebaseError: Task

```
=== Deploying to 'project'...

i  deploying hosting
i  hosting[project]: beginning deploy...
i  hosting[project]: found 141 files in client/build

Error: Task scripts/symlink-file.js.map failed: retries exhausted after 1 attempts
(node:56592) UnhandledPromiseRejectionWarning: FirebaseError: Task scripts/symlink-file.js.map failed: retries exhausted after 1 attempts
    at Queue.<anonymous> (/Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:189:27)
    at Generator.next (<anonymous>)
    at /Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:3:12)
    at Queue.executeTask (/Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:180:16)
    at Queue.<anonymous> (/Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:93:36)
    at Generator.next (<anonymous>)
    at /Users/user/.nvm/versions/node/v12.9.1/lib/node_modules/firebase-tools/lib/throttler/throttler.js:7:71
    at new Promise (<anonymous>)
(node:56592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:56592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samtstern** [comment]
@ivalsaraj sorry about our really slow response here!

It sounds like you know the issue: "one of the symlink points to a file that doesn't exist"

Is this on purpose?  Is this something you could fix?  Or could you maybe exclude this symlink from your hosting build?

**Comment by bkendall** [comment]
To be clear, we should fix the unhandled promise, but I don't think Hosting/the CLI supports symlinks in the deployed project.

**Comment by ivalsaraj** [comment]
Thank you for the response.

Yes, I could find the problem. But it took me time to debug the underlying issue. 

Fixing unhandled promise rejection and provide a valid error message would be great for developers to find the issue easily.

**Comment by ivalsaraj** [comment]
@bkendall Let me clear that, firebase hosting might support symlinks. I don't know how. But the symlinks the hosted could work for me.

**Comment by tuananhlhpnd99** [comment]
I suffer from this issue too and it turned out that I left an unused symlink in the public folder. After removing that symlink, things worked just fine. I think that is time to close the issue.

**Comment by ivalsaraj** [comment]
@tuananhlhpnd99 Yeah, that's pretty a head ache for developer, also wastes hours and hours of time to find out the right issue.

@Firebase team, If you guys can show a proper warning or error message will help to save the time instead of unhandled promise reject warning
