### ISSUE TITLE
Firebase emulator should indicate android:usesCleartextTraffic="true" required for certain API versions

### ISSUE THREAD

**Issue by noelmansour** [firebase/firebase-tools#1678]
### [REQUIRED] Environment info
**firebase-tools:** 7.4.0
**Platform:** macOS

### [REQUIRED] Test case

Use the quickstart functions project:
https://github.com/firebase/quickstart-android/tree/master/functions

Update the firebase-admin library to 8.6.0, firebase-functions library to 3.2.0 in the functions dir.

Explicitly add a node version for the engine to functions/packages.json:
```json
"engines": {
  "node": "8"
},
```

Install the node modules in the functions dir: ```npm install```

In the android project's MainActivity.java, after this line of code, https://github.com/firebase/quickstart-android/blob/a1074212f0ec271d57bdf91f851f5e8e1be4b09c/functions/app/src/main/java/com/google/samples/quickstart/functions/java/MainActivity.java#L94

add this:

```java
mFunctions.useFunctionsEmulator("http://10.0.2.2:5001");
```

Update google-services.json to use your own firebase project.

### [REQUIRED] Steps to reproduce

1. Start the firebase emulators using `firebase --project your-project emulators:start`
2. Install the app on the android emulator with an API >= 28 using `./gradlew :app:installDebug`
3. Launch the app
4. Within the app, open the "Java" version and attempt to calculate the sum of two numbers.

### [REQUIRED] Expected behavior

The emulated addNumbers function will run.

### [REQUIRED] Actual behavior

The emulated addNumbers function doesn't run.

An "INTERNAL" FirebaseFunctionsException is thrown when trying to call the function:

```
    com.google.firebase.functions.FirebaseFunctionsException: INTERNAL
        at com.google.firebase.functions.FirebaseFunctions$2.onFailure(com.google.firebase:firebase-functions@@19.0.1:270)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.UnknownServiceException: CLEARTEXT communication to 10.0.2.2 not permitted by network security policy
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
```

### Additional info

- The [documentation](https://firebase.google.com/docs/emulator-suite/connect_and_prototype#instrument_your_app_to_talk_to_the_emulators) indicates that this line should be used to point the app to the firebase emulator: ```FirebaseFunctions.getInstance().useFunctionsEmulator("10.0.2.2:5001");```. However, this results in a MalformedURLException. Prefixing it with "http://" makes the error go away, but then the INTERNAL error is thrown.
- The demo from the firebase summit https://youtu.be/wO70Pnv0yeo?t=1037 uses the line without the protocol and it seems to work fine.
- Going to `http://10.0.2.2:5001/your-project/us-central1/addNumbers` in the chrome app in the android emulator will trigger the function. It gives an error because of the missing arguments, but that's to be expected. Perhaps this indicates that this is actually a problem with the firebase-android-sdk?

### Update

Not sure how I missed the CLEARTEXT message in the stack trace. The documentation should probably be updated to indicate that either an older API emulator should be used or to update the manifest to allow clear text traffic as per https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

There's also still the issue of the documentation not including the http protocol.

**Comment by samtstern** [comment]
Thanks for filing such a detailed issue.  Are you signed in to Firebase
Auth when you make the request?  If you are, could you try it signed out?
Wondering if this has to do with authentication.

**Comment by noelmansour** [comment]
@samtstern It looks like you replied via email, looking at an outdated version of this issue. I edited the original issue as I found the source of bug (it's related to certain versions of android not allowing clear text traffic).

**Comment by samtstern** [comment]
@noelmansour thanks for figuring that out!

**Comment by samtstern** [comment]
cc @markarndt looks like we need to add a warning to the docs about use of `http` traffic on certain versions of Android.  I believe this is only an issue with Functions since it goes through a third-party HTTP library which respects this setting.  Looks like RTDB and Firestore don't (at the moment).

**Comment by markarndt** [comment]
See https://firebase.google.com/docs/emulator-suite/connect_and_prototype?database=RTDB#instrument_your_app_to_talk_to_the_emulators.

**Comment by samtstern** [comment]
@markarndt updated the docs to mention this cleartext constraint, so closing the issue.  Thanks @noelmansour !

**Comment by samtstern** [comment]
Wow ... jynx.  We did that at the same time.

**Comment by jQrgen** [comment]
@samtstern currently struggling with this, could you add a snipped for cleartext whitelisting? Thanks

**Comment by samtstern** [comment]
@jQrgen added a snippet here:
https://github.com/firebase/quickstart-android/issues/562#issuecomment-607819116

**Comment by jQrgen** [comment]
Thanks, works now

**Comment by jarrodonlo** [comment]
Just as a note... having same issue with Firebase `Storage` emulator. This thread seems to mainly focus on Firebase `Functions`, but it looks to be effecting storage as well. Here's my debug error
`W/NetworkRequest( 9632): error sending network request GET http://10.0.2.2:9199/v0/b/default-bucket/o/cat.jpg
W/NetworkRequest( 9632): java.io.IOException: Cleartext HTTP traffic to 10.0.2.2 not permitted
`

Maybe I'm missing something, but it seems like all the workarounds involved enabling clearText which seems like a security venerability. Is there a way to enable only in dev/test mode?
