### ISSUE TITLE
functions:shell not starting

### ISSUE THREAD

**Issue by Sof31t** [firebase/firebase-tools#1696]
### [REQUIRED] Environment info

**node:** v8.14.0

**firebase-tools:** 7.4.0

**Platform:** macOS

### [REQUIRED] Test case
Example is provided in next section
### [REQUIRED] Steps to reproduce

When I enter `firebase functions:shell` following output is coming

![image](https://user-images.githubusercontent.com/4134078/66325680-f54d7000-e927-11e9-9e22-8920f3c224ce.png)

After that its stuck
I have set the GOOGLE_APPLICATION_CREDENTIALS

### [REQUIRED] Expected behavior
Emulator starts

### [REQUIRED] Actual behavior
It is stuck and doesn't start.

Running the same command with `debug` will result with this output:
```
[2019-10-07T15:33:09.947Z] DEBUG: [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.2.0","resolution":"/path_to_my_project/functions/node_modules/firebase-functions/lib/index.js"}
⚠  Error: Cannot find module './lib/isAlpha'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/validator/index.js:36:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/express-validator/check/check.js:1:81)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/express-validator/check/validation-chain-builders.js:1:77)
    at Module._compile (module.js:653:30)
⚠  We were unable to load your functions code. (see above)
```

**Comment by Sof31t** [comment]
Running the same command with `debug` will result with this output:
```
[2019-10-07T15:33:09.947Z] DEBUG: [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.2.0","resolution":"/path_to_my_project/functions/node_modules/firebase-functions/lib/index.js"}
⚠  Error: Cannot find module './lib/isAlpha'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/validator/index.js:36:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/express-validator/check/check.js:1:81)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path_to_my_project/functions/node_modules/express-validator/check/validation-chain-builders.js:1:77)
    at Module._compile (module.js:653:30)
⚠  We were unable to load your functions code. (see above)
```
