### ISSUE TITLE
emulators:exec does not run provided script

### ISSUE THREAD

**Issue by alexisbg** [firebase/firebase-tools#1700]
### [REQUIRED] Environment info

**firebase-tools:** 7.4.0
**Node.js:** v10.13.0
**Ubuntu Java:** OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
**Windows 10 Java:** OpenJDK Runtime Environment (Zulu 8.33.0.1-win64) (build 1.8.0_192-b01)

**Platform:** Ubuntu 18.04 WSL and Windows 10

### [REQUIRED] Test case

On Ubuntu 18.04 WSL only, emulators:exec does not run provided script (eg: npm test). But it works fine on Windows 10.

The problem remains the same when:
npm absolute path is provided.
--only firestore flag is removed.
Windows firewall is disabled.
The antivirus is disabled.

### [REQUIRED] Steps to reproduce

```bash
firebase emulators:exec --only firestore "npm test"
```

### [REQUIRED] Expected behavior

Windows 10 output:
```bash
i  Starting emulators: ["firestore"]
i  firestore: Serving WebChannel traffic on at http://localhost:8081
i  firestore: Emulator logging to firestore-debug.log
+  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  Running script: npm test

...

+  Script exited successfully (code 0)
i  Shutting down emulators.
i  Stopping firestore emulator
!  firestore emulator has exited upon receiving signal: SIGINT
```

### [REQUIRED] Actual behavior
Ubuntu 18.04 WSL output:
```bash
i  Starting emulators: ["firestore"]
i  firestore: Serving WebChannel traffic on at http://localhost:8081
i  firestore: Emulator logging to firestore-debug.log
i  Shutting down emulators.

Error: TIMEOUT: Port 8080 was not active within 30000ms
```

With --debug flag:
```bash
[2019-10-08T08:36:25.049Z] ----------------------------------------------------------------------
[2019-10-08T08:36:25.055Z] Command:       /home/alexis/.nvm/versions/node/v10.13.0/bin/node /home/alexis/.nvm/versions/node/v10.13.0/bin/firebase --debug emulators:exec --only firestore npm test
[2019-10-08T08:36:25.056Z] CLI Version:   7.4.0
[2019-10-08T08:36:25.057Z] Platform:      linux
[2019-10-08T08:36:25.057Z] Node Version:  v10.13.0
[2019-10-08T08:36:25.356Z] Time:          Tue Oct 08 2019 09:36:25 GMT+0100 (GMT+01:00)
[2019-10-08T08:36:25.357Z] ----------------------------------------------------------------------

i  Starting emulators: ["firestore"]
i  firestore: Serving WebChannel traffic on at http://localhost:8081
[2019-10-08T08:36:25.412Z] Ignoring unsupported arg: projectId
[2019-10-08T08:36:25.412Z] Ignoring unsupported arg: auto_download
[2019-10-08T08:36:25.412Z] Starting emulator firestore with command {"binary":"java","args":["-Duser.language=en","-jar","/home/alexis/.cache/firebase/emulators/cloud-firestore-emulator-v1.8.4.jar","--host","localhost","--port",8080,"--rules","/mnt/c/nix/Dev/js/tests/cra-firestore-w-auth/firestore.rules","--webchannel_port",8081],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator"]}
i  firestore: Emulator logging to firestore-debug.log
[2019-10-08T08:36:27.010Z] API endpoint: http://localhost
[2019-10-08T08:36:27.011Z] :8080
WebChannel endpoint: http://localhost:8081
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

[2019-10-08T08:36:27.011Z]
   export FIRESTORE_EMULATOR_HOST=localhost:8080

Dev App Server is now running.


[2019-10-08T08:36:56.222Z] Error in emulators:exec FirebaseError: TIMEOUT: Port 8080 was not active within 30000ms
    at Object.<anonymous> (/home/alexis/.nvm/versions/node/v10.13.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:54:15)
    at Generator.next (<anonymous>)
    at fulfilled (/home/alexis/.nvm/versions/node/v10.13.0/lib/node_modules/firebase-tools/lib/emulator/controller.js:4:58)
i  Shutting down emulators.

Error: TIMEOUT: Port 8080 was not active within 30000ms
```

**Comment by samtstern** [comment]
@alexisbg this looks to be the same issue as #1458 which will be fixed in the next release (some time this week).
