### ISSUE TITLE
firebase init locks my dist/App folder after being generated and gives error

### ISSUE THREAD

**Issue by timucincicek** [firebase/firebase-tools#1736]
### [REQUIRED] Environment info

**firebase-tools:**
7.6.1

**Platform:**
Angular 8.2.3
### [REQUIRED] Test case

I tried to deploy my angular application on firebase hosting but I recieved error like below

`An unhandled exception occurred: EBUSY: resource busy or locked, rmdir`
### [REQUIRED] Steps to reproduce
`firebase init`(already logged in and before /dist folder created)

firebase hosting selected

directory name I gave like `dist/AppName`

then its done.Created `dist `folder under my App's folder and `index.html`

after that by `cd `command,changed directory as `dist/AppName` and

### [REQUIRED] Expected behavior

After ` ng build --prod`  for `dist/App` folder which created after firebase init,I should've been generated my dist folder succesfully.

### [REQUIRED] Actual behavior

`ng build --prod` command I applied to generate dist folder and its files but I recieved that error above I mentioned.I googled and they said some app is using this directory thats why its busy but this just happens when I do `firebase init` seems like it locks this directory and doesnt allow me to edit.Until this time I used to deploy succesfully exactly in this same way,I didn't understand what changed and why I get this error.Here that .log file below maybe makes sense to you.Also all those solutions on the internet and here as well,didn't work for me

**.log File**

```
[error] Error: EBUSY: resource busy or locked, rmdir 'C:\Users\timucin.cicek\Documents\MatApp\dist\MatApp'
    at Object.rmdirSync (fs.js:684:3)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\Users\timucin.cicek\Documents\MatApp\node_modules\@angular-devkit\core\node\host.js:207:28)
    at Observable._trySubscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\operators\mergeMap.js:39:23)
    at Observable.subscribe (C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\Observable.js:25:31)
    at C:\Users\timucin.cicek\Documents\MatApp\node_modules\rxjs\internal\util\subscribeTo.js:22:31
```

**Comment by bkendall** [comment]
I'm not sure I have enough information to reproduce this issue.

`firebase init` doesn't "lock" the directory, nor does it hold on to any references in the background that would cause this issue. I would look for other things that may have the folder open, but this doesn't seem to be related to the CLI - sorry.
