### ISSUE TITLE
firebase-tools crashes on supported GCF node version

### ISSUE THREAD

**Issue by inlined** [firebase/firebase-tools#1743]
### [REQUIRED] Environment info

**firebase-tools:** <crash>. package.json says it's 7.6.1

**Platform:** Mac OS

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

```
nvm install 8.15.0
nvm use 8.15.0
npm install -g firebase-tools
firebase --version # or any other command
```

### [REQUIRED] Expected behavior

Command to run

### [REQUIRED] Actual behavior

Crash on startup, because dependency uses the spread operator before it is available on all GCF supported versions of Node. e.g.:

```
/Users/inlined/.nvm/versions/node/v8.0.0/lib/node_modules/firebase-tools/node_modules/picomatch/lib/picomatch.js:54
    let ignoreOpts = { ...options, ignore: null, onMatch: null, onResult: null };
                       ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/inlined/.nvm/versions/node/v8.0.0/lib/node_modules/firebase-tools/node_modules/picomatch/index.js:3:18)
```

**Comment by inlined** [comment]
My mistake. The problem only happens on node 8.0.0
