### ISSUE TITLE
firebase login : an unexpected error occured

### ISSUE THREAD

**Issue by amar-belkhede** [firebase/firebase-tools#1765]
### [REQUIRED] Environment info

**firebase-tools:**
$ firebase --version
7.6.2

**Platform:** windows

### [REQUIRED] Test case

there was similar issues #1442

### [REQUIRED] Steps to reproduce

after installing firebase-tools, when we try to login using
**firebase login**
unexpected error occurred

### [REQUIRED] Expected behavior

I should have been authenticated and my account should have linked to firebase cli

### [REQUIRED] Actual behavior

**an unexpected error occurred get shown**

**C:\Users\Amar>firebase --debug login**
[2019-11-04T09:50:50.203Z] ----------------------------------------------------------------------
[2019-11-04T09:50:50.209Z] Command: C:\Program Files\nodejs\node.exe C:\Users\Amar\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js --debug login
[2019-11-04T09:50:50.211Z] CLI Version: 7.6.2
[2019-11-04T09:50:50.212Z] Platform: win32
[2019-11-04T09:50:50.212Z] Node Version: v12.13.0
[2019-11-04T09:50:50.215Z] Time: Mon Nov 04 2019 15:20:50 GMT+0530 (India Standard Time)
[2019-11-04T09:50:50.216Z] ----------------------------------------------------------------------
[2019-11-04T09:50:50.218Z]
i Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? Yes
i To change your data collection preference at any time, run firebase logout and log in again.

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprocts.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=505538794&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
[2019-11-04T09:50:53.753Z] Error: spawn cmd ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

Error: An unexpected error has occurred.

**I do have added the path C:\Users\Amar\AppData\Roaming\npm**

**Comment by doseum** [comment]
Hello I have same error with you
Can you tell me how did you solve this error?

**Comment by user-aj** [comment]
I also got some error like this so i did a lot of research i was able to overcome them using the following

1.**Modify your environment variables** (go to Power User Tasks Menu -System=Advanced system settings), edit PATH add 

> C:\Program Files;C:\Winnt;C:\Winnt\System32; C:\Users\Amar\AppData\Roaming\npm

   

separated by semicolon

2.Also  Run  command  as **admin** using the  Power User Tasks Menu not as guest (**important**)

If this does not work then try updating npm to the recent ones

**Comment by feelthecoder** [comment]
Still not working . Can anyone help.?
