### ISSUE TITLE
Internal error when using `firebase serve` command

### ISSUE THREAD

**Issue by smixqse** [firebase/firebase-tools#1771]
### [REQUIRED] Environment info

**firebase-tools:** 7.6.2

**Platform:** Windows

### [REQUIRED] Test case

Create a new Firebase folder, initialize it with Functions and Hosting, and run `firebase serve`, even with the default helloWorld function.

### [REQUIRED] Steps to reproduce

1: Create a new folder
2: Run `firebase init` and mark Functions and Hosting features without TypeScript for functions.
3: Run `firebase serve`

### [REQUIRED] Expected behavior

It serves the static pages and functions locally.

### [REQUIRED] Actual behavior

I get a TypeError and some errors involving "swarm", which i don't know what it is.
Serving ONLY the functions works: `firebase serve --only functions`

Logs:
```[debug] [2019-11-05T20:15:15.044Z] ----------------------------------------------------------------------
[debug] [2019-11-05T20:15:15.110Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2019-11-05T20:15:15.111Z] CLI Version:   7.6.2
[debug] [2019-11-05T20:15:15.111Z] Platform:      win32
[debug] [2019-11-05T20:15:15.111Z] Node Version:  v10.17.0
[debug] [2019-11-05T20:15:15.915Z] Time:          Tue Nov 05 2019 18:15:15 GMT-0200 (GMT-02:00)
[debug] [2019-11-05T20:15:15.915Z] ----------------------------------------------------------------------
[debug] [2019-11-05T20:15:15.915Z] 
[debug] [2019-11-05T20:15:16.083Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-11-05T20:15:16.084Z] > authorizing via signed-in user
[debug] [2019-11-05T20:15:16.084Z] [iam] checking project my-project for permissions ["firebase.projects.get"]
[debug] [2019-11-05T20:15:16.088Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/my-project:testIamPermissions  

[debug] [2019-11-05T20:15:20.059Z] <<< HTTP RESPONSE 200
[debug] [2019-11-05T20:15:20.062Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/my-project  
 
[debug] [2019-11-05T20:15:21.725Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from 'C:\Users\user\Criação\my-project'...
[info] 
[debug] [2019-11-05T20:15:21.835Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/my-project/webApps/-/config  
 
[debug] [2019-11-05T20:15:23.521Z] <<< HTTP RESPONSE 200
[info] +  functions: Using node@10 from host.
[info] i  hosting: Serving hosting files from: public
[info] +  hosting: Local server: http://localhost:5000
[info] +  functions: Emulator started at http://localhost:5001
[info] i  functions: Watching "C:\Users\user\Criação\my-project\functions" for Cloud Functions...
[debug] [2019-11-05T20:15:26.526Z] [worker-~diagnostic~-c39a3358-0b34-424c-966e-666504951316]: BUSY
[debug] [2019-11-05T20:15:26.656Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:26.665Z] [worker-swarm-828ab357-3022-41b2-8af4-7d5a9cd117c0]: BUSY
[debug] [2019-11-05T20:15:27.524Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:27.532Z] [worker-swarm-3378c4e5-5336-4b9a-81ad-19553672e94f]: BUSY
[debug] [2019-11-05T20:15:28.087Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:28.088Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:28.523Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:28.523Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:28.728Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:28.732Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:28.748Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:28.753Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:28.917Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.322Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.323Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.324Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.326Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.328Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:29.328Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:30.517Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:30.525Z] [worker-swarm-91182be4-dfb3-41ef-98e9-6f7dac3d5ed7]: BUSY
[debug] [2019-11-05T20:15:31.461Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:31.465Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:31.473Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:31.477Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:31.479Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:33.515Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:33.523Z] [worker-swarm-d67dc3df-09b4-4e12-8981-ca11af2739a5]: BUSY
[debug] [2019-11-05T20:15:34.629Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:34.633Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:34.641Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:34.645Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:34.647Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:36.515Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:36.523Z] [worker-swarm-e55edf35-3c2a-433a-a679-61614476f6c9]: BUSY
[debug] [2019-11-05T20:15:37.924Z] [runtime-status] Functions runtime initialized. {"cwd":"C:\\Users\\user\\Criação\\my-project\\functions","node_version":"10.17.0"}
[debug] [2019-11-05T20:15:37.929Z] [runtime-status] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"admin_stubs":true} {}
[debug] [2019-11-05T20:15:37.936Z] [runtime-status] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.7.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-admin\\lib\\index.js"}
[debug] [2019-11-05T20:15:37.940Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:37.942Z] [runtime-status] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"C:\\Users\\user\\Criação\\my-project\\functions\\node_modules\\firebase-functions\\lib\\index.js"}
[debug] [2019-11-05T20:15:39.515Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
[debug] [2019-11-05T20:15:39.523Z] [worker-swarm-8fcf63ee-85bc-4988-8a15-b4fc95dc8db6]: BUSY
[warn] !  functions: Could not find trigger "swarm" in your functions directory.
[warn] !  Your function was killed because it raised an unhandled error.
[warn] !  functions: Could not find trigger "swarm" in your functions directory.
[warn] !  Your function was killed because it raised an unhandled error.
[info] i  functions: Beginning execution of "swarm"
[warn] !  functions: Could not find trigger "swarm" in your functions directory.
[warn] !  Your function was killed because it raised an unhandled error.
[info] i  functions: Beginning execution of "swarm"
[warn] !  functions: TypeError: Cannot read property 'definition' of undefined
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:648:30
    at Generator.next (<anonymous>)
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at invokeTrigger (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:640:12)
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:757:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [2019-11-05T20:15:40.920Z] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\node_modules\express\lib\response.js:170:12)
    at EventEmitter.worker.onLogs (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:96:37)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.emit (domain.js:448:20)
    at lines.slice.forEach (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:526:21)
    at Array.forEach (<anonymous>)
    at onData (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:524:28)
    at ChildProcess.childProcess.on (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:485:9)
[error] 
[error] Error: An unexpected error has occurred.
[warn] !  functions: Could not find trigger "swarm" in your functions directory.
[warn] !  Your function was killed because it raised an unhandled error.
[info] i  functions: Beginning execution of "swarm"
[warn] !  functions: TypeError: Cannot read property 'definition' of undefined
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:648:30
    at Generator.next (<anonymous>)
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at invokeTrigger (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:640:12)
    at C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:757:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [2019-11-05T20:15:41.939Z] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\node_modules\express\lib\response.js:170:12)
    at EventEmitter.worker.onLogs (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:96:37)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.emit (domain.js:448:20)
    at lines.slice.forEach (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:526:21)
    at Array.forEach (<anonymous>)
    at onData (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:524:28)
    at ChildProcess.childProcess.on (C:\Users\user\AppData\Roaming\nvm\v10.17.0\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:485:9)
[error] 
[error] Error: An unexpected error has occurred.
[info] +  functions[helloWorld]: http function initialized (http://localhost:5001/my-project/us-central1/helloWorld).
```

**Comment by samtstern** [comment]
@smixqse could you show your `firebase.json` file?

What's happening is we are getting a request like this:
```
[debug] [2019-11-05T20:15:26.656Z] Accepted request POST /api/v0/swarm/peers?stream-channels=true --> swarm
```

We are interpreting this as a request that should go to a Cloud Function called "swarm" but it appears that function does not exist.  So it seems like there is some error in how the request is being routed.  I t's either a bug in our code or something you have specified in your configuration.

**Comment by samtstern** [comment]
Also when I google `/api/v0/swarm/peers?stream-channels=true` I get a lot of results about IPFS ... which I don't understand at all but I suspect is involved here.

**Comment by smixqse** [comment]
I've tested it with different projects, without changing the default configuration created using `firebase init`, and i couldn't find in the default files anything including `swarm`.

Here's `firebase.json` from the original project i was trying to serve locally:

```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      
    ]
  }
}
```

And another i got while testing different options in the initialization which still produces the same error:

```json
{
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

**Comment by smixqse** [comment]
> Also when I google `/api/v0/swarm/peers?stream-channels=true` I get a lot of results about IPFS ... which I don't understand at all but I suspect is involved here.

Well, i have `go-ipfs` installed but i've never used it with Firebase, and it was not running while doing the tests.

**Comment by samtstern** [comment]
Hmmm ok I wonder if there is something else on your machine that's hitting this port without your knowing?  Could you try `firebase serve --port=9000` and see if that works?

**Comment by smixqse** [comment]
Okay, I realized what was happening. I totally forgot i had `IPFS Companion` in my browser, which was pinging the same port as Firebase without me knowing. It is working now, thank you and sorry for this.

**Comment by samtstern** [comment]
@smixqse glad it's working now!  There's still actually a bug here because we shouldn't be matching such a broad set of URLs.  I will file a new issue to track this.
