### ISSUE TITLE
firebase-tools not installing, other npm packages are properly installing

### ISSUE THREAD

**Issue by ishandutta2007** [firebase/firebase-tools#1820]
$ `node -v`
v8.11.1

$ `npm -v`
5.6.0

$ `npm i -g firbase-tools@4.0.0`

> npm ERR! code E404
> npm ERR! 404 Not Found: firbase-tools@4.0.0
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/ishandutta2007/.npm/_logs/2019-11-20T05_37_29_883Z-debug.log
> 

$ `tail -10  /Users/ishandutta2007/.npm/_logs/2019-11-20T05_37_29_883Z-debug.log`

> /Users/ishandutta2007/.npm/_logs/2019-11-20T05_37_29_883Z-debug.log
> 9 verbose stack     at tryOnImmediate (timers.js:752:5)
> 9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
> 10 verbose cwd /Users/ishandutta2007/Documents/Projects/social-money-maker-angular
> 11 verbose Darwin 17.7.0
> 12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "firbase-tools@4.0.0"
> 13 verbose node v8.11.1
> 14 verbose npm  v5.6.0
> 15 error code E404
> 16 error 404 Not Found: firbase-tools@4.0.0
> 17 verbose exit [ 1, true ]

**Comment by ishandutta2007** [comment]
My bad it was a typo ; it should be `firebase-tools` not `firbase-tools`
