### ISSUE TITLE
Failed to publish event for trigger - functions Emulator host/port is not configured

### ISSUE THREAD

**Issue by xar** [firebase/firebase-tools#1877]
### [REQUIRED] Environment info

**firebase-tools:7.11.0**

**Platform:macOs**

### [REQUIRED] Test case

Currently firestore triggered cloud functions don't work in emulator locally.

### [REQUIRED] Steps to reproduce

When I run:
`npm run build && firebase serve --only firestore,functions`

then I'm able to start firestore & functions emulators. With working firestore and functions triggered via http / onCall.

But functions which should be triggered by friestore document changes are not triggered. Although after start I see: 
`✔  functions[****]: firestore function initialized.`

When I add new document - in firebase-debug.log I see:
`Dec 22, 2019 9:33:53 PM com.google.cloud.datastore.emulator.impl.events.EventLogger publishEvent
WARNING: Failed to publish event for trigger **** because Functions Emulator host/port is not configured.`

### [REQUIRED] Expected behavior

Emulated functions triggers correctly on firestore changes

### [REQUIRED] Actual behavior

`firebase serve --only firestore,functions`
`WARNING: Failed to publish event for trigger **** because Functions Emulator host/port is not configured.`

**Comment by samtstern** [comment]
If you use the emulators:start command instead of serve does this work?

**Comment by xar** [comment]
`firebase emulators:start --only functions,firestore` 

```
i  emulators: Starting emulators: functions, firestore
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5000
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: Emulator logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
```

But functions emulator won't start It says that I need to compile code before run(using typescript functions). But I had run `npm run build` before and I see compiled code in `functions/lib/**/*.js`

```
⚠  TypeError: instance.registerVersion is not a function
    at registerDatabase (..../functions/node_modules/@firebase/database/dist/index.node.cjs.js:15188:14)
    at Object.<anonymous> (..../functions/node_modules/@firebase/database/dist/index.node.cjs.js:15200:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at FirebaseNamespace.get [as database] (..../functions/node_modules/firebase-admin/lib/firebase-namespace.js:282:38)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
```

**Comment by xar** [comment]
For some reason the `functionsPort` in `firestoreEmulator` is undefined although is running via `serve` command and seems ok by console output.
https://github.com/firebase/firebase-tools/blob/141229c825aade9f548622bfa5da0690011988fd/src/emulator/firestoreEmulator.ts#L19

When I try to change `functionsPort` manually to `localhost:8080` function gets triggered correctly

**Comment by samtstern** [comment]
@xar sorry for the slow response here, was out of the office on vacation.

If the Functions emulator is failing to start then `functionsPort === undefined` is correct, since that should be the port of the running emulator.

Can you show me:

- Your `package.json` file
- The main compiled `functions/lib/index.js` file (or wherever your main functions file is)

That will help me figure out what's failing.

**Comment by xar** [comment]
@samtstern No problem! I'm also sorry I have forgot about this issue.

Current status: is that when i change `functionsPort` manually functions gets triggered. But It doesn't work out of the box...
`index.js`
```
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const functions = __importStar(require("firebase-functions"));
const nodemailer = __importStar(require("nodemailer"));
const v4_1 = __importDefault(require("uuid/v4"));
const Company_typings_1 = require("../../src/services/Company.typings");
const support_1 = require("./support");
const db_1 = require("./db");
const user_1 = require("./user");
const newsfeed_1 = require("./newsfeed");

exports.support = support_1.Support;
exports.user = user_1.userApi;
exports.newsFeed = newsfeed_1.newsFeedApi;
//# sourceMappingURL=index.js.map
```


`package.json` - in functions folder
```
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "watch": "cross-env NODE_ENV=local tsc --watch",
    "serve:local": "npm run build && cross-env NODE_ENV=local firebase serve --only functions",
    "emulator:firestore": "firebase emulators:start --only firestore",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/functions/src/index.js",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.3.0",
    "nodemailer": "^6.3.1",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@firebase/database": "^0.5.17",
    "@types/nodemailer": "^6.2.1",
    "@types/uuid": "^3.4.5",
    "cross-env": "^6.0.3",
    "firebase-functions-test": "^0.1.6",
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
  "private": true
}
```

**Comment by samtstern** [comment]
Thanks for the extra info.  This is still a total mystery to me but definitely sounds like there's a bug somewhere.

**Comment by samtstern** [comment]
@xar I apologize for the delay here ... can you run the command again with the `--debug` flag:
```
firebase --debug emulators:start --only functions,firestore
```

Then reproduce the issue and show me the logs?

**Comment by xar** [comment]
No problem,

attaching log - before starting emulator I have run `tsc` - typescript compilation
```
 firebase --debug emulators:start --only functions,firestore
[2020-01-24T09:29:18.256Z] ----------------------------------------------------------------------
[2020-01-24T09:29:18.259Z] Command:       /Users/samovrablik/.nvm/versions/node/v10.15.1/bin/node /Users/samovrablik/.nvm/versions/node/v10.15.1/bin/firebase --debug emulators:start --only functions,firestore
[2020-01-24T09:29:18.259Z] CLI Version:   7.11.0
[2020-01-24T09:29:18.259Z] Platform:      darwin
[2020-01-24T09:29:18.259Z] Node Version:  v10.15.1
[2020-01-24T09:29:18.260Z] Time:          Fri Jan 24 2020 10:29:18 GMT+0100 (Central European Standard Time)
[2020-01-24T09:29:18.260Z] ----------------------------------------------------------------------
[2020-01-24T09:29:18.260Z] 
[2020-01-24T09:29:18.270Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-01-24T09:29:18.271Z] > authorizing via signed-in user
i  emulators: Starting emulators: functions, firestore
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5000
FUNCTIONS 5000
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
[2020-01-24T09:29:18.581Z] Ignoring unsupported arg: projectId
[2020-01-24T09:29:18.581Z] Ignoring unsupported arg: auto_download
[2020-01-24T09:29:18.581Z] Starting emulator firestore with command {"binary":"java","args":["-Duser.language=en","-jar","/Users/samovrablik/.cache/firebase/emulators/cloud-firestore-emulator-v1.10.2.jar","--host","localhost","--port",8080,"--rules","/project-11/firestore.rules","--functions_emulator","localhost:5000","--webchannel_port",8081],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator"],"joinArgs":false}
i  firestore: Emulator logging to firestore-debug.log
[2020-01-24T09:29:20.218Z] API endpoint: http://localhost:
[2020-01-24T09:29:20.218Z] 8080
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:8080

Dev App Server is now running.


✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  functions: Watching "/project-11/functions" for Cloud Functions...
[2020-01-24T09:29:20.361Z] [worker-pool] addWorker(~diagnostic~)
[2020-01-24T09:29:20.361Z] [worker-pool] Adding worker with key ~diagnostic~, total=1
[2020-01-24T09:29:20.362Z] [worker-pool] submitWork(triggerId=)
[2020-01-24T09:29:20.362Z] [worker-~diagnostic~-6f2489cb-9b51-4daf-8372-e717d21e4b3e]: Assigning socketPath: /var/folders/7h/kxlvz1896wz6nh0hd756m_2c0000gn/T/fire_emu_61710.sock
[2020-01-24T09:29:20.363Z] [worker-~diagnostic~-6f2489cb-9b51-4daf-8372-e717d21e4b3e]: BUSY
[2020-01-24T09:29:20.660Z] [runtime-status] [61710] Functions runtime initialized. {"cwd":"/project-11/functions","node_version":"10.15.1"}
[2020-01-24T09:29:20.662Z] [runtime-status] [61710] Disabled runtime features: undefined
[2020-01-24T09:29:20.666Z] [runtime-status] [61710] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.9.0","resolution":"/project-11/functions/node_modules/firebase-admin/lib/index.js"}
[2020-01-24T09:29:20.668Z] [runtime-status] [61710] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"/project-11/functions/node_modules/firebase-functions/lib/index.js"}
⚠  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to /Users/samovrablik/...... Non-emulated services will access production using these credentials. Be careful!
[2020-01-24T09:29:21.009Z] [runtime-status] [61710] Found google-gax at /project-11/functions/node_modules/google-gax/build/src/index.js
[2020-01-24T09:29:21.009Z] [runtime-status] [61710] Outgoing network have been stubbed. [{"name":"http","status":"mocked"},{"name":"http","status":"mocked"},{"name":"https","status":"mocked"},{"name":"https","status":"mocked"},{"name":"net","status":"mocked"},{"name":"google-gax","status":"mocked"}]
[2020-01-24T09:29:21.068Z] [runtime-status] [61710] Checked functions.config() {"config":{}}
[2020-01-24T09:29:21.070Z] [runtime-status] [61710] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"/project-11/functions/node_modules/firebase-functions/lib/index.js"}
[2020-01-24T09:29:21.071Z] [runtime-status] [61710] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.9.0","resolution":"/project-11/functions/node_modules/firebase-admin/lib/index.js"}
[2020-01-24T09:29:21.072Z] [runtime-status] [61710] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.3.0","resolution":"/project-11/functions/node_modules/firebase-functions/lib/index.js"}
[2020-01-24T09:29:21.146Z] [runtime-status] [61710] firebase-admin has been stubbed. {"adminResolution":{"declared":true,"installed":true,"version":"8.9.0","resolution":"/project-11/functions/node_modules/firebase-admin/lib/index.js"}}
[2020-01-24T09:29:21.364Z] [runtime-status] [61710] initializeApp(DEFAULT) {"databaseURL":"https://X1.firebaseio.com","storageBucket":"X1.appspot.com","projectId":"X1"}
⚠  TypeError: instance.registerVersion is not a function
    at registerDatabase (/project-11/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15188:14)
    at Object.<anonymous> (/project-11/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15200:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at FirebaseNamespace.get [as database] (/project-11/functions/node_modules/firebase-admin/lib/firebase-namespace.js:282:38)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
[2020-01-24T09:29:21.455Z] [worker-~diagnostic~-6f2489cb-9b51-4daf-8372-e717d21e4b3e]: exited
[2020-01-24T09:29:21.455Z] [worker-~diagnostic~-6f2489cb-9b51-4daf-8372-e717d21e4b3e]: FINISHED
```

**Comment by samtstern** [comment]
Hmm this line shows that we're trying to pass the functions emulator information to the Firestore emulator:
```
[2020-01-24T09:29:18.581Z] Starting emulator firestore with command {"binary":"java","args":["-Duser.language=en","-jar","/Users/samovrablik/.cache/firebase/emulators/cloud-firestore-emulator-v1.10.2.jar","--host","localhost","--port",8080,"--rules","/project-11/firestore.rules","--functions_emulator","localhost:5000","--webchannel_port",8081],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator"],"joinArgs":false}
```

I am a little confused now though: is the main issue about `instance.registerVersion` or it's about ` Failed to publish event for trigger`?  Or are you saying that when you use `emulators:start` you get the `registerVersion` error but when you use `serve` you get the `Failed to publish event` error?

If we focus on the `registerVersion` error it looks like this issue with the firebase JS SDK:
https://github.com/firebase/firebase-js-sdk/issues/2420#issuecomment-563492913

I see that you have `@firebase/database` in your dev dependencies.  If you look at [this page](https://www.npmjs.com/package/@firebase/database) you can see that module is not intended for direct usage.

Can we try this in your `functions` folder:
```
npm uninstall --save-dev @firebase/database
rm -rf package-lock.json node_modules
npm install
```

And then try re-running `firebase emulators:start` to see if that clears things up?
