### ISSUE TITLE
firebase serve error with express (zone enabled)

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-tools#1886]
I created a function `ssr` which uses the express server to handle the request, but when I run the function via an http request `http://localhost:4201/<project-id>/us-central1/ssr`, I got an error:

```
import * as functions from "firebase-functions";
const app = require("../server");  

//this function works
export const test = functions.https.onRequest((request, response) => {
  response.send("firebase function works");
});

//this function doesn't work
export const ssr = functions.https.onRequest(app);
```
I think that the error is cause by the angular zone `import "zone.js/dist/zone-node";`

server.ts (simplified):
```
import "zone.js/dist/zone-node";
import express from "express";
import * as bodyParser from "body-parser";
import cors from "cors"; 


const PORT = process.env.PORT || 4200;
const DIST_FOLDER = join(process.cwd(), "./dist/browser"); 

const {
  AppServerModuleNgFactory,
  LAZY_MODULE_MAP,
  ngExpressEngine,
  provideModuleMap
} = require("./dist/server/main");

app.engine(
  "html",
  ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [provideModuleMap(LAZY_MODULE_MAP)]
  })
);

app.set("view engine", "html");
app.set("views", DIST_FOLDER);
app.use(bodyParser.json());
app.use(cors());


app.get("*", (req, res) => {
  res.render("index", { req });
});


app.listen(PORT, () => {
  console.log(`Node Express server listening on http://localhost:${PORT}`);
});

export { app }; //for firebase

```

```
TypeError: func is not a function
    at runFunction (firebase-tools\lib\emulator\functionsEmulatorRuntime.js:621:20)
    at firebase-tools\lib\emulator\functionsEmulatorRuntime.js:596:19
    at Generator.next (<anonymous>)
    at firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new ZoneAwarePromise (zone.js\dist\zone-node.js:931:29)
    at __awaiter (firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at runFunction (firebase-tools\lib\emulator\functionsEmulatorRuntime.js:593:12)
    at firebase-tools\lib\emulator\functionsEmulatorRuntime.js:620:15
    at Generator.next (<anonymous>)
    at firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
```

[repo](https://github.com/goblins-tech/almogtama3)

**Comment by samtstern** [comment]
@eng-dibo this looks like the same issue as https://github.com/firebase/firebase-tools/issues/1891 ... if so can we close this one?  If not can you explain the difference?

**Comment by eng-dibo** [comment]
@samtstern yes we can close this, sorry for duplication.
indeed we can close both as the issue already solved, I wrote there how did I fixed it.

**Comment by samtstern** [comment]
@eng-dibo thanks!
