### ISSUE TITLE
functions: TypeError: func is not a function

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-tools#1891]
firebase-tools with expressjs  inside an Angular project  causes an error: `! functions: TypeError: func is not a function`
[repo](https://github.com/goblins-tech/almogtama3)

log:
```
i  functions: Beginning execution of "ssr"
>  (node:4852) [DEP0005] DeprecationWarning: Buffer() is deprecated due to secur
ity and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), o
r Buffer.from() methods instead.

!  functions: TypeError: func is not a function
    at runFunction (node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:621:20)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:596:19
    at Generator.next (<anonymous>)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new ZoneAwarePromise (dist\server.js:1397:29)
    at __awaiter (node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at runFunction (node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:593:12)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:620:15
    at Generator.next (<anonymous>)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
    at new ZoneAwarePromise (dist\server.js:1397:29)
    at __awaiter (node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:3:12)
    at runHTTPS (node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:616:12)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:543:27
    at Generator.next (<anonymous>)
    at node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71

!  Your function was killed because it raised an unhandled error.
```

server.ts:
```
import "zone.js/dist/zone-node";
import express from "express";
import { join } from "path";
import * as fs from "fs";
import * as Path from "path";
import * as bodyParser from "body-parser";
import cors from "cors"; 
import multer from "multer";
import mongoose from "mongoose";

const app = express();

const PORT = process.env.PORT || 4200;
const DIST_FOLDER = join(process.cwd(), "./dist/browser"); 


const {
  AppServerModuleNgFactory,
  LAZY_MODULE_MAP,
  ngExpressEngine,
  provideModuleMap
} = require("./dist/server/main");

app.engine(
  "html",
  ngExpressEngine({
    bootstrap: AppServerModuleNgFactory,
    providers: [provideModuleMap(LAZY_MODULE_MAP)]
  })
);

app.set("view engine", "html");
app.set("views", DIST_FOLDER);
app.use(bodyParser.json());
app.use(cors());



app.use((req, res, next) => {
  if (!req.path) req.url = `/{req.url}`;
  next();
});


app.get("/api/", (req, res) => {
  res.json({ ok:true});
});

// Serve static files from /browser
app.get(
  "*.*",
  express.static(DIST_FOLDER, {
    maxAge: "1y"
  })
);

// All regular routes use the Universal engine
app.get("*", (req, res) => {
  res.render("index", { req });
});

//app.listen(POST)
export { app }; //for firebase
```

firebase function ssr:
```
import * as functions from "firebase-functions";
const app = require("../server"); 

export const ssr = functions.https.onRequest(app);
```

**Comment by samtstern** [comment]
I see you have this line:
```js
export { app }; //for firebase
```

But then you import it like this:
```js
const app = require("../server"); 
```

I think you actually want to do this:
```js
const { app } = require("../server"); 
```

**Comment by eng-dibo** [comment]
import {app} written here by mistake, the problem was due to webpack exports.app returns undefined.

fixed by setting `libraryTarget:'commonjs-module'`

**Comment by samtstern** [comment]
@eng-dibo thanks for following up!
