### ISSUE TITLE
I am getting a CERT_HAS_EXPIRED error mesage

### ISSUE THREAD

**Issue by gilr47** [firebase/firebase-tools#1901]
when using firebase-tools as a node module, I am getting this error:

FirebaseError: Server Error. certificate has expired
    at Request._callback (C:\Users\gil.r\dev\mcegithub\mce\ci\build\containers\shared\configuration\node_modules\firebase-tools\lib\api.js:31:19)
    at self.callback (C:\Users\gil.r\dev\mcegithub\mce\ci\build\containers\shared\configuration\node_modules\request\request.js:185:22)       
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.onRequestError (C:\Users\gil.r\dev\mcegithub\mce\ci\build\containers\shared\configuration\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'FirebaseError',
  children: [],
  context: undefined,
  exit: 2,
  message: 'Server Error. certificate has expired',
  original: Error: certificate has expired
      at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
      at TLSSocket.emit (events.js:210:5)
      at TLSSocket.EventEmitter.emit (domain.js:475:20)
      at TLSSocket._finishInit (_tls_wrap.js:794:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
    code: 'CERT_HAS_EXPIRED'
  },
  status: 500
}

judging from the link itself, the certificate is expired. it has expired yesterday.
screenshot can be viewed here: https://ibb.co/H4fyMJ4

the strange thing is that through the CLI it works without any problem, at first i thought it might be related to a version issue, but apparently it is not.

**Comment by mbleigh** [comment]
This is almost certainly a version issue. In current versions of the CLI, only the deprecated `firebase list` command talks to legacy `*.firebase.com` servers. If you're trying to list projects using the CLI, you should switch to using the `projects:list` command instead.

**Comment by samtstern** [comment]
@mbleigh I still see some references to that domain (through `adminOrigin`) in the `api.js` file ... it's the default `origin` in the `api.request` function.  Should we clean that up so it's not possible for the CLI to hit `*.firebase.com` ?

**Comment by mbleigh** [comment]
When we make the breaking change to remove deprecated commands, completely excising that from the CLI would be reasonable I think.

**Comment by Thangamanir** [comment]
Hi All,
 I am getting this error while Travis CI is deploying to firebase. How can this be resolved?

Updating the CLI version does not help.

firebase-tools@7.12.0 is the updated CLI version and I still get the error .

Any pointers on how to resolve this?

Thanks!

**Comment by mbleigh** [comment]
Please add --debug to the deploy command and share the resulting logs --
the version number should be printed toward the top of the log.

**Comment by Alynva** [comment]
Updating de CLI worked for me. Using the --debug flag, the version changed from 6.1.2 (before update) to 7.12.1 (after update).

**Comment by ZoSo1974** [comment]
Hi, I've the same problem.
I need to execute "firebase use staging" and i get "Error: Server Error. certificate has expired"
I tried to update firebase tools with  "npm i firebase-tools@latest --force"
But with "firebase use staging --debug" I see CLI Version:   6.2.2... why!!?
I logout/login, restart windows... I'm stucked... :(

[2020-02-28T10:11:59.140Z] ----------------------------------------------------------------------
[2020-02-28T10:11:59.145Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Alberto Boz\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js use staging --debug
[2020-02-28T10:11:59.181Z] CLI Version:   6.2.2
[2020-02-28T10:11:59.181Z] Platform:      win32
[2020-02-28T10:11:59.182Z] Node Version:  v8.11.3
[2020-02-28T10:11:59.184Z] Time:          Fri Feb 28 2020 11:11:59 GMT+0100 (ora solare Europa occidentale)
[2020-02-28T10:11:59.184Z] ----------------------------------------------------------------------

[2020-02-28T10:11:59.206Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-02-28T10:11:59.232Z] > authorizing via signed-in user
[2020-02-28T10:11:59.272Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2020-02-28T10:11:59.274Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token
 <request body omitted>
[2020-02-28T10:11:59.459Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 28 Feb 2020 10:11:59 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, connection=close
[2020-02-28T10:11:59.474Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects

[2020-02-28T10:11:59.954Z] Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)

Error: Server Error. certificate has expired

**Comment by ZoSo1974** [comment]
I solved. I need a node version > 8.13

**Comment by tb47** [comment]
I struggled on this error during a tutorial.
Solution:
Check your package.json --> devDependencies --> firebase-tools: "version".
Reason:
I had to use an old version of "firebase-tools" in a tutorial which is no longer supported by firebase to host a project. Updating the package.json solved this issue for me.
Best regards
