### ISSUE TITLE
 Error: certificate has expired     at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)

### ISSUE THREAD

**Issue by SeanDez** [firebase/firebase-tools#1914]
**firebase-tools:**

4.0.2

**Platform:**

Linux

### [REQUIRED] Steps to reproduce

1. Run `firebase serve --debug`
2. CLI will err out

### [REQUIRED] Expected behavior

Emulators run on default ports in localhost.

### [REQUIRED] Actual behavior

```
owner@G700:~/PhpstormProjects/shopify/buyUsedServer$ firebase serve --debug[2020-01-10T21:24:57.810Z] ----------------------------------------------------------------------
[2020-01-10T21:24:57.817Z] Command:       /home/owner/.nvm/versions/node/v10.16.3/bin/node /usr/local/bin/firebase serve --debug
[2020-01-10T21:24:57.818Z] CLI Version:   4.0.2
[2020-01-10T21:24:57.818Z] Platform:      linux
[2020-01-10T21:24:57.818Z] Node Version:  v10.16.3
[2020-01-10T21:24:57.892Z] Time:          Sat Jan 11 2020 04:24:57 GMT+0700 (Indochina Time)
[2020-01-10T21:24:57.893Z] ----------------------------------------------------------------------

[2020-01-10T21:24:57.931Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-01-10T21:24:57.932Z] > authorizing via signed-in user
[2020-01-10T21:24:57.935Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/buyusedshopify  
  
 Sat Jan 11 2020 04:24:57 GMT+0700 (Indochina Time)
[2020-01-10T21:24:59.003Z] Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

Error: Server Error. certificate has expired

```

**Comment by SeanDez** [comment]
Deploy shows the same error:

```
owner@G700:~/PhpstormProjects/shopify/buyUsedServer$ firebase deploy --debug
[2020-01-10T21:31:19.903Z] ----------------------------------------------------------------------
[2020-01-10T21:31:19.908Z] Command:       /home/owner/.nvm/versions/node/v10.16.3/bin/node /usr/local/bin/firebase deploy --debug
[2020-01-10T21:31:19.908Z] CLI Version:   4.0.2
[2020-01-10T21:31:19.908Z] Platform:      linux
[2020-01-10T21:31:19.908Z] Node Version:  v10.16.3
[2020-01-10T21:31:19.909Z] Time:          Sat Jan 11 2020 04:31:19 GMT+0700 (Indochina Time)
[2020-01-10T21:31:19.909Z] ----------------------------------------------------------------------

[2020-01-10T21:31:19.921Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-01-10T21:31:19.922Z] > authorizing via signed-in user
[2020-01-10T21:31:19.925Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/buyusedshopify  
  
 Sat Jan 11 2020 04:31:19 GMT+0700 (Indochina Time)
[2020-01-10T21:31:20.745Z] Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)

Error: Server Error. certificate has expired

```

**Comment by mbleigh** [comment]
You are using an outdated version of the Firebase CLI that tries to connect to deprecated endpoints. Please upgrade:

    npm i -g firebase-tools@latest
