### ISSUE TITLE
Unable to run Firebase Cloud functions locally

### ISSUE THREAD

**Issue by nehawankar174** [firebase/firebase-tools#1921]
### [REQUIRED] Environment info

**firebase-tools:**
 ^7.5.0

**Platform:**
Windows
### [REQUIRED] Test case
I am trying to run Firebase cloud functions locally during development. I have installed Firebase CLI by using command-

"npm install -g firebase-tools"
also using dependencies with following versions-

firebase-admin version 8.0.0 or higher.
firebase-functions version 3.0.0 or higher.
and set up admin credentials for emulated functions.
When I am trying start firebase emulators by "firebase emulators:start" command, getting following error:

```
**TypeError: instance.INTERNAL.registerService is not a function**
```

### [REQUIRED] Steps to reproduce
Run the following commands:
1. firebase init emulators
2. firebase setup:emulators
3. firebase emulators:start --only functions,firestore
4. firebase emulators:start
5. Observe CLI error output

### [REQUIRED] Expected behavior
Firebase cloud functions should run locally.

### [REQUIRED] Actual behavior
Unable to run finctions locally, facing error for the same:

```
!  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to D:\Test\Project\firebaseDev\functions\service_key.json. Non-emulated services will access production using these credentials. Be careful!
!  Non-existent functions.config() value requested!
   - Path: "stripe.currency"
   - Learn more at https://firebase.google.com/docs/functions/local-emulator
!  **TypeError: instance.INTERNAL.registerService is not a function**
    at registerDatabase (D:\Test\Project\firebaseDev\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15130:39)
    at Object.<anonymous> (D:\Test\Project\firebaseDev\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15153:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at FirebaseNamespace.get [as database] (D:\Test\Project\firebaseDev\functions\node_modules\firebase-admin\lib\firebase-namespace.js:282:38)
    at makeProxiedDatabase (C:\Users\CLUSTER COMPUTE 1\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:401:31)
!  We were unable to load your functions code. (see above)
```

Thanks in Advance!

**Comment by bkendall** [comment]
That's curious - I'm not sure what the best way to debug this will be. So, could you try:

1. Ensure the `stripe.currency` value is set - the directions should be here: https://firebase.google.com/docs/functions/local-emulator#set_up_functions_configuration_optional
1. Unset `GOOGLE_APPLICATION_CREDENTIALS` in your environment?

**Comment by samtstern** [comment]
This error is actually being raised by the Firebase JS SDK, which most people don't use in Cloud Functions:
https://github.com/firebase/firebase-js-sdk/issues/2420

Do you have `firebase` or `@firebase/testing` in your `package.json` and are you using them in your code?  If so make sure you're using the latest versions.
