### ISSUE TITLE
Emulator, Cannot read property '__emulator_func' of undefined

### ISSUE THREAD

**Issue by florianlenz** [firebase/firebase-tools#1927]
### [REQUIRED] Environment info

**firebase-tools:** 7.12.1

**Platform:** macOS

### [REQUIRED] Test case

Put the following code in the `index.ts` file of your project.

```typescript
export const myApi = {
    "my.handler.function": functions.https.onRequest((request, response) => {
        response.send("ping")
    }),
    "my~handler~function": functions.https.onRequest((request, response) => {
        response.send("ping")
    }),
};
```

### [REQUIRED] Steps to reproduce
Call the `my.handler.function` endpoint.

### [REQUIRED] Expected behavior
The expected behaviour is, that the ping response is sent. If you call the other endpoint (`my~handler~function`), the ping response will be sent. So it seems like that using `.` inside a firebase function name is messing with the emulator.

### [REQUIRED] Actual behavior
The actual behavour is, that I am getting the following error:
`TypeError: Cannot read property '__emulator_func' of undefined`

```
i  functions: Beginning execution of "myApi-my.handler.function"
⚠  functions: TypeError: Cannot read property '__emulator_func' of undefined
    at EmulatedTrigger.getRawFunction (/Users/florian/projects/backend/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorShared.js:51:21)
    at /Users/florian/projects/backend/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:532:42
    at Generator.next (<anonymous>)
    at /Users/florian/projects/backend/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/florian/projects/backend/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at handler (/Users/florian/projects/backend/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:529:43)
    at Layer.handle [as handle_request] (/Users/florian/projects/backend/functions/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/florian/projects/backend/functions/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/florian/projects/backend/functions/node_modules/express/lib/router/route.js:112:3)
```

**Comment by florianlenz** [comment]
Ah ok. So the fact that the emulator sends a response for the `my~handler~function` function is a bug too? Is there actually a list of allowed characters to use in cloud functions? I couldn't find it in the documentation.

**Comment by taeold** [comment]
Legal function name is specified in Cloud Functions documentation: https://cloud.google.com/functions/docs/deploy#basics
