### ISSUE TITLE
Functions emulator exits when the called function doesn't exist

### ISSUE THREAD

**Issue by eowo** [firebase/firebase-tools#1937]
### [REQUIRED] Environment info

**firebase-tools: 7.12.1**
**Platform: Ubuntu**

### [REQUIRED] Test case

```sh
$ firebase init [emulators, functions]
```
### [REQUIRED] Steps to reproduce

```sh
$ firebase emulators:start --only functions --debug
```
Then call a random function which does not exist.

### [REQUIRED] Expected behavior

The emulator should not exit.

### [REQUIRED] Actual behavior

```
⚠  functions: Could not find trigger "unknownFunction" in your functions directory.
⚠  Your function was killed because it raised an unhandled error.
i  functions: Beginning execution of "unknownFunction"
⚠  functions: TypeError: Cannot read property 'definition' of undefined
    at /data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:658:47
    at Generator.next (<anonymous>)
    at /data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:4:12)
    at invokeTrigger (/data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:650:12)
    at /data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:774:19
    at Generator.next (<anonymous>)
    at fulfilled (/data/src/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at <anonymous>
[2020-01-24T12:34:40.960Z] Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/data/src/firebase-tools/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/data/src/firebase-tools/node_modules/express/lib/response.js:170:12)
    at EventEmitter.worker.onLogs (/data/src/firebase-tools/lib/emulator/functionsEmulator.js:436:37)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at lines.slice.forEach (/data/src/firebase-tools/lib/emulator/functionsEmulator.js:499:25)
    at Array.forEach (<anonymous>)
    at FunctionsEmulator.onData (/data/src/firebase-tools/lib/emulator/functionsEmulator.js:497:32)
    at ChildProcess.childProcess.on (/data/src/firebase-tools/lib/emulator/functionsEmulator.js:376:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

Error: An unexpected error has occurred.
[2020-01-24T12:34:40.963Z] [worker-unknownFunction-aea54fa9-47f5-4587-a2a2-3b1115e5d5eb]: exited
[2020-01-24T12:34:40.963Z] [worker-unknownFunction-aea54fa9-47f5-4587-a2a2-3b1115e5d5eb]: FINISHED
```

**Comment by samtstern** [comment]
@eowo thanks for reporting!  Sounds like a pretty straightforward bug.
