### ISSUE TITLE
firebase deploy --only functions:fnName not deploying

### ISSUE THREAD

**Issue by cunundrummer** [firebase/firebase-tools#1974]
**firebase-tools:**
7.13.0

**Platform:**
maOS High Sierra 10.13.6
```
[2020-02-14T19:54:54.923Z] ----------------------------------------------------------------------
[2020-02-14T19:54:54.926Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --debug --only functions:getAllUsers
[2020-02-14T19:54:54.926Z] CLI Version:   7.13.0
[2020-02-14T19:54:54.927Z] Platform:      darwin
[2020-02-14T19:54:54.927Z] Node Version:  v10.16.3
[2020-02-14T19:54:54.928Z] Time:          Fri Feb 14 2020 14:54:54 GMT-0500 (GMT-05:00)
[2020-02-14T19:54:54.928Z] ----------------------------------------------------------------------
[2020-02-14T19:54:54.928Z] 
```
### [REQUIRED] Test case

I created a function in it's own file in a directory in the functions directory:
(functions/user-management-functions/getAllUsers.js).  
I added the export in index.js:

```
// index.js
const admin = require('firebase-admin');
const createUser = require('./user-management-functions/createUser'); // no issue deploying
const getAllUsers = require('./user-management-functions/getAllUsers'); // issue!
admin.initializeApp();

// Create and Deploy Your First Cloud Functions
// https://firebase.google.com/docs/functions/write-firebase-functions

exports.createUser = createUser.createNewUser; // no issue deploying
exports.getAllUsers = getAllUsers.getAllUsers;  // issue!

```

As the code shows - in the comments, createUser _can_ deploy, yet, getAllUsers does not.  The code in getAllUsers is from a cut and paste (for testing out).  It is suppose to show all the registered users.  And I _DO_ have a doc with users, but in this case it is for more of an administrative standpoint (admins CRUD). 

Don't know if this matter but the createUser function is an onCreate trigger fn, but getAllUsers, is a callable fn.

I've followed a few posts from google searches, [StackOverflow](https://stackoverflow.com/questions/56396688/firebase-deploy-skips-exported-function), which also led me to  #issue:1357.  Also, there are a lot of _plagiarised_ articles using that issue from the google search I did.  There are also a few closed issues I checked too, and tried, but related to '-' in the function names if not outdated by a couple years. 

### [REQUIRED] Steps to reproduce

ran this command: 
`firebase deploy --debug --only functions:getAllUsers`
and without the --debug flag.

### [REQUIRED] Expected behavior

A successful function deployment.

### [REQUIRED] Actual behavior
```
[2020-02-14T19:54:54.923Z] ----------------------------------------------------------------------
[2020-02-14T19:54:54.926Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --debug --only functions:getAllUsers
[2020-02-14T19:54:54.926Z] CLI Version:   7.13.0
[2020-02-14T19:54:54.927Z] Platform:      darwin
[2020-02-14T19:54:54.927Z] Node Version:  v10.16.3
[2020-02-14T19:54:54.928Z] Time:          Fri Feb 14 2020 14:54:54 GMT-0500 (GMT-05:00)
[2020-02-14T19:54:54.928Z] ----------------------------------------------------------------------
[2020-02-14T19:54:54.928Z] 
[2020-02-14T19:54:54.938Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-02-14T19:54:54.938Z] > authorizing via signed-in user
[2020-02-14T19:54:54.938Z] [iam] checking project XXXXXXXX-428ab for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2020-02-14T19:54:54.940Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/XXXXXXXX-428ab:testIamPermissions  
 permissions=[cloudfunctions.functions.create, cloudfunctions.functions.delete, cloudfunctions.functions.get, cloudfunctions.functions.list, cloudfunctions.functions.update, cloudfunctions.operations.get, firebase.projects.get]
[2020-02-14T19:55:05.575Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:05 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=201, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked

=== Deploying to 'XXXXXXXX'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /Users/XXXXX/WebstormProjects/AngularApps/angWebComponents/classy-components/functions
> eslint .

✔  functions: Finished running predeploy script.
[2020-02-14T19:55:08.372Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.3.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1",
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}
i  functions: ensuring necessary APIs are enabled...
[2020-02-14T19:55:08.374Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/XXXXXXXX-428ab/services/cloudfunctions.googleapis.com  
 
[2020-02-14T19:55:08.375Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/XXXXXXXX-428ab/services/runtimeconfig.googleapis.com  
 
[2020-02-14T19:55:08.983Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:08 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2020-02-14T19:55:09.043Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:08 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
✔  functions: all necessary APIs are enabled
[2020-02-14T19:55:09.044Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/XXXXXXXX-428ab/adminSdkConfig  
 
[2020-02-14T19:55:09.441Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:09 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
i  functions: preparing functions directory for uploading...
[2020-02-14T19:55:09.444Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXXXXXXX-428ab/configs  
 
[2020-02-14T19:55:10.207Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:10 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
i  functions: packaged functions (40.2 KB) for uploading
[2020-02-14T19:55:10.432Z] >>> HTTP REQUEST POST https://cloudfunctions.googleapis.com/v1/projects/XXXXXXXX-428ab/locations/us-central1/functions:generateUploadUrl  
 
[2020-02-14T19:55:12.052Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:11 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2020-02-14T19:55:12.053Z] >>> HTTP REQUEST PUT https://storage.googleapis.com/gcf-upload-us-central1-d23d23c7-2455-4876-ad97-c375d9494c31/373b581f-fecf-4f31-b306-82f2d32dd5db.zip?GoogleAccessId=service-233629207339@gcf-admin-robot.iam.gserviceaccount.com&Expires=1581711911&Signature=QHhHfwuNqJpe00lDKXZhXgc2OKvvk%2FGXsuEPih6870P4MO1HrnjWJnr7tuK5JXUAdfJkxX2JjE8oRo2oXiEqPNI1%2BgsrDqoorF%2F%2Bp7Zc81s4FfTk%2BXMvZL7bSnEGSPlhlNBM2skBOgppk5cqLo87VdseNmc5EyLjdutr7Bax4kI%2F%2BYrlicJWRJ66YEd0xwWeG%2BE59gNYD1gPh%2BWpb%2BJyhjOIJCaCp5gLjGx3OuBZTkOiWdl7GFyUdPrqUr6%2BsE6KQ%2Fb81KMwzNNdBNX0MGnxdSQknbpHfzk61FXB%2BmAycmc239jCqzCZ5rdGt4uk6YBRN14NHNf93MHSiA2tyyfnvw%3D%3D  
 <request body omitted>
[2020-02-14T19:55:12.575Z] <<< HTTP RESPONSE 200 x-guploader-uploadid=AEnB2Uo4i_07wrcXYwDyv9ApeSUMu9db4tU7iSIhPf83ovqCm77PDFY44x2uDDr8fs3Bf7r7QS7384HE5_Eo1pOZBUH5Oew5wQ, etag="8bce25607b61de435e4bc3815b5df54a", x-goog-generation=1581710112530102, x-goog-metageneration=1, x-goog-hash=crc32c=SvA3rw==, md5=i84lYHth3kNeS8OBW131Sg==, x-goog-stored-content-length=41160, x-goog-stored-content-encoding=identity, vary=Origin, content-length=0, date=Fri, 14 Feb 2020 19:55:12 GMT, server=UploadServer, content-type=text/html; charset=UTF-8, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
✔  functions: functions folder uploaded successfully
[2020-02-14T19:55:12.578Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/projects/XXXXXXXX-428ab/locations/-/functions  
 
[2020-02-14T19:55:13.280Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:13 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked
[2020-02-14T19:55:13.282Z] > [functions] filtering triggers to: []
i  functions: current functions in project: createUser(us-central1), geoGetCountryIsoAlpha3(us-central1), helloWorld(us-central1)
**⚠  functions: the following filters were specified but do not match any functions in the project: getAllUsers
[2020-02-14T19:55:13.284Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/XXXXXXXX-428ab/services/cloudscheduler.googleapis.com**  
 
[2020-02-14T19:55:13.895Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 14 Feb 2020 19:55:13 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000, accept-ranges=none, transfer-encoding=chunked

✔  Deploy complete!

```

**Comment by samtstern** [comment]
Hmm yeah I see this:
```
functions: the following filters were specified but do not match any functions in the project: getAllUsers
```

If you run `firebase emulators:start --only functions` what functions do you see?

**Comment by samtstern** [comment]
Also it would be helpful if you could show the code in this file:
```
./user-management-functions/getAllUsers
```

**Comment by cunundrummer** [comment]
> If you run firebase emulators:start --only functions what functions do you see?


i  emulators: Starting emulators: functions
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/Users/myName/WebstormProjects/AngularApps/angWebComponents/classy-components/functions" for Cloud Functions...
⚠  TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (/Users/myName/WebstormProjects/AngularApps/angWebComponents/classy-components/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15320:39)
    at Object.<anonymous> (/Users/myName/WebstormProjects/AngularApps/angWebComponents/classy-components/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15353:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at FirebaseNamespace.get [as database] (/Users/myName/WebstormProjects/AngularApps/angWebComponents/classy-components/functions/node_modules/firebase-admin/lib/firebase-namespace.js:282:38)
⚠  We were unable to load your functions code. (see above)


--------------------------------------------------------------------------------------------------


> Also it would be helpful if you could show the code in this file:
> 
> ./user-management-functions/getAllUsers
> 

getAllUsers.js . (code is copy and pasted from [here - at around mid-page](https://bigcodenerd.org/get-all-users-auth-firebase-cloud-functions/) with a little editing to see if it can get working.

```
const admin = require('firebase-admin');

exports.getAllUsers = (req, res) => {
  const maxResults = 1; // optional arg.

  admin.auth().listUsers(maxResults)
  .then((userRecords) => {
    userRecords.users.forEach((user) => console.log(user.toJSON()));
    res.end('Retrieved users list successfully.');  // also tried res.status(..).json({...}).  No difference.
    return userRecords.users.map(userRecord => {
      return {
        uid: userRecord.uid,
        email: userRecord.email
      } // I also attempted a few different ways to return
    });
  })
  .catch((error) => console.log(error));
};
```

**Comment by cunundrummer** [comment]
Ahh, the power of weekend rest!  After writing then previous thread, I went back and looked again at my code.  I noticed I was just calling a function, but not functions -> I noticed after looking at the link I provided that the author included the _functions.https.onRequest_ method.  

I believed - even after going through the docs - that I could simply call any function.  I guess since this is like a node backend, any (req, res) type of function must be taken care of with Firebases https.onRequest() method.  

If I am mistaken, can you please let me know?  Thank you for the quick help!

**Comment by samtstern** [comment]
@cunundrummer yes that's correct.  In order to deploy a function it must be an exported handler from the `firebase-functions` package. 

`exports.getAllUsers = functions.https.onRequest(...)` makes you a basic express-style HTTP endpoint.  There are also other types of functions handlers that are triggered by "background" event triggers, such as changes to a Firestore database or Analytics events.

This doc lays out some sample use cases if you're curious:
https://firebase.google.com/docs/functions/use-cases
