### ISSUE TITLE
Deploying a custom domain for dynamic links using hosting fails

### ISSUE THREAD

**Issue by kmcnellis** [firebase/firebase-tools#1987]
Following the setup instructions in the [docs](https://firebase.google.com/docs/dynamic-links/custom-domains?authuser=0#manual), setting up a domain fails

### [REQUIRED] Environment info

**firebase-tools:** 7.13.1

**Platform:** macOS

### [REQUIRED] Test case

firebase.json: (as recommended in the  [docs](https://firebase.google.com/docs/dynamic-links/custom-domains?authuser=0#manual))
```
{
  "hosting": [{
    "target": "main",
    "public": "public",
    "ignore": [
      "**/.*",
      "**/node_modules/**"
    ]
  },{
    "target": "links",
    "appAssociation": "AUTO",
    "rewrites": [
      {
        "source": "/**",
        "dynamicLinks": true
      }
    ]
  }]
}
```

### [REQUIRED] Steps to reproduce

1. Setup a hosting site with 2 sites (we'll call them main-123, and links-123)
1. Add a custom domain to hosting and dynamic links (https://firebase.google.com/docs/dynamic-links/custom-domains?authuser=0#set_up_a_custom_domain_in_the).  Link it to site `links-123`
1. Run `firebase target:apply hosting links links-123` and `firebase target:apply hosting main main-123`
1. Create a `public` folder with some content & add the above firebase.json to the project
1. Try to deploy using `firebase deploy --only hosting:main` and it will succeed
1. Try to deploy using `firebase deploy` or `firebase deploy --only hosting:links` and it will fail

### [REQUIRED] Expected behavior

The site `links-123` should be able to be deployed for dynamic links, without specifying a public directory

### [REQUIRED] Actual behavior

```
i  deploying hosting
[2020-02-19T23:49:05.287Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:978:7)
    at resolveProjectPath (/Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/lib/projectPath.js:13:17)
    at /Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:46:36
    at arrayEach (/Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9342:14)
    at module.exports (/Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:29:7)
    at _chain (/Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/lib/deploy/index.js:22:40)
    at /Users/kianam/.nvm/versions/node/v11.15.0/lib/node_modules/firebase-tools/lib/deploy/index.js:63:16
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

### Workaround

Add a `public` field to the target `links` in firebase.json, pointing it to an empty folder.

**Comment by bkendall** [comment]
I think this is working as expected (though, maybe the error message could be better).

Hosting sites require `"public": "folder"` to be set in `firebase.json`, even if it's empty. The docs linked above have `// ...` where that would actually be, which is a bit misleading. But, the CLI cannot deploy a site to hosting without a folder, even if it's empty.

**Comment by kmcnellis** [comment]
Filed an update to the docs.  Leaving this open to fix the error message
