### ISSUE TITLE
Error importing firebase client SDK in Typescript cloud function

### ISSUE THREAD

**Issue by theochampion** [firebase/firebase-tools#1999]
**firebase-tools:**
7.14.0

**Platform:**
macOS

I'm trying to import the firebase JS client SDK (to simulate user interaction) into a cloud function written in typescript but I keep getting some missing namespace error.

According to [the docs](https://www.npmjs.com/package/firebase) I have set `allowSyntheticDefaultImports` to `true` in tsconfig.json to pass the type check.

The error:

```
Error: Error occurred while parsing your function triggers.

Error: Cannot find the firebase namespace; be sure to include firebase-app.js before this library.
    at /Users/theo/Desktop/flint-cf/functions/node_modules/@firebase/auth/dist/auth.js:372:285
    at /Users/theo/Desktop/flint-cf/functions/node_modules/@firebase/auth/dist/auth.js:372:388
    at Object.<anonymous> (/Users/theo/Desktop/flint-cf/functions/node_modules/@firebase/auth/dist/auth.js:372:394)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

My code:

```javascript
import * as functions from 'firebase-functions';
// This import loads the firebase namespace.
import firebase from 'firebase/app';

// These imports load individual services into the firebase namespace.
import 'firebase/auth';
import 'firebase/functions';

// contants
import { CF_LOCATION } from '../../constants/cf_config';

firebase.initializeApp({
  // my creds
});

export = functions
  .region(CF_LOCATION)
  .pubsub.schedule('every 2 minutes')
  .onRun(context => {
    try {
      const user = firebase
        .auth()
        .signInWithEmailAndPassword('blabla@test.com', 'blablapass');
      console.log('authenticated');
      console.log(user);
    } catch (err) {
      console.log(err);
    }
    return null;
  });
``` 

What am I missing here ? 

Cheers! :)

**Comment by samtstern** [comment]
@theochampion I am going to transfer this issue to the Firebase JS SDK repo as I don't think it has to do with the Firebase CLI (this repo).
