### ISSUE TITLE
Issue with installation: "Error: Cannot find module 'update-notifier' .. `MODULE_NOT_FOUND`"

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-tools#2000]
### [REQUIRED] Environment info

**firebase-tools:** v7.14.0 (although I looked this up, the `--version` command fails, see below)

**Platform:** macOS

### [REQUIRED] Test case

```
$ firebase --version
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module 'update-notifier'
Require stack:
- /Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ],
  pkg: true
}
```

### [REQUIRED] Steps to reproduce

Install via `curl -sL https://firebase.tools | bash`
Output:

```
-- Checking for existing firebase-tools on PATH...
-- Checking your machine type...
[Binary URL] https://firebase.tools/bin/macos/latest
-- Downloading binary...
######################################################################## 100.0%#=#=#                                                  ######################################################################## 100.0%##=O#- #                                               ######################################################################## 100.0%# #=O#- #                                              ######################################################################## 100.0%
-- Setting permissions on binary...
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module 'update-notifier'
Require stack:
- /Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ],
  pkg: true
}
-- firebase-tools@ is now installed
-- All Done!
```

Any subsequent commands fail as well.

### [REQUIRED] Expected behavior

The installation to work as expected.

### [REQUIRED] Actual behavior

```
$ firebase --version
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module 'update-notifier'
Require stack:
- /Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ryan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ],
  pkg: true
}
```

**Comment by ryanwilson** [comment]
Googler here, this is my personal machine though. Let me know if you want me to do anything to test it! Note: I do not have `node` or `npm` installed.

**Comment by ryanwilson** [comment]
I just tried manually downloading the `7.13.1` binary for macOS and it works as expected, so this appears to be a regression. I'm unblocked for now though.

**Comment by abeisgoat** [comment]
Hey Ryan, thanks for the report, looks like an issue with a native extension that isn't being bundled into the native binary, it's possible there was a change in that dep between `7.13.1` and `7.14.0`. I'll investigate, thanks.

**Comment by abeisgoat** [comment]
Just tried to repro this and succeeded just fine, what version of MacOS are you on?

**Comment by developerdizzle** [comment]
@abeisgoat I'm also experiencing this on Windows 10 Pro, Version 1903, Build 18362.657, using Node 12.9.0

**Comment by monsieurpooh** [comment]
If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
