### ISSUE TITLE
ext:list throws unexpected error

### ISSUE THREAD

**Issue by abeisgoat** [firebase/firebase-tools#2006]
### [REQUIRED] Environment info
firebase-tools@latest on Ubuntu

### [REQUIRED] Test case
`firebase ext:list`

### [REQUIRED] Expected behavior
It lists exts

### [REQUIRED] Actual behavior
```[debug] [2020-03-02T17:08:42.545Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-02T17:08:42.545Z] > authorizing via signed-in user
[debug] [2020-03-02T17:08:42.546Z] [iam] checking project abe-today for permissions ["firebase.projects.get","firebasemods.instances.list"]
[debug] [2020-03-02T17:08:42.547Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/abe-today:testIamPermissions  
 [object Object]
[debug] [2020-03-02T17:08:42.708Z] <<< HTTP RESPONSE 200 [object Object]
[info] i  extensions: ensuring necessary APIs are enabled...
[debug] [2020-03-02T17:08:42.715Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/abe-today/services/firebaseextensions.googleapis.com  
 
[debug] [2020-03-02T17:08:42.923Z] <<< HTTP RESPONSE 200 [object Object]
[info] ✔  extensions: all necessary APIs are enabled
[debug] [2020-03-02T17:08:42.927Z] >>> HTTP REQUEST GET https://firebaseextensions.googleapis.com/v1beta/projects/abe-today/instances?pageSize=100&pageToken=  
 
[debug] [2020-03-02T17:08:43.175Z] <<< HTTP RESPONSE 200 [object Object]
[debug] [2020-03-02T17:08:43.337Z] TypeError: instances.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.<anonymous> (/usr/local/google/home/abehaskins/Development/ft2/lib/extensions/extensionsApi.js:78:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/google/home/abehaskins/Development/ft2/lib/extensions/extensionsApi.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by joehan** [comment]
Closing since this was fixed by #2182
