### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by vivchar** [firebase/firebase-tools#2070]
### Environment info
firebase version 7.16.0 → 7.16.1

### Test case
run any command
```
nickname$ firebase -v
```
Result: exception

### Steps to reproduce
run any firebase command

### Expected behavior
run should be successfull

### Actual behavior
Exception

```
nickname$ firebase -v
This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt
(node:27859) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'firepit-log.txt'
    at Object.openSync (fs.js:440:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:491:32)
    at Object.writeFileSync (fs.js:1265:35)
    at /snapshot/firepit/firepit.js:504:6
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:5)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1380:13)
    at internal/main/run_main_module.js:17:11
(node:27859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samtstern** [comment]
@vivchar thanks for filing this.  What happens if you create the file `firepit-log.txt` in your current directory?

**Comment by vivchar** [comment]
I restarted my pc and it works fine now
