### ISSUE TITLE
`firebase-tools@8.0.0` fails to dump SDK config for web apps

### ISSUE THREAD

**Issue by mmalecki** [firebase/firebase-tools#2088]
### [REQUIRED] Environment info

**firebase-tools:** 8.0.0

**Platform:** Linux

### [REQUIRED] Test case

`firebase apps:sdkconfig --non-interactive web $APP_ID > config.js`

### [REQUIRED] Steps to reproduce
`firebase apps:sdkconfig --non-interactive web $APP_ID > config.js`

### [REQUIRED] Expected behavior
Config is printed out to `config.js`

### [REQUIRED] Actual behavior
`firebase-tools` crashes with `ENOENT`, unable to find the template:
```
fetching configuration for dev...
✔ Preparing the list of your Firebase WEB apps
✔ Downloading configuration data of your Firebase WEB app
[debug] [2020-04-01T10:18:23.952Z] ----------------------------------------------------------------------
[debug] [2020-04-01T10:18:23.954Z] Command:       /usr/local/bin/node /home/maciej/npm/bin/firebase apps:sdkconfig --non-interactive web 1:885482610373:web:831614bcf8b2902e6bdaac
[debug] [2020-04-01T10:18:23.954Z] CLI Version:   8.0.0
[debug] [2020-04-01T10:18:23.954Z] Platform:      linux
[debug] [2020-04-01T10:18:23.954Z] Node Version:  v13.3.0
[debug] [2020-04-01T10:18:23.955Z] Time:          Wed Apr 01 2020 12:18:23 GMT+0200 (Central European Summer Time)
[debug] [2020-04-01T10:18:23.955Z] ----------------------------------------------------------------------
[debug] [2020-04-01T10:18:23.955Z] 
[debug] [2020-04-01T10:18:23.960Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-01T10:18:23.960Z] > authorizing via signed-in user
[debug] [2020-04-01T10:18:23.967Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/-/webApps/1:885482610373:web:831614bcf8b2902e6bdaac/config  
 
[debug] [2020-04-01T10:18:25.090Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Wed, 01 Apr 2020 10:18:24 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-04-01T10:18:25.094Z] Error: ENOENT: no such file or directory, open '/home/maciej/npm/lib/node_modules/firebase-tools/lib/management/../../templates/setup/web.js'
    at Object.openSync (fs.js:446:3)
    at Object.readFileSync (fs.js:348:35)
    at parseConfigFromResponse (/home/maciej/npm/lib/node_modules/firebase-tools/lib/management/apps.js:190:32)
    at Object.getAppConfigFile (/home/maciej/npm/lib/node_modules/firebase-tools/lib/management/apps.js:205:12)
    at /home/maciej/npm/lib/node_modules/firebase-tools/lib/commands/apps-sdkconfig.js:73:29
    at Generator.next (<anonymous>)
    at fulfilled (/home/maciej/npm/lib/node_modules/firebase-tools/lib/commands/apps-sdkconfig.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
Fixed by #2087
