### ISSUE TITLE
Firebase init Unexpected error

### ISSUE THREAD

**Issue by pg222jx** [firebase/firebase-tools#2092]
Having an issue with hosting with firebase. 
Writing firebase init only results in : An unexpected error occurred. 
I have no idea what to do so please help!
I use windows and get this with firebase init --debug:

[2020-04-02T08:54:38.568Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-04-02T08:54:38.623Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\perni\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\perni\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\perni\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)

Error: An unexpected error has occurred.

**Comment by samtstern** [comment]
@bkendall can you take a look at this?  Looks like it's coming from the new auth library.

@pg222jx do you have `gcloud` installed on your machine?  If so does it help if you run `gcloud auth application-default login` and try again`?

**Comment by bkendall** [comment]
@pg222jx please follow the template next time.

1. What version of `firebase-tools` do you have installed (run `firebase --version`)
1. Have you run `firebase login`? If not, what credentials are you using?
1. Do you have `gcloud` installed on your machine? (See @samtstern 's question above)

**Comment by pg222jx** [comment]
Sorry, I will follow the template next time !
The issue is solved. I needed to add  --interactive after firebase login of some reason. 
Thanks for fast answers anyway!
