### ISSUE TITLE
New CLI syntax apps:sdkconfig: file not found

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-tools#2094]
### [REQUIRED] Environment info

**firebase-tools:** 8.0.0

**Platform:** Ubuntu based Gallium OS 3 distro

**Node:** v13.11.0

### [REQUIRED] Test case

Set up a Firebase project associated with a web app

### [REQUIRED] Steps to reproduce

Running the following in a shell:
```shell
firebase apps:sdkconfig web
```

### [REQUIRED] Expected behavior

Output of JSON config (I guess)

### [REQUIRED] Actual behavior

Maybe `firestore-debug.log` contains sensitive auth data so here is the extracted error section:
```txt
Error: ENOENT: no such file or directory, open '/home/laurent/projects/myproject/node_modules/firebase-tools/lib/management/../../templates/setup/web.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at parseConfigFromResponse (/home/laurent/projects/myproject/node_modules/firebase-tools/lib/management/apps.js:190:32)
    at Object.getAppConfigFile (/home/laurent/projects/myproject/node_modules/firebase-tools/lib/management/apps.js:205:12)
    at /home/laurent/projects/myproject/node_modules/firebase-tools/lib/commands/apps-sdkconfig.js:73:29
    at Generator.next (<anonymous>)
    at fulfilled (/home/laurent/projects/myproject/node_modules/firebase-tools/lib/commands/apps-sdkconfig.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Note that with firebase tools v7.16.1 `firebase setup:web` was working fine.

**Comment by bkendall** [comment]
Fixed by #2087

**Comment by bkendall** [comment]
I'll make a patch release today.

**Comment by laurentpayot** [comment]
Wow that was fast. Thanks :+1:
