### ISSUE TITLE
TypeError: options.config.importLegacyKeys is not a function

### ISSUE THREAD

**Issue by adamreisnz** [firebase/firebase-tools#210]
```
[debug] TypeError: options.config.importLegacyKeys is not a function
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:19:20)
    at _chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:21:45)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:24:14
    at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[error] 
[error] Error: An unexpected error has occurred.
```

Command I was trying to run:

`firebase deploy --project staging --public dist/staging`

Firebase version 3.0.7

The problem arises due to the `--public` flag. I need this to work, as I have multiple environments which all have a different output folder, and I can only specify one in `firebase.json`

**Comment by adambuczynski** [comment]
The command works if I change it to:

`firebase deploy --project staging --public ./dist/staging`

I think this needs to be documented somewhere, and the error should probably still be addressed.
