### ISSUE TITLE
failed to install firebase on ubuntu18.04 

### ISSUE THREAD

**Issue by favadk** [firebase/firebase-tools#2101]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**
Linux b1d8231a2687 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### [REQUIRED] Steps to reproduce

1. installed ubuntu 18.04
2. installed npm, curl 
3. ran following command to install firebase

   apt-get install npm
   npm i -g firebase-tools
   curl -sL firebase.tools |upgrade=true bash
   firebase login
   19  npm upgrade
   20  npm update
   21  firebase update
   22  curl -sL https://firebase.tools | bash
   23  curl -sL firebase.tools | upgrade=true bash
   24  firebase login
### [REQUIRED] Expected behavior
expeted to see firebase validation link

### [REQUIRED] Actual behavior
Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/grpc.js:21:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
Something went wrong, firebase has not been installed.
Please file a bug with your system information on Github.
https://github.com/firebase/firebase-tools/
-- All done!
root@b1d8231a2687:/# firebase login
/usr/local/lib/node_modules/firebase-tools/node_modules/@grpc/grpc-js/build/src/index.js:47
    throw new Error(`@grpc/grpc-js only works on Node ${supportedNodeVersions}`);
    ^

Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/grpc.js:21:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)!-- Run the command with --debug flag, and include the logs below. -->

**Comment by samtstern** [comment]
@abeisgoat what version of Node do we bundle with Firepit?

**Comment by abeisgoat** [comment]
You need to upgrade to Node@12 probably using [nvm](https://github.com/nvm-sh/nvm) due to the fact that you install `firebase-tools` globally before installing the binary, we're actually using your global install, so if you upgrade your node version the version of the CLI install via `npm` will begin to work.
