### ISSUE TITLE
firebase init not show my projects

### ISSUE THREAD

**Issue by zahraHaghi** [firebase/firebase-tools#2121]
I am new in pwa.I want to use firebase on my project. I use these commands to init firebase :
```
 npm install -g firebase-tools

firebase login

firebase init
```
 but firebase init not show my projects!! 
`Error: Failed to list Firebase projects. See firebase-debug.log for more info.`
and this is firebase.debug.log
```
You're about to initialize a Firebase project in this directory:

  E:\pwa\pwagram

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2020-04-10T07:10:34.248Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects?pageSize=100  
 
[debug] [2020-04-10T07:10:34.840Z] <<< HTTP RESPONSE 403 {"content-type":"text/html; charset=UTF-8","referrer-policy":"no-referrer","content-length":"1595","date":"Fri, 10 Apr 2020 07:10:34 GMT","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000"}
[debug] [2020-04-10T07:10:34.840Z] <<< HTTP RESPONSE BODY <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/v1beta1/projects</code> from this server.  <ins>That’s all we know.</ins>

[debug] [2020-04-10T07:10:34.841Z] HTTP Error: 403, Unknown Error
[debug] [2020-04-10T07:10:35.437Z] FirebaseError: HTTP Error: 403, Unknown Error
    at module.exports (C:\Users\PZHR.DESKTOP-9L7JS1Q\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:38:12)
    at Request._callback (C:\Users\PZHR.DESKTOP-9L7JS1Q\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:40:35)
    at Request.self.callback (C:\Users\PZHR.DESKTOP-9L7JS1Q\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (C:\Users\PZHR.DESKTOP-9L7JS1Q\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:310:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (C:\Users\PZHR.DESKTOP-9L7JS1Q\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.

```

**Comment by bkendall** [comment]
Can you run `firebase projects:list --debug` and provide `firebase-debug.log`? It does a similar thing and could help debug your issue.
