### ISSUE TITLE
cannot deploy to firebase due to sharp.node

### ISSUE THREAD

**Issue by eng-dibo** [firebase/firebase-tools#2135]
I'm trying to deploy my Angular universal project to firebase, but it failed due to `sharp.node`.

I got the following error:
```
Cannot open node_modules/sharp/build/Release/sharp.node: 

Error: node_modules/sharp/build/Release/sharp.node: cannot open shared object file: No such file or directory

  at Object.<anonymous> (/github/workspace/dist/server.js:4756:551664)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:4756:550687)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:4756:549989)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:3247:71093)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at Object.<anonymous> (/github/workspace/dist/server.js:3009:1755)
    at __webpack_require__ (/github/workspace/dist/server.js:1:142)
    at /github/workspace/dist/server.js:1:1224
    at Object.<anonymous> (/github/workspace/dist/server.js:1:1271)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

You can see the full details of this from [here](https://github.com/goblins-tech/almogtama3/runs/540656778?check_suite_focus=true)

my webpack settings:
```
externals: {
    "./dist/server/main": 'require("./server/main")'
  }


module : {
  rules: [
     {
        test: /\.node$/,
        use: "node-loader"
      }   
  ]
}
```

I added `sharp` to `externals`
```
 externals: {
    'sharp': 'commonjs2 sharp',
    "./dist/server/main": 'require("./server/main")'
  }
```

but I got the following error:
```
Error: Error occurred while parsing your function triggers.

Error: 
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/github/workspace/dist/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by mbleigh** [comment]
Please file an issue with the sharp project itself after following the instructions they provide. The error is coming from your code when the Firebase CLI tries to load it in order to parse triggers -- it's not an issue with the Firebase CLI.

**Comment by eng-dibo** [comment]
@mbleigh 
I already filed an issue with sharp, but they told me to file an issue with firebase

https://github.com/lovell/sharp/issues/2147

**Comment by mbleigh** [comment]
I don't think we can be much help here -- it seems like you have a fairly complex setup and are using webpack to package your functions code.

If you can provide a minimal reproduction -- no webpack, just standard `firebase init` plus `sharp` and it's broken, I think we'll be able to be more help.

**Comment by mbleigh** [comment]
FWIW the trigger parser is pretty simple. The [parseTriggers](https://github.com/firebase/firebase-tools/blob/master/src/parseTriggers.js) function forks a new Node process and runs [triggerParser](https://github.com/firebase/firebase-tools/blob/master/src/triggerParser.js) to pull out the triggers. It's not doing anything very fancy.

**Comment by eng-dibo** [comment]
thank you @mbleigh for you help, 
The issue has been solved.

**Comment by mbleigh** [comment]
Glad to hear it!
