### ISSUE TITLE
Async Interators Not Supported in Node 10

### ISSUE THREAD

**Issue by transcendr** [firebase/firebase-tools#2139]
### [REQUIRED] Environment info

**firebase-tools:**
8.1.0

**Platform:**
Windows

### [REQUIRED] Test case
N/A

### [REQUIRED] Steps to reproduce
firebase deploy --only functions

Set Node.js Version to 10 (package.json):
```json
//...
 "engines": {
    "node": "10"
  },
//..
```

Use **for await of** syntax within an async function:

```js
  async getSubscriptions() {
    const subscriptions = this.client.listSubscriptions({ limit: 200 })
    for await (const subscription of subscriptions.each()) {
      console.log(subscription.uuid)
    }
  }
```

### [REQUIRED] Expected behavior
Node 10 environment natively supports async iterators.

### [REQUIRED] Actual behavior
```bash
$ firebase deploy --only functions --debug
[2020-04-17T07:09:06.692Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]        
[2020-04-17T07:09:06.696Z] > authorizing via signed-in user
[2020-04-17T07:09:06.701Z] [iam] checking project [project] for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2020-04-17T07:09:06.706Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/[project]:testIamPermissions
 {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[2020-04-17T07:09:07.420Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 17 Apr 2020 07:09:10 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=663","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}[2020-04-17T07:09:07.532Z] >>> HTTP REQUEST POST https://iam.googleapis.com/v1/projects/[project]/serviceAccounts/[project]@appspot.gserviceaccount.com:testIamPermissions
 {"permissions":["iam.serviceAccounts.actAs"]}
[2020-04-17T07:09:08.418Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 17 Apr 2020 07:09:11 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; 
ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}

=== Deploying to '[project]'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

[...]
  141:9  error  Parsing error: Unexpected token await

[...]

✖ 7 problems (1 error, 6 warnings)
  0 errors and 6 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2020-04-17T07_07_21_031Z-debug.log
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "%RESOURCE_DIR%" run lint ENOENT
    at notFoundError (C:\Users\[user]\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)    
    at verifyENOENT (C:\Users\[user]\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)    
    at ChildProcess.cp.emit (C:\Users\[user]\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)  
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\[user]\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm --prefix "%RESOURCE_DIR%" run lint',
  path: 'npm --prefix "%RESOURCE_DIR%" run lint',
  spawnargs: []
}

Error: functions predeploy error: Command terminated with non-zero exit code1 
```

**Comment by samtstern** [comment]
Looks like your project failed to lint, you can see the error by running `npm run lint` in your functions directory.  

This doesn't look like an issue with firebase-tools.
