### ISSUE TITLE
Can't run firebase deploy in sub-folders of project

### ISSUE THREAD

**Issue by rtpHarry** [firebase/firebase-tools#2145]
Could this error message be improved or am I the last idiot left in the world that gets tripped up by this?

I was running `firebase deploy --only functions` but I was inside the functions directory so I just kept getting this error:

```
[debug] [2020-04-17T22:11:10.636Z] ----------------------------------------------------------------------
[debug] [2020-04-17T22:11:10.638Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --only functions
[debug] [2020-04-17T22:11:10.638Z] CLI Version:   8.1.0
[debug] [2020-04-17T22:11:10.638Z] Platform:      darwin
[debug] [2020-04-17T22:11:10.638Z] Node Version:  v12.14.1
[debug] [2020-04-17T22:11:10.638Z] Time:          Fri Apr 17 2020 23:11:10 GMT+0100 (British Summer Time)
[debug] [2020-04-17T22:11:10.639Z] ----------------------------------------------------------------------
[debug] [2020-04-17T22:11:10.639Z] 
[debug] [2020-04-17T22:11:10.647Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-17T22:11:10.647Z] > authorizing via signed-in user
[debug] [2020-04-17T22:11:10.647Z] [iam] checking project the-weighter for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2020-04-17T22:11:10.650Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/the-weighter:testIamPermissions  
 {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[debug] [2020-04-17T22:11:10.865Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 17 Apr 2020 22:11:10 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=128","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-04-17T22:11:10.866Z] >>> HTTP REQUEST POST https://iam.googleapis.com/v1/projects/the-weighter/serviceAccounts/the-weighter@appspot.gserviceaccount.com:testIamPermissions  
 {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2020-04-17T22:11:11.793Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 17 Apr 2020 22:11:11 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}
[info] 
[info] === Deploying to 'the-weighter'...
[info] 
[info] i  deploying functions
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script.
[debug] [2020-04-17T22:11:18.231Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "actions-on-google": "^2.12.0",
    "dotenv": "^8.2.0",
    "firebase-admin": "^8.9.0",
    "firebase-functions": "^3.3.0"
  },
  "devDependencies": {
    "tslint": "^5.12.0",
    "typescript": "^3.2.2",
    "firebase-functions-test": "^0.1.6"
  },
  "private": true
}
[debug] [2020-04-17T22:11:18.323Z] Error: ENOENT: no such file or directory, stat 'functions/package.json'
    at Object.statSync (fs.js:915:3)
    at Object.load (/usr/local/lib/node_modules/firebase-tools/node_modules/cjson/index.js:200:12)
    at getRuntimeChoice (/usr/local/lib/node_modules/firebase-tools/lib/parseRuntimeAndValidateSDK.js:55:26)
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:26:29)
    at _chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:22:40)
    at /usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:63:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[error] 
[error] Error: An unexpected error has occurred.
```

Is it unavoidable? Couldn't it just move up to the parent folder internally?

If not could the message be better?

**Comment by bkendall** [comment]
Upgrade to `8.1.1` - this was a known issue fixed by #2142
