### ISSUE TITLE
" firebase init hostin"... An unexpected error has occured

### ISSUE THREAD

**Issue by CodingWookie** [firebase/firebase-tools#2169]
[debug] [2020-04-24T16:46:23.081Z] ----------------------------------------------------------------------
[debug] [2020-04-24T16:46:23.082Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\BEAST\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init hostin
[debug] [2020-04-24T16:46:23.082Z] CLI Version:   8.1.1
[debug] [2020-04-24T16:46:23.082Z] Platform:      win32
[debug] [2020-04-24T16:46:23.082Z] Node Version:  v12.16.2
[debug] [2020-04-24T16:46:23.083Z] Time:          Fri Apr 24 2020 12:46:23 GMT-0400 (Eastern Daylight Time)
[debug] [2020-04-24T16:46:23.083Z] ----------------------------------------------------------------------
[debug] [2020-04-24T16:46:23.083Z] 
[debug] [2020-04-24T16:46:23.088Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-24T16:46:23.111Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\BEAST\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\BEAST\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\BEAST\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by samtstern** [comment]
@CodingWookie thanks! This looks the same as #2144 let's handle it over there
