### ISSUE TITLE
Import Prod Firestore Data Into Emulator

### ISSUE THREAD

**Issue by prescottprue** [firebase/firebase-tools#2175]
Requesting support for importing hosted/prod Firestore Data into the emulator with the `--import` command

Following the steps in [described in this comment](https://github.com/firebase/firebase-tools/issues/1167#issuecomment-599410243) work for importing data after exporting from the emulator,  but when trying to do the following to import data from a hosted instance (using name firestore_export to match what import is expecting):

```bash
gcloud config set project <-your project id ->
gcloud firestore export gs://<-your project id ->.appspot.com/firestore_export
mkdir exported
gsutil -m cp -R gs://<-your project id ->.appspot.com/firestore_export exported/
firebase emulators:start --import ./exported
```

I receive the following error in the `firebase-debug.log`:

```txt
[debug] [2020-04-24T21:45:31.644Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:45:31.646Z] Command:       ~/.nvm/versions/node/v10.15.3/bin/node ./node_modules/.bin/firebase emulators:start --import ./exported --debug
[debug] [2020-04-24T21:45:31.647Z] CLI Version:   8.1.0
[debug] [2020-04-24T21:45:31.647Z] Platform:      darwin
[debug] [2020-04-24T21:45:31.647Z] Node Version:  v10.15.3
[debug] [2020-04-24T21:45:31.648Z] Time:          Fri Apr 24 2020 14:45:31 GMT-0700 (Pacific Daylight Time)
[debug] [2020-04-24T21:45:31.648Z] ----------------------------------------------------------------------
[debug] [2020-04-24T21:45:31.648Z] 
[debug] [2020-04-24T21:45:31.656Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-24T21:45:31.657Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions, firestore, database, hosting, pubsub
[warn] ⚠  emulators: emulator hub unable to start on port 4400, starting on 4401
[debug] [2020-04-24T21:45:31.712Z] [hub] writing locator at /var/folders/2m/9cr73fws1b9bkg6m5hsqf2b40000gn/T/hub-test.json
[info] ✔  hub: emulator hub started at http://localhost:4401
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-04-24T21:45:32.865Z] Error: ENOENT: no such file or directory, open '~/exported/firebase-export-metadata.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (./node_modules/firebase-tools/lib/emulator/controller.js:158:44)
    at Generator.next (<anonymous>)
    at fulfilled (./node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
```

Note: Replaced user path with `~` and current directory path with `.`

It appears it is looking for a `firebase-export-metadata.json` file that isn't generated by the export from production.

When trying to work around by creating one with the following content (copied from one generated by local export):
```json
{"version":"8.1.0","firestore":{"version":"1.11.3","path":"firestore_export","metadata_file":"firestore_export/firestore_export.overall_export_metadata"}}
```
then doing:

```bash
firebase emulators:start --import ./exported
```
I get the following:

```txt
[debug] [2020-04-24T22:01:18.249Z] ----------------------------------------------------------------------
[debug] [2020-04-24T22:01:18.251Z] Command:       ~/.nvm/versions/node/v10.15.3/bin/node ./node_modules/.bin/firebase emulators:start --import ./exported --debug
[debug] [2020-04-24T22:01:18.252Z] CLI Version:   8.1.0
[debug] [2020-04-24T22:01:18.252Z] Platform:      darwin
[debug] [2020-04-24T22:01:18.252Z] Node Version:  v10.15.3
[debug] [2020-04-24T22:01:18.253Z] Time:          Fri Apr 24 2020 15:01:18 GMT-0700 (Pacific Daylight Time)
[debug] [2020-04-24T22:01:18.253Z] ----------------------------------------------------------------------
[debug] [2020-04-24T22:01:18.253Z] 
[debug] [2020-04-24T22:01:18.263Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-24T22:01:18.264Z] > authorizing via signed-in user
[info] i  emulators: Starting emulators: functions, firestore, database, hosting, pubsub
[warn] ⚠  emulators: It seems that you are running multiple instances of the emulator suite for project top-agent-prue-dev. This may result in unexpected behavior.
[debug] [2020-04-24T22:01:18.313Z] [hub] writing locator at /var/folders/2m/9cr73fws1b9bkg6m5hsqf2b40000gn/T/hub-test.json
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] ✔  functions: Using node@10 from host.
[info] ✔  functions: functions emulator started at http://localhost:5001
[info] i  firestore: Importing data from ./exported/firestore_export/firestore_export.overall_export_metadata
[debug] [2020-04-24T22:01:18.336Z] Ignoring unsupported arg: projectId
[debug] [2020-04-24T22:01:18.336Z] Ignoring unsupported arg: auto_download
[debug] [2020-04-24T22:01:18.336Z] Starting firestore emulator with command {"binary":"java","args":["-Duser.language=en","-jar","~/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.3.jar","--host","localhost","--port",8080,"--seed_from_export","./exported/firestore_export/firestore_export.overall_export_metadata","--rules","./packages/cider/firestore.rules","--functions_emulator","localhost:5001"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false}
[info] i  firestore: firestore emulator logging to firestore-debug.log
[debug] [2020-04-24T22:01:18.845Z] Exception in thread "main" 
[debug] [2020-04-24T22:01:18.845Z] com.google.cloud.datastore.core.exception.DatastoreException: Failed to parse overall export metadata file

[debug] [2020-04-24T22:01:18.846Z] 	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseOverallMetadataFile(ExportImportUtil.java:225)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:54)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)

[debug] [2020-04-24T22:01:18.846Z] Caused by: java.io.FileNotFoundException: ./exported/firestore_export/firestore_export.overall_export_metadata (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)

[debug] [2020-04-24T22:01:18.847Z] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseOverallMetadataFile(ExportImportUtil.java:215)
	... 2 more

[error] 
[error] Error: firestore: firestore emulator has exited with code: 1
```

**Comment by samtstern** [comment]
@prescottprue thanks for reporting this, this is definitely confusing.  We designed the import feature of the emulators to rely on some extra metadata generated by `emulators:export`.  The reason for this is that we intend `emulators:start --import` to work for multi-emulator imports once we add support for RTDB exports and (one day) an Auth emulator.

The best way to workaround this right now is:
1) Run `emulators:export` on an empty emulator to generate the metadata file one time
2) Manually edit the metadata file to point at your prod export.

**Comment by fergusmeiklejohn** [comment]
@samtstern I got the import feature to work with data from firestore as you describe, but only by renaming the .overall_export_metadata file I downloaded from gcloud storage bucket. The default naming resulted in a file not found exception and the emulator quit, I renamed it to "backup.overall_export_metadata" and it worked perfectly

**Comment by heygambo** [comment]
We put the JSON file from the export into the functions folder and pointed it to the production export folder from there.

_functions/firebase-export-metadata.json_
```json
{
  "version": "8.4.3",
  "firestore": {
    "version": "1.11.4",
    "path": "seed/12-06-2020-before-load-testing",
    "metadata_file": "seed/12-06-2020-before-load-testing/12-06-2020-before-load-testing.overall_export_metadata"
  }
}
```

_from within the functions folder_
```shell
$ firebase emulators:start --import .
```

**Comment by weilinzung** [comment]
Hi, @samtstern

We have a project that use both RLT Database and Firestore, but it doesn't work if I have Realtime Database and Firestore data.

 If I have both, it only imports the Realtime Database.

![Screenshot 2023-03-08 at 9 43 13 AM](https://user-images.githubusercontent.com/7368063/223743636-f671c1e1-f93f-439e-a746-a43a1ab033b4.png)
