### ISSUE TITLE
Cannot deploy symlinks

### ISSUE THREAD

**Issue by hiroshi** [firebase/firebase-tools#22]
When I had symlinks in my deploy target directory I got the error.

```
$ firebase deploy
Preparing to deploy Public Directory...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Didn't get expected byte count
expect: 33
actual: 4975
    at decorate (/usr/local/lib/node_modules/firebase-tools/node_modules/fstream-ignore/node_modules/fstream/lib/abstract.js:67:36)
    at FileReader.Abstract.error (/usr/local/lib/node_modules/firebase-tools/node_modules/fstream-ignore/node_modules/fstream/lib/abstract.js:61:12)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/fstream-ignore/node_modules/fstream/lib/file-reader.js:66:10)
    at ReadStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

I replaced those symlinks with copied regular files, then the error resolved.
It is great that `firebase deploy` can handle symlinks kindly.

The version of firebase-tools are installed via npm.

```
$ firebase
Firebase Command Line Tools
Version 1.0.4
```

**Comment by pspeter3** [comment]
This seems to be the case still. Is there any reason it has to be?

**Comment by drtriumph** [comment]
This is the PR that fixes the issue: https://github.com/npm/fstream/pull/16 (though a lot has changed since that PR first saw the light of day). The fix was identified 2 1/2 years ago, but the PR finally got assigned to someone a few months ago so it might actually be moving along
