### ISSUE TITLE
Version 8.3.0 raises new error "TypeError: Cannot convert object to primitive value"

### ISSUE THREAD

**Issue by lborgman** [firebase/firebase-tools#2248]
I just updated to 8.3.0 (from 8.2.0). I now see this error:

> ! TypeError: Cannot convert object to primitive value
    at Proxy.<anonymous> (C:\MY_HOME\AppData\Roaming\nvm\v10.18.1\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:311:83)
    at Object.<anonymous> (C:\PATH_TO_MY_PROJ\functions\index.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\lejon\AppData\Roaming\nvm\v10.18.1\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:660:33
!  We were unable to load your functions code. (see above)

I am however not sure that this is related to 8.3.0 since I am rewriting some code. However I am unable to decode the error message above to something in my own code.

**Comment by samtstern** [comment]
This was a regression in `8.3.0` and will be fixed in the next release by: https://github.com/firebase/firebase-tools/pull/2247

For now the best workaround is to downgrade to `8.2.0`

**Comment by lborgman** [comment]
Thanks @samtstern , very nice.
