### ISSUE TITLE
Wrong sample code for use as a module

### ISSUE THREAD

**Issue by ripperdoc** [firebase/firebase-tools#2274]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** macOS Mojave

### [REQUIRED] Test case

I'm trying to use firebase-tools as a module, with the goal of getting current project. I use your sample code from the README.

```
var client = require("firebase-tools");
console.log(Object.getOwnPropertyNames(client))
client
  .list()
.then(function(data) {
    console.log(data);
  })
  .catch(function(err) {
    console.error(err);
});

```

### [REQUIRED] Steps to reproduce

Run above code from CLI.

### [REQUIRED] Expected behavior

That I would get some data structure representing all projects.

### [REQUIRED] Actual behavior

```
TypeError: client.list is not a function
    at Object.<anonymous> (/Users/martin/dev/src/test/test.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1182:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

It seems to work if I change the line to client.projects.list(), so maybe the README is just out of date? Is there a better reference?

**Comment by rosariopfernandes** [comment]
@ripperdoc You are correct. `client.list()` was removed in #1787 and the README was not updated. Thanks for finding that!

Should be fixed by #2278
