### ISSUE TITLE
Unable to call use() without arguments

### ISSUE THREAD

**Issue by ripperdoc** [firebase/firebase-tools#2275]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** macOS Mojave

### [REQUIRED] Test case

```
var client = require("firebase-tools");
console.log(Object.getOwnPropertyNames(client))
client
.use()
.then(function(data) {
    console.log(data);
  })
  .catch(function(err) {
    console.error(err);
});
```

### [REQUIRED] Steps to reproduce

Call above code from CLI.

### [REQUIRED] Expected behavior

I expect that when calling use() without args, it would do similar behavior as the `firebase use` command, which would print the current active project.

### [REQUIRED] Actual behavior

```
TypeError: Cannot read property 'projectRoot' of undefined
```

When I check your code, I can see that the use() command expects to always receive a first argument that is the new project ID to change to, and the second arg is an options object that includes the detected current project. But if no new project ID is given, the options become the first argument and the use() function seem to break.

I know that I can run `firebase use -j` from command line to get current project as JSON, but what can I do programatically using firebase-tools as a module?

**Comment by mbleigh** [comment]
What happens if you call `use({})` instead?

**Comment by ripperdoc** [comment]
Same error unfortunately:
```
TypeError: Cannot read property 'projectRoot' of undefined
    at Command.actionFn (/Users/martin/dev/src/test/node_modules/firebase-tools/lib/commands/use.js:44:18)
    at Command.<anonymous> (/Users/martin/dev/src/test/node_modules/firebase-tools/lib/command.js:161:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/martin/dev/src/test/node_modules/firebase-tools/lib/command.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mbleigh** [comment]
One more guess, `use('', {})` maybe?

**Comment by ripperdoc** [comment]
That did the trick, it returns just the project ID. I think I can work with that, but perhaps it can be clarified how the commands are expected to be called when used as module.

**Comment by gautamsingal** [comment]
@samtstern can you please confirm if this needs to be updated in the documentation? I would like to pick up this issue

**Comment by samtstern** [comment]
Yes the docs still need updating and a PR would be welcomed!

**Comment by gautamsingal** [comment]
Thanks for the update. Can you please point me to the docs link to be updated?

**Comment by samtstern** [comment]
https://github.com/firebase/firebase-tools#using-as-a-module

**Comment by gautamsingal** [comment]
Thanks. But it does not have mention of use(). It talks about list(). Should I add one more code snippet to the documentation stating use()?

**Comment by samtstern** [comment]
The documentation is meant to show how to call any command of `firebase-tools` and pass the appropriate args and options.  You can expand it to show another snippet with `use()` and explain how that differs from `list()` or you can do something else, whatever you think is clearest.

**Comment by gautamsingal** [comment]
@samtstern Thanks. Have raised a PR. Could you please have a look at it?

**Comment by gautamsingal** [comment]
@samtstern I have raised the PR. Could you please have a look at it? https://github.com/firebase/firebase-tools/pull/2348
