### ISSUE TITLE
error running firebase emulators:export [path]

### ISSUE THREAD

**Issue by shedali** [firebase/firebase-tools#2281]
### Environment info

**firebase-tools:**
firebase 8.4.0

**Platform:**
mac Catalina 10.15.4

### Test case
contents of firebase.json
```json
{
  "database": {
    "rules": "database.rules.json"
  },
  "emulators": {
    "database": {
      "port": 9000
    },
    "ui": {
      "enabled": true
    }
  }
}

```

### Steps to reproduce
run emulator with `firebase emulators:start`

starts successfully 
```Database │ localhost:9000 │ http://localhost:4000/database ```

then run `firebase emulator:export data`  (where data is an empty directory).

`firebase emulators:export data`

###  Expected behavior
I was hoping for the data directory to be populated with the contents of the running database

### Actual behavior
```
i  Found running emulator hub for project x-15d36 at http://localhost:4400
i  Exporting data to: /Users/franz/dev/monorepotest/packages/x-front-end-sapper/data
```

```  
emulators: Export failed: No running emulators support import/export.
```

```firebase emulators:export data --debug
[2020-05-24T16:40:42.253Z] >>> HTTP REQUEST GET http://localhost:4400/

[2020-05-24T16:40:42.267Z] <<< HTTP RESPONSE 200 {"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"50","etag":"W/\"32-rebo45ECKTRdnp8WX58/yCISkRY\"","date":"Sun, 24 May 2020 16:40:42 GMT","connection":"keep-alive"}
i  Found running emulator hub for project x-15d36 at http://localhost:4400
i  Exporting data to: /Users/franz/dev/monorepotest/packages/x-front-end-sapper/data
[2020-05-24T16:40:42.269Z] >>> HTTP REQUEST POST http://localhost:4400/_admin/export
 {"path":"/Users/franz/dev/monorepotest/packages/x-front-end-sapper/data"}
[2020-05-24T16:40:42.274Z] <<< HTTP RESPONSE 500 {"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"57","etag":"W/\"39-zFt861G8Js39Z08j6nLAktZD9Q4\"","date":"Sun, 24 May 2020 16:40:42 GMT","connection":"keep-alive"}
[2020-05-24T16:40:42.274Z] <<< HTTP RESPONSE BODYNo running emulators support import/export. {"message":"No running emulators support import/export."}
[2020-05-24T16:40:42.388Z] FirebaseError: HTTP Error: 500, Unknown Error
    at module.exports (/Users/franz/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/franz/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/api.js:41:35)
    at Request.self.callback (/Users/franz/.cache/firebase/tools/lib/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/Users/franz/.cache/firebase/tools/lib/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/Users/franz/.cache/firebase/tools/lib/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Error: Export request failed, see emulator logs for more information.

```

**Comment by samtstern** [comment]
@shedali it looks like you're only using the Realtime Database emulator.  Right now import/export only supports Cloud Firestore although we are working hard to add RTDB support! So currently this error is correct: `No running emulators support import/export.`

**Comment by shedali** [comment]
thank you @samtstern
