### ISSUE TITLE
Functions emulator should run functions.predeploy

### ISSUE THREAD

**Issue by hatboysam** [firebase/firebase-tools#2288]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** Windows - WSL2 Debian

### [REQUIRED] Test case

```
// Choose Functions and use TypeScript
firebase init
```

```
firebase emulators:start
```

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

A default `firebase init` project should be ready to run in the emulators.

### [REQUIRED] Actual behavior

**Problem 1**
```
i  functions: Watching "/home/samstern/Projects/diff-machine/functions" for Cloud Functions...
⚠  Error: Cannot find module '/home/samstern/Projects/diff-machine/functions'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/samstern/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:661:33
    at Generator.next (<anonymous>)
    at fulfilled (/home/samstern/.nvm/versions/node/v8.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
```

**Problem 2**
```
samstern@DESKTOP-KPNL712:~/Projects/diff-machine/functions$ npm run build

> functions@ build /home/samstern/Projects/diff-machine/functions
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value is never read.

1 import * as functions from 'firebase-functions';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dearborndenim** [comment]
cli isn't creating the lib folder. Looking for a solution in the docs but can't find one.

**Comment by samtstern** [comment]
@hatboysam thanks you're the best!

**Comment by samtstern** [comment]
Closing in favor of #701
