### ISSUE TITLE
Unexpected error occur when firebase login with Nodejs 7.1.0

### ISSUE THREAD

**Issue by paradigmist** [firebase/firebase-tools#232]
running `firebase login --debug` on nodejs 7.1.0, windows 10, firebase CLI 3.1.0

```
Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)

Error: An unexpected error has occurred.
Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.log (console.js:43:16)
    at process.<anonymous> (C:\Users\FONG\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase:76:17)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)

Error: An unexpected error has occurred.
```

**Comment by dannysuryadi** [comment]
Also having this issue on Windows, nodejs 7.10, firebase CLI 3.1.0

**Comment by kudavid** [comment]
Solution has been found?

And tried but could not solve it

**Comment by towlebooth** [comment]
I am also having this issue Win 10, firebase CLI 3.2.0

**Comment by maurodaprotis** [comment]
I was having the same problem. Downgrade node to 6.9.1 fix it

**Comment by Dav3Ku** [comment]
So it's colleagues, it's a detail in Node.JS v7.1.0 ... I've managed to make it run degraded to v6.9.1

**Comment by 628426** [comment]
Node 7.9 resolved this for me

https://github.com/nodejs/node/issues/9542

**Comment by mbleigh** [comment]
If it was a Node.js issue, I'm going to consider this closed. Please re-open if you feel there's something to be done on our end.
