### ISSUE TITLE
Emulator Firestore: Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by dennis-tra** [firebase/firebase-tools#2338]
### [REQUIRED] Environment info

`package.json`:
```json
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "firestore": "npm run build && firebase emulators:start --only firestore",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "test": "mocha"
  },
  "engines": {
    "node": "10"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.6.2"
  },
  "devDependencies": {
    "@firebase/app-types": "^0.6.1",
    "@firebase/testing": "^0.20.0",
    "@testdeck/mocha": "^0.1.0",
    "@types/chai": "^4.2.11",
    "@types/mocha": "^7.0.2",
    "@types/sinon": "^9.0.4",
    "chai": "^4.2.0",
    "firebase-functions-test": "^0.2.1",
    "mocha": "^7.2.0",
    "sinon": "^9.0.2",
    "source-map-support": "^0.5.19",
    "ts-node": "^8.10.2",
    "tslint": "^5.12.0",
    "typescript": "^3.8.0"
  },
  "private": true,
  "mocha": {
    "spec": "src/*.test.ts",
    "require": [
      "source-map-support/register",
      "ts-node/register"
    ]
  }
}
```

**firebase-tools:** 8.4.2
**Platform:** macOS - 10.15.4
**yarn:** 1.22.4

### [REQUIRED] Test case

```typescript
// index.ts
import * as functions from 'firebase-functions';
import * as admin from "firebase-admin"

admin.initializeApp();

export const helloWorld = functions.https.onCall(async (data, context) => {
    await admin.firestore().collection("test").doc().set({
        "hello": "world",
    })
    return "Hello world!"
});
```

```typescript
// index.test.ts

import { expect } from "chai";
import { describe, test } from "mocha";
import * as tester from "firebase-functions-test"

import { helloWorld } from "./index";

describe("group", () => {
    test("case", async () => {
        const wrapped = tester().wrap(helloWorld);
        expect(await wrapped(null)).to.equal("Hello world!")
    });
});

```

### [REQUIRED] Steps to reproduce

```shell
firebase emulators:exec "npm run test"
```

### [REQUIRED] Expected behavior

The test case passes.

### [REQUIRED] Actual behavior
I receive the error: `Channel credentials must be a ChannelCredentials object`

The complete log output below:
```
i  emulators: Starting emulators: functions, firestore, hosting
✔  functions: Using node@10 from host.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
i  functions: Watching "/Users/xxx/firebase/functions" for Cloud Functions...
✔  functions[helloWorld]: http function initialized (http://localhost:5001/gcloud-project/us-central1/helloWorld).
i  Running script: npm run test

> functions@ test /Users/xxx/firebase/functions
> mocha

Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail


  My Test
    1) test


  0 passing (277ms)
  1 failing

  1) group
       case:
     TypeError: Channel credentials must be a ChannelCredentials object
      at new ChannelImplementation (node_modules/google-gax/node_modules/@grpc/grpc-js/src/channel.ts:150:13)
      at new Client (node_modules/google-gax/node_modules/@grpc/grpc-js/src/client.ts:146:30)
      at new ServiceClientImpl (node_modules/google-gax/node_modules/@grpc/grpc-js/src/make-client.ts:119:3)
      at GrpcClient.createStub (node_modules/google-gax/src/grpc.ts:290:18)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  Caused by: Error:
      at WriteBatch.commit (node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
      at DocumentReference.set (node_modules/@google-cloud/firestore/build/src/reference.js:341:14)
      at Function.exports.helloWorld.functions.https.onCall [as run] (src/index.ts:7:54)
      at wrapped (node_modules/firebase-functions-test/lib/main.js:71:30)
      at Context.mocha_1.test (src/index.test.ts:10:22)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.cache/npm/_logs/2020-06-06T15_13_55_632Z-debug.log
⚠  Script exited unsuccessfully (code 1)
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  functions: Stopping Functions Emulator
i  firestore: Stopping Firestore Emulator
i  hosting: Stopping Hosting Emulator

Error: Script "npm run test" exited with code 1
```

### Related issues
1. #2207 : Here the function is run inside the emulator. In my case I'm running them locally and just want them to talk to the firestore emulator. By doing it this way I can stub other side effects.
2. [nodejs-firestore #998](https://github.com/googleapis/nodejs-firestore/issues/998): This seems to be a very similar issue, but none of the suggestions worked. However there was the presumption that multiple versions of `@grpc/grpc-js` could be the problem - and indeed if I browse through my `yarn.lock` I see two `@grpc/grpc-js`-versions. `0.8.1` coming from `@firebase/testing` and `1.0.3` coming from `firebase-admin`.

Removing `@firebase/testing` from my `package.json` solves the problem - this is in the stripped example above no problem because it is not used. However I actually would like to use some of the features of that package.

Is it possible to depend on both packages simultaneously without running into this error? I'm asking for a workaround because I presume the right solution would be that `firebase-js-sdk` (more precisely `@firebase/firestore`) updates its `@grpc/grpc-js` dependency.

Cheers,
Dennis

PS: For me it not a big problem to split the parts that need `@firebase/testing` into a separate package, so another intention of this issue is to have it here for reference for others.
PPS: I'm happy to move this issue to another repo. E.g. `firebase-js-sdk`

**Comment by samtstern** [comment]
@dennis-tra I do think we should move this to the JS SDK repo as this is not looking like a CLI issue. I'll transfer it.  Can you use `yarn why` to show all the places that a `@grpc/grpc-js` dependency is coming from?
