### ISSUE TITLE
firebase init not working 

### ISSUE THREAD

**Issue by yudhiesh1997** [firebase/firebase-tools#2422]
### [REQUIRED] Environment info

**firebase-tools:**
Unable to tell as firebase --version is throwing the same error 

**Platform:**
macOS Catalina 
Version 10.15.5
### [REQUIRED] Test case
I created a project then firebase functions notified me that my node.js version for the project was going to be depreciated. So I updated the package.json with version 10 of node.js instead of version 8. This resulted in the problem, I deleted the folder on my system and tried doing it all over again but now I ran into this issue. 

### [REQUIRED] Steps to reproduce
firebase init 

### [REQUIRED] Expected behavior
Menu to choose the firebase functions for my project 

### [REQUIRED] Actual behavior
internal/modules/cjs/loader.js:548
  throw e;
  ^

Error: Package exports for '/Users/yudhiesh/.config/yarn/global/node_modules/universal-analytics/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/yudhiesh/.config/yarn/global/node_modules/universal-analytics/lib/index.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by yudhiesh1997** [comment]
I have tried uninstalling and reinstalling firebase but get the same error.

**Comment by mbleigh** [comment]
Have you tried using npm instead of yarn?

**Comment by samtstern** [comment]
This looks a bit like this issue since it mentions `uuid`:
https://github.com/firebase/firebase-tools/issues/2430

Are you by chance using Node 13?  If so could you try using Node 12 or 14?

**Comment by yudhiesh1997** [comment]
> This looks a bit like this issue since it mentions `uuid`:
> #2430
> 
> Are you by chance using Node 13? If so could you try using Node 12 or 14?

I fixed it by reinstalling firebase and upgrading to Node 14 thanks
