### ISSUE TITLE
onUpdate works on Cloud Firestore but not on Realtime Database in emulator

### ISSUE THREAD

**Issue by paulyip** [firebase/firebase-tools#2441]
### [REQUIRED] Environment info

**firebase-tools:** 8.5

**Platform:** macOS

### [REQUIRED] Test case

    import * as functions from 'firebase-functions'
    import * as admin from 'firebase-admin'

    admin.initializeApp()
    const rootRef = admin.database()

    export const helloWorld = functions.https.onRequest(async(request, response) => {
    try 
    {
        await admin.database().ref().child('users').push({name : 'peter'})
        await admin.firestore().collection('users').add({name : 'peter'})
    }
    catch (error)
    {
        console.log(error)
    }
        response.send("Hello from Firebase from emulator!")
    })

    export const onFirestoreUpdate = functions.firestore
        .document('users/{userId}')
        .onUpdate((change, context) => {
            console.log('onFirestoreUpdate')
                return change.after.ref.update({age:22})
    })

    export const onDatabaseUpdate = functions.database
        .ref('/users/{userId}')
        .onUpdate(async(change, context) => {
            console.log('onDatabaseUpdate')
            return change.after.ref.update({age:22})
    })

The above code create functions helloWorld, onFirestoreUpdate, onDatabaseUpdate

### [REQUIRED] Steps to reproduce

1. Build the code above
npm run-script build

2. Start emulator
firebase emulators:start

3. Call helloWorld function
http://localhost:5001/xxx/us-central1/helloWorld

4. User created
You should find a user 'peter' in both Cloud Firestore and Realtime Database.

5. Change the user name on Cloud Firestore emulator
On Cloud Firestore emulator, change user name from 'peter' to 'mary', a field age 22 is created.

6. Change the user name on Realtime Database emulator
On Realtime Database emulator, change user name from 'peter' to 'mary', failed to create age field.

### [REQUIRED] Expected behavior

On step 6, a field age 22 is expected to be created.

### [REQUIRED] Actual behavior

The following is the log message when change the name on Realtime Database.

[2020-07-10T09:36:28.845Z] [work-queue] {"queueLength":1,"workRunningCount":0}
[2020-07-10T09:36:28.845Z] [work-queue] {"queueLength":0,"workRunningCount":1}
[2020-07-10T09:36:28.845Z] Accepted request POST /functions/projects/yyy-5ddf8/triggers/onDatabaseUpdate --> onDatabaseUpdate {"metadata":{"emulator":{"name":"functions"},"message":"Accepted request POST /functions/projects/yyy-5ddf8/triggers/onDatabaseUpdate --> onDatabaseUpdate"}}
[2020-07-10T09:36:28.845Z] [worker-pool] Cleaned up workers for onDatabaseUpdate: 1 --> 0 {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] Cleaned up workers for onDatabaseUpdate: 1 --> 0"}}
[2020-07-10T09:36:28.851Z] [worker-pool] addWorker(onDatabaseUpdate) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] addWorker(onDatabaseUpdate)"}}
[2020-07-10T09:36:28.851Z] [worker-pool] Adding worker with key onDatabaseUpdate, total=1 {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] Adding worker with key onDatabaseUpdate, total=1"}}
[2020-07-10T09:36:28.851Z] [worker-pool] submitWork(triggerId=onDatabaseUpdate) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] submitWork(triggerId=onDatabaseUpdate)"}}
[2020-07-10T09:36:28.852Z] [worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: Assigning socketPath: /var/folders/_m/gw0hprdj6k378dwcd7gbvpjr0000gp/T/fire_emu_6013.sock {"metadata":{"emulator":{"name":"functions"},"message":"[worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: Assigning socketPath: /var/folders/_m/gw0hprdj6k378dwcd7gbvpjr0000gp/T/fire_emu_6013.sock"}}
[2020-07-10T09:36:28.852Z] [worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: BUSY {"metadata":{"emulator":{"name":"functions"},"message":"[worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: BUSY"}}
[2020-07-10T09:36:29.054Z] [runtime-status] [6013] Functions runtime initialized. {"cwd":"/Users/xxx/projects/yyy/cloud-functions/functions","node_version":"12.13.0"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Functions runtime initialized. {\"cwd\":\"/Users/xxx/projects/yyy/cloud-functions/functions\",\"node_version\":\"12.13.0\"}"}}
[2020-07-10T09:36:29.055Z] [runtime-status] [6013] Disabled runtime features: undefined {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Disabled runtime features: undefined"}}
[2020-07-10T09:36:29.056Z] [runtime-status] [6013] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.12.1","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"8.12.1\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js\"}"}}
[2020-07-10T09:36:29.057Z] [runtime-status] [6013] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.7.0","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.7.0\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[2020-07-10T09:36:29.058Z] [runtime-status] [6013] Outgoing network have been stubbed. [{"name":"http","status":"mocked"},{"name":"http","status":"mocked"},{"name":"https","status":"mocked"},{"name":"https","status":"mocked"},{"name":"net","status":"mocked"}] {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Outgoing network have been stubbed. [{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"net\",\"status\":\"mocked\"}]"}}
[2020-07-10T09:36:29.058Z] [runtime-status] [6013] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.7.0","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.7.0\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[2020-07-10T09:36:29.087Z] [runtime-status] [6013] Checked functions.config() {"config":{}} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Checked functions.config() {\"config\":{}}"}}
[2020-07-10T09:36:29.087Z] [runtime-status] [6013] firebase-functions has been stubbed. {"functionsResolution":{"declared":true,"installed":true,"version":"3.7.0","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] firebase-functions has been stubbed. {\"functionsResolution\":{\"declared\":true,\"installed\":true,\"version\":\"3.7.0\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js\"}}"}}
[2020-07-10T09:36:29.088Z] [runtime-status] [6013] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.7.0","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.7.0\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[2020-07-10T09:36:29.088Z] [runtime-status] [6013] Resolved module firebase-admin {"declared":true,"installed":true,"version":"8.12.1","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"8.12.1\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js\"}"}}
[2020-07-10T09:36:29.089Z] [runtime-status] [6013] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.7.0","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.7.0\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[2020-07-10T09:36:29.089Z] [runtime-status] [6013] firebase-admin has been stubbed. {"adminResolution":{"declared":true,"installed":true,"version":"8.12.1","resolution":"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] firebase-admin has been stubbed. {\"adminResolution\":{\"declared\":true,\"installed\":true,\"version\":\"8.12.1\",\"resolution\":\"/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/index.js\"}}"}}
[2020-07-10T09:36:29.130Z] [runtime-status] [6013] initializeApp(DEFAULT) {"databaseURL":"https://yyy-5ddf8.firebaseio.com","storageBucket":"yyy-5ddf8.appspot.com","projectId":"yyy-5ddf8"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] initializeApp(DEFAULT) {\"databaseURL\":\"https://yyy-5ddf8.firebaseio.com\",\"storageBucket\":\"yyy-5ddf8.appspot.com\",\"projectId\":\"yyy-5ddf8\"}"}}
[2020-07-10T09:36:29.181Z] [runtime-status] [6013] Trigger "onDatabaseUpdate" has been found, beginning invocation! {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Trigger \"onDatabaseUpdate\" has been found, beginning invocation!"}}
i  functions: Beginning execution of "onDatabaseUpdate" {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"Beginning execution of \"onDatabaseUpdate\""}}
[2020-07-10T09:36:29.181Z] [runtime-status] [6013] triggerDefinition {"eventTrigger":{"resource":"projects/_/instances/yyy-5ddf8/refs/users/{userId}","eventType":"providers/google.firebase.database/eventTypes/ref.update","service":"firebaseio.com"},"name":"onDatabaseUpdate","entryPoint":"onDatabaseUpdate"} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] triggerDefinition {\"eventTrigger\":{\"resource\":\"projects/_/instances/yyy-5ddf8/refs/users/{userId}\",\"eventType\":\"providers/google.firebase.database/eventTypes/ref.update\",\"service\":\"firebaseio.com\"},\"name\":\"onDatabaseUpdate\",\"entryPoint\":\"onDatabaseUpdate\"}"}}
[2020-07-10T09:36:29.181Z] [runtime-status] [6013] Running onDatabaseUpdate in mode BACKGROUND {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Running onDatabaseUpdate in mode BACKGROUND"}}
[2020-07-10T09:36:29.181Z] [runtime-status] [6013] ProcessBackground {"eventType":"providers/google.firebase.database/eventTypes/ref.update","params":{"userId":"-MBs3w3iL5xBfSfxnbrX"},"auth":{"admin":true},"domain":"localhost","data":{"data":{"name":"peter"},"delta":{"name":"mary"}},"resource":"projects/_/instances/yyy-5ddf8/refs/users/-MBs3w3iL5xBfSfxnbrX","timestamp":"2020-07-10T09:36:28.839Z","eventId":"OHqDCJDT8tC5nkLjlHtu+oGxqJo="} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] ProcessBackground {\"eventType\":\"providers/google.firebase.database/eventTypes/ref.update\",\"params\":{\"userId\":\"-MBs3w3iL5xBfSfxnbrX\"},\"auth\":{\"admin\":true},\"domain\":\"localhost\",\"data\":{\"data\":{\"name\":\"peter\"},\"delta\":{\"name\":\"mary\"}},\"resource\":\"projects/_/instances/yyy-5ddf8/refs/users/-MBs3w3iL5xBfSfxnbrX\",\"timestamp\":\"2020-07-10T09:36:28.839Z\",\"eventId\":\"OHqDCJDT8tC5nkLjlHtu+oGxqJo=\"}"}}
[2020-07-10T09:36:29.182Z] [runtime-status] [6013] RunBackground {"data":{"data":{"name":"peter"},"delta":{"name":"mary"}},"context":{"eventType":"providers/google.firebase.database/eventTypes/ref.update","params":{"userId":"-MBs3w3iL5xBfSfxnbrX"},"auth":{"admin":true},"domain":"localhost","resource":"projects/_/instances/yyy-5ddf8/refs/users/-MBs3w3iL5xBfSfxnbrX","timestamp":"2020-07-10T09:36:28.839Z","eventId":"OHqDCJDT8tC5nkLjlHtu+oGxqJo="}} {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] RunBackground {\"data\":{\"data\":{\"name\":\"peter\"},\"delta\":{\"name\":\"mary\"}},\"context\":{\"eventType\":\"providers/google.firebase.database/eventTypes/ref.update\",\"params\":{\"userId\":\"-MBs3w3iL5xBfSfxnbrX\"},\"auth\":{\"admin\":true},\"domain\":\"localhost\",\"resource\":\"projects/_/instances/yyy-5ddf8/refs/users/-MBs3w3iL5xBfSfxnbrX\",\"timestamp\":\"2020-07-10T09:36:28.839Z\",\"eventId\":\"OHqDCJDT8tC5nkLjlHtu+oGxqJo=\"}}"}}
>  onDatabaseUpdate {"user":"onDatabaseUpdate","metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"\u001b[90m> \u001b[39m onDatabaseUpdate"}}
>  [2020-07-10T09:36:29.184Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com  {"user":"[2020-07-10T09:36:29.184Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com ","metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"\u001b[90m> \u001b[39m [2020-07-10T09:36:29.184Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com "}}
[2020-07-10T09:36:29.184Z] [runtime-status] [6013] Ephemeral server survived. {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"[runtime-status] [6013] Ephemeral server survived."}}
⚠  functions: Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com 
    at fatal (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:341:11)
    at parseRepoInfo (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:1295:9)
    at RepoManager.databaseFromApp (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:14986:25)
    at Object.initStandalone (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15377:45)
    at DatabaseService.getDatabase (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/database/database.js:66:23)
    at FirebaseApp.database (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-app.js:231:24)
    at DataSnapshot.get ref [as ref] (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/providers/database.js:279:34)
    at /Users/xxx/projects/yyy/cloud-functions/functions/lib/zzz.js:793:25
    at cloudFunction (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/cloud-functions.js:132:23)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:563:20 {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com \n    at fatal (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:341:11)\n    at parseRepoInfo (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:1295:9)\n    at RepoManager.databaseFromApp (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:14986:25)\n    at Object.initStandalone (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15377:45)\n    at DatabaseService.getDatabase (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/database/database.js:66:23)\n    at FirebaseApp.database (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-app.js:231:24)\n    at DataSnapshot.get ref [as ref] (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/providers/database.js:279:34)\n    at /Users/xxx/projects/yyy/cloud-functions/functions/lib/zzz.js:793:25\n    at cloudFunction (/Users/xxx/projects/yyy/cloud-functions/functions/node_modules/firebase-functions/lib/cloud-functions.js:132:23)\n    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:563:20"}}
⚠  Your function was killed because it raised an unhandled error. {"metadata":{"emulator":{"name":"functions"},"function":{"name":"onDatabaseUpdate"},"message":"Your function was killed because it raised an unhandled error."}}
[2020-07-10T09:36:29.189Z] [worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: exited {"metadata":{"emulator":{"name":"functions"},"message":"[worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: exited"}}
[2020-07-10T09:36:29.189Z] [worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: FINISHED {"metadata":{"emulator":{"name":"functions"},"message":"[worker-onDatabaseUpdate-42e77fd7-81db-4c94-b438-d00088467c72]: FINISHED"}}
[2020-07-10T09:36:29.190Z] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client {"metadata":{"emulator":{"name":"functions"},"message":{"code":"ERR_HTTP_HEADERS_SENT"}}}
[2020-07-10T09:36:29.190Z] [work-queue] {"queueLength":0,"workRunningCount":0}

**Comment by samtstern** [comment]
@paulyip this is actually the same as this issue:
https://github.com/firebase/firebase-functions/issues/726

We are working on a fix.  The issue is with `change.after.ref`, and the workaround is to build your own ref to the document inside the function using `admin.database().ref()...`
