### ISSUE TITLE
Cannot serve function locally

### ISSUE THREAD

**Issue by Mdsp9070** [firebase/firebase-tools#2447]
### [REQUIRED] Environment info

**firebase-tools:** 8.5.0

**Platform:** Manjaro Gnome

### [REQUIRED] Test case

Tried to access functions with route param like: ```http://localhost:5000/api-camera-browser/us-central1/default/2969```

### [REQUIRED] Steps to reproduce

1. Create a function with a route that receive only a route param
2. Try to serve locally

### [REQUIRED] Expected behavior

Return a response like: 
![Screenshot from 2020-07-11 16-04-32](https://user-images.githubusercontent.com/44469426/87231756-42b3ad80-c390-11ea-9cf4-be715b154309.png)

### [REQUIRED] Actual behavior

Gives me this error on console: 
```
Error: listen EACCES: permission denied 127.0.0.1:80
>      at Server.setupListenHandle [as _listen2] (net.js:1296:21)
>      at listenInCluster (net.js:1361:12)
>      at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
>      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
>  Emitted 'error' event on Server instance at:
>      at emitErrorNT (net.js:1340:8)
>      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>    code: 'EACCES',
>    errno: -13,
>    syscall: 'listen',
>    address: '127.0.0.1',
>    port: 80
>  }
```
And gives me a empty response with status 200

github repo: https://github.com/Mdsp9070/cameraBrowser

**Comment by Mdsp9070** [comment]
Was a local issue when exporting the function to ```functions.https.onRequest()```
