### ISSUE TITLE
Can't access function with route param

### ISSUE THREAD

**Issue by Mdsp9070** [firebase/firebase-tools#2448]
### [REQUIRED] Environment info

**firebase-tools:** 8.5.0

**Platform:** Manjaro Gnome

### [REQUIRED] Test case

Tried to deploy function and access it

### [REQUIRED] Steps to reproduce

1. Create a function that receives a request with a route param
2. Deploy it to firabase functions
3. Try to get a response

### [REQUIRED] Expected behavior

I want to receive this response:

![Screenshot from 2020-07-11 16-24-22](https://user-images.githubusercontent.com/44469426/87232122-fc138280-c392-11ea-9f0a-980fb0009158.png)

### [REQUIRED] Actual behavior

Gives me this error:
```
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/index.js:77:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```
And a reponse with status 500 and error: ```Error: could not handle the request```

**Comment by Mdsp9070** [comment]
Was a local mistake when exporting the function to ```functions.https.onRequest()```
