### ISSUE TITLE
Firebase CLI: features[nextFeature] is not a function

### ISSUE THREAD

**Issue by sorcerershell** [firebase/firebase-tools#246]
Error happens when I'm initializing new project.

```
$  ~ firebase init . --debug
=== . Setup
TypeError: features[nextFeature] is not a function
    at init (/usr/local/lib/node_modules/firebase-tools/lib/init/index.js:14:46)
    at /usr/local/lib/node_modules/firebase-tools/lib/init/index.js:15:14
    at tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Error: An unexpected error has occurred.
```

Please help.. Thanks!

**Comment by sorcerershell** [comment]
My bad.. sorry.. It's fixed by removing . (dot) from command
