### ISSUE TITLE
can not login in firebase through cmd

### ISSUE THREAD

**Issue by johnshu666** [firebase/firebase-tools#2472]
Waiting for authentication...

```
[2020-07-20T04:21:37.073Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token
 {"code":"4/2AHhG0fg_g8wL95r7oMNM0CfBbj8kVkhH7q7KNhNb3Hkkjvl1aOX8ttcE_fw-yalu-GYsGSubo_x9ggieJWp0cY","client_id":"563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com","client_secret":"j9iVZfS8kkCEFUPaAeJV0sAi","redirect_uri":"http://localhost:9005","grant_type":"authorization_code"}
[2020-07-20T04:21:58.105Z] Token Fetch Error: FirebaseError: Server Error. connect ETIMEDOUT 172.217.160.77:443

    at Request._callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:32:31)
    at self.callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.onRequestError (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by johnshu666** [comment]
hello, friends, I have no idea what happened!!!

**Comment by samtstern** [comment]
The error implies that there was either a backend error or a problem with your internet connection:
```
Server Error. connect ETIMEDOUT 172.217.160.77:443
```

Does this happen every time?

**Comment by htshnr** [comment]
I have the same problem too, firebase doesn't fetch my list of projects, and instead times out (FirebaseError: Server Error. connect ETIMEDOUT).

I'm guessing this might be because of the depreciated request library? #2215

**Comment by bkendall** [comment]
I would be very surprised if it was caused by `request`.

In addition to Sam's question: do any other request succeed? Can you provide more of the debug logs?

**Comment by htshnr** [comment]
Seems to be working now. Might have been a temporary issue with the network.

**Comment by johnshu666** [comment]
> The error implies that there was either a backend error or a problem with your internet connection:
> 
> ```
> Server Error. connect ETIMEDOUT 172.217.160.77:443
> ```
> 
> Does this happen every time?

yes all the time

**Comment by johnshu666** [comment]
C:\Users\AA\offical-website>firebase --debug login
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again.

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=152092506&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
[2020-07-25T03:41:58.273Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token
 {"code":"4/2QFlOwfq1DcIbMySGN2UWIvSLk08ZaXWg5fqBBhWB_1veFtOeJp-IdF6Jat0L0hGxMX9GoEPU_JjFZYzi4MUIVo","client_id":"563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com","client_secret":"j9iVZfS8kkCEFUPaAeJV0sAi","redirect_uri":"http://localhost:9005","grant_type":"authorization_code"}
[2020-07-25T03:42:19.302Z] Token Fetch Error: FirebaseError: Server Error. connect ETIMEDOUT 172.217.160.109:443
    at Request._callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:32:31)
    at self.callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.onRequestError (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

hello, I am trying it again, the whole error message in the above.

**Comment by samtstern** [comment]
@johnshu666 unfortunately there's nothing we can do if you're getting network timeout errors consistently (`ETIMEDOUT`).  It's almost certainly an issue with your network configuration, maybe you're using some kind of VPN or Proxy?  Proxy issues have been widely reported and discussed (see #155).

If you want to try and get around `firebase login` you can authorize as a service account using `GOOGLE_APPLICATION_CREDENTIALS` (see README) but I suspect you will just run into a new timeout error when you try to access the next Google API.

**Comment by tchen62** [comment]
> ```
> C:\Users\AA\offical-website>firebase --debug login
> i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
> 
> ? Allow Firebase to collect CLI usage and error reporting information? Yes
> i  To change your data collection preference at any time, run `firebase logout` and log in again.
> 
> Visit this URL on this device to log in:
> https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=152092506&redirect_uri=http%3A%2F%2Flocalhost%3A9005
> 
> Waiting for authentication...
> [2020-07-25T03:41:58.273Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token
>  {"code":"4/2QFlOwfq1DcIbMySGN2UWIvSLk08ZaXWg5fqBBhWB_1veFtOeJp-IdF6Jat0L0hGxMX9GoEPU_JjFZYzi4MUIVo","client_id":"563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com","client_secret":"j9iVZfS8kkCEFUPaAeJV0sAi","redirect_uri":"http://localhost:9005","grant_type":"authorization_code"}
> [2020-07-25T03:42:19.302Z] Token Fetch Error: FirebaseError: Server Error. connect ETIMEDOUT 172.217.160.109:443
>     at Request._callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:32:31)
>     at self.callback (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.EventEmitter.emit (domain.js:482:12)
>     at Request.onRequestError (C:\Users\AA\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
>     at ClientRequest.emit (events.js:315:20)
>     at ClientRequest.EventEmitter.emit (domain.js:482:12)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:315:20)
>     at TLSSocket.EventEmitter.emit (domain.js:482:12)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> ```
> 
> hello, I am trying it again, the whole error message in the above.

do you find solution？
