### ISSUE TITLE
Authentication error with CLI

### ISSUE THREAD

**Issue by farah** [firebase/firebase-tools#2492]
I've tried 
`npm install -g firebase-tools@latest`
`firebase logout`
`firebase login`

I don't know what the problem is as it was working fine just a few days ago. Please see the logs below:

```
[debug] [2020-07-26T02:05:48.027Z] ----------------------------------------------------------------------
[debug] [2020-07-26T02:05:48.028Z] Command:       /Users/farah/.nvm/versions/node/v12.14.0/bin/node /Users/farah/.nvm/versions/node/v12.14.0/bin/firebase projects:list
[debug] [2020-07-26T02:05:48.028Z] CLI Version:   8.6.0
[debug] [2020-07-26T02:05:48.028Z] Platform:      darwin
[debug] [2020-07-26T02:05:48.029Z] Node Version:  v12.14.0
[debug] [2020-07-26T02:05:48.029Z] Time:          Sun Jul 26 2020 12:05:48 GMT+1000 (Australian Eastern Standard Time)
[debug] [2020-07-26T02:05:48.029Z] ----------------------------------------------------------------------
[debug] [2020-07-26T02:05:48.029Z] 
[debug] [2020-07-26T02:05:48.034Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-07-26T02:05:48.034Z] > authorizing via FIREBASE_TOKEN environment variable
[debug] [2020-07-26T02:05:48.039Z] > refreshing access token with scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-07-26T02:05:48.039Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-07-26T02:05:48.407Z] <<< HTTP RESPONSE 400 {"content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 26 Jul 2020 02:05:48 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-07-26T02:05:48.408Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects?pageSize=1000  
 
[debug] [2020-07-26T02:05:48.757Z] <<< HTTP RESPONSE 401 {"www-authenticate":"Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"","vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Sun, 26 Jul 2020 02:05:48 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-07-26T02:05:48.758Z] <<< HTTP RESPONSE BODY {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
[debug] [2020-07-26T02:05:48.758Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2020-07-26T02:05:49.119Z] FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at module.exports (/Users/farah/.nvm/versions/node/v12.14.0/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/farah/.nvm/versions/node/v12.14.0/lib/node_modules/firebase-tools/lib/api.js:41:35)
    at Request.self.callback (/Users/farah/.nvm/versions/node/v12.14.0/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (/Users/farah/.nvm/versions/node/v12.14.0/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (/Users/farah/.nvm/versions/node/v12.14.0/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.

```

**Comment by bkendall** [comment]
It looks like you have `FIREBASE_TOKEN` set in your environment. Unset that, and Firebase auth via `login` should work fine.

**Comment by farah** [comment]
thanks, I realised that doing firebase logout would invalidate the token inside my environment. Fixed.
