### ISSUE TITLE
Firebase login not getting the correct credential and hence failing

### ISSUE THREAD

**Issue by aditmodhvadia** [firebase/firebase-tools#2516]
### [REQUIRED] Environment info

**firebase-tools:** v8.6.0

**Platform:** Windows

### [REQUIRED] Test case

1. Had set FIREBASE_TOKEN manually before on a different project with different google account.
2. Now cannot log in into another google account and use the firebase-cli even though it shows successful sign-in
2. It fails to fetch proper credentials.

### [REQUIRED] Steps to reproduce

Had manually set FIREBASE_TOKEN while setting up firebase-app-distribution previously with a different google account
After clearing the FIREBASE_TOKEN from the environment variable, still cannot perform any functions as it given the error mentioned below.

### [REQUIRED] Expected behavior

Should be able to update the token and fetch the oAuth token and credentials and run all functions.

### [REQUIRED] Actual behavior

```
[debug] [2020-08-03T05:10:54.006Z] ----------------------------------------------------------------------
[debug] [2020-08-03T05:10:54.008Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy --debug
[debug] [2020-08-03T05:10:54.008Z] CLI Version:   8.6.0
[debug] [2020-08-03T05:10:54.008Z] Platform:      win32
[debug] [2020-08-03T05:10:54.008Z] Node Version:  v12.16.1
[debug] [2020-08-03T05:10:54.009Z] Time:          Mon Aug 03 2020 01:10:54 GMT-0400 (Eastern Daylight Time)
[debug] [2020-08-03T05:10:54.009Z] ----------------------------------------------------------------------
[debug] [2020-08-03T05:10:54.009Z] 
[debug] [2020-08-03T05:10:54.016Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-08-03T05:10:54.018Z] > authorizing via FIREBASE_TOKEN environment variable
[debug] [2020-08-03T05:10:54.018Z] [iam] checking project track-items-73a37 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2020-08-03T05:10:54.030Z] > refreshing access token with scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-08-03T05:10:54.031Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-08-03T05:10:54.244Z] <<< HTTP RESPONSE 400 {"content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Mon, 03 Aug 2020 05:10:54 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T05:10:54.247Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/track-items-73a37:testIamPermissions  
 {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2020-08-03T05:10:54.631Z] <<< HTTP RESPONSE 401 {"www-authenticate":"Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"","vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Mon, 03 Aug 2020 05:10:54 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=193","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T05:10:54.637Z] <<< HTTP RESPONSE BODY {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
[debug] [2020-08-03T05:10:54.677Z] [iam] error while checking permissions, command may fail: FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2020-08-03T05:10:54.680Z] > refreshing access token with scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-08-03T05:10:54.681Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-08-03T05:10:54.839Z] <<< HTTP RESPONSE 400 {"content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Mon, 03 Aug 2020 05:10:55 GMT","server":"scaffolding on HTTPServer2","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T05:10:54.841Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/track-items-73a37  
 
[debug] [2020-08-03T05:10:54.975Z] <<< HTTP RESPONSE 401 {"www-authenticate":"Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"","vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Mon, 03 Aug 2020 05:10:55 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-08-03T05:10:54.977Z] <<< HTTP RESPONSE BODY {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
[debug] [2020-08-03T05:10:54.979Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2020-08-03T05:10:55.135Z] FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at module.exports (C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:38:12)
    at Request._callback (C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:41:35)
    at Request.self.callback (C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (C:\Users\aditm\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[error] 
[error] Error: Failed to get Firebase project track-items-73a37. Please make sure the project exists and your account has permission to access it.
```

**Comment by aditmodhvadia** [comment]
Although it is working normally when using the Firebase CLI via the distribution.

**Comment by aditmodhvadia** [comment]
For now, using the binary as a workaround

**Comment by samtstern** [comment]
The line `authorizing via FIREBASE_TOKEN environment variable` only shows up if `process.env.FIREBASE_TOKEN` is set.  So the debug logs imply that your environment still has that variable set somewhere.

The branching auth code is pretty simple so there's not much else we can do on our side, it's literally `if (process.env.FIREBASE_TOKEN) { ... }`

I'd suggest double-checking to make sure that var is not set anywhere.

**Comment by aditmodhvadia** [comment]
@samtstern Yes, that seemed to be the error. Even though I removed the FIREBASE_TOKEN from the environment variables, it was not working.

Then I set the variable to be an empty string, logged out, and logged back in and it is working now. Thank you for your help. I really appreciate it.

**Comment by samtstern** [comment]
@aditmodhvadia thanks for confirming!
