### ISSUE TITLE
database.rules.json argument path bug

### ISSUE THREAD

**Issue by Albertbol** [firebase/firebase-tools#2544]
### Environment info

**firebase-tools:** 8.7.0

**Platform:** macOS Catalina 10.15.5

### Test case

**npm run serve function** will not work if you remove **--only functions** argument and add **npm i firebase-tools** to your project. It will complain about **database.rules.json** path. Log from **firebase-debug.log** last line:
```
Error: ENOENT: no such file or directory, open 'database.rules.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at DatabaseEmulator.<anonymous> (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:69:59)
    at Generator.next (<anonymous>)
    at /Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:4:12)
    at DatabaseEmulator.connect (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:63:16)
    at Object.<anonymous> (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/controller.js:421:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[error] 
[error] Error: An unexpected error has occurred.
```
If you will follow up logic in the **controller**, it seems like **firebase-tools** are sending args and realtime database block is rewriting rules fields in them. Which leads to error in **databaseEmulator.js** on line:
` yield this.updateRules(c.instance, fs.readFileSync(c.rules, "utf8").toString());`
In this case, **c.rules** is **'database.rules.json'** string, which is of course **not the right relative path**.
Interesting enough is that this error will only appear if you **use script npm run serve** (corrected to npm run build && firebase emulators:start) , but if you will run **npm run build && firebase emulators:start** in **terminal** directly it will work, because it's not sending any args as project id and so on.
This args rules console logged:
` rules: [ { rules: 'database.rules.json', instance: *ProjectID* } ]`

### Steps to reproduce

```
mkdir anyName
cd anyName
firebase init
select everything without firebase hosting and select typescript
change npm run serve command from 
 "serve": "npm run build && firebase emulators:start --only functions"
to
 "serve": "npm run build && firebase emulators:start"
npm i firebase-tools
run npm run serve command and receive an error
run in terminal npm run build && firebase emulators:start and there will be no error
```

### Expected behavior

I expect emulators to work with the firebase-tools package, the question is if it's intended or not? Currently, I wanted to use this package in scheduled function to delete recursively storage folders, as it's advised here https://firebase.google.com/docs/firestore/solutions/delete-collections, of course, there are other possibilities to do that, but I'm just trying to be sure about this particular problem.

### Actual behavior
Emulator UI has exited upon receiving signal: SIGINT
Error: An unexpected error has occurred.

```
✔  functions[helloWorld]: http function initialized (http://localhost:5001/projectId/us-central1/helloWorld). {"metadata":{"emulator":{"name":"functions"},"message":"\u001b[1mhttp\u001b[22m function initialized (http://localhost:5001/projectId/us-central1/helloWorld)."}}
i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
i  ui: Stopping Emulator UI {"metadata":{"emulator":{"name":"ui"},"message":"Stopping Emulator UI"}}
i  logging: Stopping Logging Emulator {"metadata":{"emulator":{"name":"logging"},"message":"Stopping Logging Emulator"}}
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
⚠  Your function was killed because it raised an unhandled error. {"metadata":{"emulator":{"name":"functions"},"message":"Your function was killed because it raised an unhandled error."}}
i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
i  database: Stopping Database Emulator {"metadata":{"emulator":{"name":"database"},"message":"Stopping Database Emulator"}}
i  pubsub: Stopping Pub/Sub Emulator {"metadata":{"emulator":{"name":"pubsub"},"message":"Stopping Pub/Sub Emulator"}}
[2020-08-11T18:31:01.228Z] [worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: IDLE {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: IDLE"}}
[2020-08-11T18:31:01.229Z] *** shutting down gRPC server since JVM is shutting down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** shutting down gRPC server since JVM is shutting down\n"}}
⚠  Emulator UI has exited upon receiving signal: SIGINT 
[2020-08-11T18:31:01.229Z] *** shutting down gRPC server since JVM is shutting down
 {"metadata":{"emulator":{"name":"pubsub"},"message":"*** shutting down gRPC server since JVM is shutting down\n"}}
[2020-08-11T18:31:01.229Z] 20:31:01.228 [Thread-1] INFO com.firebase.server.forge.App$ - Attempting graceful shutdown.
 {"metadata":{"emulator":{"name":"database"},"message":"20:31:01.228 [Thread-1] INFO com.firebase.server.forge.App$ - Attempting graceful shutdown.\n"}}
[2020-08-11T18:31:01.230Z] [worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: exited {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: exited"}}
[2020-08-11T18:31:01.230Z] [worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: FINISHED {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-ca20a50e-2437-4b6c-9b33-932c1f474452]: FINISHED"}}
[2020-08-11T18:31:01.232Z] *** server shut down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** server shut down\n"}}
[2020-08-11T18:31:01.233Z] *** server shut down
 {"metadata":{"emulator":{"name":"pubsub"},"message":"*** server shut down\n"}}
[2020-08-11T18:31:01.234Z] 20:31:01.234 [Thread-1] INFO com.firebase.server.forge.App$ - Graceful shutdown complete.
 {"metadata":{"emulator":{"name":"database"},"message":"20:31:01.234 [Thread-1] INFO com.firebase.server.forge.App$ - Graceful shutdown complete.\n"}}
[2020-08-11T18:31:01.603Z] Error: ENOENT: no such file or directory, open 'database.rules.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at DatabaseEmulator.<anonymous> (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:69:59)
    at Generator.next (<anonymous>)
    at /Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:4:12)
    at DatabaseEmulator.connect (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/databaseEmulator.js:63:16)
    at Object.<anonymous> (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/controller.js:421:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/*****/Desktop/bug-test/functions/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: An unexpected error has occurred.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ serve: `npm run build && firebase emulators:start --debug`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2020-08-11T18_31_01_890Z-debug.log
```

**Comment by samtstern** [comment]
@Albertbol thanks for reporting this bug!  Fix on the way.
