### ISSUE TITLE
Can't init firebase project

### ISSUE THREAD

**Issue by falico** [firebase/firebase-tools#255]
Hi guys,

I've just made an upgrade in my environment to the latest Node and firebase-tools NPM package, but I'm getting an error when I try to init a new project.

Have you seen this already? I've googled it, but I didn't find anything.

versions:
node 6.9.5
npm 3.10.10
firebase-tools 3.2.2

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 Sat Feb 04 2017 22:11:28 GMT-0200 (E. South America Daylight Time)
[debug] <<< HTTP RESPONSE 200
[info] 
=== . Setup
[debug] TypeError: features[nextFeature] is not a function
    at init (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\init\index.js:14:46)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\init\index.js:15:14
    at tryCatch (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by falico** [comment]
sorry, my fault. For some reason, I thought I needed to put the directory as an argument to firebase init. I've closed the ticket

**Comment by CasparChou** [comment]
Sorry, It still happen to me
```

=== . Setup
[debug] [2018-01-04T02:37:50.636Z] TypeError: features[nextFeature] is not a function
    at init (/usr/local/lib/node_modules/firebase-tools/lib/init/index.js:14:46)
    at /usr/local/lib/node_modules/firebase-tools/lib/init/index.js:15:14
    at tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: An unexpected error has occurred.
```

```
[debug] [2018-01-04T02:37:44.448Z] ----------------------------------------------------------------------
[debug] [2018-01-04T02:37:44.450Z] Command:       /usr/local/Cellar/node/8.8.0/bin/node /usr/local/bin/firebase init .
[debug] [2018-01-04T02:37:44.450Z] CLI Version:   3.16.0
[debug] [2018-01-04T02:37:44.450Z] Platform:      darwin
[debug] [2018-01-04T02:37:44.450Z] Node Version:  v8.8.0
[debug] [2018-01-04T02:37:44.451Z] Time:          Thu Jan 04 2018 10:37:44 GMT+0800 (CST)
[debug] [2018-01-04T02:37:44.451Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-01-04T02:37:44.463Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[debug] [2018-01-04T02:37:44.463Z] > authorizing via signed-in user
```

**Comment by falico** [comment]
If I remember correctly, the error occurred because I was putting the directory path after firebase init command. 
Error: firebase init [any path]
Correct: firebase init

**Comment by CasparChou** [comment]
Oh.... right, I made this mistake

**Comment by Wenangsani** [comment]
I have same issue, i use

`firebase init`
`firebase init projectName`

and not work
i use 
win 7 32 bit
node 10.6.0
npm 6.1.0
firebase 3.19.3

```
[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2018-07-12T02:44:44.809Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
  
 Thu Jul 12 2018 10:44:44 GMT+0800 (GMT+08:00)
[debug] [2018-07-12T02:44:47.005Z] <<< HTTP RESPONSE 200
[info] 
=== Firelabkoe Setup
[debug] [2018-07-12T02:44:49.146Z] TypeError: features[nextFeature] is not a function
    at init (C:\Users\Trufio\AppData\Roaming\npm\node_modules\firebase-tools\lib\init\index.js:13:49)
    at C:\Users\Trufio\AppData\Roaming\npm\node_modules\firebase-tools\lib\init\index.js:14:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by falico** [comment]
You only need to execute:
firebase init

Are you executing both commands?

**Comment by kaloglu** [comment]
if you have error like **TypeError: features[nextFeature] is not a function**
You should remove folder and create again.
