### ISSUE TITLE
Problems with firebase init

### ISSUE THREAD

**Issue by clust3rsekt0r** [firebase/firebase-tools#257]
Hi there I got this error when I try to deploy my app, my app is using angular-cli

[debug] ----------------------------------------------------------------------
[debug] Command: C:\Program Files\nodejs\node.exe C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase init
[debug] CLI Version: 3.2.2
[debug] Platform: win32
[debug] Node Version: v7.4.0
[debug] Time: Tue Feb 07 2017 22:56:19 GMT-0500 (Eastern Standard Time)
[debug] ----------------------------------------------------------------------
[debug]
[debug] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[info]
## #### ## ## ######## ######## ## ## ###### ########

You're about to initialize a Firebase project in this directory:

C:\angprojects\tut

Before we get started, keep in mind:

You are currently outside your home directory
You are initializing in an existing Firebase project directory
[info]
=== Project Setup
[info]
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add,
[info] but for now we'll just set up a default project.
[info]
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects
Tue Feb 07 2017 22:56:24 GMT-0500 (Eastern Standard Time)
[debug] <<< HTTP RESPONSE 200
[info] i .firebaserc already has a default project, skipping
[info]
=== Hosting Setup
[info]
[info] Your public directory is the folder (relative to your project directory) that
[info] will contain Hosting assets to be uploaded with firebase deploy. If you
[info] have a build process for your assets, use your build's output directory.
[info]
[debug] Error: EEXIST: file already exists, mkdir 'C:\angprojects\tut'
at Object.fs.mkdirSync (fs.js:855:18)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:22:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:27:16)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
at mkdirsSync (C:\Users\clust\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:28:9)
[error]
[error] Error: An unexpected error has occurred.

**Comment by clust3rsekt0r** [comment]
this is the right documentation how to deploy an angular-cli project to firebase I hope will be helpful.

https://alligator.io/angular/deploying-angular-app-to-firebase/
