### ISSUE TITLE
Error EAI_AGAIN when initializing FCM

### ISSUE THREAD

**Issue by ZenHuzaini** [firebase/firebase-tools#2587]
Hi, I am new to the firebase. I build a service using Node.js in order to do push notification activity. There is no problem when I test it in development. However, when it is in the production I found an error with initialization when I am trying to send a message. 

### [REQUIRED] Environment info

**firebase-tools:** FCM, npm firebase-admin ver.812.1

**Platform:** Linux Ubuntu

### [REQUIRED] Error

```
FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo EAI_AGAIN accounts.google.com. Error code: EAI_AGAIN".
    at FirebaseAppError.FirebaseError [as constructor] (/usr/src/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/usr/src/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAppError (/usr/src/node_modules/firebase-admin/lib/utils/error.js:123:28)
    at /usr/src/node_modules/firebase-admin/lib/firebase-app.js:121:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FirebaseMessagingCloudService.sendPushNotification (/usr/src/services/FirebaseMessagingCloudService.js:106:38)
    at async MessageService.createMessage (/usr/src/services/MessageService.js:144:13)
    at async /usr/src/controllers/MessageController/MessageController.js:52:28
    at async MessageController.module.exports [as parseMultipartForm] (/usr/src/controllers/parseMultipartForm.js:13:5)
    at async MessageController.createMessage (/usr/src/controllers/MessageController/MessageController.js:51:9) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo EAI_AGAIN accounts.google.com. Error code: EAI_AGAIN".'
  },
  codePrefix: 'app'
}

```
here how I declare the serviceAccount:
```
const serviceAccount = {
    type: "service_account",
    project_id,
    private_key_id: process.env.FCM_PRIVATE_KEY_ID,
    private_key: process.env.DEVELOPMENT_ENV
        ? process.env.FCM_PRIVATE_KEY
        : process.env.FCM_PRIVATE_KEY.replace(/\\n/g, "\n"),
    client_email: `firebase-adminsdk-hb55c@${project_id}.iam.gserviceaccount.com`,
    client_id: process.env.FCM_PRIVATE_CLIENT_ID,
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://oauth2.googleapis.com/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: process.env.FCM_PRIVATE_CERT_URL,
};

...
async initializeFCM() {
        try {
            await firebaseAdmin.initializeApp({
                credential: firebaseAdmin.credential.cert(serviceAccount),
                databaseURL: `https://${project_id}.firebaseio.com`,
            });
        } catch (error) {
            console.error(error);
            return INITIALIZATION_ERROR("FCM initialization");
        }
    }
...
```

**Comment by samtstern** [comment]
@ZenHuzaini looks like it's this issue:
https://stackoverflow.com/a/55132016/324977

Please upgrade to the Blaze plan.  Your free quota will be the same!

**Comment by cuneiform-twinkle** [comment]
Is your issue resolved , I'm getting the same error
