### ISSUE TITLE
 SyntaxError: Unexpected token }     at Module._compile (internal/modules/cjs/loader.js:723:23)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)     at Module.load (internal/modules/cjs/loader.js:653:32)     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)     at Function.Module._load (internal/modules/cjs/loader.js:585:3)     at Module.require (internal/modules/cjs/loader.js:692:17)     at require (internal/modules/cjs/helpers.js:25:18)     at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:681:33     at Generator.next (<anonymous>)

### ISSUE THREAD

**Issue by itsamanverma** [firebase/firebase-tools#2614]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by samtstern** [comment]
@itsamanverma please use the issue template when filing a bug or we won't be able to help you!

**Comment by itsamanverma** [comment]
ok thanks
