### ISSUE TITLE
CLI v8.11.2 Crashes on Windows

### ISSUE THREAD

**Issue by thoren-d** [firebase/firebase-tools#2646]
### [REQUIRED] Environment info

**firebase-tools:** 8.11.2

**Platform:** Windows 10, build 18363.1082

### [REQUIRED] Test case

Any command, even `firebase --version` crashes

### [REQUIRED] Steps to reproduce

1) Download 8.11.2 (either instant or normal) on Windows.
2) Run the CLI (let's say `firebase --version`).

### [REQUIRED] Expected behavior

CLI outputs its version, 8.11.2.

### [REQUIRED] Actual behavior

Appears to do nothing with cmd.exe or PowerShell, but when I run in MINGW64, the shell outputs "Segmentation fault".
No logs are produced, even with --debug flag.

**Comment by toomanylogins** [comment]
I also have this issue. Cannot get it to work.

**Comment by bkendall** [comment]
I wasn't able to reproduce this exactly, but I think I may have fixed it none the less. I've re-built and uploaded new binaries to the release page. Could you give those a whirl and let me know if that fixes the issues you're seeing?

**Comment by thoren-d** [comment]
Works for me now. Thanks!

**Comment by toomanylogins** [comment]
Thanks for update. Some progress I am now getting a response. To test I uninstalled node.js and rebooted. Running the CLI I get the following.

\firebase-tools-instant-win.exe firebase --version

~ Let's make sure your Firebase CLI is ready...
+ Looks like your CLI is set up!

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\snapshot\firepit\welcome.js:136:14)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

>

**Comment by toomanylogins** [comment]
This folder does not exist C:\snapshot\firepit\welcome.js:

**Comment by toomanylogins** [comment]
Running login gives as follows. Also tried deleting the .cache folder

firebase login

pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'update-notifier'
Require stack:
- C:\Users\Paul\.cache\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Paul\.cache\firebase\tools\lib\node_modules\firebase-tools\lib\bin\firebase.js:15:24)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Paul\\.cache\\firebase\\tools\\lib\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ],
  pkg: true
}

**Comment by toomanylogins** [comment]
I now have it working. You need to do is follows. Make you sure you delete the .cache/firebase folder. If you do not delete this folder you get the message that the CLI is already set up and then the error.

When you run for the first time you should get message 

~ Let's make sure your Firebase CLI is ready...
~ Looks like your CLI needs to be set up.

After the setup completes this creates a new firebase folder in .cache you can run the commands.
Thanks
Paul
