### ISSUE TITLE
Upgraded firebase deps and it broke pubsub function emulation

### ISSUE THREAD

**Issue by stephenhandley** [firebase/firebase-tools#2710]
I upgraded Firebase deps and I am now seeing the following error when locally emulating PubSub functions. These were all previously working. HTTP functions are still running fine. 
```
Function ignored because the pubsub emulator does not exist or is not running
```
I've confirmed via the logs and curl that the emulator is in fact running
```
$ curl localhost:8085
Ok
```

Logs
```
$ /* DELETED */ firebase emulators:start --only functions,pubsub
i  emulators: Starting emulators: functions, pubsub
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting
✔  functions: Using node@12 from host.
⚠  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to /* DELETED */ Non-emulated services will access production using these credentials. Be careful!
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching /* DELETED */ for Cloud Functions...
⚠  Non-default "firebase-admin" instance created!
   - This instance will *not* be mocked and will access production resources.
⚠  Non-default "firebase-admin" instance created!
   - This instance will *not* be mocked and will access production resources.
✔  functions[/* DELETED */]: http function initialized (http://localhost:5001//* DELETED */).
✔  functions[/* DELETED */]: http function initialized (http://localhost:5001//* DELETED */).
✔  functions[/* DELETED */]: http function initialized (http://localhost:5001//* DELETED */).
i  functions[/* DELETED */]: function ignored because the pubsub emulator does not exist or is not running.
i  functions[/* DELETED */]: function ignored because the pubsub emulator does not exist or is not running.
i  functions[/* DELETED */]: function ignored because the pubsub emulator does not exist or is not running.
i  functions[/* DELETED */]: function ignored because the pubsub emulator does not exist or is not running.

┌───────────────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! View status and logs at http://localhost:4000 │
└───────────────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Pub/Sub   │ localhost:8085 │ n/a                             │
└───────────┴────────────────┴─────────────────────────────────┘
  Other reserved ports: 4400, 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 ```

### [REQUIRED] Environment info

**firebase-tools: 8.12.1 (upgraded from 8.2.0)**

**Platform: macOS 10.14.6**

### [REQUIRED] Test case

Described above.

### [REQUIRED] Steps to reproduce

Pub sub function w/ emulator 

### [REQUIRED] Expected behavior

That the emulator doesn't break on upgrades 

### [REQUIRED] Actual behavior

Logs above

**Comment by stephenhandley** [comment]
@samtstern Thanks for the info. My project is closed source so I'll need to think how to best recreate the issue. One thing I figured I'd mention is that I am running my project within yarn workspaces / lerna and that I have pinned the firebase-tools dep in `devDependencies` in the top level package.json rather than installing it globally, not sure if that could be an issue. 

In the meantime, I tried digging into the logging/source and it looks like this error is getting throw and silently swallowed here:
https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L608

```
hihihhi got that pubsub error FirebaseError: Could not create topic /* DELETED */
    at PubsubEmulator.<anonymous> (/DERP/node_modules/firebase-tools/lib/emulator/pubsubEmulator.js:78:27)
    at Generator.throw (<anonymous>)
    at rejected (/DERP/node_modules/firebase-tools/lib/emulator/pubsubEmulator.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  children: [],
  context: undefined,
  exit: 1,
  original: TypeError: Channel credentials must be a ChannelCredentials object
      at new ChannelImplementation (/DERP/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:65:19)
      at new Client (/DERP/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:57:36)
      at new ServiceClientImpl (/DERP/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
      at GrpcClient.createStub (/DERP/node_modules/google-gax/build/src/grpc.js:220:22)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  status: 500
}
```

**Comment by stephenhandley** [comment]
I ran `gcloud components update` to update to `314.0.0` re-bootstrapped node modules after bumping version didn't fix the issue, still seeing `Channel credentials must be a ChannelCredentials object`. 

These appear to be all the relevant deps and they're at the latest versions 
```
"@google-cloud/pubsub": "2.5.0",
"apollo-server-cloud-functions": "2.18.2",
"firebase-admin": "9.2.0",
"firebase-functions": "3.11.0",
"googleapis": "61.0.0",
```

**Comment by stephenhandley** [comment]
Ok, found [this](https://github.com/firebase/firebase-js-sdk/issues/3196#issuecomment-643779534) and installing google-gax fixed the issue.

**Comment by samtstern** [comment]
@stephenhandley thanks for digging and finding the error!  I agree, we can improve logging here.
