### ISSUE TITLE
--inspect-functions cause errors on run

### ISSUE THREAD

**Issue by joaoeudes7** [firebase/firebase-tools#2725]
### [REQUIRED] Environment info

**firebase-tools:** 8.13.0

**Platform:** Arch Linux

**Ports in use:**
```
container  535278       root   13u  IPv4  5560533      0t0  TCP 127.0.0.1:36903 (LISTEN)
adb       1696511 joaoeudes7   10u  IPv4 96044807      0t0  TCP 127.0.0.1:5037 (LISTEN)
```

### [REQUIRED] Test case

Any code and any project. Without test case for this error

### [REQUIRED] Steps to reproduce

1 - Go to folder of project firebase
2 - Run command `firebase emulators:start --inspect-functions`

### [REQUIRED] Expected behavior

Firebase-tools CLI cannot find the inspect module in versions < 8.12.1

### [REQUIRED] Actual behavior

```
[2020-10-20T22:41:52.536Z] [worker-pool] addWorker(~shared~) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] addWorker(~shared~)"}}
[2020-10-20T22:41:52.537Z] [worker-pool] Adding worker with key ~shared~, total=1 {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] Adding worker with key ~shared~, total=1"}}
[2020-10-20T22:41:52.537Z] [worker-pool] submitWork(triggerId=) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] submitWork(triggerId=)"}}
[2020-10-20T22:41:52.538Z] [worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: Assigning socketPath: /tmp/fire_emu_2428400.sock {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: Assigning socketPath: /tmp/fire_emu_2428400.sock"}}
[2020-10-20T22:41:52.539Z] [worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: BUSY {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: BUSY"}}
>  internal/modules/cjs/loader.js:967 {"user":"internal/modules/cjs/loader.js:967","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m internal/modules/cjs/loader.js:967"}}
>    throw err; {"user":"  throw err;","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m   throw err;"}}
>    ^ {"user":"  ^","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m   ^"}}
>   {"user":"","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m "}}
>  Error: Cannot find module '/home/joaoeudes7/AndroidStudioProjects/SportTrader-Manager/functions/--inspect=0.0.0.0:9229' {"user":"Error: Cannot find module '/home/joaoeudes7/AndroidStudioProjects/SportTrader-Manager/functions/--inspect=0.0.0.0:9229'","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m Error: Cannot find module '/home/joaoeudes7/AndroidStudioProjects/SportTrader-Manager/functions/--inspect=0.0.0.0:9229'"}}
>      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15) {"user":"    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)"}}
>      at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46) {"user":"    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m     at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)"}}
>      at Function.Module._load (internal/modules/cjs/loader.js:840:27) {"user":"    at Function.Module._load (internal/modules/cjs/loader.js:840:27)","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m     at Function.Module._load (internal/modules/cjs/loader.js:840:27)"}}
>      at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12) {"user":"    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m     at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)"}}
>      at internal/main/run_main_module.js:17:47 { {"user":"    at internal/main/run_main_module.js:17:47 {","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m     at internal/main/run_main_module.js:17:47 {"}}
>    code: 'MODULE_NOT_FOUND', {"user":"  code: 'MODULE_NOT_FOUND',","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m   code: 'MODULE_NOT_FOUND',"}}
>    requireStack: [] {"user":"  requireStack: []","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m   requireStack: []"}}
>  } {"user":"}","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m }"}}
[2020-10-20T22:41:52.669Z] [worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: exited {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: exited"}}
[2020-10-20T22:41:52.670Z] [worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: FINISHED {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~shared~-9dd50160-28c0-4f35-9122-cda5530e1d8a]: FINISHED"}}
```

**Comment by samtstern** [comment]
OK the error is here:
```
Error: Cannot find module '/home/joaoeudes7/AndroidStudioProjects/SportTrader-Manager/functions/--inspect=0.0.0.0:9229' {"user":"Error: Cannot find module '/home/joaoeudes7/AndroidStudioProjects/SportTrader-Manager/functions/--inspect=0.0.0.0:9229'"
```

This looks like the arguments to `node` are getting mixed up.  Looks like it's the same issue as these:
https://github.com/firebase/firebase-tools/issues/2380
https://github.com/firebase/firebase-tools/issues/2320

Looks like #2380 is the best place to discuss this, let's close this report and consolidate the discussion htere.

**Comment by joaoeudes7** [comment]
Ok @samtstern, thanks
