### ISSUE TITLE
Emulator: Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by Abhimanyu14** [firebase/firebase-tools#2832]
### [REQUIRED] Environment info
**firebase-tools:** - 8.16.2
**Platform:** - Windows

### [REQUIRED] Test case
Create an HTTP trigger function with a status code as 400.

### [REQUIRED] Steps to reproduce
1. Create any HTTP function with status code as 400.

The function I have used: 

```js
exports.indexTest = functions.https.onRequest(async (request, response) => {
    if (!request.query.environment) {
        response.status(400).send("Environment required");
    }
    response.status(200).send("OK");
});
```

2. Trigger the function

### [REQUIRED] Expected behavior
The emulator works after the HTTP trigger

### [REQUIRED] Actual behavior
The emulator crashes/quits after the HTTP trigger

Logs:
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5554198/firebase-debug.log)

**Comment by samtstern** [comment]
Looks like the error is this:
```
[warn] !  functions: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:170:12)
    at D:\chennaihomescare\firebase\functions\functions\lib\index.js:23:26
    at C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:619:20
    at C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:594:19
    at Generator.next (<anonymous>)
    at C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\abhim\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:4:12) {"metadata":{"emulator":{"name":"functions"},"function":
```

I think this is because you're actually sending *both* a 400 and a 200 response!  You need to `return` after you send:

```js
exports.indexTest = functions.https.onRequest(async (request, response) => {
    if (!request.query.environment) {
        response.status(400).send("Environment required");
        return; // ADD THIS LINE
    }
    response.status(200).send("OK");
});
```

Can you see if that fixes the issue?
