### ISSUE TITLE
Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0    

### ISSUE THREAD

**Issue by lopeselio** [firebase/firebase-tools#2860]
I have installed firebase 9.6.0 and also 8.15.0.. but the error still persists:

Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@grpc/grpc-js/build/src/index.js:47:11)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/grpc.js:21:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)

**Comment by samtstern** [comment]
@lopeselio please follow the issue template when filing issues, this is not enough information to debug.

What does `node --version` report as your node version?

**Comment by lopeselio** [comment]
the issue was with `firebase login`
Just figured out that it occurs with `sudo npm i -g firebase-tools`
I finally solved it by installing firebase tools with `curl -sL firebase.tools | bash` and finally hosted my website

**Comment by samtstern** [comment]
@lopeselio glad you were able to solve it!

By the way: `sudo npm install` is almost never a good idea, because you can get things installed at the wrong path or using the wrong `node`.
