### ISSUE TITLE
firebase deploy  Error

### ISSUE THREAD

**Issue by xiaojianli** [firebase/firebase-tools#2958]
```
[2020-12-19T14:35:49.290Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions  
 {"config":{"rewrites":[{"glob":"**","path":"/index.html"}]},"labels":{"deployment-tool":"cli-firebase"}}
[2020-12-19T14:35:51.003Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sat, 19 Dec 2020 14:35:51 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
i  hosting[superiorsmartapps]: beginning deploy... 
i  hosting[superiorsmartapps]: found 7 files in public 
[2020-12-19T14:35:51.016Z] > refreshing access token with scopes: []
[2020-12-19T14:35:51.017Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2020-12-19T14:35:51.018Z] [hosting] hash cache [cHVibGlj] stored for 7 files
[2020-12-19T14:35:51.018Z] [hosting][hash queue][FINAL] {"max":1,"min":0,"avg":0,"active":0,"complete":7,"success":7,"errored":0,"retried":0,"total":7,"elapsed":4}
[2020-12-19T14:35:52.476Z] <<< HTTP RESPONSE 200 {"pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","date":"Sat, 19 Dec 2020 14:35:51 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2020-12-19T14:35:52.478Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions/9b88f762d1f5fec5:populateFiles [none]
[2020-12-19T14:35:52.478Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions/9b88f762d1f5fec5:populateFiles {"files":{"/404.html":"05cbc6f94d7a69ce2e29646eab13be2c884e61ba93e3094df5028866876d18b3","/app-ads.txt":"c045196e4492c8da064ed1f82460815da537ea3b6171863b8a876b9c89c88582","/index.html":"51a11395b882258945fe144681f089485e4f2f7b5a2e0a2c8d9267d7bf7fa54a","/smartnote/overview.html":"cea4000a118d640fc4025fe6a4635628dcfba64d90793f16dbce852398bc115f","/smartnote/policy/terms-and-privacy.html":"57dd0c0d992d5de5bc721b3539091fc598bfe9db7a21e0e7bccf624929154b85","/smartqrcode/overview.html":"7cf4d69fc34505e17b6d911c927a6ec87f87dbb1b1ee9d5e31911039fa8caf34","/smartqrcode/policy/terms-and-privacy.html":"69f2bcf984ffebfe171084e46f9eb2d6a15f23271776069ee651fa7913b68dd3"}}
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
i  hosting: adding files to version [0/7] (0%) 
[2020-12-19T14:37:09.188Z] [populateQueue] Retrying task index 0
[2020-12-19T14:37:09.189Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions/9b88f762d1f5fec5:populateFiles [none]
[2020-12-19T14:37:09.189Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions/9b88f762d1f5fec5:populateFiles {"files":{"/404.html":"05cbc6f94d7a69ce2e29646eab13be2c884e61ba93e3094df5028866876d18b3","/app-ads.txt":"c045196e4492c8da064ed1f82460815da537ea3b6171863b8a876b9c89c88582","/index.html":"51a11395b882258945fe144681f089485e4f2f7b5a2e0a2c8d9267d7bf7fa54a","/smartnote/overview.html":"cea4000a118d640fc4025fe6a4635628dcfba64d90793f16dbce852398bc115f","/smartnote/policy/terms-and-privacy.html":"57dd0c0d992d5de5bc721b3539091fc598bfe9db7a21e0e7bccf624929154b85","/smartqrcode/overview.html":"7cf4d69fc34505e17b6d911c927a6ec87f87dbb1b1ee9d5e31911039fa8caf34","/smartqrcode/policy/terms-and-privacy.html":"69f2bcf984ffebfe171084e46f9eb2d6a15f23271776069ee651fa7913b68dd3"}}

.......


[2020-12-19T14:40:57.593Z] FirebaseError: Task index 0 failed: retries exhausted after 4 attempts
[2020-12-19T14:40:57.594Z] [hosting][upload queue][FINAL] {"max":0,"min":9999999999,"avg":0,"active":0,"complete":0,"success":0,"errored":0,"retried":0,"total":0,"elapsed":1608388857594}
[2020-12-19T14:40:57.600Z] FirebaseError: Failed to make request to https://firebasehosting.googleapis.com/v1beta1/sites/superiorsmartapps/versions/9b88f762d1f5fec5:populateFiles
    at Client.doRequest (/usr/local/Cellar/node/15.4.0/lib/node_modules/firebase-tools/lib/apiv2.js:161:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Client.request (/usr/local/Cellar/node/15.4.0/lib/node_modules/firebase-tools/lib/apiv2.js:84:20)
    at async Uploader.populateHandler (/usr/local/Cellar/node/15.4.0/lib/node_modules/firebase-tools/lib/deploy/hosting/uploader.js:156:21)
    at async Queue.executeTask (/usr/local/Cellar/node/15.4.0/lib/node_modules/firebase-tools/lib/throttler/throttler.js:175:22)
    at async Queue.handle (/usr/local/Cellar/node/15.4.0/lib/node_modules/firebase-tools/lib/throttler/throttler.js:91:22)

Error: Task index 0 failed: retries exhausted after 4 attempts
```

-------------------------------------------

This problem occurred after upgrading to 9.0.1

but < firebase projects:list > is ok

**Comment by samtstern** [comment]
@xiaojianli please follow the issue template when filing issues. Could you show more of the debug logs? Specifically the part you omitted with `...` should contain the HTTP response code for the failed request.

Also can you confirm the latest version of the CLI that does *not* have this problem?

**Comment by samtstern** [comment]
Actually this is almost certainly the same as https://github.com/firebase/firebase-tools/issues/2927 let's consolidate the discussion there.
