### ISSUE TITLE
Functions emulator crashes if firestore trigger collection name has spaces.

### ISSUE THREAD

**Issue by crazzywizard** [firebase/firebase-tools#3101]
### [REQUIRED] Environment info

**firebase-tools:9.3.0**

**Platform:Manjaro**

### [REQUIRED] Test case

```FUTURE OFFER ERROR
[1] Error: 2 UNKNOWN: 
[1]     at Object.callErrorFromStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
[1]     at Object.onReceiveStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
[1]     at Object.onReceiveStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
[1]     at Object.onReceiveStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
[1]     at Http2CallStream.outputStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
[1]     at Http2CallStream.maybeOutputStatus (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
[1]     at Http2CallStream.endCall (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
[1]     at Http2CallStream.handleTrailers (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
[1]     at ClientHttp2Stream.<anonymous> (/home/sam/Desktop/projects/enotext/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:322:26)
[1]     at ClientHttp2Stream.emit (events.js:315:20)
[1]     at emit (internal/http2/core.js:297:8)
[1]     at processTicksAndRejections (internal/process/task_queues.js:87:22)
[1] Caused by: Error
[1]     at WriteBatch.commit (/home/sam/Desktop/projects/enotext/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
[1]     at DocumentReference.create (/home/sam/Desktop/projects/enotext/functions/node_modules/@google-cloud/firestore/build/src/reference.js:283:14)
[1]     at CollectionReference.add (/home/sam/Desktop/projects/enotext/functions/node_modules/@google-cloud/firestore/build/src/reference.js:2011:28)
[1]     at saveSMS (/home/sam/Desktop/projects/enotext/functions/functions/db.js:7:46)
[1]     at sendOfferSMS (/home/sam/Desktop/projects/enotext/functions/functions/SMS.js:98:17)
[1]     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[1]   code: 2,
[1]   details: '',
[1]   metadata: Metadata {
[1]     internalRepr: Map { 'content-type' => [Array] },
[1]     options: {}
[1]   },
[1]   note: 'Exception occurred in retry method that was not classified as transient'
[1] }
```

### [REQUIRED] Steps to reproduce

create firestore trigger with collection name like `Test Payments` and watch https functions fail to work leading to a write.batch error.

### [REQUIRED] Expected behavior

All functions should work.

### [REQUIRED] Actual behavior
Https functions break with addition of a firestore trigger function with data path of `Test Payments/{payment}`, function works if I remove the space, but it is a production database and data path cannot be changed.

**Comment by kmcnellis** [comment]
I can reproduce.  It breaks (silently, without any obvious error messages) when running with firebase emulators:start

**Comment by yuchenshi** [comment]
Thanks for the bug report! I've tracked this internally as b/179941689.

**Comment by al4nnw** [comment]
happened today with me, solution was to lower the batch size.

**Comment by christhompsongoogle** [comment]
We have a fix for this one, it will be released with the next firestore emulator release.
