### ISSUE TITLE
firebase functions deployment error

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-tools#3153]
### [REQUIRED] Environment info

**firebase-tools:** 9.4.0

**Platform:** macOS

### [REQUIRED] Test case

`firebase deploy --only functions`

### [REQUIRED] Steps to reproduce

`firebase deploy --only functions`

### [REQUIRED] Expected behavior

Deployment.

### [REQUIRED] Actual behavior

```
Error: Functions did not deploy properly.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ deploy: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/janswist/.npm/_logs/2021-02-20T14_06_02_276Z-debug.log
```

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle functions@~predeploy: functions@
6 info lifecycle functions@~deploy: functions@
7 verbose lifecycle functions@~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/janswist/Developer/templater/frontend/functions/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin
9 verbose lifecycle functions@~deploy: CWD: /Users/janswist/Developer/templater/frontend/functions
10 silly lifecycle functions@~deploy: Args: [ '-c', 'firebase deploy --only functions' ]
11 silly lifecycle functions@~deploy: Returned: code: 1  signal: null
12 info lifecycle functions@~deploy: Failed to exec deploy script
13 verbose stack Error: functions@ deploy: `firebase deploy --only functions`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid functions@
15 verbose cwd /Users/janswist/Developer/templater/frontend/functions
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error functions@ deploy: `firebase deploy --only functions`
22 error Exit status 1
23 error Failed at the functions@ deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

After upgrading npm, changing node engine to 14 and reinstalling node_modules I got this debug.log:
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
1 info using npm@7.5.4
2 info using node@v14.15.5
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/janswist/Developer/templater/frontend/functions/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/janswist/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 3ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 verbose npm-session 9c436a1c514ad3cd
20 timing npm:load Completed in 27ms
21 timing command:run-script Completed in 213702ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose cwd /Users/janswist/Developer/templater/frontend/functions
24 verbose Darwin 17.7.0
25 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
26 verbose node v14.15.5
27 verbose npm  v7.5.4
28 error code 1
29 error path /Users/janswist/Developer/templater/frontend/functions
30 error command failed
31 error command sh -c firebase deploy --only functions
32 verbose exit 1
```

While I can see updated code in the Cloud Functions console it's not deployed somehow. I don't understand it.

Below is the log from Logs Explorer:
```
{
  "textPayload": "ERROR: build step 5 \"us.gcr.io/fn-img/buildpacks/nodejs14/builder:nodejs14_20201201_20_RC00\" failed: step exited with non-zero status: 246",
  "insertId": "b862377b-fd27-4a8f-9361-3eadd13d0953-248",
  "resource": {
    "type": "build",
    "labels": {
      "project_id": "templater-d1fb0",
      "build_trigger_id": "",
      "build_id": "b862377b-fd27-4a8f-9361-3eadd13d0953"
    }
  },
  "timestamp": "2021-02-20T16:57:33.830629043Z",
  "severity": "INFO",
  "labels": {
    "build_step": "MAIN"
  },
  "logName": "projects/templater-d1fb0/logs/cloudbuild",
  "receiveTimestamp": "2021-02-20T16:57:33.857086409Z"
}
```

**Comment by janswist** [comment]
I got a response from Firebase team: "The next step is to delete the following Storage bucket from the GCP Console" and that worked like a charm. Hope it will save time to others in future.
