### ISSUE TITLE
Getting a TypeError when using `firebase deploy`

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-tools#317]
```
TypeError: Not an integer
    at Object.fs.writeSync (fs.js:540:18)
    at Function.writeFileSync [as sync] (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/node_modules/configstore/node_modules/write-file-atomic/index.js:114:10)
    at Object.create.all.set (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/node_modules/configstore/index.js:27:11)
    at new UpdateNotifier (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js:34:17)
    at module.exports (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js:123:23)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/firebase-tools/bin/firebase:5:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by SUPERCILEX** [comment]
Nevermind, the issue was because I had an old node version in Travis CI. What are the minimum requirements BTW? It isn't clear in the main README...

Fixed by adding [`install: nvm install 7`](https://github.com/SUPERCILEX/Robot-Scouter/commit/1b2177e13c56a2e6c0e4342e34b59ef0590c4ee9#diff-354f30a63fb0907d4ad57269548329e3R27) in my `travis.yml`.

**Comment by d1b1** [comment]
I am also encountering this issue when using firebase tools on codeship.io. I have tried settings the firebase-tools version in the deployment script, and settings the node version in the package.json. No luck. What changed?

**Comment by SUPERCILEX** [comment]
@d1b1 I would guess they are using some new apis not available in the older node versions. I would just make sure you have node 7+.

**Comment by d1b1** [comment]
Needed to declare the node version in the codeship test to get it working. thanks

**Comment by mbleigh** [comment]
It looks like some of our recently updated dependencies may have broken Node 0.10 support. Since 0.10 is no longer in LTS, we don't plan to take any corrective action (other than perhaps to update our engine support in package.json).

If you're affected by this, please update to Node 4+. If you're getting an error like this on Node 4+, please let us know.
