### ISSUE TITLE
"TypeError: Not an integer" since upgrade to 3.0.5

### ISSUE THREAD

**Issue by hickford** [firebase/firebase-tools#318]
Yesterday:

    $ firebase --non-interactive deploy
    Error: CLI is out of date (on 3.0.4 , need at least 3.0.5)   
    Run npm install -g firebase-tools to upgrade.

I dutifully upgraded. Today:

```
$ firebase --non-interactive deploy
TypeError: Not an integer
    at Object.fs.writeSync (fs.js:540:18)
    at Function.writeFileSync [as sync] (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/node_modules/configstore/node_modules/write-file-atomic/index.js:114:10)
    at Object.create.all.set (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/node_modules/configstore/index.js:27:11)
    at new UpdateNotifier (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js:34:17)
    at module.exports (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/node_modules/update-notifier/index.js:123:23)
    at Object.<anonymous> (/home/colonelpanic/.npm-packages/lib/node_modules/firebase-tools/bin/firebase:5:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I'm using

    $ node --version
    v0.10.37

**Comment by laurenzlong** [comment]
Hey @hickford you'll need to update your Node version. Please reopen this issue if that doesn't solve it.

**Comment by hickford** [comment]
Thought that might be the reason. The server runs Ubuntu 12.04 which is pretty old now. It's not my machine to upgrade, but hopefully it will be soon.
