### ISSUE TITLE
When functions:delete command fails it prints to stdout instead of stderr

### ISSUE THREAD

**Issue by misha-reyzlin-hier** [firebase/firebase-tools#3227]
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** Ubuntu

### [REQUIRED] Test case

In node repl, attempt deleting a function group that doesn’t exist, using `require('child_process').exec`:
```
> require('child_process').exec('firebase functions:delete nonExistingFunctionGroupFooBarBaz -f', function(err, stdout, stderr) { console.log(arguments) })
[Arguments] {
  '0': Error: Command failed: firebase functions:delete asdasds -f
  
      at ChildProcess.exithandler (child_process.js:308:12)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:529:15)
      at maybeClose (internal/child_process.js:1048:16)
      at Socket.<anonymous> (internal/child_process.js:439:11)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:529:15)
      at Pipe.<anonymous> (net.js:673:12)
      at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) {
    killed: false,
    code: 1,
    signal: null,
    cmd: 'firebase functions:delete asdasds -f'
  },
  '1': '\n' +
    '\x1B[1m\x1B[31mError:\x1B[39m\x1B[22m The specified filters do not match any existing functions in project \x1B[1mhierfoods-develop\x1B[22m.\n',
  '2': ''
}
```

### [REQUIRED] Steps to reproduce
- Install firebase-tools globally
- Change into directory that has firebase project initialised in it
- Enter `node` repl 
- type `require('child_process').exec('firebase functions:delete nonExistingFunctionGroupFooBarBaz -f', function(err, stdout, stderr) { console.log(arguments) })` 
- only second argument, `stdout` will be populated

### [REQUIRED] Expected behavior

- `stderr` should be populated for errors

### [REQUIRED] Actual behavior

- `stdout` is populated with error message

**Comment by bkendall** [comment]
Question for Firebasers (maybe @samtstern @abeisgoat know): have we ever separated output between stdout and stderr? My first reaction to this is that we haven't, and that making a change to that may be breaking. 

@misha-reyzlin-hier: would either using the CLI as a module or providing the `--json` flag help out in this case? Using it [as a module](https://github.com/firebase/firebase-tools#using-as-a-module) would allow you to catch the error in this case, I believe. The `--json` flag would provide parsable output on stdout (regardless of the exit code).

**Comment by samtstern** [comment]
@bkendall I believe the `--json` flag is meant to address the difference in use cases between "machine readable" and "human readable".  Without that flag the input is *not* part of our API and you can change it at will, parsing it is not something we explicitly guarantee.

**Comment by misha-reyzlin-hier** [comment]
Thank for your replies! 

For scripting/automation, does it make sense to add a paragraph to README that mentions `--json` flag as the way to get appropriate command line friendly API with `firebase-tools`? Also that `Without that flag the CLI output is not part of our API`?

**Comment by bkendall** [comment]
@samtstern that's a very good description of the difference and I agree with it.

Adding some information to the README is always welcome! @misha-reyzlin-hier - if you wanted to start a PR with what would be useful to you, we could iterate on that with you 🙂   Otherwise, I'll leave this open for this particular follow-up
