### ISSUE TITLE
Firebase deploy   error >> failed to make projects list

### ISSUE THREAD

**Issue by mahmoud-shakouryan** [firebase/firebase-tools#3242]
**Environment info :**
firebase version: 9.8.0
Node version :14.15.3
**Platform :**
Windows 8.1

 **Test case :**
when deploying a react app via firebase CLI , when it reaches to  make a projects list it throws an error.
I got two projects at firebase and it succeeds at login via firebase CLI.
I even googled and did below things to fix the possibility issues :
firebase login/logout several times , firebase use --add , firebase login:ci to use token
checking out the firebase-debug.log it just throws an error :
**failed to make get request , invalid json response body , unexpected token**

 **Steps to reproduce**
firebase login
firebase projects:list

 **firebase-debug.log:**
```
[debug]  ----------------------------------------------------------------------
[debug]  Command:       C:\Program Files\nodejs\node.exe C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js projects:list
[debug]  CLI Version:   9.8.0
[debug]  Platform:      win32
[debug]  Node Version:  v14.15.3
[debug]  Time:          Tue Mar 30 2021 11:22:17 GMT-0700 (Pacific Daylight Time)
[debug]  ----------------------------------------------------------------------
[debug] 
[debug]  >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug]  > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug]  > authorizing via signed-in user
[debug]  >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug]  Failed to make request: invalid json response body at https://firebase.googleapis.com/v1beta1/projects?pageSize=1000 reason: Unexpected token < in JSON at position 0
[debug]  FirebaseError: Failed to make request: invalid json response body at https://firebase.googleapis.com/v1beta1/projects?pageSize=1000 reason: Unexpected token < in JSON at position 0
    at Client.request (C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:109:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getProjectPage (C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:232:17)
    at async getFirebaseProjectPage (C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:249:23)
    at async Object.listFirebaseProjects (C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:280:29)
    at async Command.actionFn (C:\Users\Maryam\AppData\Roaming\npm\node_modules\firebase-tools\lib\commands\projects-list.js:50:20)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

**Comment by lulzimgashi95** [comment]
For others who might face this issue : 
Look at your env variables on your pc you should have set an env with that name _**FIREBASE_API_URL**_ delete this one and it should work just fine

**Comment by abeisgoat** [comment]
Glad you got it working.
