### ISSUE TITLE
No CRC-32C implementation available error in 9.8.0

### ISSUE THREAD

**Issue by nicholaschiang** [firebase/firebase-tools#3247]
### [REQUIRED] Environment info

**firebase-tools:** 9.7.0

**Platform:** Vercel Serverless Functions (Linux)

### [REQUIRED] Test case

When you deploy a project to Vercel that lists `firebase-tools@9.8.0` as a dependency (even if its just a development dependency), the following error occurs at runtime:

```
2021-03-31T03:13:51.397Z	185d337e-6d34-461e-870f-d2888b290646	ERROR	Uncaught Exception 	
{
  "errorType":"Error",
  "errorMessage":"no CRC-32C implementation is available",
  "stack":[
    "Error: no CRC-32C implementation is available","
      at Object.calculate (/var/task/node_modules/fast-crc32c/loader.js:18:13)","
      at PassThrough.onData [as _transform] (/var/task/node_modules/hash-stream-validation/index.js:23:37)","
      at PassThrough.Transform._read (_stream_transform.js:191:10)","
      at PassThrough.Transform._write (_stream_transform.js:179:12)","
      at doWrite (_stream_writable.js:403:12)","
      at writeOrBuffer (_stream_writable.js:387:5)","
      at PassThrough.Writable.write (_stream_writable.js:318:11)","
      at PassThrough.ondata (_stream_readable.js:718:22)","
      at PassThrough.emit (events.js:314:20)","
      at addChunk (_stream_readable.js:297:12)"
  ]
}
Unknown application error occurred
```

### [REQUIRED] Steps to reproduce

1. Create a new Next.js app that uses `firebase-tools@9.8.0`.
2. Deploy that app to Vercel.
3. Try to call the app's API routes.
4. See error in Vercel logs.

### [REQUIRED] Expected behavior

There should be no error. While I don't actually expect you to try to create this error, I'm creating this issue just in case anyone else has a similar issue (and this issue will help them determine that the source of it is `firebase-tools@9.8.0` and not anything to do with Vercel). You might also have some good pointers for why this might be happening in their serverless runtime environment.

### [REQUIRED] Actual behavior

See the above error logs.

**Comment by samtstern** [comment]
This is fixed in version `9.9.0`
