### ISSUE TITLE
CLI Storage emulator init/start command not working.

### ISSUE THREAD

**Issue by hmmmmniek** [firebase/firebase-tools#3256]
**firebase-tools:** 9.8.0

**Platform:** Ubuntu

### [REQUIRED] Steps to reproduce
- run `firebase init`
- follow the steps, select to initialize storage
- note there is no option to initialize the storage emulator

- afterwards, `firebase emulators:start --only auth,storage`
- note the message: `storage: Not starting the storage emulator, make sure you have run firebase init.`

### [REQUIRED] Expected behavior
I would expect the storage emulator to start, since support has been added for it in 9.8.0. And I DID run firebase init!

### [REQUIRED] Actual behavior
Storage emulator does not start.

**Comment by vbeffa** [comment]
Not sure if this is documented but it looks like you need to run this command first:

```bash
firebase --open-sesame storageemulator
```

**Comment by samtstern** [comment]
@vbeffa that is the correct answer. This is the intended behavior while the storage emulator is still in preview. When we launch to the public the UX will be much better for this, sorry about the confusion!

**Comment by laurentpayot** [comment]
Using the storage emulator preview I found two annoying issues:

1. Uploaded files are not persisted when using the `--export` `--import` firebase options. Restarting a test app leads to 404 errors.
2. Auth is not supported, making the emulator quite useless. Whereas the normal, non-emulated storage is working fine, with the emulator I get the following error when using `request.auth` in my storage rules:
```
(node:13308) UnhandledPromiseRejectionWarning: FirebaseError: Can not convert variables for Cloud Storage rules runtime
    at toExpressionValue (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:263:11)
    at /home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:254:27
    at Array.forEach (<anonymous>)
    at toExpressionValue (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:253:26)
    at /home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:254:27
    at Array.forEach (<anonymous>)
    at toExpressionValue (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:253:26)
    at createAuthExpressionValue (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:275:16)
    at createRequestExpressionValue (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:293:28)
    at StorageRulesRuntime.verifyWithRuleset (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:185:114)
    at StorageRulesetInstance.verify (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/rules/runtime.js:31:29)
    at isPermitted (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:21:54)
    at handleUpload (/home/laurent/projects/my-project/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:295:25)
    at Layer.handle [as handle_request] (/home/laurent/projects/my-project/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/laurent/projects/my-project/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/laurent/projects/my-project/node_modules/express/lib/router/route.js:112:3)
(node:13308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```
Is it something known and addressed?

**Comment by abeisgoat** [comment]
@laurentpayot 

1. Yes, that's true, we're working on it but this may not make it for the initial release.
2. Auth is definitely supported (in fact it's the majority of the complexity of the emulator), can you send me an email at abehaskins@google.com with details about what type of auth you're using (and if it's production or via the Auth emulator)?

**Comment by abeisgoat** [comment]
nvm, this is known, just put up a fix in #3310

**Comment by laurentpayot** [comment]
@abeisgoat 

> nvm, this is known, just put up a fix in #3310

Awesome. Looking forward to trying the next release.

**Comment by sultanmyrza** [comment]
> @laurentpayot
> 
> 1. Yes, that's true, we're working on it but this may not make it for the initial release.
> 2. Auth is definitely supported (in fact it's the majority of the complexity of the emulator), can you send me an email at [abehaskins@google.com](mailto:abehaskins@google.com) with details about what type of auth you're using (and if it's production or via the Auth emulator)?

Today I used firebase storage emulator
```
firebase emulators:start --only firestore,functions,auth,storage --import=../dev/local-data --export-on-exit=../dev/local-data
```

I was able to succesfully upload image to firebase storage emulator
In my case create and save user in firestore/usersCollection/userDoc
```
userDoc {
  userId: "some-unique-id",
  avatarUrl: "during-development-firebase-emulator-storage/some-path/image.jpg",
  ... other fields
}
```
### After I restart emulator 
✅  **firestore** data is persisted 
✅  **authentication** data is persisted 
😭  **storage** data is gone (not persisted)  therefore `user.avatarUrl` is 404 when I start my emulator again

### should I open issue with detailed explanation?

**Comment by Methodician** [comment]
The preview unlock code is not working for me:

❯ firebase --open-sesame storageemulator
Error: Did not recognize preview feature

**Comment by laurentpayot** [comment]
@Methodician I guess that’s because the storage emulator is no more in preview as it has been added to current Firebase tools for a few months now. If you are using the latest Firebase versions it’s already build-in.
