### ISSUE TITLE
Emulator DELETE on clear users endpoint doesn't work from axios/fetch but works in cURL

### ISSUE THREAD

**Issue by Mattinton** [firebase/firebase-tools#3275]
### Environment info

**firebase-tools: 9.9.0**

**Platform: macOS**

### Test case

```
axios.delete(`http://${TEST_AUTH_URL}/emulator/v1/projects/${TEST_PROJECT_ID}/accounts`);
```

### Steps to reproduce

Use axios in any piece of code. In my case I am using it in a Jest afterEach function.

### Expected behavior

The request succeeds and clears all users from the emulator

### Actual behavior

Without debugging it prints this error.

```
Request failed with status code 400

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at XMLHttpRequestOverride.handleLoad [as onreadystatechange] (node_modules/axios/lib/adapters/xhr.js:62:7)
      at XMLHttpRequestOverride.trigger (node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:168:17)
      at XMLHttpRequestOverride.setReadyState (node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:150:14)
      at XMLHttpRequest.<anonymous> (node_modules/@mswjs/interceptors/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:363:20)
      at XMLHttpRequest.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at EventEmitter.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:893:5)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:381:41)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
```

When debugging I get:
```
Invalid content-type: text/plain;charset=UTF-8
```
But I get the sense that isn't the real error. When I try adding a 'Content-Type' header I still get the same error.
```
axios.delete(`http://${TEST_AUTH_URL}/emulator/v1/projects/${TEST_PROJECT_ID}/accounts`, {
        headers: {
            'Content-Type': 'application/json; charset=utf-8',
            Accept: 'application/json',
        },
    });
```

If I try using fetch it doesn't seem to make the request at all and therefore nothing is deleted. Could this be todo with being in a jsdom environment? I find it strange because the firestore endpoint where I delete all docs works fine.

**Comment by Mattinton** [comment]
So I've just fixed this by adding 'XMLHttpRequest: undefined' to my custom environment.

My full environment for those interested.

```
/* eslint-disable @typescript-eslint/no-var-requires */
const NodeEnvironment = require('jest-environment-jsdom');

class MyEnvironment extends NodeEnvironment {
    constructor(config) {
        super(
            Object.assign({}, config, {
                globals: Object.assign({}, config.globals, {
                    matchMedia: () => ({ matches: false, addListener: jest.fn(), removeListener: jest.fn() }),
                    Uint32Array: Uint32Array,
                    Uint8Array: Uint8Array,
                    ArrayBuffer: ArrayBuffer,
                    XMLHttpRequest: undefined,
                }),
            })
        );
    }

    async setup() {
        //
    }

    async teardown() {
        //
    }
}

// eslint-disable-next-line no-undef
module.exports = MyEnvironment;
```

**Comment by samtstern** [comment]
@Mattinton thanks for following up! Seems like it was an environment issue and not an emulator issue so I am going to close this.
