### ISSUE TITLE
Large dataset import gives unclear explanation of timeout

### ISSUE THREAD

**Issue by clive-h-townsend** [firebase/firebase-tools#3289]
### [REQUIRED] Environment info

9.8.0

**firebase-tools:**

**Platform:**
Ubuntu 20.04

### [REQUIRED] Test case

Use any large test set when importing data

### [REQUIRED] Steps to reproduce

Use firebase emulators with `firebase emulators:start --import initialData` where the initialData directory is large.

### [REQUIRED] Expected behavior

When importing a large dataset the firestore emulator times out due to https://github.com/firebase/firebase-tools/blob/66447909ab6f2defd04b257b48193c70d778c7ea/src/emulator/portUtils.ts#L142

Would be very helpful to either recommend a maximum import size or to notify that a possible cause of the issue is an import dataset that is too large.

### [REQUIRED] Actual behavior

```
[2021-04-17T21:18:55.129Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-04-17T21:18:55.133Z] > authorizing via signed-in user
i  emulators: Starting emulators: auth, functions, firestore, hosting, pubsub {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, functions, firestore, hosting, pubsub"}}
[2021-04-17T21:18:55.215Z] [hub] writing locator at /tmp/hub-refquest-pro-dev.json
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mdatabase\u001b[22m"}}
⚠  Your requested "node" version "10" doesn't match your global version "11" {"metadata":{"emulator":{"name":"functions"},"message":"Your requested \"node\" version \"10\" doesn't match your global version \"11\""}}
[2021-04-17T21:18:55.399Z] defaultcredentials: writing to file /home/scott/.config/firebase/clive_h.townsend_gmail.com_application_default_credentials.json
[2021-04-17T21:18:55.429Z] Setting GAC to /home/scott/.config/firebase/clive_h.townsend_gmail.com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to /home/scott/.config/firebase/clive_h.townsend_gmail.com_application_default_credentials.json"}}
[2021-04-17T21:18:55.436Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/refquest-pro-dev/adminSdkConfig [none]
[2021-04-17T21:18:55.859Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/refquest-pro-dev/adminSdkConfig 200
[2021-04-17T21:18:55.859Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/refquest-pro-dev/adminSdkConfig {"projectId":"refquest-pro-dev","databaseURL":"https://refquest-pro-dev.firebaseio.com","storageBucket":"refquest-pro-dev.appspot.com","locationId":"us-central"}
i  firestore: Importing data from /home/scott/repositories/refquest/plus/initialData/firestore_export/export_metadata {"metadata":{"emulator":{"name":"firestore"},"message":"Importing data from /home/scott/repositories/refquest/plus/initialData/firestore_export/export_metadata"}}
[2021-04-17T21:18:55.929Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
[2021-04-17T21:18:55.930Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[2021-04-17T21:18:55.930Z] Starting Firestore Emulator with command {"binary":"java","args":["-Dgoogle.cloud_firestore.debug_log_level=FINE","-Duser.language=en","-jar","/home/scott/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.12.jar","--host","localhost","--port",8080,"--seed_from_export","/home/scott/repositories/refquest/plus/initialData/firestore_export/export_metadata","--rules","/home/scott/repositories/refquest/plus/firestore.rules","--functions_emulator","localhost:5001"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Dgoogle.cloud_firestore.debug_log_level=FINE\",\"-Duser.language=en\",\"-jar\",\"/home/scott/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.12.jar\",\"--host\",\"localhost\",\"--port\",8080,\"--seed_from_export\",\"/home/scott/repositories/refquest/plus/initialData/firestore_export/export_metadata\",\"--rules\",\"/home/scott/repositories/refquest/plus/firestore.rules\",\"--functions_emulator\",\"localhost:5001\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
[2021-04-17T21:38:24.828Z] Exception in thread "main"  {"metadata":{"emulator":{"name":"firestore"},"message":"Exception in thread \"main\" "}}
[2021-04-17T21:38:24.905Z] java.lang.OutOfMemoryError: GC overhead limit exceeded {"metadata":{"emulator":{"name":"firestore"},"message":"java.lang.OutOfMemoryError: GC overhead limit exceeded"}}
[2021-04-17T21:38:24.905Z] 
 {"metadata":{"emulator":{"name":"firestore"},"message":"\n"}}
[2021-04-17T21:38:24.932Z] 	at com.google.protobuf.ByteString.copyFrom(ByteString.java:334) {"metadata":{"emulator":{"name":"firestore"},"message":"\tat com.google.protobuf.ByteString.copyFrom(ByteString.java:334)"}}
[2021-04-17T21:38:24.933Z] 
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:987)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property.<init>(OnestoreEntity.java:6718)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property.<init>(OnestoreEntity.java:6652)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property$1.parsePartialFrom(OnestoreEntity.java:8753)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property$1.parsePartialFrom(OnestoreEntity.java:8747)
 {"metadata":{"emulator":{"name":"firestore"},"message":"\n\tat com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:987)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property.<init>(OnestoreEntity.java:6718)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property.<init>(OnestoreEntity.java:6652)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property$1.parsePartialFrom(OnestoreEntity.java:8753)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$Property$1.parsePartialFrom(OnestoreEntity.java:8747)\n"}}
[2021-04-17T21:38:24.934Z] 	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:971)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto.<init>(OnestoreEntity.java:13993)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto.<init>(OnestoreEntity.java:13909)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto$1.parsePartialFrom(OnestoreEntity.java:16408)
	at com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto$1.parsePartialFrom(OnestoreEntity.java:16402)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:57)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:20)
 {"metadata":{"emulator":{"name":"firestore"},"message":"\tat com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:971)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto.<init>(OnestoreEntity.java:13993)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto.<init>(OnestoreEntity.java:13909)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto$1.parsePartialFrom(OnestoreEntity.java:16408)\n\tat com.google.storage.onestore.v3.proto2api.OnestoreEntity$EntityProto$1.parsePartialFrom(OnestoreEntity.java:16402)\n\tat com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:57)\n\tat com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:20)\n"}}
[2021-04-17T21:38:24.935Z] 	at com.google.cloud.datastore.emulator.impl.LevelDBLogReaderChannel.readProtoMessage(LevelDBLogReaderChannel.java:65)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseEntityProtoFile(ExportImportUtil.java:194)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:66)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)
 {"metadata":{"emulator":{"name":"firestore"},"message":"\tat com.google.cloud.datastore.emulator.impl.LevelDBLogReaderChannel.readProtoMessage(LevelDBLogReaderChannel.java:65)\n\tat com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseEntityProtoFile(ExportImportUtil.java:194)\n\tat com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:66)\n\tat com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)\n"}}
⚠  firestore: Fatal error occurred: 
   Firestore Emulator has exited with code: 1, 
   stopping all running emulators {"metadata":{"emulator":{"name":"firestore"},"message":"Fatal error occurred: \n   Firestore Emulator has exited with code: 1, \n   stopping all running emulators"}}
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
[2021-04-17T21:38:29.937Z] Firestore Emulator: Unable to terminate process (PID=502623) {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator: Unable to terminate process (PID=502623)"}}
⚠  firestore: Error stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Error stopping Firestore Emulator"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
scott@the-heart-of-the-lion:~/repositories/refquest/plus$ 
```

**Comment by yuchenshi** [comment]
As seen in the logs, there is an `OutOfMemoryError`, which may be resolved by either [increasing the heap size](https://github.com/firebase/firebase-tools/issues/2521#issuecomment-692610952) or switching to a different device with larger RAM.

In general, the Firestore emulator is not built with scalability in mind and may have trouble handling large amounts of data. We recommend trimming the data if possible (and avoiding importing large production dumps verbatim). Unfortunately, we are unable to give more detailed recommendation on size, since it depends on the app's data structure, capability of the user devices, and so on.
