### ISSUE TITLE
 functions: TypeError: Cannot read property 'toLowerCase' of undefined he declaration was marked as deprecated here firebase react native

### ISSUE THREAD

**Issue by sasa1sasa** [firebase/firebase-tools#3306]
functions: Beginning execution of "geocode"
!  functions: TypeError: Cannot read property 'toLowerCase' of undefined
    at module.exports.geocodeRequest (C:\Users\bogda\Desktop\NEXT.js\REACT_NATIVE_PROJECTS\MealsToGo-bonus-camera-4\functions\geocode\index.js:6:45)
    at C:\Users\bogda\Desktop\NEXT.js\REACT_NATIVE_PROJECTS\MealsToGo-bonus-camera-4\functions\index.js:5:5
    at C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:600:16
    at runFunction (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:579:15)
    at runHTTPS (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:599:11)
    at handler (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:528:23)
    at Layer.handle [as handle_request] (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
!  Your function was killed because it raised an unhandled error.

**Comment by samtstern** [comment]
The ereor is happening here:
```
MealsToGo-bonus-camera-4\functions\geocode\index.js:6:45
```

This is an error in your code, not in the Firebase CLI. Please follow the issue template when opening issues.

**Comment by iftkhar00490** [comment]
> functions: Beginning execution of "geocode" ! functions: TypeError: Cannot read property 'toLowerCase' of undefined at module.exports.geocodeRequest (C:\Users\bogda\Desktop\NEXT.js\REACT_NATIVE_PROJECTS\MealsToGo-bonus-camera-4\functions\geocode\index.js:6:45) at C:\Users\bogda\Desktop\NEXT.js\REACT_NATIVE_PROJECTS\MealsToGo-bonus-camera-4\functions\index.js:5:5 at C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:600:16 at runFunction (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:579:15) at runHTTPS (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:599:11) at handler (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:528:23) at Layer.handle [as handle_request] (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\Users\bogda\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5) ! Your function was killed because it raised an unhandled error.

what was the fix did you get it??

**Comment by sasa1sasa** [comment]
Thank`s a lot ,i waiting one year to answer my question ,i lose hope in
Andrei because my App is not in function i try all ,but Sir what is way to
solve my issue.
Thank you Sam.

pon, 26. tra 2021. u 12:21 Sam Stern ***@***.***> napisao je:
