### ISSUE TITLE
Hosting Deploys error when uploading multiple files with same hash

### ISSUE THREAD

**Issue by kmcnellis** [firebase/firebase-tools#3336]
From #2126, reported by @himansaE:  The CLI errors when the same file (css, in this case) is present multiple times in the deploy dir.  When it's uploaded, the server returns an "Already exists" error. 

```
i  hosting: uploading new files [0/7] (0%)
i  hosting: uploading new files [0/7] (0%)
Task a269ec6e8eae744c19c673e9898b8a8066fa40ff57e7aa6ba46a90e1e585d0b9 failed: retries exhausted after 6 attempts
[2021-05-05T19:10:43.149Z] [hosting][upload queue][FINAL] {"max":0,"min":9999999999,"avg":0,"active":6,"complete":1,"success":0,"errored":1,"retried":32,"total":7,"elapsed":1779978}
[2021-05-05T19:10:52.682Z] FirebaseError: Timeout reached making request to https://upload-firebasehosting.googleapis.com/upload/sites/xyz-app/versions/2dc3464abbdcabc4/files/a269ec6e8eae744c19c673e9898b8a8066fa40ff57e7aa6ba46a90e1e585d0b9
    at Client.doRequest (C:\node_modules\node_modules\firebase-tools\lib\apiv2.js:209:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: Task a269ec6e8eae744c19c673e9898b8a8066fa40ff57e7aa6ba46a90e1e585d0b9 failed: retries exhausted after 6 attempts

```

**Comment by kmcnellis** [comment]
This could alternately also be caused be a server-side issue, with SiteUploadedFiles being present for a file without any FIles row

**Comment by himansaE** [comment]
Adding an extra line for every css files fixed my problem.

**Comment by kmcnellis** [comment]
I've confirmed that the CLI correctly only uploads each file once.   The instances of this are the same server issue as #2126
