### ISSUE TITLE
storage emulator rules processing issue

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-tools#3376]
### [REQUIRED] Environment info

**firebase-tools:** 9.10.1

macOS 11.3.1

**Platform:**

### [REQUIRED] Test case

Use latest firestore-tools (with storage emulator activated for testing) and use `@firebase/rules-unit-testing`@latest from firebase-js-sdk to load firebase rules

### [REQUIRED] Steps to reproduce

```js

  // Force the rules for the storage emulator to be what we expect
  await testingUtils.loadStorageRules({
    rules: `rules_version = '2';
      service firebase.storage {
        match /b/{bucket}/o {
          match /{document=**} {
            allow read, write: if false;
          }
      
          match /writeOnly.txt {
            allow read: if false;
            allow write: if true;
          }
      
          match /${PATH_ROOT}/{document=**} {
            allow read, write: if true;
          }
        }
      }`,
  });
```

Note you may probably check out firebase-js-sdk then tweak this test in order to pinpoint the issue if it's not obvious from the stack https://github.com/firebase/firebase-js-sdk/blob/50860d794bfe711143b5d287e1042eeb5187e47b/packages/rules-unit-testing/test/database.test.ts#L422

### [REQUIRED] Expected behavior

~~An error since apparently my rules are bogus, but clean logs~~ [updated: I put some tracing in the code and the emulator is actually ingesting my rules and returning 200, so this is something else]

### [REQUIRED] Actual behavior

 ```
⚠  Unexpected 'allow' in storage.rules:14
⚠  Unexpected '}' in storage.rules:17
(node:54404) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/response.js:599:15)
    at ServerResponse.sendStatus (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/response.js:357:8)
    at /Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/server.js:73:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mikehardy** [comment]
Ah, what a difference a point release makes. Updated from 9.10.1 to 9.10.2 and this appears to be gone :rocket:
