### ISSUE TITLE
Storage Emulator is not compatible with `google-cloud-storage` python package

### ISSUE THREAD

**Issue by rostyslavb** [firebase/firebase-tools#3441]
### [REQUIRED] Environment info

**firebase-tools:** `9.12.1`

**Platform:** Windows

**Packages:**

- [**google-cloud-storage**](https://googleapis.dev/python/storage/latest/index.html): `1.38.0`
- [**@google-cloud/storage**](https://googleapis.dev/nodejs/storage/latest/index.html): `5.8.5`

### [REQUIRED] Test case

Get bucket list from emulated storage and print each name:

```python
# print_bucket_list.py
from os import environ
from google.cloud import storage
from google.auth.credentials import AnonymousCredentials

def main():
    # for emulators one should use anon creds
    # see https://github.com/googleapis/python-storage/issues/324#issuecomment-735225461
    credentials = AnonymousCredentials() if environ.get("STORAGE_EMULATOR_HOST") else None

    client = storage.Client(credentials=credentials)
    buckets = client.list_buckets()

    print("buckets:")
    for bucket in buckets:
        print("\t" + bucket.name)

if __name__ == "__main__":
    main()
```

### [REQUIRED] Steps to reproduce

1. Initialize Firebase project `firebase init` with default **Storage Rules** and **Storage Emulator**.
2. Run Storage Emulator process with `firebase emulators:start --only storage --debug`
3. Set environment variable: `STORAGE_EMULATOR_HOST="http://localhost:9199"`
4. Run test case `python print_bucket_list.py`

### [REQUIRED] Expected behavior

Should print:

```
buckets:
        default-bucket
```

Same test case use node package:

```js
// print_bucket_list.js
const { Storage } = require('@google-cloud/storage');

async function main() {
  const storage = new Storage();
  await storage.getProjectId();

  const [ buckets ] = await storage.getBuckets();

  console.log("buckets:");
  buckets
    .forEach(bucket => console.log("\t" + bucket.name));
}

main().catch(console.error);
```

### [REQUIRED] Actual behavior

Output from python test case:

```
Traceback (most recent call last):
  File "C:\...\print_bucket_list.py", line 25, in <module>
    main()
  File "C:\...\print_bucket_list.py", line 20, in main
    for bucket in buckets:
  File "C:\...\lib\site-packages\google\api_core\page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "C:\...\lib\site-packages\google\api_core\page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "C:\...\lib\site-packages\google\api_core\page_iterator.py", line 369, in _next_page
    response = self._get_next_page_response()
  File "C:\...\lib\site-packages\google\api_core\page_iterator.py", line 418, in _get_next_page_response
    return self.api_request(
  File "C:\...\lib\site-packages\google\cloud\storage\_http.py", line 78, in api_request
    return call()
  File "C:\...\lib\site-packages\google\api_core\retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "C:\...\lib\site-packages\google\api_core\retry.py", line 188, in retry_target
    return target()
  File "C:\...\lib\site-packages\google\cloud\_http.py", line 483, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET http://localhost:9199/storage/v1/b?project=%%PROJECT_ID%%&projection=noAcl&prettyPrint=false: Not Found
```

`firebase-debug.log`:

```
[debug] [2021-06-02T14:03:37.742Z] ----------------------------------------------------------------------
[debug] [2021-06-02T14:03:37.745Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js emulators:start --only storage --debug
[debug] [2021-06-02T14:03:37.745Z] CLI Version:   9.12.1
[debug] [2021-06-02T14:03:37.745Z] Platform:      win32
[debug] [2021-06-02T14:03:37.745Z] Node Version:  v12.0.0
[debug] [2021-06-02T14:03:37.746Z] Time:          Wed Jun 02 2021 17:03:37 GMT+0300 (Eastern European Summer Time)
[debug] [2021-06-02T14:03:37.746Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-06-02T14:03:37.754Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-06-02T14:03:37.754Z] > authorizing via signed-in user (***@gmail.com)
[info] i  emulators: Starting emulators: storage {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: storage"}}
[debug] [2021-06-02T14:03:39.806Z] [hub] writing locator at C:\...\AppData\Local\Temp\hub-%%PROJECT_ID%%.json
[debug] [2021-06-02T14:03:41.829Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"storage"},"message":"Ignoring unsupported arg: port"}}
[debug] [2021-06-02T14:03:41.981Z] Temp file directory for storage emulator: C:\...\AppData\Local\Temp/firebase/storage/blobs {"metadata":{"emulator":{"name":"storage"},"message":"Temp file directory for storage emulator: C:\\...\\AppData\\Local\\Temp/firebase/storage/blobs"}}
[warn] !  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag. {"metadata":{"emulator":{"name":"hub"},"message":"The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag."}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌──────────┬────────────────┐
│ Emulator │ Host:Port      │
├──────────┼────────────────┤
│ Storage  │ localhost:9199 │
└──────────┴────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: None
```

**Comment by abeisgoat** [comment]
Sadly all Google Cloud SDKs (and even `firebase-admin` SDKs) outside of `firebase-admin-node` are out of scope for the emulator. Over time we will slowly improve this, but for the time being, this is a wont-fix, sorry :(
