### ISSUE TITLE
Firebase init error with realtime database location asia-southeast1

### ISSUE THREAD

**Issue by jcyh0120** [firebase/firebase-tools#3455]
I cannot init firebase project with firebase cli tool when checked with database in asia-southeast1

**firebase-tools:** 9.12.1

**Platform:** macOS

### [REQUIRED] Test case
Please refer to the following reproduce part

### [REQUIRED] Steps to reproduce
1. Create a firebase project from firebase web console
2. Go to database tab and enable realtime database
3. Select asia-southeast1 from the dropdown menu
4. Use firebase cli to init the project
5. Check database and finish init

### [REQUIRED] Expected behavior

I should be able to init the project with firebase-tools of the database
```

### [REQUIRED] Actual behavior
Error Message from firebase cli:

[2021-06-06T05:32:37.633Z] >>> HTTP REQUEST GET https://firebasedatabase.googleapis.com/v1beta/projects/gt-item-shop/locations/-/instances/gt-item-shop-default-rtdb

[2021-06-06T05:32:38.358Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 06 Jun 2021 05:32:38 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-06-06T05:32:38.359Z] Unexpected location value: asia-southeast1. Only us-central1, and europe-west1 locations are supported
[2021-06-06T05:32:38.360Z] FirebaseError: Unexpected location value: asia-southeast1. Only us-central1, and europe-west1 locations are supported
    at parseDatabaseLocation (/Users/jcyh/.nvm/versions/node/v13.11.0/lib/node_modules/firebase-tools/lib/management/database.js:132:19)
    at convertDatabaseInstance (/Users/jcyh/.nvm/versions/node/v13.11.0/lib/node_modules/firebase-tools/lib/management/database.js:173:19)
    at Object.getDatabaseInstanceDetails (/Users/jcyh/.nvm/versions/node/v13.11.0/lib/node_modules/firebase-tools/lib/management/database.js:44:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.doSetup [as database] (/Users/jcyh/.nvm/versions/node/v13.11.0/lib/node_modules/firebase-tools/lib/init/features/database.js:70:27)
    at async init (/Users/jcyh/.nvm/versions/node/v13.11.0/lib/node_modules/firebase-tools/lib/init/index.js:19:9)
```

**Comment by samtstern** [comment]
@jcyh0120 thanks! This will be fixed by https://github.com/firebase/firebase-tools/pull/3460
