### ISSUE TITLE
createSessionCookie doesn't find the specified user

### ISSUE THREAD

**Issue by ad-si** [firebase/firebase-tools#3480]
### [REQUIRED] Environment info

**firebase-tools:** 9.12.1

**Platform:** macOS

### [REQUIRED] Test case

```js
const app = require('express')()
app.get('/console/sessionLogin', (req, res) => {
    const idToken = req.query.idToken

    admin.auth()
        .createSessionCookie(idToken)
        .then(
          (result) => { console.log(result) }, 
          (error)=> { console.log(error) }
        )
})

module.exports = functions
  .region('europe-west1')
  .https
  .onRequest(app)
```

### [REQUIRED] Steps to reproduce

Host this function with the Firebase Function emulator and call it with a valid `{ idToken: … }` object.

@yoavniran seems to have the same issue:
https://stackoverflow.com/questions/67401514/firebase-auth-emulator-fails-with-idp

### [REQUIRED] Expected behavior

Creates a session cookie

### [REQUIRED] Actual behavior

```txt
>  FirebaseAuthError: There is no user record corresponding to the provided identifier. {"user":"FirebaseAuthError: There is no user record corresponding to the provided identifier.","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m FirebaseAuthError: There is no user record corresponding to the provided identifier."}}
>      at FirebaseAuthError.FirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:44:28) {"user":"    at FirebaseAuthError.FirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:44:28)","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at FirebaseAuthError.FirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:44:28)"}}
>      at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:90:28) {"user":"    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:90:28)","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:90:28)"}}
>      at new FirebaseAuthError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:149:16) {"user":"    at new FirebaseAuthError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:149:16)","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at new FirebaseAuthError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:149:16)"}}
>      at Function.FirebaseAuthError.fromServerError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:188:16) {"user":"    at Function.FirebaseAuthError.fromServerError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:188:16)","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at Function.FirebaseAuthError.fromServerError (/Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/utils/error.js:188:16)"}}
>      at /Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/auth/auth-api-request.js:1571:49 {"user":"    at /Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/auth/auth-api-request.js:1571:49","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at /Users/adrian/Projects/my-app/functions/node_modules/firebase-admin/lib/auth/auth-api-request.js:1571:49"}}
>      at processTicksAndRejections (node:internal/process/task_queues:94:5) {"user":"    at processTicksAndRejections (node:internal/process/task_queues:94:5)","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at processTicksAndRejections (node:internal/process/task_queues:94:5)"}}
>      at async /Users/adrian/Projects/my-app/functions/src/admin/sessionManagement.js:45:27 { {"user":"    at async /Users/adrian/Projects/my-app/functions/src/admin/sessionManagement.js:45:27 {","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     at async /Users/adrian/Projects/my-app/functions/src/admin/sessionManagement.js:45:27 {"}}
>    errorInfo: { {"user":"  errorInfo: {","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m   errorInfo: {"}}
>      code: 'auth/user-not-found', {"user":"    code: 'auth/user-not-found',","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     code: 'auth/user-not-found',"}}
>      message: 'There is no user record corresponding to the provided identifier.' {"user":"    message: 'There is no user record corresponding to the provided identifier.'","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m     message: 'There is no user record corresponding to the provided identifier.'"}}
>    }, {"user":"  },","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m   },"}}
>    codePrefix: 'auth' {"user":"  codePrefix: 'auth'","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m   codePrefix: 'auth'"}}
>  } {"user":"}","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m }"}}
>  [2021-06-04 05:58:46] --> POST /session 401 146ms {"user":"[2021-06-04 05:58:46] --> POST /session 401 146ms","metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"\u001b[90m> \u001b[39m [2021-06-04 05:58:46] --> POST /session 401 146ms"}}
i  functions: Finished "europe-west1-admin-sessionManagement" in ~1s {"metadata":{"emulator":{"name":"functions"},"function":{"name":"europe-west1-admin-sessionManagement"},"message":"Finished \"europe-west1-admin-sessionManagement\" in ~1s"}}
```

**Comment by abeisgoat** [comment]
Are you sure you're not accidentally mixing local (emulator) credentials with production credentials?
