### ISSUE TITLE
iOS & Firebase Storage Emulator Crash

### ISSUE THREAD

**Issue by dashby3000** [firebase/firebase-tools#3523]
### [REQUIRED] Environment info

Operating System version: MacOS BigSur v11.3
Firebase: 9.13.1
Firebase SDK version: 8
Firebase Product: Storage with emulators
Apple iOS 14.5

### [REQUIRED] Describe the problem

I have some pretty basic iOS code using the FirebaseStorage SDK to upload a file to the the Storage Emulator.  When I run the code in the Gist (provided below) I get an error back from the emulator (see below).  However, the same code, unmodified, runs against the Production Storage.   

### [REQUIRED] Test case

https://gist.github.com/dashby3000/cce1e3fab445b0aee51430b9bbee2360

### [REQUIRED] Steps to reproduce

https://gist.github.com/dashby3000/cce1e3fab445b0aee51430b9bbee2360

### [REQUIRED] Expected behavior

It should upload a file to the Emulator Storage.

### [REQUIRED] Actual behavior
Error seen in the Emulator console:

(node:3149) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink '/tmp/firebase/storage/blobs/471f1c61-b5fd-4072-b5f0-46e16b40ff92_b_instagramfirestoretutori-228f4.appspot.com_o_vmk.mp4'
    at Object.unlinkSync (fs.js:1052:3)
    at Persistence.deleteFile (/usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/files.js:478:18)
    at StorageLayer.cancelUpload (/usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/files.js:152:27)
    at handleUpload (/usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:367:45)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:444:24
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:89:9
(node:3149) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3149) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dashby3000** [comment]
My issue... rookie error in setting rules and didn't realize it.
