### ISSUE TITLE
FirebaseError: Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

### ISSUE THREAD

**Issue by raider2107** [firebase/firebase-tools#3526]
### [REQUIRED] Environment info

**firebase-tools:** version 9.14.0

**Platform:** Windows 10

### [REQUIRED] Test case
Trying to login for the first time. 

### [REQUIRED] Steps to reproduce
`firebase login --reauth --no-localhost --debug`  

### [REQUIRED] Expected behavior
Successful login

### [REQUIRED] Actual behavior
```
[debug] [2021-06-23T07:44:15.377Z] ----------------------------------------------------------------------
[debug] [2021-06-23T07:44:15.380Z] Command:       E:\PROGRAMING STUFF\nodejs\node.exe C:\Users\31089\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login --reauth --no-localhost --debug
[debug] [2021-06-23T07:44:15.380Z] CLI Version:   9.14.0
[debug] [2021-06-23T07:44:15.380Z] Platform:      win32
[debug] [2021-06-23T07:44:15.380Z] Node Version:  v14.17.0
[debug] [2021-06-23T07:44:15.382Z] Time:          Wed Jun 23 2021 15:44:15 GMT+0800 (China Standard Time)
[debug] [2021-06-23T07:44:15.382Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-06-23T07:44:15.385Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=244399995&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
[info] 
[debug] [2021-06-23T07:44:32.326Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 {"code":"4/1AY0e-g6R5ARzWJqz1B-ycNp_8C4uC4IHqpP9a8SwRYiAnSvZQ3gW5B3Io0Q","client_id":"563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com","client_secret":"j9iVZfS8kkCEFUPaAeJV0sAi","redirect_uri":"urn:ietf:wg:oauth:2.0:oob","grant_type":"authorization_code"}
[debug] [2021-06-23T07:44:53.961Z] Token Fetch Error: FirebaseError: Server Error. connect ETIMEDOUT 172.217.160.77:443
    at Request._callback (C:\Users\31089\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:32:31)
    at self.callback (C:\Users\31089\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.emit (domain.js:470:12)
    at Request.onRequestError (C:\Users\31089\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:376:20)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[error] 
[error] Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci

```
  
    
![image](https://user-images.githubusercontent.com/37748022/123060156-111ae180-d43d-11eb-81d4-d3bb7f15b6bd.png)
  
I'm located in a country where the Google and all Google services and tools are blocked by local government. So I tried the above steps with and without VPN (Lantern), but the result still the same. I also tried all the steps in the below issues, but can't solve my problem.  I don't have any proxy set.
https://github.com/firebase/firebase-tools/issues/2508
https://github.com/firebase/firebase-tools/issues/486
https://stackoverflow.com/questions/44471670/firebase-init-command-failing-to-execute

**Comment by samtstern** [comment]
@raider2107 unfortunately if you're seeing `ETIMEDOUT` there's nothing we can do here. The connection is failing or being blocked somewhere (as you said).

I hope someone on StackOverflow who is in a similar situation can maybe tell you their workaround! But we, the Firebase team, are not able to give tips on this sensitive topic.
