### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by Akshit1025** [firebase/firebase-tools#3530]
### [REQUIRED] Environment info

**firebase-tools:** 9.14.0

**Platform:** Windows

### [REQUIRED] Test case

[debug] [2021-06-24T06:39:05.782Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\akshit gupta\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login:ci --no-localhost
[debug] [2021-06-24T06:39:05.784Z] CLI Version:   9.14.0
[debug] [2021-06-24T06:39:05.784Z] Platform:      win32
[debug] [2021-06-24T06:39:05.785Z] Node Version:  v14.15.1
[debug] [2021-06-24T06:39:05.786Z] Time:          Thu Jun 24 2021 12:09:05 GMT+0530 (India Standard Time)
[debug] [2021-06-24T06:39:05.786Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=682047637&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
[info] 
[debug] [2021-06-24T06:39:05.843Z] Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[error] 
[error] Error: An unexpected error has occurred.

### [REQUIRED] Steps to reproduce
run windows + r
type cmd in it
press enter

it will open your command prompt

type `firebase login`

then type y

### [REQUIRED] Expected behavior

the expected behavior is to open the browser then we will login to our firebase account and authenticate ourselves

### [REQUIRED] Actual behavior

It does not open the browser and just after it prints waiting for authentication.... and after that it says an unexpected error has occured
![Screenshot (302)](https://user-images.githubusercontent.com/76731022/123217869-ab842f00-d4e8-11eb-9d0e-1c069b809cf6.png)

**Comment by Akshit1025** [comment]
Sorry for opening 
I just tried it with admin rights
Thank You
