### ISSUE TITLE
firebase-tools node v8.0.0 compatibility

### ISSUE THREAD

**Issue by RoneyThomas** [firebase/firebase-tools#355]
Today i updated node to v8.0.0 and can't get firebase-tools working.

To reproduce install node 8 and try installing firebase-tools. 

From the log file this is part where things go wrong.

```
verbose stack TypeError: Cannot read property 'type' of undefined
verbose stack     at module.exports.rollback (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/action/finalize.js:93:16)
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:547:7
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
verbose stack     at Array.forEach (native)
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
verbose stack     at Array.forEach (native)
verbose stack     at asyncMap (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:546:5
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
verbose stack     at Array.forEach (native)
verbose stack     at /Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
verbose stack     at Array.forEach (native)
verbose stack     at asyncMap (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
verbose stack     at Installer.rollbackFailedOptional (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:545:3)
verbose stack     at Array.<anonymous> (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
verbose stack     at LOOP (/Users/roneythomas/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
verbose cwd /Users/roneythomas/code/pubsub/appengine
verbose Darwin 16.6.0
verbose argv "/Users/roneythomas/.nvm/versions/node/v8.0.0/bin/node" "/Users/roneythomas/.nvm/versions/node/v8.0.0/bin/npm" "install" "-g" "firebase-tools"
verbose node v8.0.0
verbose npm  v5.0.0
```

**Comment by laurenzlong** [comment]
Hi @RoneyThomas , we're unable to reproduce this bug by running "npm install -g firebase-tools" with Node V8.0.0
