### ISSUE TITLE
`An unexpected error has occurred` on deleting Hosting preview channel with `--force` flag

### ISSUE THREAD

**Issue by eattahm** [firebase/firebase-tools#3571]
### [REQUIRED] Environment info

**firebase-tools:** 9.14.0

**Platform:** Ubuntu 20.04

### [REQUIRED] Test case

When deleting a Firebase Hosting preview channel using the `--force` flag, `An unexpected error has occurred.` is output

### [REQUIRED] Steps to reproduce

1. From a firebase hosting project run: `firebase hosting:channel:deploy foo`
2. Check that `foo` is added to the list of Channel IDs by running: `firebase hosting:channel:list`
3. Delete channel `foo` by running `firebase hosting:channel:delete --force foo`

### [REQUIRED] Expected behavior

Channel is deleted with no error output

### [REQUIRED] Actual behavior

`Error: An unexpected error has occurred.` is displayed

```
[2021-07-10T20:55:53.719Z] >>> [apiv2][query] DELETE https://firebasehosting.googleapis.com/v1beta1/projects/web-adblockplus-org/sites/web-adblockplus-org/channels/foo [none]
[2021-07-10T20:55:54.708Z] <<< [apiv2][status] DELETE https://firebasehosting.googleapis.com/v1beta1/projects/web-adblockplus-org/sites/web-adblockplus-org/channels/foo 200
[2021-07-10T20:55:54.710Z] <<< [apiv2][body] DELETE https://firebasehosting.googleapis.com/v1beta1/projects/web-adblockplus-org/sites/web-adblockplus-org/channels/foo {}
[2021-07-10T20:55:54.713Z] >>> [apiv2][query] GET https://identitytoolkit.googleapis.com/admin/v2/projects/web-adblockplus-org/config [none]
[2021-07-10T20:55:55.049Z] <<< [apiv2][status] GET https://identitytoolkit.googleapis.com/admin/v2/projects/web-adblockplus-org/config 404
[2021-07-10T20:55:55.051Z] <<< [apiv2][body] GET https://identitytoolkit.googleapis.com/admin/v2/projects/web-adblockplus-org/config {"error":{"code":404,"message":"CONFIGURATION_NOT_FOUND","status":"NOT_FOUND"}}
[2021-07-10T20:55:55.186Z] TypeError: marked_1.default is not a function
    at Command.actionFn (/home/ewoenam/.nvm/versions/node/v14.15.4/lib/node_modules/firebase-tools/lib/commands/hosting-channel-delete.js:41:74)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: An unexpected error has occurred.
```

**Comment by joehan** [comment]
Seems like this slipped through the cracks - however, based on the `marked_1.default` in the error message, this should be fixed now.
