### ISSUE TITLE
firebase deploy --only functions fails 

### ISSUE THREAD

**Issue by jessp01** [firebase/firebase-tools#3591]
### [REQUIRED] Environment info

$ firebase --version
9.16.0

**firebase-tools:**

**Platform:**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
**NodeJS version:**
> v12.21.0

### [REQUIRED] Test case

`firebase deploy --only functions` fails with:
```
i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: An unexpected error has occurred.
```
### [REQUIRED] Steps to reproduce

Run `$ firebase deploy --only functions`

### [REQUIRED] Expected behavior

For it to deploy

### [REQUIRED] Actual behavior
RC:2; Output: `Error: An unexpected error has occurred.`

```
i  functions: preparing functions directory for uploading... 
[2021-07-21T00:43:48.267Z] Error: entry name must be a non-empty string value
    at module.exports.ZipStream.entry (/usr/local/lib/node_modules/firebase-tools/node_modules/zip-stream/index.js:124:14)
    at Zip.append (/usr/local/lib/node_modules/firebase-tools/node_modules/archiver/lib/plugins/zip.js:56:15)
    at Archiver._moduleAppend (/usr/local/lib/node_modules/firebase-tools/node_modules/archiver/lib/core.js:179:16)
    at Archiver._onQueueTask (/usr/local/lib/node_modules/firebase-tools/node_modules/archiver/lib/core.js:405:8)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/async/dist/async.js:3201:13
    at Object.process (/usr/local/lib/node_modules/firebase-tools/node_modules/async/dist/async.js:1427:21)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/async/dist/async.js:1325:19
    at /usr/local/lib/node_modules/firebase-tools/node_modules/async/dist/async.js:321:20
    at Immediate.fullCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/archiver/lib/core.js:396:5)
    at processImmediate (internal/timers.js:461:21)

Error: An unexpected error has occurred.
```

When I edit and include JSON.stringify(data) in the error output, I get:
```
{"name":"","mode":420,"sourcePath":"/home/james/AndroidStudioProjects/zjplate/functions/\\","type":"file","sourceType":"stream","date":"2021-07-13T14:54:40.914Z","prefix":null,"stats":{"dev":65028,"mode":33188,"nlink":1,"uid":1000,"gid":1000,"rdev":0,"blksize":4096,"ino":8140725,"size":2954,"blocks":8,"atimeMs":1626821959948.455,"mtimeMs":1626188080913.9495,"ctimeMs":1626188080913.9495,"birthtimeMs":1626188080913.9495,"atime":"2021-07-20T22:59:19.948Z","mtime":"2021-07-13T14:54:40.914Z","ctime":"2021-07-13T14:54:40.914Z","birthtime":"2021-07-13T14:54:40.914Z"},"namePrependSlash":false,"linkname":null,"store":false,"comment":""} 
```

So, indeed, the `name` member is empty but I have no idea why. Invoking `firebase --serve` does work as expected and registers all functions correctly.

Thanks in advance,

**Comment by jessp01** [comment]
I found the problem. In the functions directory, I had a file, literally named '\' (it was unintentional, obviously but generally speaking, it is a valid filename). This caused the creation of the above faulty data object and made the operation fail completely. Once removed, everything worked as expected.

May I suggest that you perhaps make error handling slightly more robust and verbose?

Cheers,
