### ISSUE TITLE
Error when running remoteconfig:get if no Remote Config is set

### ISSUE THREAD

**Issue by epodol** [firebase/firebase-tools#3601]
### [REQUIRED] Environment info

**firebase-tools:** 9.16.0

**Platform:** Windows with WSL 2

### [REQUIRED] Test case

Create a new project (following the normal steps).

### [REQUIRED] Steps to reproduce

Do not add any remote config data to your project.
Run `firebase remoteconfig:get`
See Error:
> Error: An unexpected error has occurred.

### [REQUIRED] Expected behavior

If there is no config set, then this should just return an empty object, but not an error.
This would make it easier for any CI steps to get the config if no config is set. A simple check to see if the result is undefined, then return an empty object would suffice.

### [REQUIRED] Actual behavior

![image](https://user-images.githubusercontent.com/34190213/126838782-7d7c6374-4838-4f2d-b2a7-ca7da8c17287.png)

```javascript
[debug] [2021-07-23T20:33:57.979Z] AssertionError [ERR_ASSERTION]: expected "string" but got "undefined"
    at new AssertionError (internal/assert/assertion_error.js:456:5)
    at Object.assertIsString (/home/epodol/.nvm/versions/node/v14.15.4/lib/node_modules/firebase-tools/lib/utils.js:339:15)
    at Command.actionFn (/home/epodol/.nvm/versions/node/v14.15.4/lib/node_modules/firebase-tools/lib/commands/remoteconfig-get.js:29:11)
    at /home/epodol/.nvm/versions/node/v14.15.4/lib/node_modules/firebase-tools/lib/command.js:171:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[error] 
[error] Error: An unexpected error has occurred.
```

Let me know if you need any more information. Thank you!

**Comment by epodol** [comment]
After looking into this, I would be happy to open a PR to fix this. Feel free to assign this issue to me.

**Comment by aalej** [comment]
This looks to be fixed in the latest version of firebase-tools, currently 15.7.0. Running `$ firebase remoteconfig:versions:list --project [PROJECT_ID]` won't raise and error will output the ff for a project that does not have Remote Config:
```
┌─────────────┬────────────────┬─────────────┐
│ Update User │ Version Number │ Update Time │
└─────────────┴────────────────┴─────────────┘
```
