### ISSUE TITLE
Firebase init error on windows with antivirus

### ISSUE THREAD

**Issue by PovilasID** [firebase/firebase-tools#362]
Firebase tools threw an error on my windows machine. Disabling bitdefender fixed it. Cudos: https://github.com/react-community/create-react-native-app/issues/191#issuecomment-304073970

However, here is  the error log 

```
12333 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12333 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
12333 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
12333 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
12333 verbose stack
12333 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12333 verbose stack     at Error (native)
12334 verbose cwd C:\Users\THEUSER\THEREPOSITRY\functions
12335 error Windows_NT 10.0.15063
12336 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
12337 error node v6.10.2
12338 error npm  v3.10.10
12339 error path C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5
12340 error code EPERM
12341 error errno -4048
12342 error syscall rename
12343 error Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12343 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
12343 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
12343 error     at FSReqWrap.oncomplete (fs.js:123:15)
12343 error
12343 error Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12343 error     at Error (native)
12343 error  { Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12343 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
12343 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
12343 error     at FSReqWrap.oncomplete (fs.js:123:15)
12343 error
12343 error Error: EPERM: operation not permitted, rename 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\.staging\@types\express-9bff9cb5' -> 'C:\Users\THEUSER\THEREPOSITRY\functions\node_modules\@types\express'
12343 error     at Error (native) parent: 'functions' }
12344 error Please try running this command again as root/Administrator.
12345 verbose exit [ -4048, true ]
```

**Comment by mbleigh** [comment]
This seems like an issue to log with bitdefender or perhaps with npm. I
don't believe there's anything we can do to mitigate here.

**Comment by jhill072** [comment]
I was receiving this same error, and to get around this issue I used the --no-localhost option when running `firebase login`.
