### ISSUE TITLE
MaxListenersExceededWarning when using emulator

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-tools#3640]
I'm getting the following spat out a lot (in the hundreds of times but we do have a lot of test cases) from running the firebase emulators (`firebase-tools` version `9.16.0`):

`(node:57642) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 log listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

From looking at the stack trace of the warning I think its specific the functions emulator.

Cause by the following line (tracked by using `NODE_OPTIONS='--trace-warnings' firebase emulators:exec`):
https://github.com/firebase/firebase-tools/blob/fdf23628f75fbfcc2adc19721ed652ea2e79e17a/src/emulator/functionsRuntimeWorker.ts#L121

```
(node:57642) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 log listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:475:17)
    at EventEmitter.addListener (events.js:497:10)
    at RuntimeWorker.onLogs (/<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/functionsRuntimeWorker.js:81:29)
    at /<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:576:20
    at new Promise (<anonymous>)
    at FunctionsEmulator.handleBackgroundTrigger (/<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:563:16)
    at /<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:98:29
    at WorkQueue.runNext (/<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/workQueue.js:91:23)
    at WorkQueue.start (/<SNIP>/.config/yarn/global/node_modules/firebase-tools/lib/emulator/workQueue.js:46:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Unfortunately I've not got the time at the moment to put together a simple reproduction case but thought I'd raise an issue to keep track in case its obvious to any maintainers!

**Comment by egorkel-altexsoft** [comment]
We ran into this problem while deploying functions using [programmatic mode](https://github.com/firebase/firebase-tools?tab=readme-ov-file#using-as-a-module).
We deploy function in cycle using command
```typescript
  const fbTools = require('firebase-tools');

  /** set up code */  

  for (const functionsChunk of chunks) {
    const onlyString = functionsChunk.map(f => `functions:${f}`).join(',');
    await fbTools.deploy({
      force: true,
      only: onlyString,
      project
    });
  }
```
We set DEBUG env var to see detailed logs and noticed that with each iteration logs are duplicated. It looks like a new logger instance created each deploy command call.

Final log on the last iteration

<img width="751" height="547" alt="Image" src="https://github.com/user-attachments/assets/7f37eae7-c0ff-4020-9dc8-1be3a1eddede" />

**Comment by egorkel-altexsoft** [comment]
I solved this problem by running firebase-tools in the child process. Each chunk has its own process, no more duplicated logs.

**Comment by joehan** [comment]
@egorkel-altexsoft Glad that you found a workaround! I think the duplicated logs issue is different from the original issue here, which has been made obsolete by some refactors. Closing this as fixed.
