### ISSUE TITLE
Firebase storage emulator : All data are not downloaded

### ISSUE THREAD

**Issue by Llacuska** [firebase/firebase-tools#3695]
### [REQUIRED] Environment info

9.16.0

Ubuntu

### [REQUIRED] Test case

https://github.com/workandplay/firebase-storage-emulator-repro

To run the project, go to the project root folder and run the firebase command : 
firebase emulators:start --project demo-repro
Open your favorite browser and go to http://localhost:5000/index.html

When downloading data from Firebase emulator storage, some requests stay "pending" so all data are not downloaded.

### [REQUIRED] Steps to reproduce

Use the following project to reproduce this behaviour. This is a simple html page with a localhost storage emulator.
String are sent to the emulator then downloaded and displayed back on the page. 
"Pending" string are data that could not be downloaded. "Success" string are data wich were downloaded succefully.

### [REQUIRED] Expected behavior

All data downloaded from the emulator storage should be displayed

### [REQUIRED] Actual behavior

Some request are stuck in pending state

**Comment by simeon9696** [comment]
I have a similar issue but with uploading. In the emulator terminal, I just get this error:

```
(node:30656) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'C:\Users\SIMEON~1.RAM\AppData\Local\Temp\firebase\storage\blobs\"penthejourney-ad280.appspot.com\products\7pkXW8yz3Wy8NwMPoCsN\hq'
    at Object.mkdirSync (fs.js:1009:3)       
    at Persistence.renameFile (C:\Users\simeon.ramjit\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\storage\files.js:501:18)
    at StorageLayer.finalizeUpload (C:\Users\simeon.ramjit\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\storage\files.js:204:27)
    at handleUpload (C:\Users\simeon.ramjit\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\storage\apis\firebase.js:397:54)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not 
handled will terminate the Node.js process with a non-zero exit code.
```

And the request just hangs

**Comment by co-admin** [comment]
We also have the same problem during downloading in case if we observing progress.

**Comment by rhodgkins** [comment]
I had similar problems so [implemented various missing features of the Storage emulator](https://github.com/firebase/firebase-tools/issues/3647) - its still waiting to be merged :-/
You could try working against this and see if it fixes your problem and try upvoting / commenting on the PR.
