### ISSUE TITLE
Error: failed to update release notes with HTTP Error: 403, Unknown Error

### ISSUE THREAD

**Issue by saeedata** [firebase/firebase-tools#3763]
how can I update the release note via firebase-cli:

```
$ firebase appdistribution:distribute app-googlePlay-debug.apk --app APP_ID --release-notes-file release_note.txt --testers-file testers.txt
i  uploading binary...
(node:429) UnhandledPromiseRejectionWarning: FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
    at Client.doRequest (/root/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/apiv2.js:211:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔  re-uploaded already existing release 300.1.1-beta (511) successfully!
i  updating release notes...
Error: failed to update release notes with HTTP Error: 403, Unknown Error
Cleaning up file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by abeisgoat** [comment]
Is this still happening? That endpoint exists, so may have been a fluke.
