### ISSUE TITLE
deploy using GOOGLE_APPLICATION_CREDENTIALS failing to get an environment config var on global scope

### ISSUE THREAD

**Issue by benshabatnoam** [firebase/firebase-tools#3796]
### [REQUIRED] Environment info

**firebase-tools:** 9.19.0

**Platform:** Windows 10

### [REQUIRED] Test case

Repo with mcve: https://github.com/benshabatnoam/config-get-test

### [REQUIRED] Steps to reproduce

1. clone/fork the repo
2. Create your [service account key](https://firebase.google.com/docs/admin/setup#initialize-sdk) (name it _service-account.json_) and place it in this path:
_functions\service-account.json_
3. Create _user.name_ config by:
* Login to firebase: run `firebase login`
* run `firebase functions:config:set user.name=yourname`
* logout from firebase: run `firebase logout`
4. run `npm run deploy-using-service-account`

Here is a link to my [StackOverflow ](https://stackoverflow.com/questions/68930667/firebase-functions-deploy-using-google-application-credentials-failing-to-get-an)question regarding this.

### [REQUIRED] Expected behavior

The deployment should complete successfully.

### [REQUIRED] Actual behavior

Deployment failed, getting this error:
`TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (C:\Projects\tests\config-get-test\functions\index.js:4:41)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadModule (C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:10:16)
    at C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:34:21
    at Object.<anonymous> (C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:72:3) `

Note that if you'll remark code line 4, in which I'm trying to get a configuration variable in the global scope, the deployement will succeed, even though I'm using the same line code inside the `helloWorld` function scope.
Here is the complete log using _--debug_ flag:
```
> cross-env GOOGLE_APPLICATION_CREDENTIALS=./service-account.json firebase deploy --only functions --debug

[2021-10-03T14:17:13.956Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-10-03T14:17:14.407Z] [iam] checking project config-get-test for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2021-10-03T14:17:14.415Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/config-get-test:testIamPermissions  
 {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[2021-10-03T14:17:15.342Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 03 Oct 2021 14:17:15 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=556","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-10-03T14:17:15.348Z] >>> HTTP REQUEST POST https://iam.googleapis.com/v1/projects/config-get-test/serviceAccounts/config-get-test@appspot.gserviceaccount.com:testIamPermissions  
 {"permissions":["iam.serviceAccounts.actAs"]}
[2021-10-03T14:17:16.185Z] <<< HTTP RESPONSE 403 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Sun, 03 Oct 2021 14:17:16 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-10-03T14:17:16.186Z] <<< HTTP RESPONSE BODY {"error":{"code":403,"message":"Identity and Access Management (IAM) API has not been used in project 396653287106 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"iam.googleapis.com","consumer":"projects/396653287106"}}]}}
[2021-10-03T14:17:16.195Z] [functions] service account IAM check errored, deploy may fail: HTTP Error: 403, Identity and Access Management (IAM) API has not been used in project 396653287106 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. {"name":"FirebaseError","children":[],"context":{"body":{"error":{"code":403,"message":"Identity and Access Management (IAM) API has not been used in project 396653287106 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"iam.googleapis.com","consumer":"projects/396653287106"}}]}},"response":{"statusCode":403,"body":{"error":{"code":403,"message":"Identity and Access Management (IAM) API has not been used in project 396653287106 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"iam.googleapis.com","consumer":"projects/396653287106"}}]}},"headers":{"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Sun, 03 Oct 2021 14:17:16 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"iam.googleapis.com","port":443,"hostname":"iam.googleapis.com","hash":null,"search":null,"query":null,"pathname":"/v1/projects/config-get-test/serviceAccounts/config-get-test@appspot.gserviceaccount.com:testIamPermissions","path":"/v1/projects/config-get-test/serviceAccounts/config-get-test@appspot.gserviceaccount.com:testIamPermissions","href":"https://iam.googleapis.com/v1/projects/config-get-test/serviceAccounts/config-get-test@appspot.gserviceaccount.com:testIamPermissions"},"method":"POST"}}},"exit":1,"message":"HTTP Error: 403, Identity and Access Management (IAM) API has not been used in project 396653287106 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=396653287106 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":403}

=== Deploying to 'config-get-test'...

i  deploying functions
[2021-10-03T14:17:16.210Z] Validating nodejs source
!  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.
[2021-10-03T14:17:23.489Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "deploy-using-service-account": "cross-env GOOGLE_APPLICATION_CREDENTIALS=./service-account.json firebase deploy --only functions --debug",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
  "devDependencies": {
    "cross-env": "^7.0.3",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
[2021-10-03T14:17:23.509Z] Building nodejs source
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
[2021-10-03T14:17:23.515Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/config-get-test/services/cloudfunctions.googleapis.com

[2021-10-03T14:17:23.518Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/config-get-test/services/runtimeconfig.googleapis.com

[2021-10-03T14:17:23.520Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/config-get-test/services/cloudbuild.googleapis.com

[2021-10-03T14:17:24.554Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 03 Oct 2021 14:17:24 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-10-03T14:17:24.652Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 03 Oct 2021 14:17:24 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
+  functions: required API cloudfunctions.googleapis.com is enabled 
[2021-10-03T14:17:24.693Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 03 Oct 2021 14:17:24 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
+  functions: required API cloudbuild.googleapis.com is enabled 
[2021-10-03T14:17:24.696Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/config-get-test/adminSdkConfig

[2021-10-03T14:17:25.183Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sun, 03 Oct 2021 14:17:25 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-10-03T14:17:25.186Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/config-get-test/configs  

[2021-10-03T14:17:26.497Z] <<< HTTP RESPONSE 403 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Sun, 03 Oct 2021 14:17:26 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-10-03T14:17:26.500Z] <<< HTTP RESPONSE BODY {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
HTTP Error: 403, The caller does not have permission
[2021-10-03T14:17:26.506Z] Analyzing nodejs backend spec

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (C:\Projects\tests\config-get-test\functions\index.js:4:41)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadModule (C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:10:16)
    at C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:34:21
    at Object.<anonymous> (C:\Users\n0556\AppData\Roaming\nvm\v14.17.0\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\triggerParser.js:72:3)      
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ deploy-using-service-account: `cross-env GOOGLE_APPLICATION_CREDENTIALS=./service-account.json firebase deploy --only functions --debug`      
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ deploy-using-service-account script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\n0556\AppData\Roaming\npm-cache\_logs\2021-10-03T14_17_27_345Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run deploy-using-service-account" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

Thanks!

**Comment by mbleigh** [comment]
It seems likely that this is a permissions issue given the `403` response. Can you give your service account the `roles/firebase.developAdmin` role and see if it works after that?

**Comment by benshabatnoam** [comment]
@mbleigh thanks so much, that was really the problem. Once I added that role `roles/firebase.developAdmin`, I managed to deploy successfully!
