### ISSUE TITLE
TypeError: this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by chalin** [firebase/firebase-tools#382]
Starting today, on an attempted `firebase deploy` of the https://webdev.dartlang.org site from [Travis](https://travis-ci.org/dart-lang/site-webdev) we now get the following error (the excerpt is from the end of this [Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/248175713)):
```
=== Deploying to 'webdev-dartlang-org'...

i  deploying hosting
i  hosting: preparing publish directory for upload...
FIREBASE WARNING: Exception was thrown by user callback. TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/progress/lib/node-progress.js:177:17)
    at ProgressBar.tick (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/progress/lib/node-progress.js:91:10)
    at /home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/lib/deploy/hosting/deploy.js:65:17
    at /home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:201:710
    at ec (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:52:165)
    at ac (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:31:216)
    at bc (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:30:1259)
    at Ji.h.Ib (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:220:287)
    at Rh.h.Jd (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:186:283)
    at Fh.Jd (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:176:364) 
```

A regression of #73?

cc @kwalrath

**Comment by laurenzlong** [comment]
https://github.com/firebase/firebase-tools/pull/373 Should have fixed this (it's not released yet). Can you try the tip of the master branch?

**Comment by laurenzlong** [comment]
Alternatively, reinstalling firebase-tools should update all the dependencies to the latest versions, and will thereby update the progress module too.

**Comment by chalin** [comment]
@mit-mit offered a fix via https://github.com/dart-lang/site-webdev/pull/788. Thanks.

**Comment by laurenzlong** [comment]
Yes that works too! Thanks for the update.

**Comment by akshaynaik404** [comment]
@laurenzlong Installing directly from master branch works for now. Your fix still not released yet, I guess.
