### ISSUE TITLE
firebase init yields: TypeError: Cannot read properties of undefined (reading 'predeploy')

### ISSUE THREAD

**Issue by dzoba** [firebase/firebase-tools#3868]
### [REQUIRED] Environment info

**firebase-tools:** 9.21.0

**Platform:** Mac

### [REQUIRED] Test case
CLI Interaction

### [REQUIRED] Steps to reproduce
Use `firebase init` and select `Hosting: Set up GitHub Action deploys`.  
Select `Use and existing project`.  
Select a project. 
Select a Github repository.

Result:

```Waiting for authentication...

✔  Success! Logged into GitHub as dzoba

? For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) <edited>

✔  Created service account github-action-421226657 with Firebase Hosting admin permissions.
✔  Uploaded service account JSON to GitHub as secret <edited>.
i  You can manage your secrets at <edited>.


Error: An unexpected error has occurred.
```

In the logs I see

```
[debug] [2021-10-26T14:58:01.929Z] TypeError: Cannot read properties of undefined (reading 'predeploy')
    at Object.initGitHub [as hosting:github] (/Users/christopherdzoba/.nvm/versions/node/v16.11.1/lib/node_modules/firebase-tools/lib/init/features/hosting/github.js:65:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (/Users/christopherdzoba/.nvm/versions/node/v16.11.1/lib/node_modules/firebase-tools/lib/init/index.js:19:9)
[error] 
[error] Error: An unexpected error has occurred.
```

### [REQUIRED] Expected behavior
No error

### [REQUIRED] Actual behavior
Error

**Comment by aalej** [comment]
Hey, sorry not being able to respond to this sooner. This issue isn't reproducible on the latest version of the firebase-tools(v15.11.0) so I'll go ahead and close this. Looking at the lines where the error occurred, it looks like the change from `setup.config.hosting.predeploy` to `setup.config.hosting?.predeploy` fixed this issue

https://github.com/firebase/firebase-tools/blob/77e877ca10070f484aba3d33b11223bb7f913faa/src/init/features/hosting/github.ts#L135-L137

Also, in the recent versions of firebase-tools, for `firebase init hosting:github` to run, an existing Hosting config in firebase.json is required, which also prevents this error from occurring.

If you're still encountering this issue using the latest version, please leave comment so that we can re-open this or open up a new report. Thanks!
