### ISSUE TITLE
Failed to decode param - This error should be handled by the developer

### ISSUE THREAD

**Issue by devlucem** [firebase/firebase-tools#3891]
### [REQUIRED] Environment info

**9.10.0**

**Windows:**

### [REQUIRED] Test case

```
const app = express();
app.get('/404', (req, res) => res.send('failed to work'));
app.get('**', (req, res) => res.send('working'));
app.use((err, req, res, next) => res.redirect('/404'));
exports.app = functions.https.onRequest(app)
```

### [REQUIRED] Steps to reproduce

Run the command `firebase serve --only functions` then add `/%CO` at the end of your invocation URL. Example `http://localhost:5000/project-name/us-central1/app/%CO`

### [REQUIRED] Expected behavior

The text returned should say 'failed to work'

### [REQUIRED] Actual behavior
A log of the firebase-tools is returned

```
URIError: Failed to decode param '/tradingviewto/us-central1/serving/%CO'
    at decodeURIComponent (<anonymous>)
    at decode_param (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:574:18)
    at next (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:220:15)
    at expressInit (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
    at query (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\lucem\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
```

**Comment by devlucem** [comment]
This generally happens because firebase catches the error in the URL. Instead, the developer should be the one catching this error in order to respond correctly to the client.

**Comment by abeisgoat** [comment]
What's the production behavior for providing that illegal character in the URL?

**Comment by devlucem** [comment]
visiting the function in production will return `404 bad request` in the browser. 
Instead, Id like to catch that error and redirect to a page of my choice

**Comment by inlined** [comment]
This seems to originate in the functions framework that Google Cloud maintains. I've reproduced it with the following (non-firebase) function:

```
const express = require('express');
const app = express();

app.get('/404', (req, res) => res.send('failed to work'));
app.get('**', (req, res) => res.send('working'));
app.use((err, req, res, next) => res.redirect('/404'));

module.exports.app = app;
```

The problem can be reproduced at https://us-central1-inlined-junkdrawer.cloudfunctions.net/param-encoding/404/%C0

**Comment by inlined** [comment]
Rather than moving the issue I've created one that is focused on non-Firebase layers. Closing this copy
