### ISSUE TITLE
firebase login error on Windows 10 PC without administrator access

### ISSUE THREAD

**Issue by dvghm** [firebase/firebase-tools#3933]
### [REQUIRED] Environment info
**firebase-tools:** 9.23.0
**Platform:** Windows 10 Enterprise, 20H2
**Shell:** PowerShell Core 7.2
**Node version:** 14.18.2

### [REQUIRED] Test case
Attempting to execute 'firebase login' repeatedly results in the following error message.

`Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth`

I have attempted:
- `firebase login`
- `firebase login --reauth`
- `firebase login --no-localhost`
- `firebase login:ci` (and then placing the resulting token in the FIREBASE_TOKEN environment variable)

On a device where I have administrative rights, I have no issues logging in and using the Firebase CLI.

#### Actual results in the case of `login`, `login --reauth`
1. A browser tab opens
2. I select my google account
3. I allow permissions
4. Login fails
5. A second browser tab automatically opens
6. I select my google account
7. I allow permissions
8. Login succeeds and I am presented with a token
9. I paste the token into my shell prompt
10. I receive the Authentication Error message above.

#### Actual results in the case of `login --no-localhost`:
1. A browser tab opens
2. I select my google account
3. I allow permissions
4. Login succeeds and I am presented with a token
5. I paste the token into my shell prompt
6. I receive the Authentication Error message above.

#### Actual results in the case of `login:ci`:
1. A browser tab opens
2. I select my google account
3. I allow permissions
4. Login fails
5. A second browser tab automatically opens
6. I select my google account
7. I allow permissions
8. Login succeeds and I am presented with a token
9. I set the FIREBASE_TOKEN user environment variable to the token
10. I execute a firebase command, e.g. `firebase projects:list`
11. I receive an error:
`Error: Failed to list Firebase projects. See firebase-debug.log for more info.`

### [REQUIRED] Expected behavior
On a machine where I have administrator rights, the `firebase login` successfully opens a browser tab, allows me to select my Google account and grant permissions, and presents a token, which I can use in the shell to execute Firebase commands.

### [REQUIRED] Actual behavior
Any attempt to login (including login with options) results in the following error:
`Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth`

####The content of firebase-debug.log are:
```
[debug] [2021-12-07T06:26:32.985Z] ----------------------------------------------------------------------
[debug] [2021-12-07T06:26:32.987Z] Command:       C:\Users\<user>\bin\node-v14.18.2-win-x64\node.exe C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\bin\firebase.js projects:list
[debug] [2021-12-07T06:26:32.988Z] CLI Version:   9.23.0
[debug] [2021-12-07T06:26:32.988Z] Platform:      win32
[debug] [2021-12-07T06:26:32.988Z] Node Version:  v14.18.2
[debug] [2021-12-07T06:26:32.990Z] Time:          Mon Dec 06 2021 22:26:32 GMT-0800 (Pacific Standard Time)
[debug] [2021-12-07T06:26:32.990Z] ----------------------------------------------------------------------
[debug]
[debug] [2021-12-07T06:26:32.998Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-12-07T06:26:32.998Z] > authorizing via FIREBASE_TOKEN environment variable
[debug] [2021-12-07T06:26:33.003Z] > refreshing access token with scopes: []
[debug] [2021-12-07T06:26:33.004Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token
 <request body omitted>
[debug] [2021-12-07T06:26:33.044Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2021-12-07T06:26:33.048Z] FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
    at invalidCredentialError (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\auth.js:141:12)
    at refreshTokens (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\auth.js:448:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.getAccessToken (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\apiv2.js:146:23)
    at async Client.addAuthHeader (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\apiv2.js:137:21)
    at async Client.request (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\apiv2.js:93:34)
    at async getProjectPage (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\management\projects.js:233:17)
    at async getFirebaseProjectPage (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\management\projects.js:250:23)
    at async Object.listFirebaseProjects (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\management\projects.js:281:29)
    at async Command.actionFn (C:\Users\<user>\bin\node-v14.18.2-win-x64\node_modules\firebase-tools\lib\commands\projects-list.js:50:20)
[error]
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

**Comment by dvghm** [comment]
Closing this issue. I don't want to spend time debugging.

Have decided to use firebase tools in a Google Cloud Shell on machines where I don't have local admin rights.
