### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by xxyzz** [firebase/firebase-tools#397]
When I use Travis CI I got this error: 
FIREBASE WARNING: Exception was thrown by user callback. TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/progress/lib/node-progress.js:177:17)
    at ProgressBar.tick (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/progress/lib/node-progress.js:91:10)
    at /home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/lib/deploy/hosting/deploy.js:65:17
    at /home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:201:710
    at ec (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:52:165)
    at ac (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:31:216)
    at bc (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:30:1259)
    at Ji.h.Ib (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:220:287)
    at Rh.h.Jd (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:186:283)
    at Fh.Jd (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/firebase-tools/node_modules/firebase/lib/firebase-node.js:176:364) 
Error: An unexpected error has occurred.

Then I try to use my computer to deploy it keeps saying: 
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
Error: Server Error. socket hang up

The full Travis CI build log is here, I don't know what's wrong, it worked well a few weeks ago.
https://travis-ci.org/xxyzz/myblog/builds/253201191

**Comment by laurenzlong** [comment]
Please update your CLI to the latest version.

**Comment by mbleigh** [comment]
Also, add `--non-interactive` to your Travis command. For some reason the Travis environment doesn't seem to be detected properly as non-interactive.

**Comment by xxyzz** [comment]
Wow! Thanks for reply.
I updated it yesterday, but still the same error. Today I updated again and it works.
