### ISSUE TITLE
Emulator Issue:  Cannot query for references

### ISSUE THREAD

**Issue by s2young** [firebase/firebase-tools#4109]
I'm running a query in a firebase function that looks for a reference:

>     let query = await firestore_instance.collection(`clients/${context.params.client_id}/threads`)
>                     .where('ref', '==', event.after.ref)
>                     .get();

This works fine on firebase itself, but getting the following on the emulator:

>     Error: Value for argument "value" is not a valid Firestore document. Detected an object of type "DocumentReference"  that doesn't match the expected instance. Please ensure that the Firestore types you are using are from the same NPM package.)
>      at Object.validateUserInput (/Users/stuart/Documents/dev/nxt/functions/core/node_modules/@google-cloud/firestore/build/src/serializer.js:332:15)
>      at validateQueryValue (/Users/stuart/Documents/dev/nxt/functions/core/node_modules/@google-cloud/firestore/build/src/reference.js:2230:18)
>      at CollectionReference.where (/Users/stuart/Documents/dev/nxt/functions/core/node_modules/@google-cloud/firestore/build/src/reference.js:1061:9)
>      at /Users/stuart/Documents/dev/nxt/functions/laro/lib/src/Quotes.js:79:30
>      at step (/Users/stuart/Documents/dev/nxt/functions/laro/lib/src/Quotes.js:33:23)
>      at Object.next (/Users/stuart/Documents/dev/nxt/functions/laro/lib/src/Quotes.js:14:53)
>      at fulfilled (/Users/stuart/Documents/dev/nxt/functions/laro/lib/src/Quotes.js:5:58)
>      at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

"firebase-admin": "^10.0.2",
"firebase-functions": "^3.16.0",
"firebase-tools": "^10.1.2",

firebase --version 
10.1.2

**Comment by yuchenshi** [comment]
Any chance you can upload a minimal repro of this issue on GitHub? Also, please do double check if you have two instances / versions of the Admin SDK (e.g. `firestore_instance` is from a different npm module version than `event.after.ref`)

**Comment by grundius** [comment]
I am having a similar issue although I do not see the error. Using `firebase-admin@10.1.0` and `firebase-tools@10.7.1`. 

To reproduce:
1. A top-level collection `monkeys` with documents that contain a field `banana` which contains a reference to the `bananas` top-level collection.
2. Query: 
```
firestore().collection('monkeys')
  .where('banana', '==', firestore().collection('bananas').doc('12345'))
  .where('active', '==', true)
  .get()
```

On the emulator, this code returns an empty snapshot. Same query for the same data on the live Firestore server _does_ give results.

(Note that the actual collections and documents are invented, but based on real data we use).

**Comment by grundius** [comment]
I am having a similar issue although I do not see the error. Using `firebase-admin@10.1.0` and `firebase-tools@10.7.1`. 

To reproduce:
1. Start the Firebase emulator with Firestore support
2. Create a top-level collection `monkeys` with documents that contain a field `banana` which contains a reference to the `bananas` top-level collection (create this one as well) and a boolean `active` field.
3. Create a document in `monkeys` with the `active` set tot `true` and `banana` set to a reference `/bananas/12345` (create this document).
4. Run the following script against that emulator: 
```
// initialize firebase admin with the default app.

const result = await firestore().collection('monkeys')
  .where('banana', '==', firestore().collection('bananas').doc('12345'))
  .where('active', '==', true)
  .get()
```
5. `result.empty` is truthy and `result.docs` is empty.
6. Create the same data as in steps 2 and 3 in a live Firestore.
7. Run the script from 4 against that Firestore.
8. `result.empty` is falsy and `result.docs` is not empty.

Note that I ran several tests to ensure that Firebase is talking to the local emulator. In fact, in our codebase we run a collection group query right before that _does_ work on both emulator and Firestore live. Our actual code is private.

**Comment by yuchenshi** [comment]
@grundius would you mind taking an export right after Step 3 and share with us? We can look into if the issue within document creation or query execution. `monkeys` and `bananas` are good enough and there's no need to include real data or private code.

**Comment by grundius** [comment]
> @grundius would you mind taking an export right after Step 3 and share with us? We can look into if the issue within document creation or query execution. `monkeys` and `bananas` are good enough and there's no need to include real data or private code.
> 
> (P.S. In addition, an export from live Firestore after Step 6 will help even more, but please be careful not to include production data (e.g. by using an empty test project)

I can send you the dummy data, getting it from a live project is somewhat harder, but with the test data you should be able to reproduce the issue.
[monkeys_and_bananas.zip](https://github.com/firebase/firebase-tools/files/8653275/monkeys_and_bananas.zip)

**Comment by grundius** [comment]
@yuchenshi 
The code for running against the dummy data:
```
// initialize firebase admin with the default app.

const result = await firestore().collection('monkeys')
  .where('banana', '==', firestore().collection('bananas').doc('green'))
  .where('active', '==', true)
  .get()
```

The snapshot should contain at least one document.

**Comment by grundius** [comment]
@yuchenshi Is there any progress in this one? Where you able to reproduce the error?

**Comment by grundius** [comment]
@yuchenshi Thanks for the reply and looking into to this. 

I already, for different reasons, changed our tests to no longer reply on imported data (pretty brittle anyway) and in stead create the data for the test. And it works, so it seems like the inclusion of the project reference was was caused the wrong test results. 

So, for me, this issue can be closed.
