### ISSUE TITLE
Firebase Emulator: Command failed with exit code 2

### ISSUE THREAD

**Issue by moses-20** [firebase/firebase-tools#4163]
Firebase emulators quit suddenly when uploading to Firestore emulator 

### Firebase Debug Log

```
Dev App Server is now running.

 {"metadata":{"emulator":{"name":"firestore"},"message":"\n\nDev App Server is now running.\n\n"}}
[info] i  auth: Importing config from /Users/moozeire/Programs/Web/CrossWord/proto/firebox/auth_export/config.json {"metadata":{"emulator":{"name":"database"},"message":"Importing config from /Users/moozeire/Programs/Web/CrossWord/proto/firebox/auth_export/config.json"}}
[info] i  auth: Importing accounts from /Users/moozeire/Programs/Web/CrossWord/proto/firebox/auth_export/accounts.json {"metadata":{"emulator":{"name":"database"},"message":"Importing accounts from /Users/moozeire/Programs/Web/CrossWord/proto/firebox/auth_export/accounts.json"}}
[debug] [2022-02-12T12:33:03.029Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"storage"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-02-12T12:33:03.247Z] Temp file directory for storage emulator: /var/folders/f0/nh2dwc3j0dl1nfzsr_h_kr4w0000gt/T/firebase/storage/blobs {"metadata":{"emulator":{"name":"storage"},"message":"Temp file directory for storage emulator: /var/folders/f0/nh2dwc3j0dl1nfzsr_h_kr4w0000gt/T/firebase/storage/blobs"}}
[debug] [2022-02-12T12:33:04.109Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-02-12T12:33:04.109Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-02-12T12:33:04.109Z] Starting Emulator UI with command {"binary":"node","args":["/Users/moozeire/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/moozeire/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2022-02-12T12:33:04.249Z] Web / API server started at localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at localhost:4000\n"}}
[info] 

  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

[debug] [2022-02-12T12:33:05.850Z] Feb 12, 2022 12:33:05 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Feb 12, 2022 12:33:05 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[debug] [2022-02-12T12:33:05.886Z] Feb 12, 2022 12:33:05 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
 {"metadata":{"emulator":{"name":"firestore"},"message":"Feb 12, 2022 12:33:05 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel\nINFO: Connected to new websocket client\n"}}
[debug] [2022-02-12T12:33:34.785Z] Feb 12, 2022 12:33:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Feb 12, 2022 12:33:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[debug] [2022-02-12T12:33:35.832Z] Feb 12, 2022 12:33:35 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Feb 12, 2022 12:33:35 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[debug] [2022-02-12T12:34:22.306Z] Error: EISDIR: illegal operation on a directory, open '/var/folders/f0/nh2dwc3j0dl1nfzsr_h_kr4w0000gt/T/firebase/storage/blobs/crossword-devotional.appspot.com/images/2022/January'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at Object.appendFileSync (node:fs:2215:6)
    at Persistence.appendBytes (/Users/moozeire/.config/yarn/global/node_modules/firebase-tools/lib/emulator/storage/files.js:456:16)
    at StorageLayer.oneShotUpload (/Users/moozeire/.config/yarn/global/node_modules/firebase-tools/lib/emulator/storage/files.js:216:27)
    at handleUpload (/Users/moozeire/.config/yarn/global/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:291:37)
    at Layer.handle [as handle_request] (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)
    at /Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:281:22
    at param (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/moozeire/.config/yarn/global/node_modules/express/lib/router/index.js:275:10)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by yuchenshi** [comment]
Did you mean *Storage* emulator instead of Firestore? How are you uploading the file? via Emulator UI or SDK (what platform and version)?

Also, would you mind sharing your OS and version? Are you using a M1 Macbook by any chance?

**Comment by moses-20** [comment]
Oh sorry, I meant the Storage emulator

But I think I found the problem. 
I had the emulator exports folder hidden with VS Code settings. 

It works now.
