### ISSUE TITLE
firebase projects:list fails with error

### ISSUE THREAD

**Issue by quantuminformation** [firebase/firebase-tools#4176]
Trying to start a new project and installed firebase tools

### [REQUIRED] Environment info

firebase-tools: 10.2.0

Platform: MacOS JavaScript sdk

### [REQUIRED] Test case

trying to generate project or list after I logged in from the cli

### [REQUIRED] Steps to reproduce
git:(master) ✗ firebase projects:list
✖ Preparing the list of your Firebase projects

Error: Failed to list Firebase projects. See firebase-debug.log for more info.

### [REQUIRED] Actual behavior

logs:

```
info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2022-02-16T21:34:39.924Z] > refreshing access token with scopes: []
[debug] [2022-02-16T21:34:39.925Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2022-02-16T21:34:40.063Z] <<< HTTP RESPONSE 400 {"pragma":"no-cache","date":"Wed, 16 Feb 2022 21:34:40 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","expires":"Mon, 01 Jan 1990 00:00:00 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2022-02-16T21:34:40.066Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2022-02-16T21:34:40.175Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 401
[debug] [2022-02-16T21:34:40.175Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2022-02-16T21:34:40.176Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2022-02-16T21:34:40.177Z] FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at module.exports (/Users/nikos/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at RetryOperation._fn (/Users/nikos/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/lib/apiv2.js:283:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.

```

**Comment by bkendall** [comment]
Can you try re-logging in with `firebase login --reauth` and try this again? Seems like your auth/refresh token might be invalid.

**Comment by quantuminformation** [comment]
thanks, that fixed it

**Comment by quantuminformation** [comment]
did you get my BAT tip @bkendall ?

**Comment by bigfish** [comment]
Ran into this as well and spent half an hour googling to find this solution. Perhaps the docs should be updated, or the solution suggested when the CLI auth fails?
