### ISSUE TITLE
Firestore emulator crash on export with ~0.5 GB of data

### ISSUE THREAD

**Issue by samborambo305** [firebase/firebase-tools#4336]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** macOS

### [REQUIRED] Test case

See below

### [REQUIRED] Steps to reproduce

Export ~0.56GB of data for the firebase emulator. The emulator crashes and fails to export due to running out of buffer memory. My machine has 64GB ram so this should not be an issue

### [REQUIRED] Expected behavior

Export completes successfully

### [REQUIRED] Actual behavior

Export crashes with following error:
```
WARNING: Server fails to send the message, abort the channel!
Mar 18, 2022 12:55:25 PM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreListenHandler onError
WARNING: [ERROR] NETWORK_ERROR ()
Mar 18, 2022 12:55:25 PM com.google.net.webchannel.server.v8.BackChannel add
WARNING: Failed to send a new message due to too many pending messagings in the back channel (10001). May need enable flow control.
Mar 18, 2022 12:55:25 PM com.google.net.webchannel.server.v8.ChannelInternalImpl handle
WARNING: Server fails to send the message, abort the channel!
Mar 18, 2022 12:55:25 PM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreListenHandler onError

<this is repeated for 1.762 million lines>


Mar 18, 2022 1:08:36 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: null
java.nio.BufferOverflowException
    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:211)
    at com.google.cloud.datastore.emulator.impl.LevelDBLogWriterChannel.writePhysicalRecord(LevelDBLogWriterChannel.java:154)
    at com.google.cloud.datastore.emulator.impl.LevelDBLogWriterChannel.write(LevelDBLogWriterChannel.java:77)
    at com.google.cloud.datastore.emulator.impl.LevelDBLogWriterChannel.write(LevelDBLogWriterChannel.java:56)
    at com.google.cloud.datastore.emulator.impl.ExportImportUtil.writeEntitiesToFile(ExportImportUtil.java:182)
    at com.google.cloud.datastore.emulator.impl.ExportImportUtil.exportEntitiesForSpec(ExportImportUtil.java:157)
    at com.google.cloud.datastore.emulator.impl.ExportImportUtil.exportEntities(ExportImportUtil.java:89)
    at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.exportData(CloudFirestoreV1.java:688)
    at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.exportData(CloudFirestoreV1Router.java:206)
    at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter$1.lambda$exportData$3(EmulatorAuxiliaryGrpcAdapter.java:98)
    at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter.unary(EmulatorAuxiliaryGrpcAdapter.java:49)
    at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter.access$000(EmulatorAuxiliaryGrpcAdapter.java:28)
    at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter$1.exportData(EmulatorAuxiliaryGrpcAdapter.java:95)
    at com.google.firestore.emulator.v1.FirestoreEmulatorGrpc$MethodHandlers.invoke(FirestoreEmulatorGrpc.java:631)
    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
    at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
    at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)

Mar 18, 2022 1:08:36 PM io.gapi.emulators.netty.HttpHandler$1 onError
INFO: Exception when handling request: UNKNOWN
*** shutting down gRPC server since JVM is shutting down
*** server shut down
```

**Comment by evelant** [comment]
I've found a similar thing with trying to import a 1.5gb production database for local debugging. The emulators just choke even though my machine has 64gb of ram. I opened an issue about it but unfortunately the resolution was "the emulators can't do that". https://github.com/firebase/firebase-tools/issues/3929

**Comment by jakeleventhal** [comment]
i have 64gb of ram and have the same issue. the emulator ought to support this or at least support a flag to give users the option to specify the size of the process to override the defaults

**Comment by evelant** [comment]
IIRC I tried changing java options to give the process much more ram but larger data sets seem to trigger a bug where it just eats up all available memory then crashes or hangs. I gave it something like 32gb for a 1.5gb data set and it still hung the same way as the default memory limit. For some reason the emulator is incapable of loading a larger data set no matter how many resources it is given.

**Comment by yuchenshi** [comment]
FYI the JVM behavior for Firestore Emulator can be tweaked using an environment variable, such as `export JAVA_TOOL_OPTIONS="-Xmx4g"` before starting the emulators. Please try with larger heap sizes and all that -- and let us know if it still fails with more RAM. (We're still working to document this env var. See #2521 for previous discussion)

**Comment by evelant** [comment]
@yuchenshi in https://github.com/firebase/firebase-tools/issues/3929 I tried it with -Xmx48g on my machine with 64gb of ram on a 1.5gb data set... It filled 48gb of ram then failed. There's seemingly a bug that once an import reaches a certain size the emulator gets "stuck" and just continues allocating memory until it runs out and crashes no matter how much you give it.

**Comment by yuchenshi** [comment]
@evelant Thanks for the reply. In order to pinpoint the issue, it'd be great if we can look into the particular dump you're trying to import. Would you mind contacting [Firebase Support](https://firebase.google.com/support) where you can privately share your exports file for reproducing the bug?

**Comment by jakeleventhal** [comment]
@evelant @yuchenshi let me know the result of this. I can't send over my data because it contains sensitive information

**Comment by jakeleventhal** [comment]
I was able to recreate the issue with the following snippet in Node:
```javascript
const createDay = (
  id,
  marketplace,
  cogs,
  estimatedFees,
  sales,
  cancels,
  orders,
  units,
  storageFees,
  date,
  productId
) => {
  const dayObject = {
    AtoZClaims: {
      AmazonFees: {},
      Other: {},
      ProductCharges: 0
    },
    Orders: {
      AmazonFees: {
        Commission: 0,
        EstimatedFees: 0,
        FBAPerOrderFulfillmentFee: 0,
        FBAPerUnitFulfillmentFee: 0,
        FBAWeightBasedFee: 0,
        NonAmazonFBAPerUnitFulfillmentFee: 0,
        Other: {}
      },
      Other: {},
      ProductCharges: 0,
      PromoRebates: {
        Orders: 0,
        Shipping: 0
      }
    },
    OtherTransactions: {},
    PaidToAmazon: {},
    PostedOrders: {
      AmazonFees: {
        Commission: 0,
        EstimatedFees: 0,
        FBAPerOrderFulfillmentFee: 0,
        FBAPerUnitFulfillmentFee: 0,
        FBAWeightBasedFee: 0,
        NonAmazonFBAPerUnitFulfillmentFee: 0,
        Other: {}
      },
      Other: {},
      ProductCharges: 0,
      PromoRebates: {
        Orders: 0,
        Shipping: 0
      }
    },
    Refunds: {
      AmazonFees: {},
      Other: {},
      ProductCharges: 0,
      PromoRebates: {
        Orders: 0,
        Shipping: 0
      }
    },
    SellingFees: {
      CostOfAdvertising: 0,
      FBAFees: {},
      Other: {
        Coupons: 0
      }
    },
    ShippingServices: {},
    Ads: {
      Clicks: 0,
      Conversions: 0,
      Cost: 0,
      Impressions: 0,
      Sales: 0,
      Units: 0
    },
    COGS: cogs,
    Counts: {
      CanceledOrders: cancels,
      Orders: orders,
      RefundedUnits: 0,
      ShippedOrders: 0,
      ShippedUnits: 0,
      Units: units
    },
    Date: date,
    FIFOCOGS: 0,
    Marketplace: marketplace,
    ProductData: productId
      ? {
        HasProduct: true,
        ProductId: productId
      }
      : null,
    ShippedCOGS: 0,
    StorageFees: storageFees,
    UserId: id
  };
  dayObject.Orders.AmazonFees.EstimatedFees = Number(estimatedFees);
  dayObject.Orders.ProductCharges += sales;

  return dayObject;
};

const { v4: uuid } = require('uuid');

for (let i = 0; i < 7500; i++) {
  console.log(i);
  await Promise.all([...Array(100)].map(async (value, j) => {
    const collection = `TestCollection${j % 15}`;
    await firestore.collection(collection).doc(uuid()).set(createDay(
      'testid',
      'asdf',
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      '2020-02-02',
      'testid'
    ));
  }));
}
```

After all 7500 loop iterations complete I get the following firestore-debug.log
```
Mar 29, 2022 10:34:11 AM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketServer start
INFO: Started WebSocket server on ws://localhost:54165
API endpoint: http://localhost:9000
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:9000

Dev App Server is now running.

Mar 29, 2022 10:34:16 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Mar 29, 2022 10:38:52 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Mar 29, 2022 10:38:52 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Mar 29, 2022 10:41:51 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Mar 29, 2022 10:43:31 AM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
  at java.lang.StringCoding.encode(StringCoding.java:350)
  at java.lang.String.getBytes(String.java:941)
  at com.google.cloud.datastore.core.rep.converter.ConverterHelper.convertStringToBytes(ConverterHelper.java:98)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.addProperty(AppEngV3EntityFromRepConverter.java:65)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.convertMapToEntity(AppEngV3EntityFromRepConverter.java:57)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.convertValue(AppEngV3EntityFromRepConverter.java:192)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.addSingleProperty(AppEngV3EntityFromRepConverter.java:91)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.addProperty(AppEngV3EntityFromRepConverter.java:79)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.convertMapToEntity(AppEngV3EntityFromRepConverter.java:57)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.convertEntity(AppEngV3EntityFromRepConverter.java:35)
  at com.google.cloud.datastore.core.appengv3.converter.AppEngV3EntityFromRepConverter.convertEntityUnchecked(AppEngV3EntityFromRepConverter.java:28)
  at com.google.cloud.datastore.emulator.impl.util.FirestoreEmulatorConverters.entityToProto(FirestoreEmulatorConverters.java:300)
  at com.google.cloud.datastore.emulator.impl.util.FirestoreEmulatorConverters.entityToProto2(FirestoreEmulatorConverters.java:304)
  at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.lambda$exportData$16(CloudFirestoreV1.java:758)
  at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1$$Lambda$1287/780587234.apply(Unknown Source)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
  at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.exportData(CloudFirestoreV1.java:759)
  at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1Router.exportData(CloudFirestoreV1Router.java:215)
  at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter$1.lambda$exportData$3(EmulatorAuxiliaryGrpcAdapter.java:98)
  at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter$1$$Lambda$1282/1298309044.process(Unknown Source)
  at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter.unary(EmulatorAuxiliaryGrpcAdapter.java:49)
  at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter.access$000(EmulatorAuxiliaryGrpcAdapter.java:28)
  at com.google.cloud.datastore.emulator.firestore.EmulatorAuxiliaryGrpcAdapter$1.exportData(EmulatorAuxiliaryGrpcAdapter.java:95)
  at com.google.firestore.emulator.v1.FirestoreEmulatorGrpc$MethodHandlers.invoke(FirestoreEmulatorGrpc.java:631)
  at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
  at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)

Mar 29, 2022 10:43:31 AM io.gapi.emulators.netty.HttpHandler$1 onError
INFO: Exception when handling request: UNKNOWN
```

**Comment by yuchenshi** [comment]
@jakeleventhal  May I ask if you've tried with the memory flags? If so, how much heap space did you start it with?

**Comment by joehan** [comment]
@AndreasJJ Would you be able to provide a repro for that BufferOverflowException? This would help the Firestore team identify what's going wrong here.

Additionally, are you using a Mac with Intel chips or an M1 Mac?

**Comment by AndreasJJ** [comment]
@joehan

I am using a Intel chip Mac.

So i tried to create a new repo for repro, where i simply copied the entire firebase folder into the new repo. In addition to changing the project id to a new project (as i didnt want my original project id to be shown in a public repo). However trying to edit the dataset in the new repo (which should have the exact same state as the one throwing the BufferOverflowException) doesn't end with an export error. As such i wonder if the error might have something to do with whatever files and states firebase saves locally on my computer that is associated with my original project id.

**Comment by jakeleventhal** [comment]
@joehan @yuchenshi i am using m1 mac
