### ISSUE TITLE
`CLOUD_RUNTIME_CONFIG` is not detected as expected on firebase (>= 10.2) emulator starts

### ISSUE THREAD

**Issue by daenamkim** [firebase/firebase-tools#4382]
### [REQUIRED] Environment info

**firebase-tools:**

```sh
firebase --version
10.5.0
```

**Platform:**

- macOS (Monterey 12.3 (21E230))
- Apple M1 Pro

### [REQUIRED] Test case

_index.ts_

```ts
import * as admin from "firebase-admin";
import * as functions from "firebase-functions";

const { app_options: appOptions } = functions.config();

console.log("!!!!!!!!!", appOptions);

admin.initializeApp({
  storageBucket: appOptions.storage_bucket,
});
```

_package.json_
```json
"test": "yarn build && CLOUD_RUNTIME_CONFIG='.runtimeconfig.test.json' TZ=UTC firebase emulators:exec --project demo-project --only auth,functions,firestore,storage,hosting 'mocha --exit --require ts-node/register --require ./test/mocha-hooks.ts --reporter spec \"./test/**/*.test.ts\"'",
```

_.runtimeconfig.test.json_
```json
{
  "app_options": {
    "storage_bucket": "demo-project.appspot.com"
  }
}
```

_.runtimeconfig.json_
```json
{
  "app_options": {
    "storage_bucket": "foo"
  }
}
```

### [REQUIRED] Steps to reproduce

- Remove `.runtimeconfig.json` (or rename it to the different e.g .runtimeconfig.jsonxyz) 
- Run `yarn test`

### [REQUIRED] Expected behavior

It should print:

```sh
!!!!!!!!! { storage_bucket: 'demo-project.appspot.com' }
```

and test works.

### [REQUIRED] Actual behavior

```sh
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read properties of undefined (reading 'storage_bucket')
    at Object.<anonymous> (/Users/daenamkim/Developments/workspace/curvegrid/nfteapot/functions/lib/index.js:35:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (/Users/daenamkim/.config/yarn/global/node_modules/firebase-tools/lib/deploy/functions/runtimes/node/triggerParser.js:10:16)
    at /Users/daenamkim/.config/yarn/global/node_modules/firebase-tools/lib/deploy/functions/runtimes/node/triggerParser.js:34:21
    at Object.<anonymous> (/Users/daenamkim/.config/yarn/global/node_modules/firebase-tools/lib/deploy/functions/runtimes/node/triggerParser.js:72:3)
error Command failed with exit code 1.
```

BUT if I let both  `.runtimeconfig.test.json` and `.runtimeconfig.json` and run `yarn test` it works as expected:

```sh
!!!!!!!!! { storage_bucket: 'demo-project.appspot.com' }
```

Note that `storage_bucket` is NOT `foo` but `demo-project.appspot.com`. This is the part that I could not understand at all.
This issue was not happening `firebase-tools@10.1.5` so I guess something has been changed in the higher version. 🤔

**Comment by trex-quo** [comment]
I have had this issue repeatedly as well and cannot upgrade my package to 10.2 or above.

**Comment by dahu33** [comment]
@taeold any update on this? It's broken since firebase-tools v10.2.0 so we are stuck on a old version which has other bugs... We would appreciate a solution.

**Comment by ishowta** [comment]
> Configuration specfied in runtimeconfig is not available during trigger parsing time.

Which timing do you mean by "trigger parsing time"? At least the following code that dynamically specifies minInstances at deploy time works in a latest packages in both deployed and emulated environments.

```typescript
import * as functions from "firebase-functions";

export const helloWorld = functions.runWith({
  minInstances: functions.config().functions.env === 'development' ? 1 : 2
}).https.onCall(() => {
  return "Hello from Firebase!";
});
```
