### ISSUE TITLE
Failed to list Firebase projects even using firebase login --reauth

### ISSUE THREAD

**Issue by MansonLuo** [firebase/firebase-tools#4394]
### [REQUIRED] Environment info

**firebase-tools:**
version 10.5.0

**Platform:**
windows 11.

### [REQUIRED] Test case

p> firebase init
cannot list projects

p> firebase login --reauth
p> firebase projects:list
cannot list projects.
### [REQUIRED] Steps to reproduce

i configured proxy using v2ray.
### # 2. modify request.js in ...\node_global\node_modules\firebase-tools\node_modules\request
modify the code at 277 lines from
```javascript
if (!self.hasOwnProperty('proxy')) {
	self.proxy = getProxyFromURI(self.uri)
}
```
to
```javascript
// if (!self.hasOwnProperty('proxy')) {
//   self.proxy = getProxyFromURI(self.uri)
// }
self.proxy = "http://127.0.0.1:1087";  // this is your proxy addres
```

### #3. login
```shell
> firebase login --no-localhost
......
   loggin success.
```

### #4. init (failed)
```shell
> firebase init

......
Error: Failed to list Firebase projects. See firebase-debug.log for more info
```

following is content of firebase-debug.log
```javascript
You're about to initialize a Firebase project in this directory:

  F:\Projects\Web\frontend

[info] 
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2022-04-03T11:21:45.937Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2022-04-03T11:22:06.994Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
[debug] [2022-04-03T11:22:07.155Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=100
    at RetryOperation._fn (D:\Nodejs\node_global\node_modules\firebase-tools\lib\apiv2.js:240:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

### #5: tried solution 1 (failed)
```shell
> firebase login --reauth
...
success.

> firebase projects:list
......
Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

following is content of firebase-debug.log
```javascript
[debug] [2022-04-03T11:55:08.118Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-04-03T11:55:08.119Z] > authorizing via signed-in user (mansonluolks@gmail.com)
[debug] [2022-04-03T11:55:08.125Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2022-04-03T11:55:29.206Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
[debug] [2022-04-03T11:55:29.368Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
    at RetryOperation._fn (D:\Nodejs\node_global\node_modules\firebase-tools\lib\apiv2.js:240:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

### #6 tried sollution 2 (still failed)
```shell
> firebase logout

> firebase login --no-localhost
> set FIREBASE_TOKEN= 4/0AX4XfWgV97x3Qz5RDCIbd_hg3UJbUrszuo4TGRoobz10SeHgShlYw (authorization code)
> firebase projects:list
.....
Error: Failed to list Firebase projects. See firebase-debug.log for more info
```

the content of firebase-debug.log is still similar.

```javascript
[debug] [2022-04-03T12:04:51.305Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-04-03T12:04:51.306Z] > authorizing via FIREBASE_TOKEN environment variable
[debug] [2022-04-03T12:04:51.310Z] > refreshing access token with scopes: []
[debug] [2022-04-03T12:04:51.311Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2022-04-03T12:04:53.400Z] <<< HTTP RESPONSE 400 {"date":"Sun, 03 Apr 2022 12:04:53 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2022-04-03T12:04:53.403Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2022-04-03T12:05:14.501Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
[debug] [2022-04-03T12:05:14.679Z] FirebaseError: Failed to make request to https://firebase.googleapis.com/v1beta1/projects?pageSize=1000
    at RetryOperation._fn (D:\Nodejs\node_global\node_modules\firebase-tools\lib\apiv2.js:240:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
```

### [REQUIRED] Expected behavior
firebase init success.

### [REQUIRED] Actual behavior
firebase init failed, firebase projects:list failed.

**Comment by yuchenshi** [comment]
Hi, thanks for reaching out! This sounds like a network issue and please make sure you can reach the Firebase servers from your network.
