### ISSUE TITLE
Doesn't work on node 10.x anymore

### ISSUE THREAD

**Issue by Igor10k** [firebase/firebase-tools#448]
`google-auto-auth` starting with version `0.7.0` requires `node >= v4`. So either the dependency should be downgraded or minimum `node` version requirement for `firebase-tools` should be updated to `v4`.

### error stack

```
firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --non-interactive

/home/ubuntu/nvm/v0.10.33/lib/node_modules/firebase-tools/node_modules/google-auto-auth/index.js:10
class Auth {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/nvm/v0.10.33/lib/node_modules/firebase-tools/lib/requireAuth.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Igor10k** [comment]
`tar` starting with version `3.0.0` requires `node ^4.5.0` or `node >= 5.10.0` because of the usage of `Buffer.alloc`. Either downgrade the `tar` dependency or update the `node` version requirement for `firebase-tools`.

### error stack

```
firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --non-interactive
/home/ubuntu/nvm/versions/node/v5.1.0/lib/node_modules/firebase-tools/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/home/ubuntu/nvm/versions/node/v5.1.0/lib/node_modules/firebase-tools/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ubuntu/nvm/versions/node/v5.1.0/lib/node_modules/firebase-tools/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```
