### ISSUE TITLE
Crash regression in storage emulator with StorageReference.put and empty buffer

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-tools#4547]
Hi there, I work with Invertase to maintain [react-native-firebase](https://github.com/invertase/react-native-firebase), and I've noticed a regression in the latest version(s) of the storage emulator. We are going to work around it locally by disabling one of our test cases but it would be great to fix it here upstream from us, so I thought I'd send all the details I've got.

Let me know if there is any piece of information I could provide to help, if this doesn't contain enough

### [REQUIRED] Environment info

10.9.2 (current stable)

macOS 11.6.5

### [REQUIRED] Test case

Reproduced in react-native-firebase on both iOS and Android platforms - indicating it doesn't seem to matter if we are going through firebase-android-sdk or firebase-ios-sdk

Test case is here:

- instructions to execute (it's pretty automated): https://github.com/invertase/react-native-firebase/blob/main/tests/README.md
- failing test case: https://github.com/invertase/react-native-firebase/blob/42f6d96313cb193ae7918c72622c6a75e945570a/packages/storage/e2e/StorageReference.e2e.js#L615-L628

You can replace `it` with `it.only` to run just that test in combination with for example `yarn tests:ios:test-reuse` to really quickly iterate and crash the storage emulator

### [REQUIRED] Steps to reproduce

This is the exact code - but the whole open source repo above makes the case easily executable per linked instructions above

```javascript
    xit('allows valid metadata properties for upload', async function () {
      const storageReference = firebase.storage().ref(`${PATH}/metadataTest.jpeg`);
      await storageReference.put(new jet.context.window.ArrayBuffer(), {
        contentType: 'image/jpg',
        md5hash: '123412341234',
        cacheControl: 'true',
        contentDisposition: 'disposed',
        contentEncoding: 'encoded',
        contentLanguage: 'martian',
        customMetadata: {
          customMetadata1: 'metadata1value',
        },
      });
    });
```

Note: the ArrayBuffer with no parameter gets you a length-zero buffer: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer

### [REQUIRED] Expected behavior

No crash, and the put works - it worked as recently as firebase-tools v10.2.2, I'm not sure which version it started to fail but it was as early as 10.7

### [REQUIRED] Actual behavior

Crash:

```
[2022-05-16T17:58:51.773Z] Error: ENOENT: no such file or directory, open '/var/folders/wt/93w7tbwn00x276758j3lksz80000gn/T/firebase/storage/blobs/daaf0829-ab56-4e75-a082-3a6fa92a8dfa_b_react-native-firebase-testing.appspot.com_o_react-native-tests%252F1652723926474%252FmetadataTest.jpeg'
    at openSync (node:fs:585:3)
    at Persistence.readBytes (/Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/persistence.js:37:36)
    at StorageLayer.uploadObject (/Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/files.js:157:52)
    at handleUpload (/Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:302:53)
    at handleObjectPostRequest (/Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:387:16)
    at /Users/mike/work/Invertase/react-native-firebase/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:423:24
    at Layer.handle [as handle_request] (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:281:22
    at param (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:360:14)
    at param (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:371:14)
    at param (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:416:3)
    at next (/Users/mike/work/Invertase/react-native-firebase/node_modules/express/lib/router/index.js:275:10)

Error: An unexpected error has occurred.
```

**Comment by tonyjhuang** [comment]
@abhis3 can you see if this is related to https://github.com/firebase/firebase-tools/pull/4278?

**Comment by mikehardy** [comment]
Failure starts at 10.3.0, working correctly at 10.2.2

**Comment by mikehardy** [comment]
Still happening on current version 11.1.0

**Comment by tonyjhuang** [comment]
Filed internal bug to track, b/240585809

**Comment by tonyjhuang** [comment]
Hi @mikehardy I've tried running the commands in https://github.com/invertase/react-native-firebase/blob/main/tests/README.md but they're failing with the following error message:

```
% yarn tests:android:test                                              15:25:31

yarn run v1.22.19
$ cd tests && yarn detox test --configuration android.emu.debug
$ /Users/tonyjhuang/dev/react-native-firebase/tests/node_modules/.bin/detox test --configuration android.emu.debug
15:25:38.162 detox[82189] INFO:  [test.js] mocha --config e2e/.mocharc.js --configuration android.emu.debug --grep :ios: --invert --use-custom-logger true e2e


15:25:48.074 detox[82190] ERROR: [EXEC_FAIL, #29] ""/Users/tonyjhuang/Library/Android/sdk/platform-tools/adb" -s emulator-17912 shell "ps | grep \"com\.invertase\.testing$\""" failed with error = ChildProcessError: Command failed: "/Users/tonyjhuang/Library/Android/sdk/platform-tools/adb" -s emulator-17912 shell "ps | grep \"com\.invertase\.testing$\""
 `"/Users/tonyjhuang/Library/Android/sdk/platform-tools/adb" -s emulator-17912 shell "ps | grep \"com\.invertase\.testing$\""` (exited with error code 1) (code=1), stdout and stderr:
```

Admittedly I'm not very familiar with the react native dev environment, although reading the test case, it should be semantically equivalent to the following call to the JS SDK equivalent:

```
firebase.storage().ref("testing/empty_file").put(new ArrayBuffer(0));
```

Would you say that's accurate?

**Comment by tonyjhuang** [comment]
I've added a new test case to our integration test suite in https://github.com/firebase/firebase-tools/pull/4841

**Comment by tonyjhuang** [comment]
From that same readme, ios pod install seems to work: `yarn tests:ios:pod:install`

But failing to build ios tests: 

```
% yarn tests:ios:build                                                 16:15:59

yarn run v1.22.19
$ cd tests && yarn detox build --configuration ios.sim.debug
$ /Users/tonyjhuang/dev/react-native-firebase/tests/node_modules/.bin/detox build --configuration ios.sim.debug
16:16:26.348 detox[73007] INFO:  [build.js] set -o pipefail && xcodebuild VALID_ARCHS="`uname -m`"  CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ -workspace ios/testing.xcworkspace -scheme testing -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build | xcbeautify
/bin/sh: xcbeautify: command not found
2022-08-08 16:16:27.089 xcodebuild[73009:1138891] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-08-08 16:16:27.089 xcodebuild[73009:1138891] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:FE24A259-F5E9-484F-B630-69B66BDE6608, OS:15.5, name:iPhone 8 }
{ platform:iOS Simulator, id:852AC042-1119-443B-A43F-C2A3643D4643, OS:15.5, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:A16C09D3-3773-458E-B892-DCBA7EFBA5FE, OS:15.5, name:iPhone 11 }
{ platform:iOS Simulator, id:BF98183F-B0CA-4A05-BD98-CEA0BA2AAB87, OS:15.5, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:83DAE39F-3ED3-4340-9E34-E59199F1AFEF, OS:15.5, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:3227CDC3-A381-4E11-AAF5-18321FB783C2, OS:15.5, name:iPhone 12 }
{ platform:iOS Simulator, id:00A6DA11-AFF8-4CA7-AB69-4772055F5AB2, OS:15.5, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:AD94EBF1-9C61-4F68-95A7-27B0762CD0EA, OS:15.5, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:766ABBA4-30BB-4C0D-A09D-D97BE4E0E4E8, OS:15.5, name:iPhone 12 mini }
{ platform:iOS Simulator, id:15DED65A-3B99-41EB-BD31-E0C99A545C36, OS:15.5, name:iPhone 13 }
{ platform:iOS Simulator, id:CB95500E-B00B-4664-9957-FA547BCEB271, OS:15.5, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:FE9CCDB4-47D4-444D-A0ED-F3258B3E2D0C, OS:15.5, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:F01888A2-8DBE-41D7-8882-969964E80E36, OS:15.5, name:iPhone 13 mini }
{ platform:iOS Simulator, id:35480C3E-7318-448E-BA13-B3E130745B39, OS:15.5, name:iPhone SE (3rd generation) }
{ platform:iOS Simulator, id:D3AC76F8-8B46-4378-AEF3-1338D4471FFA, OS:15.5, name:iPod touch (7th generation) }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:B86FECFA-0219-4A85-8A6C-2406711DF2EC, OS:15.5, name:iPad (9th generation) }
{ platform:iOS Simulator, id:154700BE-892C-46D1-9A90-CB5BE4494495, OS:15.5, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:DACDE592-6CCA-41C2-8F30-3859AFDA16F0, OS:15.5, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:48BF2C99-5610-40C6-942C-0EB206348A6B, OS:15.5, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:AD4D98CD-A17E-49C7-A158-0AC87CC4E253, OS:15.5, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:A7EFE086-EE55-4124-915F-D49A315B0A45, OS:15.5, name:iPad mini (6th generation) }
16:23:07.232 detox[73007] WARN:  [build.js] 

Important: 'detox build' is a convenience shortcut for calling your own build command, as provided in the config file.
Failures in this build command are not the responsibility of Detox. You are responsible for maintaining this command.

16:23:07.234 detox[73007] ERROR: [cli.js] Command failed: set -o pipefail && xcodebuild VALID_ARCHS="`uname -m`"  CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ -workspace ios/testing.xcworkspace -scheme testing -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build | xcbeautify

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Yuangwang** [comment]
Hi @mikehardy I just pushed a fix to a similar issue (https://github.com/firebase/firebase-tools/pull/4843) where the emulator was crashing with the same error that you see when an empty buffer was uploaded from the android sdks. Please keep an eye out for the new release and give it another try once the change gets shipped!

**Comment by Yuangwang** [comment]
New update was just released! please give it a try and see if this issue is still there

**Comment by mikehardy** [comment]
@tonyjhuang really sorry for the delayed reply, I've been traveling and only just saw these. I really appreciate the effort giving our test suite a try! I'm sorry it did not work out from you. I do work from clean environments semi-frequently but there must be something missing with regards to checking for + validating environment before the run starts. On the android side it looks like maybe the emulator was not created + running, and on the ios side perhaps there was a utility missing (maybe xcbeautify...).

I'll work through those issues on our side to make sure tests do in fact run correctly from scratch using our instructions

Either way, I can say congratulations to you and @Yuangwang because I have updated to firebase-tools v11.6.0 and this seems to work now! So I believe this issue is closed
