### ISSUE TITLE
firebase serve --only functions works only with chmod change to global functions-emulator

### ISSUE THREAD

**Issue by stardotbmp** [firebase/firebase-tools#455]
### Version info

3.10.1

### Steps to reproduce

`firebase serve --only functions`

### Expected behavior

firebase functions should be emulated

```
$ firebase serve --only functions

=== Serving from '/Users/{user}/{path}'...

i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
✔  functions: bcf: http://localhost:5000/{project_id}/us-central1/{function}
✔  functions: bcf: http://localhost:5000/{project_id}/us-central1/{function}
```

### Actual behavior

```
$ firebase serve --only functions --debug
[2017-09-11T13:10:47.014Z] ----------------------------------------------------------------------
[2017-09-11T13:10:47.017Z] Command:       /usr/local/share/npm/lib/node_modules/node/bin/node /usr/local/share/npm/bin/firebase serve --only functions --debug
[2017-09-11T13:10:47.018Z] CLI Version:   3.10.1
[2017-09-11T13:10:47.018Z] Platform:      darwin
[2017-09-11T13:10:47.018Z] Node Version:  v6.11.1
[2017-09-11T13:10:47.019Z] Time:          Mon Sep 11 2017 14:10:47 GMT+0100 (BST)
[2017-09-11T13:10:47.019Z] ----------------------------------------------------------------------

[2017-09-11T13:10:47.036Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2017-09-11T13:10:47.036Z] > authorizing via signed-in user
[2017-09-11T13:10:47.039Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/bcf-test-58aad
 Mon Sep 11 2017 14:10:47 GMT+0100 (BST)
[2017-09-11T13:10:47.702Z] <<< HTTP RESPONSE 200 server=nginx, date=Mon, 11 Sep 2017 13:10:47 GMT, content-type=application/json; charset=utf-8, content-length=111, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2017-09-11T13:10:47.703Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/bcf-test-58aad/tokens
 Mon Sep 11 2017 14:10:47 GMT+0100 (BST)
[2017-09-11T13:10:48.517Z] <<< HTTP RESPONSE 200 server=nginx, date=Mon, 11 Sep 2017 13:10:48 GMT, content-type=application/json; charset=utf-8, content-length=263, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Serving from '/Users/jonathon.broughton/Documents/bcf-test'...

i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
[2017-09-11T13:10:49.046Z] Error: EACCES: permission denied, mkdir '/usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.assertLogsPath (/usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:85:32)
    at Object._startEmulator [as start] (/usr/local/share/npm/lib/node_modules/firebase-tools/lib/serve/functions.js:88:16)
    at /usr/local/share/npm/lib/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/share/npm/lib/node_modules/firebase-tools/lib/serve/index.js:14:21)
    at Command._action (/usr/local/share/npm/lib/node_modules/firebase-tools/commands/serve.js:42:12)

Error: An unexpected error has occurred.
```

**Comment by stardotbmp** [comment]
Normal behaviour is possible after
```
chmod u=rwx,g=rx,o=r /usr/local/share/npm/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator
```
But this seems to be an unnecessary undocumented step.

**Comment by laurenzlong** [comment]
I think this is due to defaults you have on your computer, since we've never had reports like this before. Are you able to check out the permissions of the directories that contain your other installed node modules to see if they are also read only?

**Comment by stardotbmp** [comment]
possibly. everything is nigh on unchanged from base osx install. i've changed ownership of the npm prefix as all npm was being run as sudo - perhaps that'll help
