### ISSUE TITLE
Cant call firebase at all, always returns TypeError: dns.setDefaultResultOrder is not a function

### ISSUE THREAD

**Issue by readyiman** [firebase/firebase-tools#4580]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.0

**Platform:** Windows

### [REQUIRED] Test case

npm update from version 10.9.2

### [REQUIRED] Steps to reproduce

npm update from version 10.9.2

### [REQUIRED] Expected behavior

Can call firebase

### [REQUIRED] Actual behavior

Any firebase call returns to this:

C:\Users\Redi\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\portUtils.js:9
dns.setDefaultResultOrder("ipv4first");
    ^

TypeError: dns.setDefaultResultOrder is not a function
    at Object.<anonymous> (C:\Users\Redi\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\portUtils.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\Redi\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\registry.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)

**Comment by readyiman** [comment]
Solved by updating node to v16.15.0 LTS (was 16.something before). 
I'll keep this open, because firebase didn't say this as minimum requirement.

**Comment by readyiman** [comment]
@timstoute I'm pretty sure I didn't do anything else. Just download node from it site then just install it. Maybe, just maybe, had you try `npm audit fix` on your firebase folder? (honestly, I'm still wondering why for every firebase npm install always has vulnerabilities and need this audit fix thing).

**Comment by bkendall** [comment]
Our minimum node requirement is in our package.json (which _should_ be enforced by the CLI as well), but this made me realize that `>=14.17.0` isn't quite enough, `>=16.4.0` should be there to make sure `setDefaultResultOrder` is included in node 16 installations (even though `16.4` is fairly old.

I'd ask @readyiman - how had you installed the CLI and node? I don't have a good windows flow myself, so it's hard for me to test and verify fixes sometimes. :)

**Comment by readyiman** [comment]
> I'd ask @readyiman - how had you installed the CLI and node? I don't have a good windows flow myself, so it's hard for me to test and verify fixes sometimes. :)

Just casual one. I install node directly from it site https://nodejs.org/en/, And I install CLI from npm `npm install -g firebase-tools` usually from vscode terminal (cmd) just like in doc https://firebase.google.com/docs/cli#windows-npm (btw it actually written minimum CLI is v14.18.0).
