### ISSUE TITLE
`firebase app:sdkconfig` throws argument error

### ISSUE THREAD

**Issue by exaby73** [firebase/firebase-tools#4610]
### Environment info

**firebase-tools:** 11.0.1

**Platform:** MacOS

### Test case

Getting SDK config for android or iOS apps does not work.

### Steps to reproduce

Run `firebase app:sdkconfig android com.example.app --project=project-name`

### Expected behavior

Output the contents of `google-services.json`

### Actual behavior

```
[2022-06-02T08:11:54.156Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-06-02T08:11:54.157Z] > authorizing via --token option
⠋ Downloading configuration data of your Firebase ANDROID app[2022-06-02T08:11:54.161Z] > refreshing access token with scopes: []
[2022-06-02T08:11:54.161Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token
 <request body omitted>
⠹ Downloading configuration data of your Firebase ANDROID app[2022-06-02T08:11:54.386Z] <<< HTTP RESPONSE 200 {"expires":"Mon, 01 Jan 1990 00:00:00 GMT","date":"Thu, 02 Jun 2022 08:11:54 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2022-06-02T08:11:54.388Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/-/androidApps/com.example.app/config [none]
⠇ Downloading configuration data of your Firebase ANDROID app[2022-06-02T08:11:54.876Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/-/androidApps/com.example.app/config 400
[2022-06-02T08:11:54.877Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/-/androidApps/com.example.app/config {"error":{"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"}}
[2022-06-02T08:11:54.879Z] HTTP Error: 400, Request contains an invalid argument.
✖ Downloading configuration data of your Firebase ANDROID app
[2022-06-02T08:11:54.882Z] FirebaseError: HTTP Error: 400, Request contains an invalid argument.
    at module.exports (/Users/nabeelparkar/nvm/versions/node/v16.14.2/lib/node_modules/firebase-tools/lib/responseToError.js:47:12)
    at RetryOperation._fn (/Users/nabeelparkar/nvm/versions/node/v16.14.2/lib/node_modules/firebase-tools/lib/apiv2.js:286:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: Failed to get ANDROID app configuration. See firebase-debug.log for more info.
```

I believe this is happening because the tool is not adding the project name in the URL. `https://firebase.googleapis.com/v1beta1/projects/-/androidApps/com.example.app/config` should be `https://firebase.googleapis.com/v1beta1/projects/project-name/androidApps/com.example.app/config`

See the return value of this function

https://github.com/firebase/firebase-tools/blob/81ec80303ced030d12c2c444da698686b17fa483/src/management/apps.ts#L278-L295

**Comment by bkendall** [comment]
I can replicate this - I even see a couple other bugs along the way. I'll see if I can fix it up :)

**Comment by bkendall** [comment]
Actually, I think the arguments used here are wrong. The App ID  is a string that looks like `1:[projectnumber]:android:[hex]`. Take a look at `apps:list` for the App ID to be listed there.

**Comment by exaby73** [comment]
Hey @bkendall. Thanks for the input there, and yes, you were right. I just looked into it a bit more and that's exactly what I need. I'll close this issue. Thanks again :)
