### ISSUE TITLE
Unable to deploy 8GB functions

### ISSUE THREAD

**Issue by jirizavadil** [firebase/firebase-tools#4626]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:** macOS Monterey 12.4 (21F79)

### [REQUIRED] Test case

```const functions = require("firebase-functions")

module.exports.default = functions
  .region("europe-west1")
  .runWith({memory: "8GB", timeoutSeconds: 300})
  .https.onCall(async (data, context) => {
   console.log('lala')
  })
```

### [REQUIRED] Steps to reproduce

1. run emulator or deploy

### [REQUIRED] Expected behavior

running or deployed function

### [REQUIRED] Actual behavior

```
Error: Error occurred while parsing your function triggers.

Error: The only valid memory allocation values are: 128MB, 256MB, 512MB, 1GB, 2GB, 4GB
    at assertRuntimeOptionsValid (/Users/tralala/dev/platforma.one/functions/node_modules/firebase-functions/lib/function-builder.js:45:15)
    at FunctionBuilder.runWith (/Users/tralala/dev/platforma.one/functions/node_modules/firebase-functions/lib/function-builder.js:157:13)
    at Object.<anonymous> (/Users/tralala/dev/platforma.one/functions/calls/commerce/admin/export.fn/index.js:7:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ex (/Users/tralala/dev/platforma.one/functions/index.js:37:22)

```

Link to docs allowing 8GB deployment: https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--memory

**Comment by inlined** [comment]
I can't reproduce your issue no matter how hard I try. The error is coming from the `firebase-functions` SDK, not the CLI. Can you try running `npm install --save firebase-functions@latest` and see if that solves your problem?

**Comment by jirizavadil** [comment]
@inlined I'm such a disgrace, did not realize it's a `firebase-functions` issue, had that on `3.13.0` 🤦🏻‍♂️ Apologies for wasting your time.
