### ISSUE TITLE
firebase deploy hosting target fails in CI

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-tools#4713]
### [REQUIRED] Environment info

**firebase-tools:** 11.2.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Trying to deploy using a `FIREBASE_TOKEN` environment variable in GitHub Actions (the native action doesn't support my use case)

### [REQUIRED] Steps to reproduce

```yml
- name: run many deployments
  run: npx nx affected --target=deploy
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENROLL_FE }}
```

```json
"deploy": {
  "executor": "nx:run-commands",
  "options": {
    "command": "npx firebase deploy --only hosting:health-connector --debug"
  }
}
```

### [REQUIRED] Expected behavior

This command should Just Work™️ because I'm providing a service account via the `FIREBASE_TOKEN`

### [REQUIRED] Actual behavior

With the `--debug` flag turned on:
``` bash
> nx run health-connector:deploy
[2022-07-06T17:27:50.407Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-07-06T17:27:50.408Z] > authorizing via FIREBASE_TOKEN environment variable
[2022-07-06T17:27:50.408Z] [iam] checking project enroll-fe for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2022-07-06T17:27:50.409Z] > refreshing access token with scopes: []
[2022-07-06T17:27:50.410Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[2022-07-06T17:27:50.410Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2022-07-06T17:27:50.[47](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:48)7Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 400
[2022-07-06T17:27:[50](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:51).477Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2022-07-06T17:27:50.478Z] [iam] error while checking permissions, command may fail: TypeError: ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
***
 is not a legal HTTP header value
[2022-07-06T17:27:50.478Z] > refreshing access token with scopes: []
[2022-07-06T17:27:50.479Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[2022-07-06T17:27:50.479Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2022-07-06T17:27:50.[52](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:53)6Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 400
[2022-07-06T17:27:50.527Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2022-07-06T17:27:50.527Z] ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
***
 is not a legal HTTP header value
[2022-07-06T17:27:50.528Z] TypeError: ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
***
 is not a legal HTTP header value
    at validateValue (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/node_modules/node-fetch/lib/index.js:684:9)
    at Headers.set (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/node_modules/node-fetch/lib/index.js:820:3)
    at Client.addAuthHeader (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/apiv2.js:141:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.request (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/apiv2.js:95:34)
    at async getFirebaseProject (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/management/projects.js:296:21)
    at async getDefaultHostingSite (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/getDefaultHostingSite.js:8:21)
    at async requireHostingSite (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/requireHostingSite.js:9:18)
    at async Object.fn (/home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/commands/deploy.js:74:9)
    at async /home/runner/work/enroll-fe/enroll-fe/node_modules/firebase-tools/lib/command.js:188:17
Error: Failed to get Firebase project enroll-fe. Please make sure the project exists and your account has permission to access it.
[2022-07-06T17:27:50.[57](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:58)3Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[2022-07-06T17:27:50.574Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json ***"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":161[58](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:59)09[60](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:61)0000,"node8WarnAfter":160012[80](https://github.com/ideacrew/enroll-fe/runs/7219815886?check_suite_focus=true#step:8:81)00000***
```

**Comment by bkendall** [comment]
This is gonna be very difficult to help you through - auth things are tricky.

Is it literally returning a bunch of `*`s? It's clearly returning a `400` error, so something's not right, but it's hard to know.

Does using the `TOKEN` locally work?

I'd honestly recommend using a service account, rather than `FIREBASE_TOKEN` - we have it in mind to deprecate `FIREBASE_TOKEN` in favor of service accounts Soon, and it's actually a little more flexible/safer to use service accounts.

It's really easy to set up once you have the SA - we base64 encode it and have the [action dump it into a file for us](https://github.com/firebase/firebase-tools/blob/master/.github/workflows/node-test.yml#L96), then set `GOOGLE_APPLICATION_CREDENTIALS` in the environment pointed to that file. 

Sorry my answer is basically "don't do this", but... yeah, it's difficult to do auth stuff. 🙁  Let me know what you think.

**Comment by dereekb** [comment]
Looks like the firebase-tools repo has a base64 encoded version of their `.json` file. If you've got access to unix/linux terminal, you can pipe your file into `base64` for the string that goes into your secrets:

`cat mysecrets.json | base64` -> `eCiAgICAiZGVmYXVs...<base64 encoded secret>`

Then in your Github action you can decode it and save it to a file using `echo` and `base64` like they do here:

https://github.com/firebase/firebase-tools/blob/110dd6a7f08d3527526267bb057a44587ef799d2/.github/workflows/node-test.yml#L105

**Comment by 96312** [comment]
@dereekb Thank you for the help! Appreciate that.
