### ISSUE TITLE
Firebase storage emulator crashes on upload

### ISSUE THREAD

**Issue by bjankie1** [firebase/firebase-tools#4716]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.2

**Platform:** macOS

### [REQUIRED] Test case

Reproduction `script.ts`
```typescript
  import { getApp, getApps, initializeApp } from '@firebase/app'
  import { connectStorageEmulator, getStorage, ref, uploadString } from '@firebase/storage'

  const app = getApps().length ? getApp() : initializeApp(firebaseConfig)

  const storage = getStorage()
  connectStorageEmulator(storage, 'localhost', 9199)

  const stateRef = ref(storage, `test/data`)
  await uploadString(stateRef, 'test')
```

### [REQUIRED] Steps to reproduce

1. Start emulators: `firebase emulators:start --only firestore,auth,storage`
2. Run the `script.ts` above
3. Observe emulator crashes with:
```
[debug] [2022-07-06T21:36:12.506Z] TypeError: Cannot read properties of undefined (reading 'split')
    at handleUpload (/usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:273:50)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:89:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:284:7
    at param (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:354:14)
[error] 
[error] Error: An unexpected error has occurred.
```

### [REQUIRED] Expected behavior

1. Emulator doesn't crash
2. Upload operation succeeds.

### [REQUIRED] Actual behavior

Firebase emulator crashes, upload fails

**Comment by dereekb** [comment]
Are you running this on Node or in the browser?

For what it's worth that test passed for me when using the `@firebase/rules-unit-testing` package in a jest Node environment, and using storage rules that allowed writing to all files.

**Comment by yuchenshi** [comment]
@bjankie1  Looks like we need more logs on this. Would you mind uploading all log files (e.g. in a zip file)?
