### ISSUE TITLE
Firestore indexes issue - when empty

### ISSUE THREAD

**Issue by rootux** [firebase/firebase-tools#495]
When my `firestore.indexes.json` is empty like so:
```
{
  "indexes": [
    {
    }
  ]
}

```
I'm getting an error on `firebase deploy`
`Error: An unexpected error has occurred.`
The content of my `firebase-debug.log` contains:
```
[debug] [2017-10-05T23:13:59.475Z] TypeError: Cannot read property 'length' of undefined
    at Object.hash (/Users/rootux/.nvm/versions/node/v8.1.2/lib/node_modules/firebase-tools/lib/firestore/indexes.js:158:35)
```
I would expect a better error message or just accepting of this empty file

**Comment by mbleigh** [comment]
Hmm, we could have a better error message here but your indexes file isn't *empty* since you have one empty object in there. I'd consider this to be empty:

```js
{
  "indexes": []
}
```

**Comment by samtstern** [comment]
@rootux fix merged, this will have a much more obvious error message in the next release.

**Comment by kazuma1989** [comment]
After upgrading firebase-tools from 5.1.1 -> 6.2.0, I got a similar error:

    [2018-12-21T02:09:26.730Z] TypeError: Cannot read property 'collectionId' of undefined
        at FirestoreIndexes.upgradeOldSpec (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/firestore/indexes.js:307:29)
        at FirestoreIndexes.<anonymous> (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/firestore/indexes.js:23:31)
        at Generator.next (<anonymous>)
        at /home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/firestore/indexes.js:7:71
        at new Promise (<anonymous>)
        at __awaiter (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/firestore/indexes.js:3:12)
        at FirestoreIndexes.deploy (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/firestore/indexes.js:22:16)
        at _deployIndexes (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/deploy/firestore/deploy.js:30:10)
        at module.exports (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/deploy/firestore/deploy.js:39:48)
        at _chain (/home/vsts/.npm/_npx/23791/lib/node_modules/firebase-tools/lib/deploy/index.js:22:40)

My firestore.indexes.json (good for firebase-tools@5.1.1) is:
```json
{
  "indexes": []
}
```

This seems to be caused by changing the schema of firestore.indexes.json.
How do I fix this?
Could you please show me the correct empty JSON compatible for new firebase-tools?

**Comment by samtstern** [comment]
Well this is my fault and I can fix it first thing tomorrow.  In the
meantime if you remove the entry for Firestore indexes in your
firebase.json file I think that will fix it.

**Comment by u12206050** [comment]
All deploys are failing because of this!?

What should the firestore.indexes.json file look like if it should be empty?

**Comment by samtstern** [comment]
In your firebase.json file you probably have a section like this:

```
"firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
```

Change it to this

```
"firestore": {
    "rules": "firestore.rules"
  }
```

That will prevent the index deploy from happening at all.

**Comment by vsimon** [comment]
Just hit this issue, reverted to the previous version for now, looking forward to the PR merge @samtstern

**Comment by vsimon** [comment]
Thanks @samtstern, 6.2.1 got further but I'm getting a different error next.

```
[2018-12-21T22:48:10.753Z] TypeError: Cannot read property 'map' of undefined
    at FirestoreIndexes.<anonymous> (/usr/lib/node_modules/firebase-tools/lib/firestore/indexes.js:70:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/firebase-tools/lib/firestore/indexes.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by samtstern** [comment]
@vsimon what does your `firestore.indexes.json` file look like?

**Comment by vsimon** [comment]
```
{
  "indexes": []
}`
```

**Comment by samtstern** [comment]
@vsimon I can't reproduce:

```
$ firebase --version
6.2.1
samstern@freewifi:/tmp/tmp.XYhqvivdvk
$ cat firestore.indexes.json
{
  "indexes": []
}
samstern@freewifi:/tmp/tmp.XYhqvivdvk
$ firebase --project=fir-dumpster deploy --only firestore:indexes

=== Deploying to 'fir-dumpster'...

i  deploying firestore
i  firestore: reading indexes from firestore.indexes.json...
i  firestore: there are some indexes defined in your project that are not present in your firestore indexes file. Run firebase firestore:indexes and save the result to correct the discrepancy.
✔  firestore: deployed indexes in firestore.indexes.json successfully

✔  Deploy complete!
```

**Comment by vsimon** [comment]
Weird. 

The `firebase deploy --debug` is using `login:ci` token but I don't think that would make a difference. This is more of the output right before the error. I can try just removing the file, but its bummer that 6.2.1 didn't just work for me.


```
i  firestore: uploading rules firestore.rules...
[2018-12-21T23:14:08.104Z] >>> HTTP REQUEST POST https://firebaserules.googleapis.com/v1/projects/XXXXXXXXXX/rulesets  
 files=[name=firestore.rules, content=service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow get: if true;
      allow write: if false;
    }
  }
}]
[2018-12-21T23:14:08.105Z] >>> HTTP REQUEST GET https://firestore.googleapis.com/v1beta2/projects/XXXXXXXXXX/databases/(default)/collectionGroups/-/indexes  
 
[2018-12-21T23:14:08.466Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 21 Dec 2018 23:14:08 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-12-21T23:14:08.467Z] [rules] created ruleset projects/XXXXXXXXXX/rulesets/1aa1a549-a4d6-4f79-b101-2f81afb930ea
[2018-12-21T23:14:08.474Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 21 Dec 2018 23:14:08 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-12-21T23:14:08.475Z] TypeError: Cannot read property 'map' of undefined
    at FirestoreIndexes.<anonymous> (/usr/lib/node_modules/firebase-tools/lib/firestore/indexes.js:70:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/firebase-tools/lib/firestore/indexes.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: An unexpected error has occurred.
```

**Comment by samtstern** [comment]
See #1069
