### ISSUE TITLE
Error: Not Implemented on storage copy

### ISSUE THREAD

**Issue by balazss** [firebase/firebase-tools#4963]
### [REQUIRED] Environment info

**firebase-tools:** `firebase-tools@11.8.1`

**Platform:** `MacOS 12.5.1`

### [REQUIRED] Test case

```javascript
import { getStorage } from "firebase-admin/storage";
import * as functions from "firebase-functions";

export const moveImage = functions.storage
  .object()
  .onFinalize(async (object) => {
    const fileBucket = object.bucket;
    const filePath = object.name;

    const bucket = getStorage().bucket(fileBucket);

    const newFilePath = filePath.replace("uploads/", "");

    await bucket.file(filePath).copy(bucket.file(newFilePath));

    return newFilePath;
  });
```

### [REQUIRED] Steps to reproduce

1. Upload a file from client e.g: `uploadBytesResumable`.
2. Trigger `onFinalize()` Cloud Function with `copy()` 

### [REQUIRED] Expected behavior
Copying files moves it to specified location. 

### [REQUIRED] Actual behavior
Following error is logged:

```
Error: Not Implemented
    at new ApiError (/Users/b****s/S***e/a*****f/backend/functions/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:78:15)
    at Util.parseHttpRespMessage (/Users/b****s/S***e/a*****f/backend/functions/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:180:41)
    at Util.handleResp (/Users/b****s/S***e/a*****f/backend/functions/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:154:76)
    at /Users/b****s/S***e/a*****f/backend/functions/node_modules/@google-cloud/storage/build/src/nodejs-common/util.js:500:22
    at onResponse (/Users/b****s/S***e/a*****f/backend/functions/node_modules/retry-request/index.js:228:7)
    at/Users/b****s/S***e/a*****f/backend/functions/node_modules/teeny-request/build/src/index.js:226:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by aalej** [comment]
I can’t reproduce this issue using the latest version of firebase-tools, which is currently [v14.5.1](https://github.com/firebase/firebase-tools/releases). When running the `copy()` code, no errors are being raised in the emulators. Here’s my [MCVE](https://github.com/aalej/issues-4963). 

It looks like this may have been fixed. That said, I’ll  go ahead and close this, but if you’re still encountering this issue, please leave a comment so that we can reopen this and take a look
