### ISSUE TITLE
generateEmailVerificationLink() was occurred TOO_MANY_ATTEMPTS_TRY_LATER error.

### ISSUE THREAD

**Issue by Kurogoma939** [firebase/firebase-tools#5053]
### [REQUIRED] Environment info

**firebase-tools: functions**

**Platform: macOS / node.js**

### [REQUIRED] Test case

I tried reproduce's function.

### [REQUIRED] Steps to reproduce

1. deploy this to Firebase Functions.

```typescript
import admin = require("firebase-admin");
import functions = require("firebase-functions");
import { info, warn, error } from "firebase-functions/lib/logger";

exports.sendEmailConfirmation = functions
.region("asia-northeast1")
.runWith({ failurePolicy: true })
.auth.user()
.onCreate(async (user) => {

  const auth = admin.auth();
  const email = user.email as string;
  info("email", email);

  try {
    // The problem point is here.
    const confirmLink = await auth.generateEmailVerificationLink(email)
    .then(async (emailLink) => {
      console.log("emailLink");
      console.log(emailLink);
      ...
      });
    })
    .catch((error) => {
      return console.log(error);
    });
  } catch (error) {
    console.log(error);
  }

```
2. create new user on website.
※ I succeeded create new user.

### [REQUIRED] Expected behavior

I want to get vertificationLink

### [REQUIRED] Actual behavior

I found this error log in Log Explorer. 
```
FirebaseAuthError: An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"TOO_MANY_ATTEMPTS_TRY_LATER","errors":[{"message":"TOO_MANY_ATTEMPTS_TRY_LATER","domain":"global","reason":"invalid"}]}}"
    at FirebaseAuthError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAuthError (/workspace/node_modules/firebase-admin/lib/utils/error.js:149:16)
    at Function.FirebaseAuthError.fromServerError (/workspace/node_modules/firebase-admin/lib/utils/error.js:188:16)
```

**Comment by bkendall** [comment]
Since you're having an issue with the prod service, could you please open an issue with [Firebase Support](https://firebase.google.com/support)? If this is with the emulator, this is the right spot, but we're unable to debug production issues from this repo.
