### ISSUE TITLE
[BUG]: firebase tools v:11.14.0 fails to serve and deploy hosting

### ISSUE THREAD

**Issue by Chetana-Joymo** [firebase/firebase-tools#5073]
### [REQUIRED] Environment info

**firebase-tools:**

11.14.0

**Platform:**

macOS Monterey version: 12.6

### [REQUIRED] Test case

Tryin to deploy/serve my project which works fine with firebase-tools version 11.13.0

### [REQUIRED] Steps to reproduce

`firebase deploy --only hosting` or ` firebase serve --only hosting`

### [REQUIRED] Expected behavior

It should deploy or serve the application

### [REQUIRED] Actual behavior

```log
[debug] [2022-10-06T11:47:35.585Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/*** 200
[debug] [2022-10-06T11:47:35.586Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/*** {"projectId":"***","projectNumber":"***","displayName":"***","name":"projects/***","resources":{"hostingSite":"***","realtimeDatabaseInstance":"***","storageBucket":"***.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"**"}
[info] 
[info] === Deploying to '***'...
[info] 
[info] i  deploying hosting 
[debug] [2022-10-06T11:47:35.590Z] TypeError: Cannot read properties of undefined (reading 'join')
    at validateOne (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/hosting/config.js:122:41)
    at validate (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/hosting/config.js:85:9)
    at Object.hostingConfig (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/hosting/config.js:186:9)
    at prepare (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/deploy/hosting/prepare.js:16:28)
    at chain (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/deploy/index.js:33:15)
    at deploy (/Users/***/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/deploy/index.js:69:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by bkendall** [comment]
Ah, this is fixed by #5077
