### ISSUE TITLE
init hosting with experimental webframework fails with detecting angular workspace

### ISSUE THREAD

**Issue by marcjulian** [firebase/firebase-tools#5146]
### [REQUIRED] Environment info

**firebase-tools:** 11.4.2 and 11.15.0, using experimental webframeworks support

**Platform:** macOS

### [REQUIRED] Steps to reproduce

1. Installed latest `firebase-tools` and `@angular/cli` (v14.2.6).
2. Create a new angular project `ng new --minimal`
3. Enabling webframeworks experiment `firebase experiments:enable webframeworks`
4. Initialize firebase hosting `firebase init hosting`

### [REQUIRED] Expected behavior

Creating `firebase.json` and `.firebaserc` with the hosting configuration.

### [REQUIRED] Actual behavior

CLI output of `firebase init hosting`

```
=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

? Please select an option: Use an existing project
? Select a default Firebase project for this directory: ng-ssr (ng-ssr)
i  Using project ng-ssr (ng-ssr)

=== Hosting Setup
? Detected an existing Angular codebase in the current directory, should we use this? Yes

Error: An unexpected error has occurred.
```

Errors from `firebase-debug.log`

```
=== Project Setup
[info] 
[info] First, let's associate this project directory with a Firebase project.
[info] You can create multiple project aliases by running firebase use --add, 
[info] but for now we'll just set up a default project.
[info] 
[debug] [2022-10-19T09:46:15.451Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=100
[debug] [2022-10-19T09:46:16.000Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2022-10-19T09:46:16.000Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[info] i  Using project ng-ssr (ng-ssr) 
[info] 
=== Hosting Setup
[debug] [2022-10-19T09:46:26.507Z] Error: Unable to determine format for workspace path.
    at Object.readWorkspace (/Dev/wip/ng-ssr-firebase/node_modules/@angular-devkit/core/src/workspace/core.js:86:15)
    at async getContext (/.fnm/node-versions/v16.16.0/installation/lib/node_modules/firebase-tools/lib/frameworks/angular/index.js:144:27)
    at async discover (/.fnm/node-versions/v16.16.0/installation/lib/node_modules/firebase-tools/lib/frameworks/angular/index.js:20:30)
    at async discover (/.fnm/node-versions/v16.16.0/installation/lib/node_modules/firebase-tools/lib/frameworks/index.js:77:32)
    at async doSetup (/.fnm/node-versions/v16.16.0/installation/lib/node_modules/firebase-tools/lib/init/features/hosting/index.js:54:31)
    at async init (/.fnm/node-versions/v16.16.0/installation/lib/node_modules/firebase-tools/lib/init/index.js:36:9)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by bleuscyther** [comment]
From what I am seeing the path to the workspace is set to "." .  I think they need to add a resolver.

**Comment by kponda** [comment]
I encounter the same issue
and the following folder structure worked well.

[parent folder] (run firebase init here)
  firebase.json
  [ AngularProject ]

**Comment by osamamalik2000** [comment]
I tried did not work can you explain the steps


> I encounter the same issue and the following folder structure worked well.
> 
> [parent folder] (run firebase init here) firebase.json [ AngularProject ]

**Comment by Soolan** [comment]
Ping.
Same problem here.

**Comment by viv9k** [comment]
Same problem, Is there any temporary solution or any proposed solution?

**Comment by jamesdaniels** [comment]
This should be fixed in the next release, turns out ng devkit doesn't like when you pass "." as the directory, fixed by always passing in the absolute path rather than relative
