### ISSUE TITLE
Deploy next.js webframework with predeploy hook fails

### ISSUE THREAD

**Issue by freakness** [firebase/firebase-tools#5159]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0

**Platform:** macOS 12.6 (ARM/M1)

### [REQUIRED] Test case

Create a nextjs project. Add a predeploy hook to firebase.json:

```
{
  "hosting": {
    "source": ".",
    "public": ".",
    "predeploy": "npm run copyfiles",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
  }
}
```

### [REQUIRED] Steps to reproduce

run `firebase deploy`

### [REQUIRED] Expected behavior

The project is deployed to hosting and the predeploy hook is run correctly.

### [REQUIRED] Actual behavior

Relevant part of logs: 

[info] i  deploying functions, hosting 
[debug] [2022-10-23T11:55:29.960Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1172:7)
    at Config.path (/Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/config.js:123:45)
    at getChildEnvironment (/Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/deploy/lifecycleHooks.js:48:49)
    at runTargetCommands (/Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/deploy/lifecycleHooks.js:72:14)
    at /Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/deploy/lifecycleHooks.js:124:24
    at async chain (/Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/deploy/index.js:35:9)
    at async deploy (/Users/louis/.nvm/versions/node/v16.18.0/lib/node_modules/firebase-tools/lib/deploy/index.js:78:5)
[error] 
[error] Error: An unexpected error has occurred.

It seems that the lifecycleHooks incorrectly tries to use the _public_ directory, which is not specified for webframeworks

**Comment by diegood12** [comment]
It seems to have something to do with this

https://github.com/firebase/firebase-tools/blob/f29a7202e1a17e272f9f1617357d11367f7ce805/src/deploy/lifecycleHooks.ts#L51

Changing this to

```typescript
resourceDir = overallOptions.config.path(config.public ?? config.source);
```

in the compiled output solved it for me.
