### ISSUE TITLE
firebase deploy error

### ISSUE THREAD

**Issue by IagoBarboza** [firebase/firebase-tools#520]
### Version info
3.13.1

### Steps to reproduce
* Create a web app containing the index.html, js and css files
* Run firebase init and select the option Hosting
* Run firebase deploy -P <alias_or_project_id>

### Expected behavior
The web app is available on the firebase host

### Actual behavior
=== Deploying to '{project_id}'...

i  deploying hosting
i  hosting: preparing ./ directory for upload...
[2017-10-27T00:52:45.039Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/{project_id}/uploads/-KxQJGY4BIFvPrDGIxye?fileCount=130&message=  
 Thu Oct 26 2017 21:52:45 GMT-0300 (BRT)
Uploading: [                                        ] 0%[2017-10-27T00:54:08.867Z] <<< HTTP RESPONSE 409 server=nginx, date=Fri, 27 Oct 2017 00:54:08 GMT, content-type=application/json; charset=utf-8, content-length=82, connection=close, access-control-allow-origin=*, access-control-allow-methods=GET, PUT, POST, DELETE, OPTIONS, strict-transport-security=max-age=31556926; includeSubDomains; preload, x-content-type-options=nosniff
[2017-10-27T00:54:08.867Z] <<< HTTP RESPONSE BODY undefined
[2017-10-27T00:54:08.870Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:43:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:312:30)

Error: An unexpected error has occurred.

**Comment by IagoBarboza** [comment]
New error:

=== Deploying to {project_id}...

i  deploying hosting
i  hosting: preparing ./ directory for upload...
Uploading: [                                        ] 0%
Error: An unexpected error has occurred.

Error: File upload failed: Storage error. Please try again. Failed to upload file "public/Icon\r": Disallowed unicode characters present in object name '%s'

**Comment by merlinnot** [comment]
The error tells everything: 

> Failed to upload file "public/Icon\r": Disallowed unicode characters present in object name '%s'

You have a `\r` in your filename.

**Comment by IagoBarboza** [comment]
I've removed all files, including firebase.json and .firebaserc, and compiled the app again.
It seems it's solved. 
I'll close once the problem is not on firebase-tools.
Thanks.
