### ISSUE TITLE
demo projects can not be initialized without configuration data from real projects

### ISSUE THREAD

**Issue by joaomelo** [firebase/firebase-tools#5218]
### [REQUIRED] Environment info

**firebase-tools:** 11.14.3
**Platform:** Windows 11

### [REQUIRED] Test case

You can clone this repo and start the firebase emulators in it: https://github.com/joaomelo/hot-vue/tree/ec4e3bc8c4da0bffc9b42c6e5e5eecc393676326

### [REQUIRED] Steps to reproduce

Clone the repo (I think it will have the same behavior for any project thought), install firebase tools globally, open the windows terminal, and start emulators with `firebase --project demo-test emulators:exec "npm run test"`

### [REQUIRED] Expected behavior

The firebase [docs](https://firebase.google.com/docs/emulator-suite/connect_auth) says that "Local Emulator Suite supports emulation of real Firebase projects and demo projects." and that "A demo Firebase project has no real Firebase configuration and no live resources. These projects are usually accessed via codelabs or other tutorials. Project IDs for demo projects have the demo- prefix."

There was not a connection example I was able to find in the docs. Since it mentions only the project name starting with "demo-" as a requirement, the expected behavior I assumed was to pass just the projectID in the code below.

```js
  const app = initializeApp({
    projectId: "demo-test",
  });
  const auth = getAuth(app);
  const db = getFirestore(app);
```
 
### [REQUIRED] Actual behavior

The instructions fail and complain about an invalid API key (image below). But how can I have a valid API key if it is a fake demo project?

![demo-project](https://user-images.githubusercontent.com/5727050/200126556-1b81f935-3a06-4dd9-80b0-4e239020133d.png)

**Comment by ishowta** [comment]
@joaomelo I got a reply from you on Stackoverflow that it didn't work, but at least the Auth error disappeared when I used the hack I posted.
https://stackoverflow.com/questions/72194253/firebase-error-auth-invalid-api-key-with-demo-project/72839398?noredirect=1#comment131222727_72839398

![2022-11-08_000528](https://user-images.githubusercontent.com/7393198/200343575-16ea7b3e-077e-47af-846f-628778ab84e9.png)

**Comment by ishowta** [comment]
Ah, it was simply the `firebase-js-sdk` throwing an exception if the `apiKey` field was not present...
https://github.com/firebase/firebase-js-sdk/blob/6efd96b78ed06a30dd09c109bb1236eb9925c365/packages/auth/src/core/auth/register.ts#L68-L72

**Comment by joaomelo** [comment]
Hi @ishowta thanks so much for your attention and time. 

I confirm that what you report here works.

I've removed the feedback from StackOverflow, upvoted your answer, and added a suggestion that the "ProjectId" over there is updated to "demo-test".

Regarding the issue I opened here, I still believe that the need to add fake apiKey and authDomain values should be removed or explicitly documented in firebase docs and/or the error messages.

**Comment by aalej** [comment]
Hi @joaomelo, apologies for the delay and thanks for reporting this. I was able to replicate the issue described, when starting the emulator with a demo-project and trying to initialize Firebase Auth without providing an apiKey, an error is raised. 

As mentioned by @ishowta, it does look like a workaround for this is providing a random apiKey, and that the error is being raised when the Javascript SDK does not find a value for the apiKey [here](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/auth/register.ts#L68-L71).

Let me notify the team of this issue so that we can provide more context about this and investigate this behavior.

**Comment by ishowta** [comment]
@aalej Oh sorry, I had already created an Issue on firebase-js-sdk https://github.com/firebase/firebase-js-sdk/issues/6776, I didn't comment on this thread because I thought linking it with Github mention would be enough.

**Comment by christhompsongoogle** [comment]
I ran into this also, full stack:

```
file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:490
    return _DEFAULT_AUTH_ERROR_FACTORY.create(authOrCode, ...rest);
                                       ^

FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:490:40)
    at _assert (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:494:15)
    at Component.instanceFactory (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:6506:9)
    at Provider.getOrInitializeService (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:2943:27)
    at getAuth (file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/node_modules/@firebase/auth/dist/node-esm/totp-035c6eef.js:6571:18)
    at file:///usr/local/google/home/christhompson/firebaseprojects/onlyEmulators/src/index.js:14:14
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}

Node.js v18.13.0
```
