### ISSUE TITLE
firebase deploy --only hosting [ERROR] Could not resolve "pnpapi"

### ISSUE THREAD

**Issue by chinesehemp** [firebase/firebase-tools#5223]
### [REQUIRED] Environment info

**firebase-tools:** 11.16.0

**Platform:** macOS 12.6 (21G115)

### [REQUIRED] Test case

`package.json`
```
{
  "name": "thecannabisapp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "serve": "firebase serve",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "export": "next export",
    "emulator": "firebase emulators:start"
  },
  "dependencies": {
    "@emotion/cache": "^11.10.5",
    "@emotion/react": "^11.10.5",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.5",
    "@googlemaps/js-api-loader": "^1.15.1",
    "@mui/icons-material": "^5.10.9",
    "@mui/material": "^5.10.12",
    "@stream-io/stream-chat-css": "^3.7.0",
    "@tanstack/react-query": "^4.14.5",
    "@tanstack/react-query-devtools": "^4.14.5",
    "@virgilsecurity/e3kit-browser": "^2.4.5",
    "autosuggest-highlight": "^3.3.4",
    "date-fns": "^2.29.3",
    "firebase": "^9.13.0",
    "formik": "^2.2.9",
    "framer-motion": "^7.6.5",
    "libphonenumber-js": "^1.10.14",
    "mui-markdown": "^0.5.5",
    "mui-tel-input": "^2.0.4",
    "next": "12.3.1",
    "next-pwa": "^5.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-firebase-hooks": "^5.0.3",
    "react-hot-toast": "^2.4.0",
    "remark": "^14.0.2",
    "remark-html": "^15.0.1",
    "stream-chat": "^8.1.0",
    "stream-chat-react": "^10.4.0",
    "yup": "^0.32.11",
    "yup-phone": "^1.3.2"
  },
  "devDependencies": {
    "@types/autosuggest-highlight": "^3.2.0",
    "@types/emoji-mart": "^3.0.9",
    "@types/google.maps": "^3.50.5",
    "@types/grecaptcha": "^3.0.4",
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.8",
    "eslint": "8.27.0",
    "eslint-config-next": "12.3.1",
    "file-loader": "^6.2.0",
    "next-transpile-modules": "^9.1.0",
    "sass": "^1.56.0",
    "typescript": "4.8.4"
  },
  "author": "chinesehemp"
}
```

`next.config.js`
```
/** @type {import('next').NextConfig} */

const path = require("path");

const withTM = require("next-transpile-modules")([
  "@virgilsecurity/e3kit-browser",
  "virgil-crypto",
  "@virgilsecurity/pythia-crypto",
]);

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  sassOptions: {
    includePaths: [path.join(__dirname, "styles")],
  },
  compiler: {
    removeConsole: {
      exclude: ["error", "debug"],
    },
  },
  async rewrites() {
    return [
      {
        source: "/@:username",
        destination: "/:username",
      },
    ];
  },
  webpack: (config) => {
    config.experiments = {
      asyncWebAssembly: true,
      syncWebAssembly: true,
      backCompat: true,
    };
    config.module.rules[
      config.module.rules.findIndex((rule) => rule.oneOf)
    ].oneOf.unshift({
      test: /\.wasm$/,
      type: "javascript/auto",
      loader: "file-loader",
      options: {
        outputPath: "static/wasm/",
      },
    });

    return config;
  },
};

module.exports = withTM(nextConfig);
```

### [REQUIRED] Steps to reproduce

```
❯ firebase deploy --only hosting
Detected a Next.js codebase. This is an experimental integration, proceed with caution.

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (7/7)
info  - Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ ○ / (5636 ms)                            192 B           577 kB
├   /_app                                  0 B             263 kB
├ ○ /[username] (5585 ms)                  2.48 kB         582 kB
├ ○ /404                                   183 B           263 kB
├ ○ /channel/[cid] (5747 ms)               328 kB          743 kB
├ ○ /chat (5822 ms)                        15.6 kB         706 kB
└ ○ /contacts (5733 ms)                    4.09 kB         631 kB
+ First Load JS shared by all              283 kB
  ├ chunks/framework-b3802df6cb251587.js   45.5 kB
  ├ chunks/main-75fd11754c169a69.js        35.1 kB
  ├ chunks/pages/_app-6d8d20671b151b8a.js  180 kB
  ├ chunks/webpack-d4c7a602324d07a4.js     1.92 kB
  └ css/3dd171819a422d23.css               20.5 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

✘ [ERROR] Could not resolve "pnpapi"

    node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17:
      126 │     return require("pnpapi"); // eslint-disable-line node/no-missing-require
          ╵                    ~~~~~~~~

  You can mark the path "pnpapi" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.


Error: An unexpected error has occurred.
```

### [REQUIRED] Expected behavior

Expecting my Next.js app to deploy to Firebase hosting. Running `yarn build` works fine.

<img width="711" alt="Screenshot 2022-11-07 at 13 37 22" src="https://user-images.githubusercontent.com/58605231/200324088-431f2beb-689a-4afb-9d70-4c74e5fbe174.png">

### [REQUIRED] Actual behavior

```
✘ [ERROR] Could not resolve "pnpapi"

    node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17:
      126 │     return require("pnpapi"); // eslint-disable-line node/no-missing-require
          ╵                    ~~~~~~~~

  You can mark the path "pnpapi" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

[2022-11-07T12:39:06.015Z] Error: Build failed with 1 error:
node_modules/enhanced-resolve/lib/ResolverFactory.js:126:17: ERROR: Could not resolve "pnpapi"
    at failureErrorWithLog (/usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1566:15)
    at /usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1024:28
    at /usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:969:67
    at buildResponseToResult (/usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1022:7)
    at /usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/usr/local/Cellar/firebase-cli/11.16.0/libexec/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Error: An unexpected error has occurred.
```

**Comment by chinesehemp** [comment]
Okay, it looks like the issue was with `next-transpile-modules` pointing to `enhanced-resolve@5.10.0` and `@virgilsecurity/e3kit-browser` using webpack 4 depending on `enhanced-resolve@4.5.0`. After I changed my `package.json` to forced`next-transpile-modules` to resolve to `enhanced-resolve@4.5.0` I was able to get pass the error.
 
 ```
   "resolutions": {
    "next-transpile-modules/enhanced-resolve": "4.5.0"
  },
```

**Comment by f2ka07** [comment]
The error message "Could not resolve 'pnpapi'" suggests that there is an issue with the package manager that you are using to manage your project's dependencies.

Here are a few potential solutions to resolve this issue:

Try clearing your package manager cache and reinstalling your dependencies. You can do this by running the following commands:

**### For NPM:**

`npm cache clean --force
rm -rf node_modules
npm install
`
**### For Yarn:**

`yarn cache clean
rm -rf node_modules
yarn install
`
If you are using Yarn, you can try running the command with the --ignore-engines flag. This will allow Yarn to install packages even if they don't meet the engine requirements specified in the package.json file. You can run the command with this flag like this:

`firebase deploy --only hosting --ignore-engines
`

See this video on  [Firebase deploy --only hosting](https://solid-future.com/docs/host-static-websites-on-firebase-firebase-deploy-only-hosting/) .  If none of the above solutions work, you may need to update your package manager or switch to a different one. For example, if you are using NPM, try updating to the latest version by running:

`npm install -g npm
`

If none of these solutions work, you may need to look into other potential causes of the issue or seek help from Firebase support.
