### ISSUE TITLE
Firebase deploy is not working with hosting,functions

### ISSUE THREAD

**Issue by dharmendrasha** [firebase/firebase-tools#5301]
### [REQUIRED] Environment info

> Firebase: 11.8.1
> Node.js: 16.13.0
> Npm: 8.1.0
> System: MacBookPro 13" m2 
> Project Architecture: Monorepo (PNPM v7.14.0)

**firebase-tools:**
11.8.1

**Platform:**
macOS

### [REQUIRED] Test case
1. Create a basic express app with public folder.
2. Try to deploy with above environment.

### [REQUIRED] Steps to reproduce
1. Create a monorepo project.
3. Have a express.js (with typescritpt and eslint)

FireabseJsonConf: 

``````
{
  "emulators": {
    "hosting": {
      "port": 3002,
      "host": "0.0.0.0"
    }
  },
  "hosting": {
    "public": "public",
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "app"
      }
    ]
  },
  "functions": {
    "source": ".",
    "ignore": [
      "node_modules",
      ".git",
      "firebase-debug.log",
      "firebase-debug.*.log"
    ],
    "predeploy": [
      "npm run build"
    ]
  }
}
``````

7. package.json script
```
"build": "pnpm run gulp",
    "gulp": "gulp",
    "build:watch": "tsc --watch",
    "serve": "pnpm run build && firebase emulators:start --only hosting,functions",
    "shell": "pnpm run build && firebase functions:shell",
    "start": "pnpm run shell",
    "deploy": "firebase deploy --only hosting,functions",
    "logs": "firebase functions:log",
    "prebuild": "rm -rf build dist lib",
    "test:react": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "ts-node": "ts-node",
    "start:dev": "nodemon",
    "test": "jest --config ./test/jest.config.ts --passWithNoTests",
    "test:ci": "jest --config ./test/jest.config.ts --ci --coverage --reporters=default --reporters=jest-junit",
    "test:watch": "jest --config ./test/jest.config.ts --watch",
    "test:cov": "jest --config ./test/jest.config.ts --coverage",
    "test:debug": "node --config ./test/jest.config.ts --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "eslint:check": "eslint \"./src/**/*.ts\"",
    "eslint:fix": "npm run eslint:check -- --fix",
    "lint": "npm run eslint:check && npm run prettier:write",
    "precommit": "pnpm run lint",
    "prettier:check": "prettier --check ./src/**/*.{ts,js,json,*rc}",
    "prettier:write": "prettier --write ./src/**/*.ts"
```

### [REQUIRED] Expected behaviour

It should deploy the code to the google cloud function

Note: Emulators are working fine

### [REQUIRED] Actual behaviour
```
> pnpm run --filter @dashrath/frontend deploy   
> > @dashrath/frontend@0.0.1 deploy /Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/apps/frontend
> > firebase deploy --only hosting,functions --debug
> [2022-12-05T15:18:37.202Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
> [2022-12-05T15:18:37.204Z] > authorizing via signed-in user (dharmendrashaheagle@gmail.com)
> [2022-12-05T15:18:37.204Z] [iam] checking project dashrath-6e6b9 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
> [2022-12-05T15:18:37.207Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/dashrath-6e6b9:testIamPermissions [none]
> [2022-12-05T15:18:37.208Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/dashrath-6e6b9:testIamPermissions x-goog-quota-user=projects/dashrath-6e6b9
> [2022-12-05T15:18:37.209Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/dashrath-6e6b9:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
> [2022-12-05T15:18:38.987Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/dashrath-6e6b9:testIamPermissions 200
> [2022-12-05T15:18:38.992Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/dashrath-6e6b9:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
> [2022-12-05T15:18:38.994Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/dashrath-6e6b9/serviceAccounts/dashrath-6e6b9@appspot.gserviceaccount.com:testIamPermissions [none]
> [2022-12-05T15:18:38.996Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/dashrath-6e6b9/serviceAccounts/dashrath-6e6b9@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
> [2022-12-05T15:18:40.725Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/dashrath-6e6b9/serviceAccounts/dashrath-6e6b9@appspot.gserviceaccount.com:testIamPermissions 200
> [2022-12-05T15:18:40.727Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/dashrath-6e6b9/serviceAccounts/dashrath-6e6b9@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
> [2022-12-05T15:18:40.729Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/dashrath-6e6b9 [none]
> [2022-12-05T15:18:41.344Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/dashrath-6e6b9 200
> [2022-12-05T15:18:41.347Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/dashrath-6e6b9 {"projectId":"dashrath-6e6b9","projectNumber":"558090587536","displayName":"dashrath","name":"projects/dashrath-6e6b9","resources":{"hostingSite":"dashrath-6e6b9","realtimeDatabaseInstance":"dashrath-6e6b9-default-rtdb"},"state":"ACTIVE","etag":"1_85b9e968-6be3-4d77-ba67-abc762302133"}
> 
> === Deploying to 'dashrath-6e6b9'...
> 
> i  deploying functions, hosting
> Running command: npm run build
> 
> > @dashrath/frontend@0.0.1 prebuild /Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/apps/frontend
> > rm -rf build dist lib
> 
> 
> > @dashrath/frontend@0.0.1 build /Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/apps/frontend
> > pnpm run gulp
> 
> 
> > @dashrath/frontend@0.0.1 gulp /Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/apps/frontend
> > gulp
> 
> /Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/node_modules/.pnpm/liftoff@3.1.0/node_modules/liftoff/index.js:187
>       throw err;
>       ^
> 
> Error: Command failed: /usr/local/bin/firebase --help
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '/Users/dharmendra/personnel/dashrath/dashrathsoftwaresolutions.com/apps/frontend/--help'
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
>     at node:internal/main/run_main_module:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
>     at ChildProcess.exithandler (node:child_process:398:12)
>     at ChildProcess.emit (node:events:527:28)
>     at maybeClose (node:internal/child_process:1092:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
>   code: 1,
>   killed: false,
>   signal: null,
>   cmd: '/usr/local/bin/firebase --help'
> }
>  ELIFECYCLE  Command failed with exit code 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @dashrath/frontend@0.0.1 build: `pnpm run gulp`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @dashrath/frontend@0.0.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/dharmendra/.npm/_logs/2022-12-05T15_18_43_734Z-debug.log
> Error: functions predeploy error: Command terminated with non-zero exit code 1
>  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @dashrath/frontend@0.0.1 deploy: `firebase deploy --only hosting,functions --debug`
> Exit status 1
```

Note:It is overwriting my node path on my machine.

**Comment by dharmendrasha** [comment]
updated my bug report

**Comment by bkendall** [comment]
1. May not be relevant, but how did you install `firebase-tools`? `npm`, or via `https://firebase.tools`? Or other?
2. Are you using the webframeworks experiment? You can confirm by running `firebase experiments:list`.
