### ISSUE TITLE
FirebaseError: CEL tried to evaluate param."production" ? 1 : params.FUNCTION_ENVIRONMENT == "demo" in a context which only permits literal values

### ISSUE THREAD

**Issue by rrnara** [firebase/firebase-tools#5324]
### [REQUIRED] Environment info

**firebase-tools:**
11.0.1

**Platform:**
macOS

### [REQUIRED] Test case

Use firebase functions v2, have an environment variable like MY_FUNCTIONS_ENVIRONMENT and define it as:
export const MY_FUNCTION_ENVIRONMENT = defineString('MY_FUNCTION_ENVIRONMENT', { default: 'development' })

In startup, setup minInstances based on MY_FUNCTION_ENVIRONMENT using:
MY_FUNCTION_ENVIRONMENT.equals('production').thenElse(1, 0)

### [REQUIRED] Steps to reproduce

Start firebase emulator after code changes above:
firebase emulators:start --only functions

### [REQUIRED] Expected behavior

Functions startup as expected, instead see a CEL error

### [REQUIRED] Actual behavior

```
[2022-12-12T18:18:57.922Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-12-12T18:18:57.923Z] > authorizing via signed-in user (ram@paerpay.com)
i  emulators: Starting emulators: functions {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: functions"}}
[2022-12-12T18:18:59.635Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2022-12-12T18:18:59.635Z] assigned listening specs for emulators {"user":{"ui":[{"address":"0.0.0.0","family":"IPv4","port":4000}],"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}]},"metadata":{"message":"assigned listening specs for emulators"}}
[2022-12-12T18:18:59.640Z] [hub] writing locator at /var/folders/fr/ll8j59_j7pd7kyq7sygx_phc0000gn/T/hub-paerpay-web.json
[2022-12-12T18:19:00.654Z] [eventarc] Eventarc Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2022-12-12T18:19:00.654Z] late-assigned ports for functions and eventarc emulators {"user":{"ui":[{"address":"0.0.0.0","family":"IPv4","port":4000}],"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"functions":[{"address":"0.0.0.0","family":"IPv4","port":5001}],"eventarc":[{"address":"127.0.0.1","family":"IPv4","port":9299}]},"metadata":{"message":"late-assigned ports for functions and eventarc emulators"}}
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mauth, firestore, database, hosting, pubsub, storage\u001b[22m"}}
✔  functions: Using node@16 from host. {"metadata":{"emulator":{"name":"functions"},"message":"Using node@16 from host."}}
[2022-12-12T18:19:00.662Z] defaultcredentials: writing to file /Users/rrnara/.config/firebase/ram_paerpay_com_application_default_credentials.json
[2022-12-12T18:19:00.664Z] Setting GAC to /Users/rrnara/.config/firebase/ram_paerpay_com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to /Users/rrnara/.config/firebase/ram_paerpay_com_application_default_credentials.json"}}
[2022-12-12T18:19:00.666Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/paerpay-web/adminSdkConfig [none]
[2022-12-12T18:19:00.961Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/paerpay-web/adminSdkConfig 200
[2022-12-12T18:19:00.961Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/paerpay-web/adminSdkConfig {"projectId":"paerpay-web","databaseURL":"https://paerpay-web.firebaseio.com","storageBucket":"paerpay-web.appspot.com","locationId":"us-central"}
[2022-12-12T18:19:00.993Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[2022-12-12T18:19:00.994Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[2022-12-12T18:19:00.994Z] Starting Emulator UI with command {"binary":"node","args":["/Users/rrnara/.cache/firebase/emulators/ui-v1.11.1/server/server.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/rrnara/.cache/firebase/emulators/ui-v1.11.1/server/server.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[2022-12-12T18:19:01.132Z] Web / API server started at 0.0.0.0:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at 0.0.0.0:4000\n"}}
i  functions: Watching "/Users/rrnara/Work/paerpay/paerpay-web/functions" for Cloud Functions... {"metadata":{"emulator":{"name":"functions"},"message":"Watching \"/Users/rrnara/Work/paerpay/paerpay-web/functions\" for Cloud Functions..."}}
[2022-12-12T18:19:01.265Z] Validating nodejs source
[2022-12-12T18:19:02.769Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "npx eslint ./src --ext .ts",
    "format": "npx eslint ./src --ext .ts --fix",
    "build": "tsc",
    "watch": "tsc -w --preserveWatchOutput",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "remote-login": "npx firebase login --no-localhost",
    "generate-config": "npx firebase functions:config:get > /tmp/.runtimeconfig.json",
    "start": "npx firebase emulators:start --only functions",
    "start-with-ngrok": "./startNgrok.sh && firebase emulators:start --only functions",
    "inspect": "npx firebase emulators:start --only functions --inspect-functions",
    "emulate": "./startNgrok.sh && npx firebase emulators:start --only functions,firestore,auth,storage",
    "test": "FIREBASE_CONFIG={} GCP_PROJECT=test npx jest --watchAll",
    "deploy": "npx firebase use default && firebase deploy --only functions",
    "logs": "npx firebase functions:log",
    "generate": "npx ts-node ./src/migrations/generate.ts",
    "script": "npx ts-node ./src/migrations/script.ts"
  },
  "_moduleAliases": {
    "src": "./lib",
    "cjs_utils": "./src/cjs_utils/"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@curveball/http-errors": "^0.4.1",
    "@google-cloud/bigquery": "^6.0.3",
    "@google-cloud/firestore": "^6.4.1",
    "@google-cloud/functions-framework": "3.1.2",
    "@google-cloud/logging": "^10.3.2",
    "@googlemaps/google-maps-services-js": "^3.3.16",
    "@sendgrid/mail": "^7.7.0",
    "@sentry/node": "^7.25.0",
    "@types/adm-zip": "^0.5.0",
    "@types/node": "^18.11.13",
    "adm-zip": "^0.5.9",
    "axios": "^1.2.1",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "cssjson": "^2.1.3",
    "express": "^4.18.2",
    "express-joi-validation": "^5.0.1",
    "firebase-admin": "^11.3.0",
    "firebase-functions": "^4.1.0",
    "generate-password": "^1.7.0",
    "https": "^1.0.0",
    "joi": "^17.7.0",
    "json-2-csv": "^3.18.0",
    "libphonenumber-js": "^1.10.15",
    "lodash": "^4.17.21",
    "module-alias": "^2.2.2",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.40",
    "pb-util": "^1.0.3",
    "set-cookie-parser": "^2.5.1",
    "stripe": "^11.3.0",
    "twilio": "^3.83.4",
    "typesense": "^1.4.4",
    "winston": "^3.8.2",
    "xml-js": "^1.6.11"
  },
  "devDependencies": {
    "@bonobolabs/firebase-mock": "^3.1.2",
    "@types/assert": "^1.5.6",
    "@types/cookie-parser": "^1.4.3",
    "@types/cors": "^2.8.13",
    "@types/express": "4.17.14",
    "@types/google.maps": "^3.51.0",
    "@types/jest": "^29.2.4",
    "@types/lodash": "^4.14.191",
    "@types/set-cookie-parser": "^2.4.2",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.46.0",
    "@typescript-eslint/parser": "^5.46.0",
    "eslint": "^8.29.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-unused-imports": "^2.0.0",
    "firebase-functions-test": "3.0",
    "firestore-jest-mock": "^0.19.0",
    "glob": "^8.0.3",
    "jest": "^29.3.1",
    "jest-haste-map": "^29.3.1",
    "prettier": "^2.8.1",
    "supertest": "^6.3.3",
    "ts-jest": "^29.0.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  },
  "private": true
}
[2022-12-12T18:19:02.770Z] Building nodejs source
[2022-12-12T18:19:02.770Z] Analyzing nodejs backend spec
[2022-12-12T18:19:02.773Z] Could not find functions.yaml. Must use http discovery
[2022-12-12T18:19:02.942Z] Serving at port 9008

[2022-12-12T18:19:03.754Z] Got response from /__/functions.yaml {"endpoints":{"webhooks":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"webhooks"},"tickets":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"tickets"},"payment":{"availableMemoryMb":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? \"1GiB\" : \"512MiB\" }}","timeoutSeconds":540,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"payment"},"configuration":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"configuration"},"site":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"site"},"onboarding":{"availableMemoryMb":256,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"onboarding"},"organization":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"organization"},"locations":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"locations"},"api":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"api"},"logging":{"availableMemoryMb":512,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"logging"},"users":{"availableMemoryMb":256,"timeoutSeconds":540,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"users"},"search":{"availableMemoryMb":128,"timeoutSeconds":null,"minInstances":"{{ params.MY_FUNCTION_ENVIRONMENT == \"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" ? 1 : 0 }}","maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"search"},"taskrunner":{"availableMemoryMb":2048,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"* * * * *","retryConfig":{}},"entryPoint":"taskrunner"},"instantTaskRunner":{"platform":"gcfv1","availableMemoryMb":256,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.write","eventFilters":{"resource":"projects/paerpay-web/databases/(default)/documents/instantTasks/{eventId}"},"retry":false},"labels":{},"entryPoint":"instantTaskRunner"},"reviewTaskRunner":{"platform":"gcfv1","availableMemoryMb":128,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.update","eventFilters":{"resource":"projects/paerpay-web/databases/(default)/documents/ratings/{ratingId}"},"retry":false},"labels":{},"entryPoint":"reviewTaskRunner"},"syncticketsrunner":{"availableMemoryMb":2048,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"*/3 * * * *","retryConfig":{}},"entryPoint":"syncticketsrunner"},"syncmetadatarunner":{"availableMemoryMb":2048,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"0 2 * * *","retryConfig":{}},"entryPoint":"syncmetadatarunner"},"placeholderRunner":{"platform":"gcfv1","availableMemoryMb":256,"timeoutSeconds":540,"minInstances":1,"maxInstances":null,"ingressSettings":null,"serviceAccountEmail":null,"vpc":null,"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.create","eventFilters":{"resource":"projects/paerpay-web/databases/(default)/documents/placeholders/{placeholderId}"},"retry":false},"labels":{},"entryPoint":"placeholderRunner"},"backuprunner":{"availableMemoryMb":512,"timeoutSeconds":300,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"0 1 * * *","retryConfig":{}},"entryPoint":"backuprunner"},"weeklylocationreportrunner":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"0 4 * * 2","retryConfig":{}},"entryPoint":"weeklylocationreportrunner"},"allcleanup":{"availableMemoryMb":1024,"timeoutSeconds":540,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"0 1 * * *","retryConfig":{}},"entryPoint":"allcleanup"},"migrationrunner":{"availableMemoryMb":512,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"scheduleTrigger":{"schedule":"30 1 * * *","retryConfig":{}},"entryPoint":"migrationrunner"},"analytics":{"availableMemoryMb":256,"timeoutSeconds":null,"minInstances":null,"maxInstances":null,"ingressSettings":null,"concurrency":null,"serviceAccountEmail":null,"vpc":null,"platform":"gcfv2","labels":{},"httpsTrigger":{},"entryPoint":"analytics"}},"specVersion":"v1alpha1","requiredAPIs":[{"api":"cloudscheduler.googleapis.com","reason":"Needed for scheduled functions."}],"params":[{"name":"MY_FUNCTION_ENVIRONMENT","type":"string","default":"staging"}]}
[2022-12-12T18:19:03.766Z] shutdown requested via /__/quitquitquit

{"severity":"ERROR","message":"Error: ngrok failed to start\n    at entryFromArgs (/Users/rrnara/Work/paerpay/paerpay-web/functions/node_modules/firebase-functions/lib/logger/index.js:130:19)\n    at Object.error (/Users/rrnara/Work/paerpay/paerpay-web/functions/node_modules/firebase-functions/lib/logger/index.js:116:11)\n    at getNgrokUrl (/Users/rrnara/Work/paerpay/paerpay-web/functions/lib/services/ngrok.js:25:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async assignRedirectUrl (/Users/rrnara/Work/paerpay/paerpay-web/functions/lib/services/stripe.js:34:26)"}
? Enter a string value for MY_FUNCTION_ENVIRONMENT: staging
i  functions: Created new local file .env.paerpay-web to store param values. We suggest explicitly adding or excluding this file from version control.
i  functions: Loaded environment variables from .env.paerpay-web.
i  functions: Loaded environment variables from .env.paerpay-web.
i  functions: Writing new parameter values to disk: .env.paerpay-web
⬢  functions: Failed to load function definition from source: FirebaseError: CEL tried to evaluate param."production" ? 1 : params.MY_FUNCTION_ENVIRONMENT == "demo" in a context which only permits literal values {"metadata":{"emulator":{"name":"functions"},"message":"Failed to load function definition from source: FirebaseError: CEL tried to evaluate param.\"production\" ? 1 : params.MY_FUNCTION_ENVIRONMENT == \"demo\" in a context which only permits literal values"}}

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4000/               │
└─────────────────────────────────────────────────────────────┘

┌───────────┬──────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port    │ View in Emulator UI             │
├───────────┼──────────────┼─────────────────────────────────┤
│ Functions │ 0.0.0.0:5001 │ http://127.0.0.1:4000/functions │
└───────────┴──────────────┴─────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

^C[2022-12-12T18:19:13.845Z] Received signal SIGINT (Ctrl-C) 1

i  emulators: Received SIGINT (Ctrl-C) for the first time. Starting a clean shutdown.
i  emulators: Please wait for a clean shutdown or send the SIGINT (Ctrl-C) signal again to stop right now.
i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
i  ui: Stopping Emulator UI {"metadata":{"emulator":{"name":"ui"},"message":"Stopping Emulator UI"}}
[2022-12-12T18:19:13.847Z] Ignoring signal SIGINT due to short delay of 2ms
⚠  Emulator UI has exited upon receiving signal: SIGINT
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
i  eventarc: Stopping Eventarc Emulator {"metadata":{"emulator":{"name":"eventarc"},"message":"Stopping Eventarc Emulator"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
i  logging: Stopping Logging Emulator {"metadata":{"emulator":{"name":"logging"},"message":"Stopping Logging Emulator"}}
```

**Comment by rrnara** [comment]
Any updates on this? What is the suggested way to have ternary of environment variable on startup? We are using documented way and it doesn't work locally

**Comment by rrnara** [comment]
Changed our code to instead use:
```
JSON.parse(process.env.FIREBASE_CONFIG).projectId
```

**Comment by Berlioz** [comment]
Hello--I'm glad you came up with a solution that works for you, and I'm sorry we let this one fall through the cracks over the holidays. I'm trying to figure out what happened to you and how to reproduce the error, and I'm having some trouble here.

On the most recent versions of firebase-tools and firebase-functions, I can't reproduce the error*. Your bug report says that firebase-tools is on v11.0.1, but the ability to use params at all shouldn't have existed back then--the error is clearly from the CEL parsing engine in src/deploy/functions/cel.ts but that file didn't even exist in the 11.0.1 release branch. In the logs we can see some hideously malformed CEL being generated by firebase-functions, so whatever happened to you is likely part of a bug in that repo, but you have it pinned to ^4.1.0 and I've tried to reproduce this in all the versions of firebase-functions since then.

* if I'm understanding the bug report correctly,
```
const params = require('firebase-functions/params');
const { onRequest } = require('firebase-functions/v2/https');

export const MY_FUNCTION_ENVIRONMENT = params.defineString('MY_FUNCTION_ENVIRONMENT', { default: 'development' });

export const hello = onRequest(
  {minInstances: MY_FUNCTION_ENVIRONMENT.equals('production').thenElse(1, 0), cpu: 1},
  (_:any, res:any) => {
    res.send(`hello world`);
  }
);
```
should have triggered your issue.

**Comment by bkendall** [comment]
@rrnara let us know if you're still seeing this issue! thanks!

**Comment by rrnara** [comment]
Yes that is how we coded up. Local startup in emulator was failing

**Comment by taeold** [comment]
@rrnara Sorry for a late followup. I did my best to reproduce the error locally, but it seems that latest CLI/SDK version should resolve the issue. Do you mind trying them once more?

**Comment by rrnara** [comment]
We have moved on to making our code to use JSON.parse(process.env.FIREBASE_CONFIG).projectId. But if I get some time in future to try this out, I will try it and let you know. Thanks for looking into this

**Comment by taeold** [comment]
@rrnara Good to hear.

Just noticed that if you are after projectId, you can access it via `process.env.GCLOUD_PROJECT`.
