### ISSUE TITLE
Deploy functions fails with: Error: Failed to fetch Run service undefined 

### ISSUE THREAD

**Issue by smorgrav** [firebase/firebase-tools#5326]
### [REQUIRED] Environment info

**firebase-tools: 11.8.0 and 11.6.0**

**Platform: macOS and Ubuntu**

### [REQUIRED] Test case

Sorry, I'm not going to do that. If the provided description is not enough - than fair enough, 

### [REQUIRED] Steps to reproduce

firebase deploy --project myproject --only functions

### [REQUIRED] Expected behavior

The deployment should go through

### [REQUIRED] Actual behavior

Debug run ends with: 

[2022-12-13T10:48:06.100Z] FirebaseError: Failed to make request: Cannot read property 'startsWith' of undefined
    at Client.request (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/apiv2.js:112:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getService (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/gcp/run.js:17:26)
    at async Promise.all (index 0)
    at async loadExistingBackend (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/deploy/functions/backend.js:199:28)
    at async Object.existingBackend (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/deploy/functions/backend.js:175:9)
    at async prepare (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/deploy/functions/prepare.js:110:115)
    at async chain (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/Users/smorgrav/dev/myproject/node_modules/firebase-tools/lib/deploy/index.js:68:5)

A little digging found that as for version 11.8.0 the backend.js at line 199, the map is mapping to a non existing property called service. 

backend.js line 199:  const runResults = await Promise.all(gcfV2Results.functions.map((fn) => run.getService(fn.serviceConfig.service)));

There are three service configs mapped here in my case. One example here is the serviceConfig for the rest api:

{
  timeoutSeconds: 60,
  environmentVariables: {
    FIREBASE_CONFIG: '{"projectId":"myproject","storageBucket":"myproject","locationId":"europe-west"}',
    GCLOUD_PROJECT: 'myproject'
  },
  ingressSettings: 'ALLOW_ALL',
  uri: 'https://us-central1-myproject.cloudfunctions.net/api',
  serviceAccountEmail: 'myproject@appspot.gserviceaccount.com',
  availableMemory: '256M',
  revision: '206',
  maxInstanceRequestConcurrency: 1,
  securityLevel: 'SECURE_OPTIONAL'
}

Since the property service is not present - this eventually ends up as a non existing path variable for the option object passed in at doRequest inn apiv2.js. 

And here to goes boom:
apiv2.js line 158:  if (!options.path.startsWith("/")) {

---- 
There has been a some weeks from last time I deployed new functions so I'm not sure when it started. Rerunning the github actions that was running successfully some weeks ago, now fails.

**Comment by smorgrav** [comment]
So it looks like this is spesifically linked to listing functions. The behavior above is replicated with the command:

`firebase functions:list`

[2022-12-13T13:00:47.653Z] FirebaseError: Failed to fetch Run service undefined
    at Object.getService (/Users/smorgrav/.nvm/versions/node/v16.6.0/lib/node_modules/firebase-tools/lib/gcp/run.js:21:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async loadExistingBackend (/Users/smorgrav/.nvm/versions/node/v16.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:199:28)
    at async Object.existingBackend (/Users/smorgrav/.nvm/versions/node/v16.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:175:9)
    at async Command.actionFn (/Users/smorgrav/.nvm/versions/node/v16.6.0/lib/node_modules/firebase-tools/lib/commands/functions-list.js:19:26)

**Comment by smorgrav** [comment]
argh... When updating tools I updated from 11.6.0 to 11.8.0 while the newest was indeed 11.18.0 - with the new firebase-tools library installed it seems to be all good

**Comment by omar-dev-amrk** [comment]
I'm facing this issue today surprisingly!

Last deployment was 2 days ago and everything was working fine. I didn't update any packages in the system.
The firebase-tools version I use is `10.9.2`. Upgrading it to latest version is not an option for me at the time being.

What other options do I have?
I checked the updates that were installed on my Ubuntu system, and it seems like google cloud cli was updated after the last successful deployment, So I suspect it to be the cause.

I downgraded from 412.0.0-0 to 411 and 410 but still same issue.

Any help?

**Comment by rendomnet** [comment]
Why we even forced to update if our current version is working fine?

**Comment by brschwalm** [comment]
I am blocked from upgrading firebase-tools past version 10.9.2 due to [this bug](https://github.com/firebase/firebase-tools/issues/5654), and I cannot upgrade firebase-functions past 3.24.1 due to [this bug](https://github.com/firebase/firebase-functions/issues/1263), and the tools version above. I've spent the last 3 days figuring out which versions of the libraries work (and work together). And now that I have it all working, I can't deploy it.

So upgrading to the latest version is not a solution while there are active blocking bugs with the current versions. is there another solution to this issue? I am using CI, so manually deleting all the functions from the console before deploying is not an option.

@omar-dev-amrk it looks like you were blocked from upgrading firebase-tools as well, did you find a solution?
