### ISSUE TITLE
deploy fail

### ISSUE THREAD

**Issue by PhilipBrodovsky** [firebase/firebase-tools#5362]
firebase deploy error:

[debug] [2022-12-22T18:43:31.460Z] TypeError: Cannot read properties of null (reading 'toString')
    at ɵcodegenFunctionsDirectory (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\next\index.js:220:18)
    at async prepareFrameworks (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:305:84)
    at async deploy (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:53:13)
[error]

version: 11.19.0

**Comment by bkendall** [comment]
Please follow the template and provide a little more details in a new issue about this error. Thanks.
