### ISSUE TITLE
[emulator] HTTP 408 Response missing data using auth emulator

### ISSUE THREAD

**Issue by yharaskrik** [firebase/firebase-tools#5446]
### [REQUIRED] Environment info

**firebase-tools:*10.6.0*

**Platform:*Ubuntu*

### [REQUIRED] Test case

I am not able to reproduce it outside of our repository and only happens while in a CI environment. Open to ideas on how to create a repo if anyone has ideas. It is not consistently reproducible even in our CI, only happens every so often and a rerun works every time.

### [REQUIRED] Steps to reproduce

Spin up emulator using `node node_modules/.bin/firebase emulators:start` with a firebase.json

```
{
    "emulators": {
        "auth": {
            "port": 9117
        },
        "ui": {
            "enabled": true,
            "port": 4117
        },
        "logging": {
            "port": 4517
        },
        "hub": {
            "port": 4417
        }
    }
}
```

Our E2E tests using Jest and Supertest run by spinning up a Nestjs API in memory and making requests to it. Issue comes up every so often with no detectible patterns.

### [REQUIRED] Expected behavior

Emulator does not return HTTP 408 errors.

### [REQUIRED] Actual behavior

```
Error while parsing response data: "Error: HTTP response missing data.". Raw server response: "". Status code: "408". Outgoing request: "POST http://localhost:9114/identitytoolkit.googleapis.com/v1/projects/<app-name>/accounts:lookup."
```

The only debug logs I see are
```
[2023-01-20T20:14:52.446Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
Failed to authenticate, have you run firebase login?
⚠  emulators: You are not currently authenticated so some features may not work correctly. Please run firebase login to authenticate the CLI. 
i  emulators: Starting emulators: auth {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth"}}
[2023-01-20T20:14:52.486Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2023-01-20T20:14:52.486Z] [auth] Authentication Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2023-01-20T20:14:52.486Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4402},{"address":"::1","family":"IPv6","port":4402}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4102},{"address":"::1","family":"IPv6","port":4102}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4502}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9102}]},"metadata":{"message":"assigned listening specs for emulators"}}
[2023-01-20T20:14:52.508Z] [hub] writing locator at /tmp/hub-<project name>.json
```

There is some failed to authenticate stuff in there but those logs are also outputted for e2e tests that spin up emulators and also pass so I think its a red herring. We aren't using any functionality that would require authentication with the CLI I don't think, just the Auth emulator.

**Comment by christhompsongoogle** [comment]
It looks like it's trying to authenticate the specified user. Are you using a service account or a regular account? if you use the project ID prefix `demo-` does it work then?

**Comment by yharaskrik** [comment]
> It looks like it's trying to authenticate the specified user. Are you using a service account or a regular account? if you use the project ID prefix `demo-` does it work then?


Hey Chris, I do not think we are authenticating at all when using the emulators here, just spinning them up to have the auth backend available during end to end tests (we are only using auth). I can try the different prefix but I don't think that will have any effect as these tests are not failing every time, instead, they seem to be flaky when running in parallel. A rerun makes them pass the next time through (where some would be cached so the failed isn't running alongside any others during the rerun). I have switched our CI to running in serial now and haven't seen this happen since so my guess is it is something to do with spinning up multiple emulators in parallel but can't find anything that would be conflicting (I have confirmed they are all running on different ports)

**Comment by christhompsongoogle** [comment]
Interesting ... my hunch was that sometimes the emulators DO call out to production for some specific cases (hosting for example). Full disclosure: running multiple emulators in parallel isn't a primary use-case and without a clear repro it's hard for me to pin this one down. I'll leave it open in case anyone else encounters similar behavior.

**Comment by yharaskrik** [comment]
> Interesting ... my hunch was that sometimes the emulators DO call out to production for some specific cases (hosting for example). Full disclosure: running multiple emulators in parallel isn't a primary use-case and without a clear repro it's hard for me to pin this one down. I'll leave it open in case anyone else encounters similar behavior.

Duly noted thank you! I guess an alternative would be to run a single emulator and use that emulator for all our e2e suites then hey>

**Comment by yharaskrik** [comment]
Looks like I just ran into this again and I am only running a single emulator at a time now.

```
Error while parsing response data: "Error: HTTP response missing data.". Raw server response: "". Status code: "408". Outgoing request: "POST http://localhost:9111/identitytoolkit.googleapis.com/v1/projects/*******/accounts:lookup."

      22 |     async checkEmailExists(email: string): Promise<boolean> {
      23 |         try {
    > 24 |             const user = await this.auth.getUserByEmail(email.toLowerCase());
         |                          ^
      25 |             return user != null;
      26 |         } catch (e) {

      at FirebaseAppError.FirebaseError [as constructor] (../../../node_modules/firebase-admin/lib/utils/error.js:44:28)
      at FirebaseAppError.PrefixedFirebaseError [as constructor] (../../../node_modules/firebase-admin/lib/utils/error.js:90:28)
      at new FirebaseAppError (../../../node_modules/firebase-admin/lib/utils/error.js:125:28)
      at DefaultHttpResponse.get (../../../node_modules/firebase-admin/lib/utils/api-request.js:65:19)
      at ../../../node_modules/firebase-admin/lib/auth/auth-api-request.js:1563:42
```

Reruns fix it (seems to be flaky as noted originally)
