### ISSUE TITLE
An error when running "firebase remoteconfig:get" with no version

### ISSUE THREAD

**Issue by yuvalyellin** [firebase/firebase-tools#5497]
### [REQUIRED] Environment info

9.23.1

macOS

### [REQUIRED] Test case

When -v is not supplied, an error occurs 

### [REQUIRED] Steps to reproduce

`firebase remoteconfig:get  -o template1.json` 

### [REQUIRED] Expected behavior
 latest version should be saved when no version is supplied

### [REQUIRED] Actual behavior

[2023-02-09T17:22:07.035Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-02-09T17:22:07.036Z] > authorizing via signed-in user (********)
[2023-02-09T17:22:07.037Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-02-09T17:22:07.037Z] > authorizing via signed-in user (********)
[2023-02-09T17:22:07.037Z] [iam] checking project pangea-stage for permissions ["cloudconfig.configs.get","firebase.projects.get"]
[2023-02-09T17:22:07.047Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/***:testIamPermissions  
 {"permissions":["cloudconfig.configs.get","firebase.projects.get"]}
[2023-02-09T17:22:08.541Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Thu, 09 Feb 2023 17:22:08 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=857","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","accept-ranges":"none","transfer-encoding":"chunked"}
[2023-02-09T17:22:08.758Z] AssertionError [ERR_ASSERTION]: expected "string" but got "undefined"
    at new AssertionError (node:internal/assert/assertion_error:466:5)
    at Object.assertIsString (/Users//.npm-packages/lib/node_modules/firebase-tools/lib/utils.js:368:15)
    at Command.actionFn (/Users//.npm-packages/lib/node_modules/firebase-tools/lib/commands/remoteconfig-get.js:29:11)
    at /Users//.npm-packages/lib/node_modules/firebase-tools/lib/command.js:190:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: An unexpected error has occurred.

**Comment by aalej** [comment]
Hi @yuvalyellin, thanks for filing this issue. I tried running the `firebase remoteconfig:get  -o template1.json` command without passing the -v option and I did not encounter any errors.

I noticed that you mentioned `9.23.1`. Just to verify, are you using firebase-tools v9.23.1? If you are, could you try updating to the latest version of firebase-tools, which is currently v11.22.0, to see if that would fix the issue? Also, there was previously this similar issue [#3559](https://github.com/firebase/firebase-tools/issues/3559) which was fixed in firebase-tools [v9.23.2](https://github.com/firebase/firebase-tools/releases/tag/v9.23.2).

**Comment by yuvalyellin** [comment]
It is working in the latest version, 
I am not sure why it didn't ask me to upgrade the package like it used to, but after upgrading it works, 
Thank you.
