### ISSUE TITLE
CHANGELOG.md missing from extensions template

### ISSUE THREAD

**Issue by cabljac** [firebase/firebase-tools#5530]
### [REQUIRED] Environment info

**firebase-tools:** 11.20.0 and 11.23.1

**Platform:** macOS

### [REQUIRED] Test case

(this is a CLI issue)

### [REQUIRED] Steps to reproduce

In a fresh directory run `firebase ext:dev:init` and follow prompts

### [REQUIRED] Expected behavior

The command should execute without error and create an extension project from the template in the directory

### [REQUIRED] Actual behavior

Complains that CHANGELOG.md is missing in the template. If I manually add the changelog file, the command works.

<img width="1283" alt="Screenshot 2023-02-17 at 10 42 12" src="https://user-images.githubusercontent.com/32874567/219622298-ee6fa64e-dcd6-42e2-903b-55d18fdc69f8.png">

```
❯ firebase ext:dev:init --debug
? In which language do you want to write the Cloud Functions for your extension? JavaScript
? Do you want to use ESLint to catch probable bugs and enforce style? No
[2023-02-17T10:43:00.380Z] Error: ENOENT: no such file or directory, open '/Users/jacobcable/.nvm/versions/node/v14.19.1/lib/node_modules/firebase-tools/templates/extensions/CHANGELOG.md'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at readCommonTemplates (/Users/jacobcable/.nvm/versions/node/v14.19.1/lib/node_modules/firebase-tools/lib/commands/ext-dev-init.js:27:31)
    at javascriptSelected (/Users/jacobcable/.nvm/versions/node/v14.19.1/lib/node_modules/firebase-tools/lib/commands/ext-dev-init.js:131:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.actionFn (/Users/jacobcable/.nvm/versions/node/v14.19.1/lib/node_modules/firebase-tools/lib/commands/ext-dev-init.js:55:17)

Error: Error occurred when initializing files for new extension: ENOENT: no such file or directory, open '/Users/jacobcable/.nvm/versions/node/v14.19.1/lib/node_modules/firebase-tools/templates/extensions/CHANGELOG.md'
```

**Comment by joehan** [comment]
I'm pretty confused by this one, since https://github.com/firebase/firebase-tools/blob/master/templates/extensions/CHANGELOG.md exists, and I'm not able to replicate it locally. My best guess is that there is something that throws away the CHANGELOG.md when firebase-tools is pacakged?

Will keep digging.

**Comment by joehan** [comment]
Update - with help from @ifielker, I've repro'd this and I'm working on a fix

**Comment by cabljac** [comment]
awesome, thanks!
