### ISSUE TITLE
SyntaxError: Invalid regular expression: /(?P<basename>.*)\.html$/: Invalid group

### ISSUE THREAD

**Issue by MeandNi** [firebase/firebase-tools#5541]
### [REQUIRED] Environment info

**firebase-tools:** 11.16.0

**Platform:** macOS

### [REQUIRED] Steps to reproduce

When I visit `localhost:5500`, the terminal will automatically exit and display Error: An unexpected error has occurred.

### [REQUIRED] Expected behavior

can visit my website

### [REQUIRED] Actual behavior

```
[debug] [2023-02-21T06:42:38.573Z] ----------------------------------------------------------------------
[debug] [2023-02-21T06:42:38.578Z] Command:       /opt/homebrew/Cellar/node/19.6.1/bin/node /opt/homebrew/bin/firebase emulators:start --only hosting --project default
[debug] [2023-02-21T06:42:38.578Z] CLI Version:   11.16.0
[debug] [2023-02-21T06:42:38.578Z] Platform:      darwin
[debug] [2023-02-21T06:42:38.578Z] Node Version:  v19.6.1
[debug] [2023-02-21T06:42:38.578Z] Time:          Tue Feb 21 2023 14:42:38 GMT+0800 (China Standard Time)
[debug] [2023-02-21T06:42:38.578Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-02-21T06:42:38.625Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-02-21T06:42:38.626Z] > authorizing via signed-in user (yangjiakay@gmail.com)
[info] i  emulators: Starting emulators: hosting {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: hosting"}}
[debug] [2023-02-21T06:42:39.614Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-02-21T06:42:39.615Z] assigned listening specs for emulators {"user":{"hosting":[{"address":"0.0.0.0","family":"IPv4","port":5100}],"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}]},"metadata":{"message":"assigned listening specs for emulators"}}
[warn] ⚠  emulators: It seems that you are running multiple instances of the emulator suite for project flutter-docs-prod. This may result in unexpected behavior. 
[debug] [2023-02-21T06:42:39.618Z] [hub] writing locator at /var/folders/px/d4rysvx16x7dtjvccxtpdw640000gn/T/hub-flutter-docs-prod.json
[debug] [2023-02-21T06:42:39.626Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/flutter-docs-prod/sites 
[debug] [2023-02-21T06:42:40.407Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/flutter-docs-prod/sites 403
[debug] [2023-02-21T06:42:40.407Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/flutter-docs-prod/sites {"error":{"code":403,"message":"Permission 'firebasehosting.sites.get' denied on resource 'projects/flutter-docs-prod' (or it may not exist)","status":"PERMISSION_DENIED"}}
[debug] [2023-02-21T06:42:40.408Z] Failed to list hosting sites
[debug] HTTP Error: 403, Permission 'firebasehosting.sites.get' denied on resource 'projects/flutter-docs-prod' (or it may not exist)
[debug] [2023-02-21T06:42:40.409Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod/webApps/-/config [none]
[debug] [2023-02-21T06:42:40.947Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod/webApps/-/config 403
[debug] [2023-02-21T06:42:40.947Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod/webApps/-/config {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-02-21T06:42:40.947Z] fetchWebSetup error: FirebaseError: HTTP Error: 403, The caller does not have permission
[warn] ⚠  hosting: Authentication error when trying to fetch your current web app configuration, have you run firebase login? 
[warn] ⚠  hosting: Could not fetch web app configuration and there is no cached configuration on this machine. Check your internet connection and make sure you are authenticated. To continue, you must call firebase.initializeApp({...}) in your code before using Firebase. 
[debug] [2023-02-21T06:42:40.950Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod [none]
[debug] [2023-02-21T06:42:41.542Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod 403
[debug] [2023-02-21T06:42:41.542Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/flutter-docs-prod {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-02-21T06:42:41.542Z] HTTP Error: 403, The caller does not have permission
[info] i  hosting[flutter-docs-prod]: Serving hosting files from: _site {"metadata":{"emulator":{"name":"hosting"},"message":"Serving hosting files from: \u001b[1m_site\u001b[22m"}}
[info] ✔  hosting[flutter-docs-prod]: Local server: http://0.0.0.0:5100 {"metadata":{"emulator":{"name":"hosting"},"message":"Local server: \u001b[4m\u001b[1mhttp://0.0.0.0:5100\u001b[22m\u001b[24m"}}
[warn] ⚠  emulators: The Emulator UI is not starting, either because none of the emulated products have an interaction layer in Emulator UI or it cannot determine the Project ID. Pass the --project flag to specify a project. {"metadata":{"emulator":{"name":"hub"},"message":"The Emulator UI is not starting, either because none of the emulated products have an interaction layer in Emulator UI or it cannot determine the Project ID. Pass the --project flag to specify a project."}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌──────────┬──────────────┐
│ Emulator │ Host:Port    │
├──────────┼──────────────┤
│ Hosting  │ 0.0.0.0:5100 │
└──────────┴──────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
[debug] [2023-02-21T06:42:44.527Z] SyntaxError: Invalid regular expression: /(?P<basename>.*)\.html$/: Invalid group
    at new RegExp (<anonymous>)
    at Object.createRaw (/opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/utils/patterns.js:51:42)
    at new Redirect (/opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/middleware/redirects.js:41:37)
    at /opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/middleware/redirects.js:105:32
    at Array.forEach (<anonymous>)
    at /opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/middleware/redirects.js:103:20
    at _run (/opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/activator.js:48:24)
    at /opt/homebrew/lib/node_modules/firebase-tools/node_modules/superstatic/lib/activator.js:50:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by MeandNi** [comment]
It should be my configuration problem, please close this issue.
