### ISSUE TITLE
firebase init firestore

### ISSUE THREAD

**Issue by lucafaggianelli** [firebase/firebase-tools#555]
### Version info

firebase-tools v3.6.0

### Steps to reproduce

run `firebase init firestore` in a project folder or in an empty folder

### Expected behavior

It should create template files with rules and indexes and link those files paths to firebase.json

### Actual behavior

An error occurs

```
=== Firestore Setup
TypeError: features[nextFeature] is not a function
    at init (/usr/local/lib/node_modules/firebase-tools/lib/init/index.js:14:46)
    at /usr/local/lib/node_modules/firebase-tools/lib/init/index.js:15:14
    at tryCatch (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/usr/local/lib/node_modules/firebase-tools/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Error: An unexpected error has occurred.
```

Now I created the file on my own, but which prop should I add in firebase.json to point the rules file?

**Comment by lucafaggianelli** [comment]
For some reasons the tool wasn't updated
