### ISSUE TITLE
Firebase tools cannot deploy on Node v9.x

### ISSUE THREAD

**Issue by Tivoli** [firebase/firebase-tools#557]
This is probably due to the current version of `tar` being used by firebase-tools.

### Version info
3.16.0

### Steps to reproduce
Install node@9.2.x
firebase deploy --only hosting

### Expected behavior
Firebase should deploy the application

### Actual behavior
```
i  deploying hosting
i  hosting: preparing clients/web-app/build directory for upload...
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node[10834]: ../src/node_zlib.cc:437:static void node::(anonymous namespace)::ZCtx::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 2: node::(anonymous namespace)::DomainEnter(node::Environment*, v8::Local<v8::Object>) [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 3: node::(anonymous namespace)::ZCtx::Init(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/Tivs/.nvm/versions/node/v9.2.0/bin/node]
 7: 0x622099042fd
error Command failed with signal "SIGABRT".
```

**Comment by Sam3077** [comment]
Install nvm (https://github.com/creationix/nvm)
uninstall node:
`brew uninstall node`
install node version 7.10.1 using nvm
`nvm install 7.10.1`

navigate to your project directory and run
`firebase deploy --only hosting`

**Comment by rof20004** [comment]
I got this issue too, right now '-'

**Comment by andrioli** [comment]
Same issue here with Node v9.4.0 on macOS with firebase-tools 3.17.4.

During install phase (i'm running yarn 1.3.2) I got the following warning:

```
warning Error running install script for optional dependency:

/Users/me/project/node_modules/grpc: Command failed.
Exit code: 1
Command: ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: /Users/me/project/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@9.4.0 | darwin | x64
node-pre-gyp info check checked for "/Users/me/project/node_modules/grpc/src/node/extension_binary/grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/project/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/9.4.0/bin/node...
```

During deploy the error is the following:

```
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
node[61985]: ../src/node_zlib.cc:437:static void node::(anonymous namespace)::ZCtx::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::Assert(char const* const (*) [4]) [/usr/local/bin/node]
 3: node::(anonymous namespace)::ZCtx::Init(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1b159cb042fd
 8: 0x1b159cbbd196
```

Is working perfectly with Node v6.11.5 (the one that Firebase team [recommend](https://firebase.google.com/docs/functions/get-started#set_up_and_initialize) for developing functions locally as is the version used in Cloud Functions)

**Comment by andrioli** [comment]
Not sure the warning is related to the error (I guess not as `grpc` is used only by optional dependency `functions-emulator`).
