### ISSUE TITLE
TypeError: Cannot destructure property 'on' of 'loadYML(...)' as it is undefined.

### ISSUE THREAD

**Issue by mhansen** [firebase/firebase-tools#5581]
### [REQUIRED] Environment info

**firebase-tools:** Firebase 11.24.1

**Platform:** macOS

### [REQUIRED] Test case

Run

```
$ firebase init hosting:github
```

### [REQUIRED] Steps to reproduce

Run

```
$ firebase init hosting:github
```

### [REQUIRED] Expected behavior

No errors

### [REQUIRED] Actual behavior

I'm not including all the logs as they include secrets. Here's the last bit:

```
? Set up the workflow to run a build script before every deploy? Yes
? What script should be run before every deploy? npm ci && npm run build
[2023-03-08T10:21:19.107Z] TypeError: Cannot destructure property 'on' of 'loadYML(...)' as it is undefined.
    at loadYMLDeploy (/opt/homebrew/lib/node_modules/firebase-tools/lib/init/features/hosting/github.js:141:17)
    at initGitHub (/opt/homebrew/lib/node_modules/firebase-tools/lib/init/features/hosting/github.js:72:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/opt/homebrew/lib/node_modules/firebase-tools/lib/init/index.js:36:9)
```

**Comment by aalej** [comment]
Hey, apologies for the late response here, this issue fell through the cracks. I can't reproduce this using the latest version of firebase-tools, currently v15.11.0, so it looks like this issue is fixed.  Running `firebase init hosting:github` correctly sets up the yml files for the GitHub workflows.

I'm going to close this issue, however if you're still encountering this issue using the latest version, just let us know and we'll re-open this.
