### ISSUE TITLE
Error: Cannot find module 'p-limit'

### ISSUE THREAD

**Issue by bkendall** [firebase/firebase-tools#5619]
### [REQUIRED] Environment info

**firebase-tools:** v11.25.0

**Platform:** macOS

### [REQUIRED] Test case

see below

### [REQUIRED] Steps to reproduce

```bash
nvm i 18 
npm i -g firebase-tools
firebase login
```

Turned out I _was_ logged in - downgrading to v11.24 worked fine.

### [REQUIRED] Expected behavior

Not a crash!

### [REQUIRED] Actual behavior

```
» firebase login
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'p-limit'
Require stack:
- /Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/database/import.js
- /Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/commands/database-import.js
- /Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/commands/index.js
- /Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/index.js
- /Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/database/import.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/commands/database-import.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/database/import.js',
    '/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/commands/database-import.js',
    '/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/commands/index.js',
    '/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/index.js',
    '/Users/bkend/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/bin/firebase.js'
  ]
}

Node.js v18.15.0
```

**Comment by aaronadamsCA** [comment]
Can confirm, this just broke our GitHub Actions.

**Comment by joehan** [comment]
Looks like we let a bit of code with a missing dependency slip in. Working on a patch ASAP, but in the mean time please use the previous version.

**Comment by bkendall** [comment]
FWIW, if you're using `FirebaseExtended/action-hosting-deploy`, you can set [`firebaseToolsVersion`](https://github.com/FirebaseExtended/action-hosting-deploy#firebasetoolsversion-string) to `v11.24` to use the previous version.

**Comment by leonardorb** [comment]
Yes. It broke our GitHub Actions.
```
Error: Cannot find module 'p-limit'
Require stack:
- /home/runner/.config/yarn/global/node_modules/firebase-tools/lib/database/import.js
- /home/runner/.config/yarn/global/node_modules/firebase-tools/lib/commands/database-import.js
- /home/runner/.config/yarn/global/node_modules/firebase-tools/lib/commands/index.js
- /home/runner/.config/yarn/global/node_modules/firebase-tools/lib/index.js
- /home/runner/.config/yarn/global/node_modules/firebase-tools/lib/bin/firebase.js
```

**Comment by shadow1349** [comment]
I'm seeing the same issue

**Comment by dustinlyons** [comment]
Yep, impacted.

**Comment by joehan** [comment]
@dustinlyons If you want to tie to a specific version, as described on firebase.tools:
```
# Alternatively, you can download a specific version.
#
:   curl -Lo ./firebase_bin https://firebase.tools/bin/linux/v7.2.2
```

FWIW, the release job for 11.25.1 is running right now, and we are going to address the hole in our CI that let this slip through. Apologies for the trouble everyone!

**Comment by SpencerMartel** [comment]
Same issue just accessing through the CLI, glad to see its being worked on

**Comment by joehan** [comment]
11.25.1 has been released with a fix for this issue. Apologies everyone!

**Comment by SpencerMartel** [comment]
Fixes it for me, I appreciate the quick response to the issue!! @joehan

**Comment by dustinlyons** [comment]
Thank you for the quick response!
