### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '/www-data-home/.config/configstore' with node 18 on deploy

### ISSUE THREAD

**Issue by devloic** [firebase/firebase-tools#5672]
### [REQUIRED] Environment info

**firebase-tools:**
11.25.3

**Platform:**
macOS
### [REQUIRED] Test case
firebase deploy

### [REQUIRED] Steps to reproduce
firebase deploy --only functions
with 
package.json :
...
"engines": {
    "node": "18"
  }
...
 "firebase-tools": "^11.25.3"
...

### [REQUIRED] Expected behavior

I expect a deployment on google cloud.
If I change to node 16 deployment works again.

### [REQUIRED] Actual behavior

Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: ENOENT: no such file or directory, mkdir '/www-data-home/.config/configstore'
    at Object.mkdirSync (node:fs:1396:3)
    at module.exports.sync (/workspace/node_modules/firebase-tools/node_modules/make-dir/index.js:114:6)
    at set all [as all] (/workspace/node_modules/firebase-tools/node_modules/configstore/index.js:59:12)
    at Configstore.set (/workspace/node_modules/firebase-tools/node_modules/configstore/index.js:91:12)
    at Object.<anonymous> (/workspace/node_modules/firebase-tools/lib/track.js:20:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
Could not load the function, shutting down.
. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

Functions deploy had errors with the following functions:
        myfunction(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions

**Comment by aalej** [comment]
Hi @devloic, thanks for reaching out to us. It looks like the issue you described is similar to  [#5672](https://github.com/firebase/firebase-tools/issues/5631). A fix([#5666](https://github.com/firebase/firebase-tools/pull/5666)) has been created to address this issue. With this, I’ll be closing this ticket as a duplicate.

For now, I can only recommend downgrading to node 16 while waiting for the fix to be released. Thank you for your patience and apologies for the inconvenience this may have caused.

**Comment by devloic** [comment]
release https://github.com/firebase/firebase-tools/releases/tag/v11.26.0 fixes the issue

updated package.json with 

"firebase-tools": "^11.26.0"
"engines": {
"node": "18"
}

and redeployed.

Thanks for the fix!
