### ISSUE TITLE
Firebase Function deploy build fails but predeploy succeeded

### ISSUE THREAD

**Issue by Roee-Tsur** [firebase/firebase-tools#5738]
I have a react.js project with Firebase functions configured in a sub-folder: root/functions. The functions are written in typescript and have paths option configured in tsconfig.json. In my functions/index.ts file I import multiple files from all over the project, not only from the functions directory.

I have deployed my functions successfully multiple times.

Now the functions build successfully but fail when deploying. error TS2307: Cannot find module '@/custom/file' or its corresponding type declarations. I get this error for all 8 custom files that I import.

The confusing part is that the function builds without a problem locally but only fails when Firebase tries to update the function remotely.

versions:

firebase: ^9.19.1
firebase-admin: ^11.6.0
firebase-functions: ^3.23.0
firebase-tools: 11.16.0

**Comment by oconnorjoseph** [comment]
@cundejo @Roee-Tsur for us, we we're able to resolve this by upgrading firebase-tools to the latest version.

**Comment by oconnorjoseph** [comment]
For more context on the error, the debug logs display the following error message over and over:
```
[error] Error: An unexpected error has occurred.
[debug] [2023-04-26T16:26:22.559Z] Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Console.log (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/winston-transport/index.js:103:17)
    at doWrite (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Console.Writable.write (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DerivedLogger.emit (node:events:402:35)
    at DerivedLogger.emit (node:domain:475:12)
    at addChunk (/home/gitpod/.nvm/versions/node/v16.13.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_readable.js:298:12)
```

**Comment by cundejo** [comment]
Thank you @oconnorjoseph, upgrading `firebase-tools` to 11.29.0 worked for us too.

**Comment by colerogers** [comment]
Hey everyone, we've been trying to make firebase-functions & firebase-tools compatible with a monorepo setup since it was originally designed for a vanilla npm workflow. I'm glad that upgrading to the latest version works for you all. I was going to point out that [v`11.23.1`](https://github.com/firebase/firebase-tools/releases/tag/v11.23.1) fixed some issues folks had with monorepo and was going to ask you to upgrade to at least that version. Thanks for your patience on this monorepo journey!
