### ISSUE TITLE
command:firebase crashlytics : symbols:upload  -  java command failed

### ISSUE THREAD

**Issue by FetFrumos** [firebase/firebase-tools#5761]
[REQUIRED] Environment info

**firebase-tools:11.29.1

**Platform:macOS -Version 13.2.1 (22D68)

info from flutter doctor

`[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2.1 22D68 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] HTTP Host Availability
`

[REQUIRED] Test case

I have flutter app. I working on mac. I used obfuscation for my appbundle. 

`flutter build appbundle --obfuscate  --split-debug-info=symbols`

I get logs for Crashlytics in unreadable form. I found that it is necessary to load symbols on Crashlytics(Firebase). I installed Firebase cli and got my app id. I run it command: 

`firebase crashlytics:symbols:upload --app myId debug-info/app.android-arm64.symbols`

[REQUIRED] Expected behavior
generate a Crashlytics-compatible symbol file and upload it to Firebase servers

[REQUIRED] Actual behavior
The following error was found in the debug log file:

`i  Generating symbols for debug-info-droid/app.android-arm64.symbols
i  Generated symbols for debug-info-droid/app.android-arm64.symbols
.......
i  Uploading all generated symbols...
[CRASHLYTICS LOG DEBUG] PUT headers:
[CRASHLYTICS LOG DEBUG]         User-Agent = firebase-cli;crashlytics-buildtools/2.9.2
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-TYPE = firebase-cli;crashlytics-buildtools
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-VERSION = 2.9.2
[CRASHLYTICS LOG DEBUG] PUT response: [reqId=null] 400
......
response: 400 HTTP/1.1 400 Bad Request]
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:109)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.uploadFile(RestfulWebApi.java:119)
        at com.google.firebase.crashlytics.buildtools.api.FirebaseSymbolFileService.uploadNativeSymbolFile(FirebaseSymbolFileService.java:35)
        at com.google.firebase.crashlytics.buildtools.Buildtools.uploadNativeSymbolFiles(Buildtools.java:301)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeUploadSymbols(CommandLineHelper.java:194)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:120)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
Error: java command failed with args: -jar,/Users/rockstar/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/jg/../nativeSymbols/.../breakpad,-verbose,-uploadNativeSymbols,-googleAppId,myId,-clientName,
firebase-cli;crashlytics-buildtools`

how can i fix this problem?

is it related to java settings on my mac? (But 'flutter doctor' not found issue on ma mac)

maybe i can use another solution to uploading symbols for Android?

**Comment by mrober** [comment]
Thanks for providing the debug logs. It looks like the app id you provided is malformed. The app id should be formatted something like 1:123:android:123abc.... You can find your app id in the Firebase console's project settings page. Then try your command again `firebase crashlytics:symbols:upload --app 1:123:android:123abc debug-info/app.android-arm64.symbols`

I will update the Firebase CLI tool to provide a more meaningful error message for this case.

**Comment by mrober** [comment]
I landed the change to our build tools. It should go out in the next release that includes Crashlytics.

**Comment by FetFrumos** [comment]
Hi @mrober , sorry one more question.
I loadded symbols to crashlistics, but I keep seeing the error "readable"

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'CD'.
BuildId: bca64abf89f4326e31bb8f1c7fb6e819
#00 abs 0000007d00deb837 virt 0000000000403837 _kDartIsolateSnapshotInstructions+0x211eb7
#01 abs 0000007d0115e8a3 virt 00000000007768a3 _kDartIsolateSnapshotInstructions+0x584f23
#02 abs 0000007d00c18783 virt 0000000000230783 _kDartIsolateSnapshotInstructions+0x3ee03
#03 abs 0000007d00dea32b virt 000000000040232b _kDartIsolateSnapshotInstructions+0x2109ab
#04 abs 0000007d011a1dc3 virt 00000000007b9dc3 _kDartIsolateSnapshotInstructions+0x5c8443
```
how do I check that the symbols are really downloaded for the right version? how can this be fixed? thank you

**Comment by mrober** [comment]
Unfortunately, you likely have lost of the symbols for that build if you didn't already upload them. Most developers will just overwrite the symbols when they do their next build.

When you do upload symbols, you can see the build id in the debug logs. It is part of the url. So you can confirm the build id of your uploaded symbols matches the build ids your seeing in your crash reports.

**Comment by fellipetav** [comment]
@mrober ,

Thank you very much for your answers!

However, I have an important feedback:

For instance, take a look in https://firebase.google.com/docs/crashlytics/get-started?platform=flutter#add-sdk . You'll see:

`firebase crashlytics:symbols:upload --app=APP_ID PATH/TO/symbols`

There are other infos among Google's tools using the terminology "app id", not only the one formatted as "1:123:android:123abc...", such as this one "https://developer.android.com/build/configure-app-module#set_the_application_id".

It would be much easier. 

Another feedback is about on how to install Firebase CLI. The lack of more details about node and node package modules  makes things really hard for frontend devs. It is a peach for me. But we find tons of problems about installing Firebase CLI on forums.

Have a good coding!
