### ISSUE TITLE
Webframeworks [NextJS] - Failed to deploy API Routes with App Folder

### ISSUE THREAD

**Issue by AlexBrasileiro** [firebase/firebase-tools#5836]
### [REQUIRED] Environment info

**firebase-tools:** v12.0.0

**Platform:** macOS

### [REQUIRED] Test case

"next": "13.4.2",
"react": "18.2.0",
"react-dom": "18.2.0"

### [REQUIRED] Steps to reproduce

When trying to deploy (passing the ```firebase deploy```command), when adding the Api directory with Routes (as shown in the image in the attachment), for example to use backend functions executed only by the Node server side (such as an API to fetch data in the database), the deploy attempt fails 😢

Without the api folder inside the app folder, deploy proceeds normally 🤗

### [REQUIRED] Expected behavior

That when deploying with the api folder inside the APP folder, the Next Route Handlers option would work as expected as an API route.

### [REQUIRED] Actual behavior

The deploy gives an error, here is the log file:

```log
[debug] [2023-05-14T19:46:48.709Z] ----------------------------------------------------------------------
[debug] [2023-05-14T19:46:48.710Z] Command:       /Users/user/.nvm/versions/node/v16.16.0/bin/node /Users/user/.nvm/versions/node/v16.16.0/bin/firebase deploy
[debug] [2023-05-14T19:46:48.711Z] CLI Version:   11.29.1
[debug] [2023-05-14T19:46:48.711Z] Platform:      darwin
[debug] [2023-05-14T19:46:48.711Z] Node Version:  v16.16.0
[debug] [2023-05-14T19:46:48.712Z] Time:          Sun May 14 2023 16:46:48 GMT-0300 (Brasilia Standard Time)
[debug] [2023-05-14T19:46:48.712Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-05-14T19:46:48.773Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-05-14T19:46:48.774Z] > authorizing via signed-in user (user@gmail.com)
[debug] [2023-05-14T19:46:48.774Z] [iam] checking project nextjs-firebase-test for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions [none]
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions x-goog-quota-user=projects/nextjs-firebase-test
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-05-14T19:46:49.739Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions 200
[debug] [2023-05-14T19:46:49.739Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-05-14T19:46:49.740Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions [none]
[debug] [2023-05-14T19:46:49.741Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2023-05-14T19:46:50.736Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions 200
[debug] [2023-05-14T19:46:50.736Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2023-05-14T19:46:50.738Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test [none]
[debug] [2023-05-14T19:46:51.137Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test 200
[debug] [2023-05-14T19:46:51.137Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test {"projectId":"nextjs-firebase-test","projectNumber":"863676582419","displayName":"NextJS Firebase Test ","name":"projects/nextjs-firebase-test","resources":{"hostingSite":"nextjs-firebase-test"},"state":"ACTIVE","etag":"1_b68ede31-c607-42c6-8f32-3e57e9bdc093"}
[debug] [2023-05-14T19:47:05.405Z] TypeError: Cannot read properties of null (reading 'endsWith')
    at ɵcodegenPublicDirectory (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:206:56)
    at async prepareFrameworks (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/frameworks/index.js:294:13)
    at async deploy (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.

```
![Screenshot 2023-05-14 at 16 56 41](https://github.com/firebase/firebase-tools/assets/15070031/3cc21d39-44ee-4622-8822-532aba76edee)

**Comment by jamesdaniels** [comment]
You need to upgrade the Firebase CLI to get the updates for the app directory, your console log reports you're on version 11.29.1. Both 11.30 and 12 have significant updates for our handling of NextJS.

**Comment by AlexBrasileiro** [comment]
Thank you @jamesdaniels, with the update of the CLI to firebase-tools@12.0.0, everything works like charm 🥳!

**Comment by mariale-mentaport** [comment]
I am having this exact issue but with the latest firebase-tools (12.4.3) and Next.js(13.4.7) and Node18.  
The error I get is 

````
{"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}
[error] 
[error] Error: HTTP Error: 404, Requested entity was not found.
[debug] [2023-07-12T18:45:33.190Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
```
