### ISSUE TITLE
fail to deploy firebase

### ISSUE THREAD

**Issue by fcvuongdc** [firebase/firebase-tools#5849]
### [REQUIRED] Environment info

**firebase-tools:**
$ firebase --version
12.0.0

**Platform:**
windows
### [REQUIRED] Test case
I don't have any test case

### [REQUIRED] Steps to reproduce
cd CuoiKy
npm install -g firebase-tools
firebase login
firebase init
firebase deploy --only functions

### [REQUIRED] Expected behavior
firebase deploy doesn't cause any errors

### [REQUIRED] Actual behavior
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8264
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (E:\CloudComputing\CuoiKy\functions\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (E:\CloudComputing\CuoiKy\functions\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8264
}

Node.js v18.16.0

Error: An unexpected error has occurred.

**Comment by aalej** [comment]
Hi @fcvuongdc, I understand that you’re encountering an error when trying to deploy your functions. I am unable to reproduce the issue using the steps you provided. I created a fresh project and no issues were encountered when running `firebase deploy --only functions`. 

Would it be okay if you could provide us with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details on the steps you took so that we can reproduce the issue on our end? Thanks!

**Comment by fcvuongdc** [comment]
> Hi @fcvuongdc, I understand that you’re encountering an error when trying to deploy your functions. I am unable to reproduce the issue using the steps you provided. I created a fresh project and no issues were encountered when running `firebase deploy --only functions`.
> 
> Would it be okay if you could provide us with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details on the steps you took so that we can reproduce the issue on our end? Thanks!PS E:\CloudComputing\CuoiKy> firebase deploy --only functions

=== Deploying to 'group13-62976'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .

+  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
+  artifactregistry: required API artifactregistry.googleapis.com is enabled
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8224
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (E:\CloudComputing\CuoiKy\functions\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (E:\CloudComputing\CuoiKy\functions\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8224
}

Node.js v18.16.0

Error: An unexpected error has occurred.

**Comment by fcvuongdc** [comment]
give me your index.js?

**Comment by christhompsongoogle** [comment]
Suggestion: If you use a tool like netstat to get who is using port 8224 you can clear that process before deploying functions. Currently the 8224 port may be required to be available for functions deployment.

**Comment by fcvuongdc** [comment]
Cảm ơn, tôi sẽ kiểm tra nó.

**Comment by christhompsongoogle** [comment]
[fcvuongdc](https://github.com/fcvuongdc) can you share your index.js file or a reduced version that reproduces the problem? It looks like you may be calling Node's express.listen() somewhere inside the function.
