### ISSUE TITLE
Firebase Cloud Functions 2nd Gen Scheduler does not work correctly on the emulators.

### ISSUE THREAD

**Issue by gladevise** [firebase/firebase-tools#5875]
Firebase Cloud Functions 2nd Gen Scheduler does not work correctly on the emulators.

When I start the emulators and try to execute a function with `firebase functions:shell` , the following error occurs.

```sh
firebase > scheduleTestV2()
'Successfully invoked function.'
firebase > ⚠  functions: TypeError: req.header is not a function
    at httpFunc (/home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/providers/scheduler.js:63:26)
    at /home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/trace.js:16:28
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:524:16
    at runFunction (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:15)
    at runCloudEvent (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:523:11)
    at processBackground (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:490:16)
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:689:27
    at Layer.handle [as handle_request] (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:144:13)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:140:7)
⚠  Your function was killed because it raised an unhandled error.
```

I have confirmed that the 1st Gen scheduler functions work fine in the same environment.

```sh
firebase > scheduleTestV1()
'Successfully invoked function.'
firebase > >  {"severity":"INFO","message":"scheduleTestV1 called at 2023-05-22T04:15:25.128Z"}
```

### [REQUIRED] Version info

```
node: v18.16.0
firebase-functions: ^4.3.1
firebase-admin: ^11.8.0
firebase-tools: 12.1.0
```

### [REQUIRED] Test case

I have published code in the following repository that can reproduce the error.

https://github.com/gladevise/firebase-cloud-functions-schedule-v2-not-working-emulator

### [REQUIRED] Steps to reproduce

You can reproduce the error by executing the command in the following steps.

```
git clone https://github.com/gladevise/firebase-cloud-functions-schedule-v2-not-working-emulator

cd firebase-cloud-functions-schedule-v2-not-working-emulator/functions

pnpm install

pnpm run serve
```

Run the following on another terminal

```sh
pnpm run shell

firebase > scheduleTestV1()
'Successfully invoked function.'
firebase > >  {"severity":"INFO","message":"scheduleTestV1 called at 2023-05-22T04:15:25.128Z"}

firebase > scheduleTestV2()
'Successfully invoked function.'
firebase > ⚠  functions: TypeError: req.header is not a function
    at httpFunc (/home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/providers/scheduler.js:63:26)
    at /home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/trace.js:16:28
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:524:16
    at runFunction (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:15)
    at runCloudEvent (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:523:11)
    at processBackground (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:490:16)
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:689:27
    at Layer.handle [as handle_request] (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:144:13)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:140:7)
⚠  Your function was killed because it raised an unhandled error.
```

### [REQUIRED] Expected behavior

```sh
firebase > scheduleTestV2()
'Successfully invoked function.'
firebase > >  {"severity":"INFO","message":"scheduleTestV2 called at 2023-05-22T04:15:25.128Z"}
```
### [REQUIRED] Actual behavior

```
firebase > scheduleTestV2()
'Successfully invoked function.'
firebase > ⚠  functions: TypeError: req.header is not a function
    at httpFunc (/home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/providers/scheduler.js:63:26)
    at /home/username/workspace/tests/firebase-cloud-functions-schedule-v2-not-working-emulator/functions/node_modules/.pnpm/firebase-functions@4.3.1_firebase-admin@11.8.0/node_modules/firebase-functions/lib/v2/trace.js:16:28
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:524:16
    at runFunction (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:15)
    at runCloudEvent (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:523:11)
    at processBackground (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:490:16)
    at /home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:689:27
    at Layer.handle [as handle_request] (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:144:13)
    at next (/home/username/.nvm/versions/node/v18.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:140:7)
⚠  Your function was killed because it raised an unhandled error.
```

### Were you able to successfully deploy your functions?

Both `scheduleTestV1` and `scheduleTestV2` can be deployed successfully.

I may have a bad Firebase setup, but please check it out.

**Comment by aalej** [comment]
Hi @gladevise, thanks for the detailed description and for providing a test case. I was able to replicate the behavior you mentioned. When calling `scheduleTestV2()` via `functions:shell`, an error is raised.

I’ll notify our engineers about this issue so that they can investigate, and I’ll be marking this as reproducible.

**Comment by sriganesh-nagaraj** [comment]
@gladevise I'm still facing this issue. Does it work for you?
