### ISSUE TITLE
Make hosting emulator work even if the command was executed from outside of the hosting directory

### ISSUE THREAD

**Issue by iSuslov** [firebase/firebase-tools#5903]
### [REQUIRED] Environment info

**firebase-tools:** 12.2.0

**Platform:** MacOS

### [REQUIRED] Test case

Create a new NextJs app:

```
npx create-next-app@latest
```
Initialize a firebase app in the parent directory and configure it to use nextjs for hosting. 

`hosting.source` in your `firebase.json` should point to the nextjs app like this `"source": "./my-app"`

Start hosting emulator running `firebase emulators:start` from outside of the nextjs directory. 

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

Nextjs app starts inside hosting emulator.

### [REQUIRED] Actual behavior

App crashes because it can't resolve paths.

```
Server Error
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js):
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:87:62)
    at /Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:99:92
    at /Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
    at plugins (/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js:206:17)

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
getTailwindConfig
/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (87:62)
<unknown>
/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (99:92)
<unknown>
/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/processTailwindFeatures.js (48:11)
plugins
/Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/plugin.js (38:63)
LazyResult.runOnRoot
/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (339:16)
LazyResult.runAsync
/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (393:26)
LazyResult.async
/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (221:30)
LazyResult.then
/Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (206:17)
getTailwindConfig
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (87:62)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (99:92)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/processTailwindFeatures.js (48:11)
plugins
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/tailwindcss/lib/plugin.js (38:63)
LazyResult.runOnRoot
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (339:16)
LazyResult.runAsync
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (393:26)
LazyResult.async
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (221:30)
LazyResult.then
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/node_modules/postcss/lib/lazy-result.js (206:17)
processResult
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/compiled/webpack/bundle5.js (28:394802)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/compiled/webpack/bundle5.js (28:396519)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:8645)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:5828)
r.callback
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:4039)
<unknown>
file:///Users/zuzel/Projects/hs/apps/new-web/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js (113:37)
```

**Comment by iSuslov** [comment]
The biggest issue is there is no way to know how folder structure is emulated and people have to debug this blindfolded, spending hours.

**Comment by bogacg** [comment]
I am having a very similar problem with SvelteKit apps on Firebase project multi-hosting setup. Separated my web apps and `firebase.json`  is in their parent folder. When I call for `deploy` only static assets are sent to Firebase hosting. No build step gets executed.

**Comment by jamesdaniels** [comment]
> I am having a very similar problem with SvelteKit apps on Firebase project multi-hosting setup. Separated my web apps and `firebase.json`  is in their parent folder. When I call for `deploy` only static assets are sent to Firebase hosting. No build step gets executed.

That sounds like #5896

**Comment by bogacg** [comment]
@jamesdaniels I'm not sure, I didn't get any error messages in that particular case. I'll test it with the next release then, if I see the same problem I'll open a new issue and put an example repo.
Thanks 💕

**Comment by iSuslov** [comment]
To clarify things here. My issue only happens when `firebase emulators:start` or `firebase deploy --only hosting` is called from outside of the directory:

```
# Outside nextjs directory
firebase emulators:start --config firebase.json
# failure
```

```
# Inside nextjs directory
firebase emulators:start --config ../firebase.json
# will work
```

There is no easy way to debug it if you don't have the information above.
