### ISSUE TITLE
Firebase login is not working

### ISSUE THREAD

**Issue by VishnuZee** [firebase/firebase-tools#6058]
### [REQUIRED] Environment info

**firebase-tools:**

macOS
**Platform:**

### [REQUIRED] Test case

vishnu.duggisetty ~ % firebase --debug login
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
? Allow Firebase to collect CLI and Emulator Suite usage and error reporting 
information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again. 

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=371796461&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
[2023-06-29T12:31:31.876Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[2023-06-29T12:31:31.876Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2023-06-29T12:31:32.093Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:242:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-06-29T12:31:32.101Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[2023-06-29T12:31:32.102Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"acc1475e-717a-4072-b3f7-69ee2331c133"}
[2023-06-29T12:31:32.747Z] <<< [apiv2][status] POST https://auth.firebase.tools/attest 200
[2023-06-29T12:31:32.747Z] <<< [apiv2][body] POST https://auth.firebase.tools/attest {"token":"y7MBhtXTNjZsKaSWqv3lS6k2Uoi1KPxQIlf4_QhDm30"}

To sign in to the Firebase CLI:

1. Take note of your session ID:

   ACC14

2. Visit the URL below on any device and follow the instructions to get your code:

   https://auth.firebase.tools/login?code_challenge=hBO7VybJaegihs0OFNr2YolrSMUQ0cv1uKCgSDuw3aQ&session=acc1475e-717a-4072-b3f7-69ee2331c133&attest=y7MBhtXTNjZsKaSWqv3lS6k2Uoi1KPxQIlf4_QhDm30

3. Paste or enter the authorization code below once you have it:

? Enter authorization code: 
4/0AZEOvhXVrE0XoxVSNYcK42j7LDeq_LtccxVKmMEgQgLk8OGhlMPvQcyNj9eZIwAu8LQ0rA
[2023-06-29T12:33:47.103Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[2023-06-29T12:33:47.117Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2023-06-29T12:33:47.403Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:242:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Error: Unable to authenticate using the provided code. Please try again.

### [REQUIRED] Actual behavior

<img width="1437" alt="Screenshot 2023-06-29 at 6 10 16 PM" src="https://github.com/firebase/firebase-tools/assets/84703261/c66affdb-9ba2-43db-82a2-40f867f5cab4">

**Comment by bkendall** [comment]
That's a lot of info! Thanks for the logs.

What's concerning to me is that the request to `https://accounts.google.com/o/oauth2/token` is simply failing to make the request - it's not returning (otherwise you'd see `<<<` logs), so the message is maybe not even making out from your computer.

Are you using a VPN or proxy of any kind?
Are you able to reach that host via `curl` on that machine? (e.g. `curl -I https://accounts.google.com/o/oauth2/token` will give you a 404 response?)

**Comment by VishnuZee** [comment]
> That's a lot of info! Thanks for the logs.
> 
> What's concerning to me is that the request to `https://accounts.google.com/o/oauth2/token` is simply failing to make the request - it's not returning (otherwise you'd see `<<<` logs), so the message is maybe not even making out from your computer.
> 
> Are you using a VPN or proxy of any kind? 
Not using any proxy.
Are you able to reach that host via `curl` on that machine? (e.g. `curl -I https://accounts.google.com/o/oauth2/token` will give you a 404 response?) 
<img width="534" alt="Screenshot 2023-06-29 at 8 21 15 PM" src="https://github.com/firebase/firebase-tools/assets/84703261/64af732d-9453-41a1-a2d7-9ec4257df3db">

**Comment by EngMoAmri** [comment]
same here

**Comment by jw834ksj43** [comment]
I had a nearly identical log messages and it was caused by being on a connection using IPv6. I disabled IPv6 in my network adapter and it authenticated without issue.

**Comment by knott-todd** [comment]
> I had a nearly identical log messages and it was caused by being on a connection using IPv6. I disabled IPv6 in my network adapter and it authenticated without issue.

This worked for me as a linux/ubuntu user.

**Comment by ebesojoseph** [comment]
> I had a nearly identical log messages and it was caused by being on a connection using IPv6. I disabled IPv6 in my network adapter and it authenticated without issue.

I did exactly this and it work form me 

This method edits a system configuration file to disable IPv6. The changes are temporary, but they persist until the system is rebooted.

Here's how to do it:

    Open a terminal window.

    Edit the /etc/sysctl.conf file with a text editor by running:

   ` sudo nano /etc/sysctl.conf`

    Add the following lines to the end of the file:

    ```net.ipv6.conf.all.disable_ipv6 = 1
    net.ipv6.conf.default.disable_ipv6 = 1
    net.ipv6.conf.lo.disable_ipv6 = 1```

    Save and close the file.

    Apply the changes with:

    `sudo sysctl -p`

    Verify if IPv6 is disabled by running:

   `cat /proc/sys/net/ipv6/conf/all/disable_ipv6`

    If the output is 1, IPv6 is disabled.

**Comment by HaydenFaulkner** [comment]
Potential solution in #10692
