### ISSUE TITLE
Unable to deploy functions from m1 machine.

### ISSUE THREAD

**Issue by WarisShams** [firebase/firebase-tools#6126]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.4

**Platform:** MAC OSX 13.4.1 with M1 Pro apple silicon chip.

### [REQUIRED] Test case
Attempt to deploy functions for the first time.

### [REQUIRED] Steps to reproduce
Deploy via CLI with **firebase deploy** command and also tried Deploy via **firebase deploy --only functions** command

### [REQUIRED] Expected behavior
Deploy code normally.

### [REQUIRED] Actual behavior
Giving error at the end after compiling successfully on emulator.

Here is some detail with --debug command.

```waris@Wariss-MacBook-Pro amfunctions % firebase deploy --debug           
[2023-07-13T13:23:54.941Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-07-13T13:23:54.943Z] > authorizing via signed-in user (analysedmaster.nl@gmail.com)
[2023-07-13T13:23:54.943Z] [iam] checking project analysed-master for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get"]
[2023-07-13T13:23:54.946Z] > refreshing access token with scopes: []
[2023-07-13T13:23:54.949Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[2023-07-13T13:23:54.951Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-07-13T13:23:55.466Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[2023-07-13T13:23:55.470Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-07-13T13:23:55.491Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/analysed-master:testIamPermissions [none]
[2023-07-13T13:23:55.493Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/analysed-master:testIamPermissions x-goog-quota-user=projects/analysed-master
[2023-07-13T13:23:55.494Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/analysed-master:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get"]}
[2023-07-13T13:23:57.149Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/analysed-master:testIamPermissions 200
[2023-07-13T13:23:57.151Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/analysed-master:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get"]}
[2023-07-13T13:23:57.152Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/analysed-master/serviceAccounts/analysed-master@appspot.gserviceaccount.com:testIamPermissions [none]
[2023-07-13T13:23:57.152Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/analysed-master/serviceAccounts/analysed-master@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[2023-07-13T13:23:58.747Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/analysed-master/serviceAccounts/analysed-master@appspot.gserviceaccount.com:testIamPermissions 200
[2023-07-13T13:23:58.749Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/analysed-master/serviceAccounts/analysed-master@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}

=== Deploying to 'analysed-master'...

i  deploying firestore, functions 
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts . --fix


/Users/waris/Documents/Projects/amfunctions/functions/src/index.ts
  99:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 1 problem (0 errors, 1 warning)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script. 
i  firestore: reading indexes from firestore.indexes.json... 
i  cloud.firestore: checking firestore.rules for compilation errors... 
[2023-07-13T13:24:16.988Z] >>> [apiv2][query] POST https://firebaserules.googleapis.com/v1/projects/analysed-master:test [none]
[2023-07-13T13:24:16.988Z] >>> [apiv2][body] POST https://firebaserules.googleapis.com/v1/projects/analysed-master:test [omitted]
[2023-07-13T13:24:18.154Z] <<< [apiv2][status] POST https://firebaserules.googleapis.com/v1/projects/analysed-master:test 200
[2023-07-13T13:24:18.156Z] <<< [apiv2][body] POST https://firebaserules.googleapis.com/v1/projects/analysed-master:test {}
✔  cloud.firestore: rules file firestore.rules compiled successfully 
[2023-07-13T13:24:18.161Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master [none]
[2023-07-13T13:24:18.818Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master 200
[2023-07-13T13:24:18.821Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master {"projectId":"analysed-master","projectNumber":"998874559501","displayName":"Analysed Master","name":"projects/analysed-master","resources":{"hostingSite":"analysed-master","storageBucket":"analysed-master.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_09940000-a213-484f-9143-98b423a6435e"}
i  functions: preparing codebase default for deployment 
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled... 
[2023-07-13T13:24:18.826Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudfunctions.googleapis.com [none]
[2023-07-13T13:24:18.826Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudfunctions.googleapis.com x-goog-quota-user=projects/analysed-master
[2023-07-13T13:24:18.829Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/runtimeconfig.googleapis.com [none]
[2023-07-13T13:24:18.831Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/runtimeconfig.googleapis.com x-goog-quota-user=projects/analysed-master
[2023-07-13T13:24:18.833Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudbuild.googleapis.com [none]
[2023-07-13T13:24:18.834Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudbuild.googleapis.com x-goog-quota-user=projects/analysed-master
[2023-07-13T13:24:18.834Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/artifactregistry.googleapis.com [none]
[2023-07-13T13:24:18.834Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/artifactregistry.googleapis.com x-goog-quota-user=projects/analysed-master
[2023-07-13T13:24:20.723Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudbuild.googleapis.com 200
[2023-07-13T13:24:20.728Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudbuild.googleapis.com [omitted]
✔  functions: required API cloudbuild.googleapis.com is enabled 
[2023-07-13T13:24:20.731Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/runtimeconfig.googleapis.com 200
[2023-07-13T13:24:20.732Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/runtimeconfig.googleapis.com [omitted]
[2023-07-13T13:24:20.734Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/artifactregistry.googleapis.com 200
[2023-07-13T13:24:20.734Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/artifactregistry.googleapis.com [omitted]
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled 
[2023-07-13T13:24:20.764Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudfunctions.googleapis.com 200
[2023-07-13T13:24:20.764Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/analysed-master/services/cloudfunctions.googleapis.com [omitted]
✔  functions: required API cloudfunctions.googleapis.com is enabled 
[2023-07-13T13:24:20.765Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master/adminSdkConfig [none]
[2023-07-13T13:24:21.308Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master/adminSdkConfig 200
[2023-07-13T13:24:21.309Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/analysed-master/adminSdkConfig {"projectId":"analysed-master","storageBucket":"analysed-master.appspot.com","locationId":"us-central"}
[2023-07-13T13:24:21.310Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/analysed-master/configs [none]
[2023-07-13T13:24:22.024Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/analysed-master/configs 200
[2023-07-13T13:24:22.024Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/analysed-master/configs {}
[2023-07-13T13:24:22.027Z] Validating nodejs source
[2023-07-13T13:24:23.119Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts . --fix",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "src/index.ts",
  "dependencies": {
    "firebase-admin": "^11.8.0",
    "firebase-functions": "^4.3.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^3.1.0",
    "typescript": "^4.9.0"
  },
  "private": true
}
[2023-07-13T13:24:23.120Z] Building nodejs source
i  functions: Loading and analyzing source code for codebase default to determine what to deploy 
[2023-07-13T13:24:23.122Z] Could not find functions.yaml. Must use http discovery
[2023-07-13T13:24:23.139Z] Found firebase-functions binary at '/Users/waris/Documents/Projects/amfunctions/functions/node_modules/.bin/firebase-functions'
Serving at port 8957

[2023-07-13T13:24:23.433Z] Got response code 400; body Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module
shutdown requested via /__/quitquitquit


Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error```

Every thing's response is 200 OK then why not uploading?
Please help i am stuck on this for a week and found no solution.
Thanks.

**Comment by WarisShams** [comment]
Hi @blidd-google thanks for quick reply but adding `"type": "module"` in package.json creates a lot of other issues like

```
Oops! Something went wrong! :(

ESLint: 8.44.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/waris/Documents/Projects/amfunctions/functions/.eslintrc.js from /Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
.eslintrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename .eslintrc.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/waris/Documents/Projects/amfunctions/functions/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at module.exports [as default] (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2574:47)
    at loadConfigFile (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2658:20)
    at ConfigArrayFactory.loadInDirectory (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2868:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3860:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3781:18)
    at FileEnumerator._iterateFilesRecursive (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/lib/cli-engine/cli-engine.js:797:48)
    at ESLint.lintFiles (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/lib/cli.js:391:36)
    at async main (/Users/waris/Documents/Projects/amfunctions/functions/node_modules/eslint/bin/eslint.js:135:24)

Error: functions predeploy error: Command terminated with non-zero exit code 2
```


while i am using only these import statements in `index.ts` file

```import * as functions from "firebase-functions";
import * as firebaseAdmin from "firebase-admin";
import {Chat, JsonObject, User} from "./interfaces";
import {Message, MulticastMessage}  
from "firebase-admin/lib/messaging/messaging-api";```
