### ISSUE TITLE
"firebase serve --only functions" doesn't work anymore after update to 3.17.2

### ISSUE THREAD

**Issue by Metsuryu** [firebase/firebase-tools#617]
I got the message to update firebase-tools, and I did that as usual with "npm install -g firebase-tools". After the update was complete, I got an error when trying to run "firebase serve --only functions":

```
i  functions: Preparing to emulate functions.
!  functions: Failed to load functions source code. Ensure that you have the lat
est SDK by running npm i --save firebase-functions inside the functions director
y.
!  functions: Error from emulator. FirebaseError: Error occurred while parsing y
our function triggers. Please ensure you have the latest firebase-functions SDK
by running "npm i --save firebase-functions@latest" inside your functions folder
.

Error: Firebase config variables are not available. Please use the latest versio
n of the Firebase CLI to deploy this function.
```

So I ran "npm i --save firebase-functions@latest" inside my functions folder, as the error asked and then it said I also had to update firebase-admin, so I did, but I keep getting the same error, after trying to uninstall and reinstall, trying to downgrade to the previous versions (  "firebase-admin": "^5.5.1", "firebase-functions": "^0.7.5") doesn't work, saying there is no such version available.

Before the update everything was working fine.

### Version info

Firebase: 3.17.2
Node: 6.12.2
Npm: 3.10.10

### Steps to reproduce

I had:

```
"firebase-admin": "^5.5.1"
"firebase-functions": "^0.7.5"
```

and updated them with 
"npm i --save firebase-functions@latest" and "npm i --save firebase-admin@latest" inside my functions folder.

Then, running "firebase serve --only functions" gives me the error above.

### Expected behavior

"firebase serve --only functions" should emulate the cloud functions inside the index.js file in the "functions" folder, as usual. 

### Actual behavior

"firebase serve --only functions --debug" outputs the following:

```

D:\Users\2Punx2Furious\Desktop\Dev\Projects\Work\new-lantea>firebase serve --onl
y functions --debug
[2018-01-19T22:58:57.096Z] -----------------------------------------------------
-----------------
[2018-01-19T22:58:57.100Z] Command:       C:\Program Files\nodejs\node.exe C:\Us
ers\Metsuryu\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase serve
--only functions --debug
[2018-01-19T22:58:57.101Z] CLI Version:   3.17.2
[2018-01-19T22:58:57.101Z] Platform:      win32
[2018-01-19T22:58:57.101Z] Node Version:  v6.12.2
[2018-01-19T22:58:57.102Z] Time:          Fri Jan 19 2018 23:58:57 GMT+0100 (W.
Europe Standard Time)
[2018-01-19T22:58:57.102Z] -----------------------------------------------------
-----------------

[2018-01-19T22:58:57.113Z] > command requires scopes: ["email","openid","https:/
/www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis
.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-01-19T22:58:57.113Z] > authorizing via signed-in user
[2018-01-19T22:58:57.115Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/pr
ojects/new-lantea

 Fri Jan 19 2018 23:58:57 GMT+0100 (W. Europe Standard Time)
[2018-01-19T22:58:58.439Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 19 Jan
2018 22:58:51 GMT, content-type=application/json; charset=utf-8, content-length=
106, connection=close, x-content-type-options=nosniff, strict-transport-security
=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-01-19T22:58:58.440Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/da
tabase/new-lantea/tokens

 Fri Jan 19 2018 23:58:58 GMT+0100 (W. Europe Standard Time)
[2018-01-19T22:59:01.259Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 19 Jan
2018 22:58:52 GMT, content-type=application/json; charset=utf-8, content-length=
259, connection=close, x-content-type-options=nosniff, strict-transport-security
=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Serving from 'D:\Users\2Punx2Furious\Desktop\Dev\Projects\Work\new-lantea'..
.

i  functions: Preparing to emulate functions.
[2018-01-19T22:59:02.082Z] Fetching environment
[2018-01-19T22:59:02.084Z] >>> HTTP REQUEST GET https://appengine.googleapis.com
/v1/apps/new-lantea

 Fri Jan 19 2018 23:59:02 GMT+0100 (W. Europe Standard Time)
[2018-01-19T22:59:02.085Z] >>> HTTP REQUEST GET https://apikeys.googleapis.com/v
1/projects/new-lantea/apiKeys

 Fri Jan 19 2018 23:59:02 GMT+0100 (W. Europe Standard Time)
[2018-01-19T22:59:03.037Z] <<< HTTP RESPONSE 200 content-type=application/json;
charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 19 Jan
2018 22:58:56 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=b
lock, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":4
43"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; qui
c=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35", accept-ranges=none, conn
ection=close
[2018-01-19T22:59:03.275Z] <<< HTTP RESPONSE 200 content-type=application/json;
charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 19 Jan
2018 22:58:56 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=b
lock, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":4
43"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; qui
c=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35", accept-ranges=none, conn
ection=close
[2018-01-19T22:59:03.277Z] Starting @google-cloud/functions-emulator
[2018-01-19T22:59:05.379Z] Parsing function triggers
!  functions: Failed to load functions source code. Ensure that you have the lat
est SDK by running npm i --save firebase-functions inside the functions director
y.
!  functions: Error from emulator. FirebaseError: Error occurred while parsing y
our function triggers. Please ensure you have the latest firebase-functions SDK
by running "npm i --save firebase-functions@latest" inside your functions folder
.

Error: Firebase config variables are not available. Please use the latest versio
n of the Firebase CLI to deploy this function.
    at init (D:\Users\2Punx2Furious\Desktop\Dev\Projects\Work\new-lantea\functio
ns\node_modules\firebase-functions\lib\config.js:55:15)
    at Object.config (D:\Users\2Punx2Furious\Desktop\Dev\Projects\Work\new-lante
a\functions\node_modules\firebase-functions\lib\config.js:29:9)
    at Object.<anonymous> (D:\Users\2Punx2Furious\Desktop\Dev\Projects\Work\new-
lantea\functions\index.js:19:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

```

**Comment by laurenzlong** [comment]
I think I fixed it in https://github.com/firebase/firebase-tools/pull/618, can you try using that branch?

npm install -g https://github.com/firebase/firebase-tools.git#laurenzlong-patch-1

**Comment by Metsuryu** [comment]
Thank you, I'll try tomorrow and let you know.

**Comment by laurenzlong** [comment]
Duplicate of https://github.com/firebase/firebase-tools/issues/609, please follow along there now. (And ignore the comment above to try a branch)
