### ISSUE TITLE
Apparent version mismatch with default configuration

### ISSUE THREAD

**Issue by Kamshak** [firebase/firebase-tools#624]
### Version info

3.17.3

### Steps to reproduce

- firebase init
- fill out what it asks you
- confirm npm install
- uncomment the function and use firebase.config()
- firebase deploy --only functions:helloWorld

### Expected behavior

It works

### Actual behavior

Error: Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.

Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (/home/valentin/repro/functions/node_modules/firebase-functions/lib/config.js:51:15)
    at Object.config (/home/valentin/repro/functions/node_modules/firebase-functions/lib/config.js:29:9)
    at Object.<anonymous> (/home/valentin/repro/functions/lib/index.js:5:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by laurenzlong** [comment]
Sorry, I can't reproduce. The template for JS does have firebase-functions v0.8.1, which is what's required.
https://github.com/firebase/firebase-tools/blob/master/templates/init/functions/javascript/package.lint.json
https://github.com/firebase/firebase-tools/blob/master/templates/init/functions/javascript/package.nolint.json

**Comment by Radzell** [comment]
Anyone able to fix this it just started happening today?
