### ISSUE TITLE
.env is not loading properly its loaded first time but after complete loading of website .env removed 

### ISSUE THREAD

**Issue by Your-Ehsan** [firebase/firebase-tools#6279]
[debug] [2023-08-19T19:08:05.229Z] ----------------------------------------------------------------------
[debug] [2023-08-19T19:08:05.232Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js emulators:start
[debug] [2023-08-19T19:08:05.233Z] CLI Version:   12.4.8
[debug] [2023-08-19T19:08:05.234Z] Platform:      win32
[debug] [2023-08-19T19:08:05.234Z] Node Version:  v18.17.1
[debug] [2023-08-19T19:08:05.235Z] Time:          Sun Aug 20 2023 00:08:05 GMT+0500 (Pakistan Standard Time)
[debug] [2023-08-19T19:08:05.236Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-08-19T19:08:05.446Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-08-19T19:08:05.447Z] > authorizing via signed-in user (ehsanshahid787@gmail.com)
[debug] [2023-08-19T19:08:05.692Z] java version "20.0.1" 2023-04-18

[debug] [2023-08-19T19:08:05.693Z] Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

[debug] [2023-08-19T19:08:05.720Z] Parsed Java major version: 20
[info] i  emulators: Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc"}}
[debug] [2023-08-19T19:08:05.765Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.765Z] [auth] Authentication Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.765Z] [firestore] Firestore Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.766Z] [firestore.websocket] websocket server for firestore only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.766Z] [database] Database Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.766Z] [hosting] Hosting Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.766Z] [pubsub] Pub/Sub Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:05.766Z] [storage] Storage Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[warn] !  ui: Emulator UI unable to start on port 4000, starting on 4001 instead. {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI unable to start on port 4000, starting on 4001 instead."}}
[debug] [2023-08-19T19:08:05.769Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9099}],"firestore":[{"address":"127.0.0.1","family":"IPv4","port":8080}],"firestore.websocket":[{"address":"127.0.0.1","family":"IPv4","port":9150}],"database":[{"address":"127.0.0.1","family":"IPv4","port":9000}],"hosting":[{"address":"127.0.0.1","family":"IPv4","port":5000}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}],"storage":[{"address":"127.0.0.1","family":"IPv4","port":9199}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4001},{"address":"::1","family":"IPv6","port":4001}]},"metadata":{"message":"assigned listening specs for emulators"}}
[debug] [2023-08-19T19:08:05.789Z] [hub] writing locator at C:\Users\YOUR-E~1\AppData\Local\Temp\hub-copy-cats.json
[debug] [2023-08-19T19:08:05.809Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats [none]
[debug] [2023-08-19T19:08:07.223Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats 200
[debug] [2023-08-19T19:08:07.224Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats {"projectId":"copy-cats","projectNumber":"490619769432","displayName":"copy-cats","name":"projects/copy-cats","resources":{"hostingSite":"copy-cats","storageBucket":"copy-cats.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_41f7c7a2-bb3a-4b69-9bcd-ab8a5ed576cb"}
[info] i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
[info] i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
[debug] [2023-08-19T19:08:18.948Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at findDependency (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\utils.js:178:23)
    at prepareFrameworks (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:123:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.startAll (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\controller.js:300:9)
    at async C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\commands\emulators-start.js:32:43
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-08-19T19:08:30.114Z] ----------------------------------------------------------------------
[debug] [2023-08-19T19:08:30.118Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js emulators:start
[debug] [2023-08-19T19:08:30.118Z] CLI Version:   12.4.8
[debug] [2023-08-19T19:08:30.119Z] Platform:      win32
[debug] [2023-08-19T19:08:30.119Z] Node Version:  v18.17.1
[debug] [2023-08-19T19:08:30.121Z] Time:          Sun Aug 20 2023 00:08:30 GMT+0500 (Pakistan Standard Time)
[debug] [2023-08-19T19:08:30.121Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-08-19T19:08:30.336Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-08-19T19:08:30.337Z] > authorizing via signed-in user (ehsanshahid787@gmail.com)
[debug] [2023-08-19T19:08:30.531Z] java version "20.0.1" 2023-04-18

[debug] [2023-08-19T19:08:30.532Z] Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

[debug] [2023-08-19T19:08:30.554Z] Parsed Java major version: 20
[info] i  emulators: Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc"}}
[debug] [2023-08-19T19:08:30.595Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.595Z] [auth] Authentication Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [firestore] Firestore Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [firestore.websocket] websocket server for firestore only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [database] Database Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [hosting] Hosting Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [pubsub] Pub/Sub Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:30.596Z] [storage] Storage Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[warn] !  ui: Emulator UI unable to start on port 4000, starting on 4001 instead. {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI unable to start on port 4000, starting on 4001 instead."}}
[debug] [2023-08-19T19:08:30.599Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9099}],"firestore":[{"address":"127.0.0.1","family":"IPv4","port":8080}],"firestore.websocket":[{"address":"127.0.0.1","family":"IPv4","port":9150}],"database":[{"address":"127.0.0.1","family":"IPv4","port":9000}],"hosting":[{"address":"127.0.0.1","family":"IPv4","port":5000}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}],"storage":[{"address":"127.0.0.1","family":"IPv4","port":9199}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4001},{"address":"::1","family":"IPv6","port":4001}]},"metadata":{"message":"assigned listening specs for emulators"}}
[debug] [2023-08-19T19:08:30.616Z] [hub] writing locator at C:\Users\YOUR-E~1\AppData\Local\Temp\hub-copy-cats.json
[debug] [2023-08-19T19:08:30.633Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats [none]
[debug] [2023-08-19T19:08:32.805Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats 200
[debug] [2023-08-19T19:08:32.805Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats {"projectId":"copy-cats","projectNumber":"490619769432","displayName":"copy-cats","name":"projects/copy-cats","resources":{"hostingSite":"copy-cats","storageBucket":"copy-cats.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_41f7c7a2-bb3a-4b69-9bcd-ab8a5ed576cb"}
[info] i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
[info] i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
[debug] [2023-08-19T19:08:44.391Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at findDependency (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\utils.js:178:23)
    at prepareFrameworks (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:123:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.startAll (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\controller.js:300:9)
    at async C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\commands\emulators-start.js:32:43
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-08-19T19:08:55.135Z] ----------------------------------------------------------------------
[debug] [2023-08-19T19:08:55.138Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js emulators:start
[debug] [2023-08-19T19:08:55.139Z] CLI Version:   12.4.8
[debug] [2023-08-19T19:08:55.140Z] Platform:      win32
[debug] [2023-08-19T19:08:55.140Z] Node Version:  v18.17.1
[debug] [2023-08-19T19:08:55.142Z] Time:          Sun Aug 20 2023 00:08:55 GMT+0500 (Pakistan Standard Time)
[debug] [2023-08-19T19:08:55.142Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-08-19T19:08:55.357Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-08-19T19:08:55.358Z] > authorizing via signed-in user (ehsanshahid787@gmail.com)
[debug] [2023-08-19T19:08:55.560Z] java version "20.0.1" 2023-04-18

[debug] [2023-08-19T19:08:55.561Z] Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

[debug] [2023-08-19T19:08:55.617Z] Parsed Java major version: 20
[info] i  emulators: Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, functions, firestore, database, hosting, pubsub, storage, eventarc"}}
[debug] [2023-08-19T19:08:55.659Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.659Z] [auth] Authentication Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.659Z] [firestore] Firestore Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.659Z] [firestore.websocket] websocket server for firestore only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.659Z] [database] Database Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.660Z] [hosting] Hosting Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.660Z] [pubsub] Pub/Sub Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-08-19T19:08:55.660Z] [storage] Storage Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[warn] !  ui: Emulator UI unable to start on port 4000, starting on 4001 instead. {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI unable to start on port 4000, starting on 4001 instead."}}
[debug] [2023-08-19T19:08:55.662Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9099}],"firestore":[{"address":"127.0.0.1","family":"IPv4","port":8080}],"firestore.websocket":[{"address":"127.0.0.1","family":"IPv4","port":9150}],"database":[{"address":"127.0.0.1","family":"IPv4","port":9000}],"hosting":[{"address":"127.0.0.1","family":"IPv4","port":5000}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}],"storage":[{"address":"127.0.0.1","family":"IPv4","port":9199}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4001},{"address":"::1","family":"IPv6","port":4001}]},"metadata":{"message":"assigned listening specs for emulators"}}
[debug] [2023-08-19T19:08:55.679Z] [hub] writing locator at C:\Users\YOUR-E~1\AppData\Local\Temp\hub-copy-cats.json
[debug] [2023-08-19T19:08:55.695Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats [none]
[debug] [2023-08-19T19:08:56.738Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats 200
[debug] [2023-08-19T19:08:56.738Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/copy-cats {"projectId":"copy-cats","projectNumber":"490619769432","displayName":"copy-cats","name":"projects/copy-cats","resources":{"hostingSite":"copy-cats","storageBucket":"copy-cats.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_41f7c7a2-bb3a-4b69-9bcd-ab8a5ed576cb"}
[info] i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
[info] i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
[debug] [2023-08-19T19:09:08.394Z] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at findDependency (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\utils.js:178:23)
    at prepareFrameworks (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:123:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.startAll (C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\controller.js:300:9)
    at async C:\Users\your-ehsan\AppData\Roaming\npm\node_modules\firebase-tools\lib\commands\emulators-start.js:32:43
[error] 
[error] Error: An unexpected error has occurred.

**Comment by Your-Ehsan** [comment]
firebase-tools are not working properly with next.js hosting on firebase
