### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by DiptiKadamNextqore** [firebase/firebase-tools#6311]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** Windows

Node version 16.16.0

### [REQUIRED] Test case

npm run build && firebase emulators:start --only functions

### [REQUIRED] Steps to reproduce
As my project, I wrote in the typescript. I can able to deploy the function but can't able to point to local emulator functions
I am not an owner of the project. 
1.Install latest firebase-tools 
2. Run the following command
npm run build && firebase emulators:start --only functions

### [REQUIRED] Expected behavior
It should pointed to the respective function loadUserData1 which is written in the index.ts file.

### [REQUIRED] Actual behavior

!  TypeError: Cannot convert object to primitive value
    at Proxy.<anonymous> (C:\Users\info\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:358:79)
    at Object.<anonymous> (D:\FloorWire\backend\lib\index.js:7:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadTriggers (C:\Users\info\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:584:25)
    at main (C:\Users\info\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:637:32)
!  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.
!  functions: Failed to initialize and load triggers. This shouldn't happen: Cannot convert object to primitive value
!  Your function was killed because it raised an unhandled error.

!!  functions: Failed to handle request for function us-central1-loadUserData1

**Comment by aalej** [comment]
Hey @DiptiKadamNextqore, thanks for reaching out to us. My understanding is that you’re encountering an error when running `firebase emulators:start`. I’m trying to reproduce this issue, but so far I haven’t encountered any issues with running my functions written in Typescript on the Firebase Emulators. The steps I took were:

1. Run `firebase init functions --project <project_id>`
2. Select Typescript
3. Under “functions/src/index.ts”, uncomment the `helloWorld` code template
4. Run `cd functions`
5. Run `npm run build`
6. Run `firebase emulators:start`

Could you provide code snippets of the function `loadUserData1` or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so that we can reproduce the issue on our end? Thanks!

**Comment by UXDart** [comment]
did you update deps inside functions? you need to use the specific versions google/firebase is using
