### ISSUE TITLE
CLI hosting:disable command doesn't work as node module

### ISSUE THREAD

**Issue by ivan-mosayc** [firebase/firebase-tools#6319]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** Windows

### [REQUIRED] Test case

Inside any node firebase function:

```
import client from 'firebase-tools';

client.hosting.disable({
  site: '<any published target site in the project>',
  force: true
});
```

### [REQUIRED] Steps to reproduce

Execute that method inside any function.

### [REQUIRED] Expected behavior

The target site should be disabled.

### [REQUIRED] Actual behavior

The disable method fails:

```
FirebaseError: HTTP Error: 401, Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at responseToError (/workspace/node_modules/firebase-tools/lib/responseToError.js:49:12)
    at RetryOperation._fn (/workspace/node_modules/firebase-tools/lib/apiv2.js:285:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Additional logs:

```
{
  "name": "FirebaseError",
  "children": [],
  "context": {
    "body": {
      "error": {
        "code": 401,
        "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
        "status": "UNAUTHENTICATED",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.ErrorInfo",
            "reason": "CREDENTIALS_MISSING",
            "domain": "googleapis.com",
            "metadata": {
              "service": "firebasehosting.googleapis.com",
              "method": "google.firebase.hosting.v1beta1.MetadataService.CreateRelease"
            }
          }
        ]
      }
    },
    "response": {
      "statusCode": 401
    }
  },
  "exit": 1,
  "message": "HTTP Error: 401, Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
  "status": 401
}
```

**Comment by aalej** [comment]
Hi @ivan-mosayc, thanks for reaching out to us and for providing a detailed report. Let me know if I may be wrong, but from what I can tell, you’re trying to authenticate using a Service Account. 

To authenticate, could you try setting an environment variable called `GOOGLE_APPLICATION_CREDENTIALS` as a path pointing to your service account JSON file. Also, specify the project in the argument of the `hosting.disable()` method:

```js
import client from "firebase-tools";

process.env.GOOGLE_APPLICATION_CREDENTIALS = "<path_to_service_account_key.json>";

client.hosting.disable({
  project: "<project_id>",
  site: "<site_id>",
  force: true,
});
```

Are able to to authenticate using `GOOGLE_APPLICATION_CREDENTIALS` or are there any errors being raised? Could you also provide additional information on how you’re currently trying to authenticate, and could you explain what you mean by “Works fine on the emulator”?
