### ISSUE TITLE
Can't install cloud functions

### ISSUE THREAD

**Issue by Levelleor** [firebase/firebase-tools#640]
### Version info

Firebase version: 3.17.4

### Steps to reproduce

```
cd functions
npm install
```

### Expected behavior

Successful functions installation. 

### Actual behavior

> npm ERR! path C:\Users\Admin\firebaseApps\project-name\functions\node_modules\firebase-admin\node_modules\grpc\node_modules\abbrev
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Admin\firebaseApps\project-name\functions\node_modules\firebase-admin\node_modules\grpc\node_modules\abbrev' -> 'C:\Users\Admin\firebaseApps\project-name\functions\node_modules\firebase-admin\node_modules\grpc\node_modules\.abbrev.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-01-27T03_43_22_282Z-debug.log

How do I install firebase cloud functions, am I doing something wrong? Hosting works perfectly. I don't understand what's happening, never seen this before...

**Comment by jeeteshnariya** [comment]
can't install firebase tools

 ``` npm install -g firebase-tools
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\Mi10\AppData\Roaming\npm\firebase -> C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase

> grpc@1.4.1 install C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.4.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.4.1 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Mi10\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable. gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Mi10\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Mi10\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Mi10\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mi10\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Mi10\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Mi10\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\src\\node\\extension_binary"
gyp ERR! cwd C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Mi10\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mi10\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Mi10\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Mi10\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\grpc\src\node\extension_binary' (1)npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 (node_modules\firebase-tools\node_modules\grpc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: grpc@1.4.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ firebase-tools@3.17.4
added 502 packages and updated 1 package in 165.515s ```

**Comment by dudukk1312** [comment]
I have the same problem above. Please fix it,

**Comment by mbleigh** [comment]
NPM install errors are outside the purview of what we can really help with, unfortunately. I'd recommend you get on the latest (stable) Node version (v8.X) as well as the latest version of NPM:

    npm install -g npm@latest

**Comment by Levelleor** [comment]
@mbleigh Wait, what I supposed to do then? I have the latest node and npm versions and you tell me there is nothing you can do? At least give me some list of actions that could definitely fix this even if they require some reinstalls. 

> node -v
> v8.9.1
> npm -v
> 5.6.0

**Comment by mbleigh** [comment]
Please follow up on grpc/grpc-node#121 -- I'm trying to consolidate grpc install issues there.
