### ISSUE TITLE
Failed to make request to https://auth.firebase.tools/attest

### ISSUE THREAD

**Issue by huangsir0** [firebase/firebase-tools#6407]
### [REQUIRED] Environment info

**firebase-tools:**

firebase --version
12.6.0

**Platform:**
Windows

#### firebase --debug login --no-localhost
PS E:\WorkSpace\Flutter\kx-flutter\walang> set "NODE_TLS_REJECT_UNAUTHORIZED=0";  
PS E:\WorkSpace\Flutter\kx-flutter\walang> set "http_proxy=http://127.0.0.1:7890";
PS E:\WorkSpace\Flutter\kx-flutter\walang> firebase --debug login --no-localhost
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[2023-09-27T09:07:06.637Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[2023-09-27T09:07:06.637Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"dd98fcd2-b7ef-4a2e-90a7-86e27f0de192"}
[2023-09-27T09:07:27.718Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"dd98fcd2-b7ef-4a2e-90a7-86e27f0de192\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 216.239.36.21:443
[2023-09-27T09:07:28.013Z] FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 216.239.36.21:443
    at ClientRequest.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Error: Failed to make request to https://auth.firebase.tools/attest

#### firebase --debug login 

PS E:\WorkSpace\Flutter\kx-flutter\walang> set "NODE_TLS_REJECT_UNAUTHORIZED=0";  
PS E:\WorkSpace\Flutter\kx-flutter\walang> set "http_proxy=http://127.0.0.1:7890";
PS E:\WorkSpace\Flutter\kx-flutter\walang> firebase --debug login                 
i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
? Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? Yes
i  To change your data collection preference at any time, run `firebase logout` and log in again. 

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=490408244&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
[2023-09-27T09:17:22.022Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[2023-09-27T09:17:22.023Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2023-09-27T09:17:43.115Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------953720652476551300675371","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 59.24.3.174:443
[2023-09-27T09:17:43.116Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:239:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-27T09:17:43.120Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[2023-09-27T09:17:43.121Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"22269acb-9fba-4713-87b3-6f6ffc0c68d0"}
[2023-09-27T09:18:04.173Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"22269acb-9fba-4713-87b3-6f6ffc0c68d0\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 216.239.36.21:443
[2023-09-27T09:18:04.450Z] FetchError: request to https://auth.firebase.tools/attest failed, reason: connect ETIMEDOUT 216.239.36.21:443
    at ClientRequest.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Error: Failed to make request to https://auth.firebase.tools/attest

**Comment by aalej** [comment]
Hi @huangsir0, thanks for providing debug logs. It looks like the request is failing because it’s taking too long for it to complete(`ETIMEDOUT`).

I don't think there is much we can do to address this since this error usually means that there is an issue with your proxy, internet connection, or the request is being blocked.

I would recommend trying to connect to a different network or temporarily turning off any proxy, firewall or VPN that you may have.
