### ISSUE TITLE
Firebase deploy not working for astro project using webframeworks

### ISSUE THREAD

**Issue by DanielSepulveda** [firebase/firebase-tools#6443]
### [REQUIRED] Environment info

**firebase-tools:** 12.7.0

**Platform:** macOS

### [REQUIRED] Test case

Deploying a new astro project with SSR enabled:
```zsh
firebase deploy --only hosting
```

### [REQUIRED] Steps to reproduce

1. Create new astro project
```zsh
npm create astro@latest
```
2. Setup SSR in astro project (use node adapter in middleware mode)
```zsh
npx astro add node
```
3. Init firebase hosting with webframeworks enabled
```zsh
firebase init hosting
```
4. Deploy firebase hosting
```zsh
firebase deploy --only hosting
```

### [REQUIRED] Expected behavior

Deploy to succeed without errors

### [REQUIRED] Actual behavior

Firebase deploy throws an error during building of the astro project:
```
Thank you for trying our experimental support for Astro on Firebase Hosting.
While this integration is maintained by Googlers it is not a supported Firebase product.
Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members.

Documentation: https://firebase.google.com/docs/hosting/frameworks/frameworks-overview
File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/***/Desktop/projects/***/firebase-test/hosting/node_modules/astro/astro.js not supported.
astro.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename astro.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/***/Desktop/projects/***/firebase-test/hosting/node_modules/astro/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_REQUIRE_ESM'
}

Error: Unable to build your Astro app
```

Full logs:
```
[2023-10-12T06:25:13.355Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-10-12T06:25:13.357Z] > authorizing via signed-in user (********@gmail.com)
[2023-10-12T06:25:13.358Z] [iam] checking project ****** for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2023-10-12T06:25:13.362Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/*****:testIamPermissions [none]
[2023-10-12T06:25:13.363Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/***:testIamPermissions x-goog-quota-user=projects/***
[2023-10-12T06:25:13.363Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/***:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-10-12T06:25:13.880Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/***:testIamPermissions 200
[2023-10-12T06:25:13.883Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/***:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-10-12T06:25:13.885Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/*** [none]
[2023-10-12T06:25:14.310Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/*** 200
[2023-10-12T06:25:14.311Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/*** {"projectId":"***","projectNumber":"***","displayName":"***","name":"projects/***","resources":{"hostingSite":"***"},"state":"ACTIVE","etag":"1_ae7c33aa-8ae7-4899-bef6-8e0739f2dd71"}

   Thank you for trying our experimental support for Astro on Firebase Hosting.
   While this integration is maintained by Googlers it is not a supported Firebase product.
   Issues filed on GitHub will be addressed on a best-effort basis by maintainers and other community members.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/frameworks-overview
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/***/Desktop/projects/***/firebase-test/hosting/node_modules/astro/astro.js not supported.
astro.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename astro.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/***/Desktop/projects/***/firebase-test/hosting/node_modules/astro/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_REQUIRE_ESM'
}

Error: Unable to build your Astro app
```

**Comment by 9kubczas4** [comment]
Hi @DanielSepulveda,

Does the error still occur in the latest version of firebase-tools? If yes, then please let me know which version of Astro are you using.
I was able to deploy the latest Astro to Firebase using Firebase-tools v12.7.0 without any issues.

Also, this issue could be related to: https://github.com/withastro/astro/issues/6715.
