### ISSUE TITLE
After firebase update setCustomUserClaims() throws an error

### ISSUE THREAD

**Issue by juliamobile** [firebase/firebase-tools#6514]
### [REQUIRED] Environment info

**firebase-tools:**
"firebase-functions": "^4.4.1",
"firebase": "^10.5.2",
"firebase-admin": "^11.0.1",
"firebase-tools": "^12.7.0",

**Platform:**
macOS

### [REQUIRED] Test case

```
const setCustomUserClaims = (users: User[]) => {
  for (let i = 0; i < users.length; i++) {
    admin
    .auth()
    .getUserByEmail(users[i].email)
    .then(user => {
      admin.auth().setCustomUserClaims(user.uid, {
        region: users[i].region
      })
    .then(() => console.log('User role defined'))
    })
    .catch(error => {
      console.error('Error defining user role', error);
    });
  }
}
```

### [REQUIRED] Steps to reproduce

- build functions
- run emulator with google credentials:
GOOGLE_APPLICATION_CREDENTIALS=certs/lbs-sales-firebase-adminsdk.json concurrently --kill-others firebase emulators:start --only functions

### [REQUIRED] Expected behavior

Firebase emulator hosts the functions like before update. 

### [REQUIRED] Actual behavior

The firebase-admit throws the error below, although ADC and quota project are set.

[0] Error defining user role FirebaseAuthError: //cloud.google.com/docs/authentication/adc-troubleshooting/user-creds . Raw server response: "{"error":{"code":403,"message":"Your application is authenticating by using local Application Default Credentials. The identitytoolkit.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .","errors":[{"message":"Your application is authenticating by using local Application Default Credentials. The identitytoolkit.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .","domain":"usageLimits","reason":"accessNotConfigured","extendedHelp":"https://console.developers.google.com"}],"status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"identitytoolkit.googleapis.com","consumer":"projects/764086051850"}}]}}"
[0]     at Function.fromServerError (/Users/jmikov/Projects/lbs/fix-firebase-build/lbs-sales/node_modules/firebase-admin/lib/utils/error.js:146:16)
[0]     at /Users/jmikov/Projects/lbs/fix-firebase-build/lbs-sales/node_modules/firebase-admin/lib/auth/auth-api-request.js:1628:49
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[0]   errorInfo: {
[0]     code: 'auth/internal-error',
[0]     message: '//cloud.google.com/docs/authentication/adc-troubleshooting/user-creds . Raw server response: "{"error":{"code":403,"message":"Your application is authenticating by using local Application Default Credentials. The identitytoolkit.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .","errors":[{"message":"Your application is authenticating by using local Application Default Credentials. The identitytoolkit.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds .","domain":"usageLimits","reason":"accessNotConfigured","extendedHelp":"https://console.developers.google.com"}],"status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"identitytoolkit.googleapis.com","consumer":"projects/764086051850"}}]}}"'
[0]   },
[0]   codePrefix: 'auth'
[0] }

**Comment by aalej** [comment]
Hi @juliamobile, looking through the issue you reported, it looks like the cause of the error is more related to the Firebase Admin SDK or a config issue with your project.

I’m thinking it might be the former since you mentioned that “ADC and quota project are set”. That said, could you reach out to the [Firebase Admin SDK team](https://github.com/firebase/firebase-admin-node/issues) as they have a better overview of the issues that occur with the Firebase Admin SDK?
