### ISSUE TITLE
Unable to create an eventarc triggered function in australia-southeast1

### ISSUE THREAD

**Issue by lox** [firebase/firebase-tools#6523]
I'm unable to create a Firebase V2 function triggered by Eventarc in australia-southeast1 (which looks to be supported by Eventarc).

### [REQUIRED] Environment info

**firebase-tools:** 12.8.1

**Platform:** macOS

### [REQUIRED] Test case

```js
import { onCustomEventPublished } from 'firebase-functions/v2/eventarc'

export const onEmailVerify = onCustomEventPublished(
  {
    eventType: 'blah.emailVerified',
    channel: 'locations/australia-southeast1/channels/firebase',
    region: 'australia-southeast1',
  },
  async (event) => {
    ...
  }
)
```

### [REQUIRED] Steps to reproduce

Deploy a function with an eventarc trigger

### [REQUIRED] Expected behavior

I expected the function and eventarc channel to be created. 

### [REQUIRED] Actual behavior

```bash
firebase deploy --only functions:eventarc-onEmailVerify --debug

...

[2023-11-14T21:54:28.926Z] Functions deploy failed.
[2023-11-14T21:54:28.926Z] {
  "endpoint": {
    "id": "eventarc-onEmailVerify",
    "project": "blah-dev",
    "region": "australia-southeast1",
    "entryPoint": "eventarc.onEmailVerify",
    "platform": "gcfv2",
    "runtime": "nodejs20",
    "eventTrigger": {
      "eventType": "blah.emailVerified",
      "retry": false,
      "eventFilters": {},
      "channel": "projects/blah-dev/locations/australia-southeast1/channels/firebase"
    },
    "labels": {
      "deployment-tool": "cli-firebase"
    },
    "ingressSettings": null,
    "availableMemoryMb": null,
    "serviceAccount": null,
    "timeoutSeconds": null,
    "maxInstances": null,
    "minInstances": null,
    "concurrency": 80,
    "vpc": null,
    "environmentVariables": {
      "FIREBASE_CONFIG": "{\"projectId\":\"blah-dev\",\"storageBucket\":\"blah-dev.appspot.com\",\"locationId\":\"australia-southeast1\"}",
      "GCLOUD_PROJECT": "blah-dev",
      "FIRESTORE_PREFER_REST": "true",
      "EVENTARC_CLOUD_EVENT_SOURCE": "projects/blah-dev/locations/australia-southeast1/services/eventarc-onEmailVerify"
    },
    "codebase": "default",
    "cpu": 1,
    "targetedByOnly": true,
    "hash": "7ffc5bbd72ea35279b2dd630151c9a026b3011bb"
  },
  "op": "upsert eventarc channel",
  "original": {
    "name": "FirebaseError",
    "children": [],
    "exit": 1,
    "message": "Unexpected error creating Eventarc channel",
    "original": {
      "name": "FirebaseError",
      "children": [],
      "context": {
        "body": {
          "error": {
            "code": 400,
            "message": "The request was invalid: [INVALID_ARGUMENT] The request was invalid: the location of channel australia-southeast1 is not supported\n[type.googleapis.com/google.rpc.DebugInfo]:{stack_entries:\"cloud/saas_accelerator/public/apierrors.go:619 +0x25 google3/cloud/saas_accelerator/public/apierrors.debugInfoWithMessage({0x55c68bbc8315, 0xa})\"  stack_entries:\"cloud/saas_accelerator/public/apierrors.go:591 +0x99 google3/cloud/saas_accelerator/public/apierrors.debugInfoWithError({0x0?, 0x0?})\"  stack_entries:\"cloud/saas_accelerator/public/apierrors.go:300 +0xe7 google3/cloud/saas_accelerator/public/apierrors.InvalidArgument({0x55c692e1dd28, 0xc00e39a930}, {0x0, 0x0}, {0x55c68bbd94ea, 0x10}, {0x55c68bc40995?, 0xc010e103f0?}, {0xc00bd78228, 0x1, ...})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel/validator.go:110 +0x7a5 google3/cloud/eventflow/controlplane/clh/v1/channel/validator.validateChannel({0x55c692e1dd28, 0xc00e39a930}, 0xc009d46e60, {{0xc001ac7c40, 0x14}, 0xc00e39b080, {0xc0127e54c0, 0x10}})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel/validator.go:31 +0x7f google3/cloud/eventflow/controlplane/clh/v1/channel/validator.ValidateCreateChannelRequest({0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, {{0xc001ac7c40, 0x14}, 0xc00e39b080, {0xc0127e54c0, 0x10}})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel_handler.go:99 +0x3c5 google3/cloud/eventflow/controlplane/clh/v1/handler.(*Handler).prepareCreateChannel(0xc005b0e9c0, {0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, 0xc0037073e0, 0xc00e39b080)\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel_handler.go:71 +0x58 google3/cloud/eventflow/controlplane/clh/v1/handler.(*Handler).PrepareCreateChannel(0xc005b0e9c0, {0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, 0xc0037073e0)\"  stack_entries:\"net/goa/rpc/rpchandler.go:100 +0x504 google3/net/goa/rpc/rpchandler.ExecHandlerSubset({0x55c692e1dd28?, 0xc00e39a840?}, 0xc00bd797b8)\"  stack_entries:\"net/goa/rpc/rpchandler.go:324 +0x97f google3/net/goa/rpc/rpchandler.(*closedRegistry).hook(0xc00be59b60, {0x55c692e1e070, 0xc0052fe120}, 0xc013402ee0)\"  detail:\"<no error>\"}[type.googleapis.com/google.rpc.BadRequest]:{field_violations:{field:\"channel.location\"}}[type.googleapis.com/google.rpc.RequestInfo]:{request_id:\"6ae638a35d68a3ca\"}",
            "status": "INVALID_ARGUMENT",
            "details": [
              {
                "@type": "type.googleapis.com/google.rpc.BadRequest",
                "fieldViolations": [
                  {
                    "field": "CreateChannelRequest"
                  }
                ]
              },
              {
                "@type": "type.googleapis.com/google.rpc.RequestInfo",
                "requestId": "6ae638a35d68a3ca"
              }
            ]
          }
        },
        "response": {
          "statusCode": 400
        }
      },
      "exit": 1,
      "message": "HTTP Error: 400, The request was invalid: [INVALID_ARGUMENT] The request was invalid: the location of channel australia-southeast1 is not supported\n[type.googleapis.com/google.rpc.DebugInfo]:{stack_entries:\"cloud/saas_accelerator/public/apierrors.go:619 +0x25 google3/cloud/saas_accelerator/public/apierrors.debugInfoWithMessage({0x55c68bbc8315, 0xa})\"  stack_entries:\"cloud/saas_accelerator/public/apierrors.go:591 +0x99 google3/cloud/saas_accelerator/public/apierrors.debugInfoWithError({0x0?, 0x0?})\"  stack_entries:\"cloud/saas_accelerator/public/apierrors.go:300 +0xe7 google3/cloud/saas_accelerator/public/apierrors.InvalidArgument({0x55c692e1dd28, 0xc00e39a930}, {0x0, 0x0}, {0x55c68bbd94ea, 0x10}, {0x55c68bc40995?, 0xc010e103f0?}, {0xc00bd78228, 0x1, ...})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel/validator.go:110 +0x7a5 google3/cloud/eventflow/controlplane/clh/v1/channel/validator.validateChannel({0x55c692e1dd28, 0xc00e39a930}, 0xc009d46e60, {{0xc001ac7c40, 0x14}, 0xc00e39b080, {0xc0127e54c0, 0x10}})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel/validator.go:31 +0x7f google3/cloud/eventflow/controlplane/clh/v1/channel/validator.ValidateCreateChannelRequest({0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, {{0xc001ac7c40, 0x14}, 0xc00e39b080, {0xc0127e54c0, 0x10}})\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel_handler.go:99 +0x3c5 google3/cloud/eventflow/controlplane/clh/v1/handler.(*Handler).prepareCreateChannel(0xc005b0e9c0, {0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, 0xc0037073e0, 0xc00e39b080)\"  stack_entries:\"cloud/eventflow/controlplane/clh/v1/channel_handler.go:71 +0x58 google3/cloud/eventflow/controlplane/clh/v1/handler.(*Handler).PrepareCreateChannel(0xc005b0e9c0, {0x55c692e1dd28, 0xc00e39a930}, 0xc0052fe540, 0xc0037073e0)\"  stack_entries:\"net/goa/rpc/rpchandler.go:100 +0x504 google3/net/goa/rpc/rpchandler.ExecHandlerSubset({0x55c692e1dd28?, 0xc00e39a840?}, 0xc00bd797b8)\"  stack_entries:\"net/goa/rpc/rpchandler.go:324 +0x97f google3/net/goa/rpc/rpchandler.(*closedRegistry).hook(0xc00be59b60, {0x55c692e1e070, 0xc0052fe120}, 0xc013402ee0)\"  detail:\"<no error>\"}[type.googleapis.com/google.rpc.BadRequest]:{field_violations:{field:\"channel.location\"}}[type.googleapis.com/google.rpc.RequestInfo]:{request_id:\"6ae638a35d68a3ca\"}",
      "status": 400
    },
    "status": 400,
    "code": 400
  }
}
[2023-11-14T21:54:28.928Z] Error: Failed to upsert eventarc channel function eventarc-onEmailVerify in region australia-southeast1
    at /Users/blah/Projects/blah/blah-firebase/node_modules/.pnpm/firebase-tools@12.8.1/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:51:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fabricator.createV2Function (/Users/lachlan/Projects/blah/blah-firebase/node_modules/.pnpm/firebase-tools@12.8.1/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:254:13)
    at async Fabricator.createEndpoint (/Users/blah/Projects/blah/blah-firebase/node_modules/.pnpm/firebase-tools@12.8.1/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:136:13)
    at async handle (/Users/lachlan/Projects/blah/blah-firebase/node_modules/.pnpm/firebase-tools@12.8.1/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:88:17)

Error: There was an error deploying functions
```

**Comment by blidd-google** [comment]
Hi @lox, sorry to hear you're running into this issue. This is indeed odd and it doesn't look like a Firebase functions-related error, but if you create a Firebase support ticket, we can help you triage this to the Eventarc team to investigate. I'm going to close this issue for now, but if you have further questions about escalating the issue to the right people, feel free to ping this thread.
