### ISSUE TITLE
firestore: unable to write firestore local emulator from Firebase SDK (javascript)

### ISSUE THREAD

**Issue by KentaYamada** [firebase/firebase-tools#6546]
### [REQUIRED] Environment info

**firebase-tools:** 12.9.1
**firebase (javascript):** 10.6.0
**jdk:** 21 (openjdk version)
**node:** 16.18.0

**Platform:** MacOS & Manjaro Linux

### [REQUIRED] Test case

1. start emulator
2. write document from react app
3. In the browser console, the message '@firebase/firestore: Firestore (10.6.0): WebChannelConnection RPC 'Write' stream 0x52387818 transport errored' is displayed

The following is the executed source code.

``` typescript
const client: FirebaseApp = initializeApp({
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  databaseURL: import.meta.env.VITE_FIREBASE_DATABASE_URL,
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
});
export const db: Firestore = getFirestore(client);

const modes = ["development", "test"];
if (modes.includes(import.meta.env.MODE)) {
  setLogLevel("debug");
  connectFirestoreEmulator(db, "127.0.0.1", 8080, { mockUserToken: "testUser" });
}

export async function createTimezone(payload: Timezone): Promise<void> {
  const collectionRef = collection(db, "timezones");
  const docRef = doc(collectionRef);
  await setDoc(docRef, {
    start_time: payload.start_time,
    end_time: payload.end_time,
    is_default_select: payload.is_default_select,
  });
}
```

``` json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 5000
    },
    "ui": {
      "enabled": true,
      "port": 4000
    }
  }
}

```
### [REQUIRED] Steps to reproduce

- [x] access to the emulator UI
- [x] access to firestore console of the emulator
- [x] the document was created successfully from the firestore console
- [ ] :ng:  Able to write documents to the local emulator from Firebase SDK. 

### [REQUIRED] Expected behavior

- Successfully connected to the emulator and able to write documents.

### [REQUIRED] Actual behavior

**firestore-debug.log**
```
Nov 26, 2023 11:18:42 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Nov 26, 2023 11:19:58 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Nov 26, 2023 11:21:13 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Nov 26, 2023 11:21:41 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Nov 26, 2023 11:21:41 AM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler doChannel
WARNING: failed to set up stream
java.lang.RuntimeException: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:139)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.lambda$wrapper$2(FirestoreV1WebChannelAdapter.java:117)
	at io.grpc.Context.run(Context.java:536)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.wrapper(FirestoreV1WebChannelAdapter.java:113)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.doChannel(FirestoreV1WebChannelAdapter.java:70)
	at com.google.net.webchannel.server.v8.HttpServerHandlerImpl.publishNewChannel(HttpServerHandlerImpl.java:166)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:140)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:91)
	at com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:86)
Caused by: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt
	at com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:120)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:109)
	at com.google.cloud.datastore.emulator.impl.firestore.CloudFirestoreV1Router.constructRequestContext(CloudFirestoreV1Router.java:412)
	at com.google.cloud.datastore.emulator.impl.firestore.CloudFirestoreV1Router.writeStream(CloudFirestoreV1Router.java:198)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:137)
	... 8 more
Caused by: com.google.firebase.firebear.client.JwtVerificationException: Invalid JWT Token. The JWT Token should consist of three parts separated by dot.
	at com.google.firebase.firebear.client.JwtToken.deserialize(JwtToken.java:119)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:101)
	... 11 more
```

**firebase-debug.log**
```
[debug] [2023-11-26T02:21:41.778Z] Nov 26, 2023 11:21:41 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Nov 26, 2023 11:21:41 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[debug] [2023-11-26T02:21:41.781Z] Nov 26, 2023 11:21:41 AM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler doChannel
WARNING: failed to set up stream
java.lang.RuntimeException: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:139)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.lambda$wrapper$2(FirestoreV1WebChannelAdapter.java:117)
	at io.grpc.Context.run(Context.java:536)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.wrapper(FirestoreV1WebChannelAdapter.java:113)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.doChannel(FirestoreV1WebChannelAdapter.java:70)
	at com.google.net.webchannel.server.v8.HttpServerHandlerImpl.publishNewChannel(HttpServerHandlerImpl.java:166)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:140)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:91)
	at com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:86)
Caused by: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt
	at com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:120)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:109)
	at com.google.cloud.datastore.emulator.impl.firestore.CloudFirestoreV1Router.constructRequestContext(CloudFirestoreV1Router.java:412)
	at com.google.cloud.datastore.emulator.impl.firestore.CloudFirestoreV1Router.writeStream(CloudFirestoreV1Router.java:198)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:137)
	... 8 more
Caused by: com.google.firebase.firebear.client.JwtVerificationException: Invalid JWT Token. The JWT Token should consist of three parts separated by dot.
	at com.google.firebase.firebear.client.JwtToken.deserialize(JwtToken.java:119)
	at com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:101)
	... 11 more

 {"metadata":{"emulator":{"name":"firestore"},"message":"Nov 26, 2023 11:21:41 AM com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler doChannel\nWARNING: failed to set up stream\njava.lang.RuntimeException: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:139)\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.lambda$wrapper$2(FirestoreV1WebChannelAdapter.java:117)\n\tat io.grpc.Context.run(Context.java:536)\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.wrapper(FirestoreV1WebChannelAdapter.java:113)\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreServerHandler.doChannel(FirestoreV1WebChannelAdapter.java:70)\n\tat com.google.net.webchannel.server.v8.HttpServerHandlerImpl.publishNewChannel(HttpServerHandlerImpl.java:166)\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:140)\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:91)\n\tat com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:86)\nCaused by: com.google.cloud.datastore.core.exception.DatastoreException: invalid jwt\n\tat com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:120)\n\tat com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:109)\n\tat com.google.cloud.datastore.emulator.impl
.firestore.CloudFirestoreV1Router.constructRequestContext(CloudFirestoreV1Router.java:412)\n\tat com.google.cloud.datastore.emulator.impl.firestore.CloudFirestoreV1Router.writeStream(CloudFirestoreV1Router.java:198)\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.<init>(FirestoreV1WebChannelAdapter.java:137)\n\t... 8 more\nCaused by: com.google.firebase.firebear.client.JwtVerificationException: Invalid JWT Token. The JWT Token should consist of three parts separated by dot.\n\tat com.google.firebase.firebear.client.JwtToken.deserialize(JwtToken.java:119)\n\tat com.google.cloud.datastore.emulator.impl.context.EmulatorAuthorization.fromHeader(EmulatorAuthorization.java:101)\n\t... 11 more\n\n"}}
```

The log shows 'Invalid JWT,' but I am not configuring this from the SDK side. If there are any missing parameters or settings, please let me know.

**The result of operations performed from the emulator UI**
![Screenshot from 2023-11-26 11-21-22](https://github.com/firebase/firebase-tools/assets/4031717/c1e8f6f9-a51e-4d7d-998e-95094e2ff73e)

**The result of writing a document from the browser**
![Screenshot from 2023-11-26 11-27-32](https://github.com/firebase/firebase-tools/assets/4031717/06e98744-a7f0-407b-acd0-06b83f7a9002)

**Comment by KentaYamada** [comment]
@aalej  
I was able to resolve the issue on my own. The cause was an error in the specification of the `mockUserToken`.

Incorrect:
``` javascript
connectFirestoreEmulator(db, "127.0.0.1", 8080, { mockUserToken: "testUser" });
```

Correct:
``` javascript
connectFirestoreEmulator(db, "127.0.0.1", 8080, { mockUserToken: { user_id: "testUser" }});
```

I can now successfully connect to the emulator using this configuration. Please consider this issue closed; there is no further problem.
I apologize for any inconvenience caused.
