### ISSUE TITLE
Auth Emulator requests timeout

### ISSUE THREAD

**Issue by Tridie2000** [firebase/firebase-tools#6650]
### [REQUIRED] Environment info

**firebase-tools:** 12.9.1

**Platform:** Alpine Linux 3.18.0 (Docker image)

### [REQUIRED] Test case

[firebase.zip](https://github.com/firebase/firebase-tools/files/13794534/firebase.zip)

### [REQUIRED] Steps to reproduce

1. Build the image: `docker build -t firebase ./firebase`
2. Run the container:
```
docker run \
  --name firebase \
  -p 4000:4000 \
  -p 9099:9099 \
  -p 8080:8080 \
  -p 9199:9199 \
  -p 4400:4400 \
  -p 4500:4500 \
  -p 9150:9150 \
 firebase
```

3. Go to the Emulator UI (auth tab)
4. Try to create a new user (or call any firebase auth SDK method

### [REQUIRED] Expected behavior

Requests do not time out and succeed without errors.
This used to work.

### [REQUIRED] Actual behavior

All auth emulator requests time out
[firebase-ui-log.txt](https://github.com/firebase/firebase-tools/files/13794656/firebase-ui-log.txt)

```
const listUsersResult = await auth().listUsers();
```

Causes:

```
db seed error: FirebaseAppError: Error while making request: timeout of 25000ms exceeded.
    at FirebaseAppError.FirebaseError [as constructor] (/workspaces/binfinder-api/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/workspaces/binfinder-api/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/workspaces/binfinder-api/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at /workspaces/binfinder-api/node_modules/firebase-admin/lib/utils/api-request.js:209:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resetAuth (/workspaces/binfinder-api/node_modules/@tridie2000/reset-firebase-emulators-js/sandbox.js:7:29)
    at async reset (/workspaces/binfinder-api/node_modules/@tridie2000/reset-firebase-emulators-js/sandbox.js:36:5)
    at async main (/workspaces/binfinder-api/prisma/seed.ts:33:3) {
  errorInfo: {
    code: 'app/network-timeout',
    message: 'Error while making request: timeout of 25000ms exceeded.'
  },
  codePrefix: 'app'
}
```

**Comment by Tridie2000** [comment]
I've found out that for some unknown reason there was a port-forward configured in VSCode for port 9099 which was interfering with the Authentication Emulator. Since I've removed the port-forward, the issue appears to be resolved.

**Comment by pdalvi1893** [comment]
But this error throws an exception which is not caught in the exception handler and stops the application. Below is the error that I receive
FirebaseAppError: Error while making requests: Error: getaddrinfo ENOTFOUND [fcm.googleapis.com](http://fcm.googleapis.com/)
    at ClientHttp2Session.<anonymous> (C:\Data\Code\ADGM\node_modules\firebase-admin\lib\utils\api-request.js:1012:23)
    at ClientHttp2Session.emit (node:events:518:28)
    at ClientHttp2Session.emit (node:domain:489:12)
    at emitClose (node:internal/http2/core:1099:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errorInfo: {
    code: 'app/network-error',
    message: 'Error while making requests: Error: getaddrinfo ENOTFOUND [fcm.googleapis.com](http://fcm.googleapis.com/)'
  },
  codePrefix: 'app'
}

and this is not getting caught in my exception handler of the application . How to handle this case.
const sendFCMMessage = async ({ others }) => {
  try {
    let success;
    if (others.tokens?.length > 0) {
      try {
        success = await admin.messaging().sendEachForMulticast(others);
      } catch (e) {
        let test = e;
      }
    }
    else {
      try {
        success = await admin.messaging().send(others);
      } catch (e) {
        let test = e;
      }
    }

    strapi.service(fcmModel).removeTokens(success.responses, others.tokens);
  } catch (error) {
    return false;
  }
};

please suggest on an approach.
