### ISSUE TITLE
Uploading large file to Storage Emulator => "PayloadTooLargeError"

### ISSUE THREAD

**Issue by exo-pla-net** [firebase/firebase-tools#6738]
### [REQUIRED] Environment info

**firebase-tools:** 13.0.3

**Platform:** Windows

### [REQUIRED] Test case

Upload a big honker of an .mp4 to http://127.0.0.1:4000/storage/your-app.appspot.com.
350MB is adequate.

### [REQUIRED] Steps to reproduce

Try to upload.
Observe the firebase-tools log.

### [REQUIRED] Expected behavior

Upload succeeds.

### [REQUIRED] Actual behavior

Spits out:
`
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\raw-body\index.js:163:17)
    at getRawBody (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\raw-body\index.js:116:12)
    at read (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\read.js:79:3)
    at rawParser (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\types\raw.js:81:5)
    at Layer.handle [as handle_request] (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:280:10)
    at rawParser (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\types\raw.js:76:7)
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\raw-body\index.js:163:17)
    at getRawBody (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\raw-body\index.js:116:12)
    at read (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\read.js:79:3)
    at rawParser (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\types\raw.js:81:5)
    at Layer.handle [as handle_request] (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\express\lib\router\index.js:280:10)
    at rawParser (C:\Users\micro\.nvm\versions\node\v20.11.0\bin\node_modules\firebase-tools\node_modules\body-parser\lib\types\raw.js:76:7)
`

**Comment by aalej** [comment]
Hey @exo-pla-net, thanks for reaching out. I was able to reproduce the error you mentioned. However, looking though [these lines](https://github.com/firebase/firebase-tools/blob/c7fbe6430471d3010ad6f12c71152377e889dc3d/src/emulator/storage/server.ts#L61-L62), it looks like the emulator has an upload size limit of ~130mb. Since the emulator is used for small scale testing, I’d recommend using files smaller in size.

**Comment by exo-pla-net** [comment]
Notes:
- 130mb represents only a few seconds of an 8k video.
- Testing a few seconds of a single video should fall under any sane definition of "small scale testing".
- "PayloadTooLargeError" is not informative. Other uses are going to be burned by this.
- Be careful glibly closing issues, or you're going to get fewer contributors. We're not getting paid to chip in.

**Comment by agoransson** [comment]
I am seeing the same issue, however my data is far below the 130mb limit proposed here.

Some debug logging from my project, the length printed here is the length of the base64 encoded string sent in the request. I gather it's about 1 MB large.

```
Request size: 1298692
POST http://127.0.0.1:4000/my-project-beta-832da/us-central1/myFunctions 413 (Payload Too Large)
```


In the terminal where I'm running the Functions Emulator I see this:

```
PayloadTooLargeError: request entity too large
    at readStream (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:163:17)
    at getRawBody (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:116:12)
    at read (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/json.js:138:5)
    at Layer.handle [as handle_request] (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:328:13)
    at /Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:280:10)
    at /Users/agoransson/.nvm/versions/node/v20.12.2/lib/node_modules/firebase-tools/lib/emulator/ExpressBasedEmulator.js:23:17
```

**Comment by mgraczyk** [comment]
Same, I am getting this error with a 200KB payload
