### ISSUE TITLE
Content-Disposition Header Error with Non-Standard Whitespace in Filenames in Storage Emulator

### ISSUE THREAD

**Issue by peteshilling** [firebase/firebase-tools#6834]
### [REQUIRED] Environment info

**firebase-tools:** 13.4.0

**Platform:** macOS 14.2.1, M2

### [REQUIRED] Test case

This can be reproduced in the emulator UI tool itself without any additional code.

### [REQUIRED] Steps to reproduce

1. Run `firebase emulators:start`
2. Capture a screenshot in macOS (cmd + shift + 3)
3. Open emulator UI, go to Storage, click 'Upload file', select screenshot that was captured in step 2
4. After upload, click on the file.

### [REQUIRED] Expected behavior

You should be able to view a preview of the uploaded image.

### [REQUIRED] Actual behavior

After I select the image file the preview image in the right side panel shows a broken image and the emulators crash.

Error log shows this

```
[debug] [2024-03-05T03:27:42.889Z] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at sendFileBytes (/Users/x/Documents/GitHub/x/node_modules/firebase-tools/lib/emulator/storage/apis/shared.js:20:9)
    at /Users/x/Documents/GitHub/x/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:101:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

Upon investigating, it looks like adding the filename to the Content-Disposition header in [this commit](https://github.com/firebase/firebase-tools/commit/5c5c17964258da5dab2c559087bef9cea887b609) caused the bug to start occurring.

It took me a while to realize there is something about the automated screenshot filenames that is causing the issue, but as best as I can tell, that's what it is.

**Comment by aalej** [comment]
Hey @peteshilling, thanks for the detailed report and for sharing your observations. I was able to reproduce this issue. I’ll notify our engineering team about this so they can take a look.

**Comment by peteshilling** [comment]
Thank you, @aalej. It's one of those bugs that isn't a big deal once you know what is happening (just avoid using screenshot files when testing), but at first it looked like a much bigger issue and took some time to narrow down.

**Comment by garrett-wombat** [comment]
Im having the same issue, except its happening when i `await bucket.file(filePath).download({ destination: tempFilePath });` within a cloud function. The function is onFinalize of storage object.

```
[debug] [2024-05-03T04:27:42.785Z] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:651:3)
    at sendFileBytes (/X/services/firebase/node_modules/.pnpm/firebase-tools@13.0.3/node_modules/firebase-tools/lib/emulator/storage/apis/shared.js:19:9)
    at /X/services/firebase/node_modules/.pnpm/firebase-tools@13.0.3/node_modules/firebase-tools/lib/emulator/storage/apis/gcloud.js:88:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by KyleFoleyImajion** [comment]
Seeing the exact same thing. Any update on this bug @aalej ? Firebase-tools version `13.7.2`

**Comment by jarodl** [comment]
I'm seeing this issue when the client app attempts to download images stored using Firebase Storage while using the emulator.

**Comment by lautenschlager-dev** [comment]
> I'm seeing this issue when the client app attempts to download images stored using Firebase Storage while using the emulator.

I can confirm that. Any news if that gets resolved?

**Comment by kylefoley** [comment]
@aalej this still reproduces in v13.11.4.

**Comment by kylefoley** [comment]
@aalej @joehan this still reproduces in 13.11.4. Filename is "Screenshot 2024-06-2
<img width="991" alt="Screenshot 2024-06-24 at 10 56 31 AM" src="https://github.com/firebase/firebase-tools/assets/34553266/93b76b25-c95c-4c60-9b5a-0808036897be">
<img width="389" alt="Screenshot 2024-06-24 at 10 56 52 AM" src="https://github.com/firebase/firebase-tools/assets/34553266/53b9a246-4c5b-46f2-8fce-061872abaf14">

3 at 8.35.19 AM.png".

**Comment by kylefoley** [comment]
Absolutely, sorry I should have added this to start. I'm locally running an angular app pointed to emulator cloud functions. When I call `getSignedURL` (`admin.storage().bucket(FIREBASE_STORAGE_BUCKET).file(path).getSignedUrl({
      action: 'read',
      expires: Date.now() + 15 * 60 * 1000
    })`)

**Comment by kylefoley** [comment]
Absolutely, sorry I should have added this to start. 

I'm locally running an angular app pointed to emulator cloud functions. When I call `admin.storage().bucket(FIREBASE_STORAGE_BUCKET).file(path).getSignedUrl({ action: 'read', expires: Date.now() + 15 * 60 * 1000 }))` on the cloud function side, I get that error and it kills the emulator. Uploading seems to work ok, but getting the signed URL is where it dies.

This cloud function performs just fine when deployed. Let me know if you need any more debug information.

**Comment by aalej** [comment]
Apologies for the delayed response here. I created this [repo](https://github.com/aalej/issues-6834-1) to try and replicate the setup you mentioned. It has a Cloud Function that has an `onFinalize` trigger which runs when a screenshot is uploaded. I’m uploading the image via the UI emulator.

At the moment, I’m still unable to reproduce the issue. Any chance you could give additional snippets of your functions code?

**Comment by aalej** [comment]
Hey folks, I can't reproduce this issue anymore using the latest version of firebase-tools, which is currently [v14.5.1](https://github.com/firebase/firebase-tools/releases). That said, I’ll go ahead and close this as this seems to have been fixed.

If anyone is still encountering this issue, please leave a comment so that we can re-open and take another look.
