### ISSUE TITLE
[firestore-emulator: datastore-mode] reserve_ids_sequential doesn't work 

### ISSUE THREAD

**Issue by artoale** [firebase/firebase-tools#6841]
### [REQUIRED] Environment info

**firebase-tools:** Using the gcloud cli version 467.0.0, firestore emulator: 1.19.2

**Platform:** macOS (intel), python client library

### [REQUIRED] Test case

```python
import os

from google.cloud import datastore

def main():
    PORT = 10901
    os.environ["DATASTORE_EMULATOR_HOST"] = "127.0.0.1:%s" % PORT
    os.environ["DATASTORE_PROJECT_ID"] = "test"

    def get_new_client():
        return datastore.Client(
            project=os.environ.get("GCLOUDC_PROJECT_ID", "test"),
            namespace=None,
            _http=None,
        )

    client = get_new_client()
    kind = "a_kind"
    key = client.key(kind, 123)

    client.reserve_ids_sequential(key, 1)


if __name__ == "__main__":
    main()
```

### [REQUIRED] Steps to reproduce
1. Start the emulator with `gcloud emulators firestore start --host-port=127.0.0.1:10901 --database-mode=datastore-mode`
2. Install the python deps: `pip install google-cloud-datastore==2.19.0` 
3. Run the above python script

### [REQUIRED] Expected behavior

Completes without errors

### [REQUIRED] Actual behavior
An exception is raised:

```
_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = ""
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-03-07T11:21:46.526089+01:00", grpc_status:2, grpc_message:""}"
>
Traceback (most recent call last):
  File "/Users/aartoni/dev/django-gcloud-connectors/firestore.py", line 31, in <module>
    main()
  File "/Users/aartoni/dev/django-gcloud-connectors/firestore.py", line 27, in main
    client.reserve_ids_sequential(to_reserve_key, 1)
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/cloud/datastore/client.py", line 1010, in reserve_ids_sequential
    self._datastore_api.reserve_ids(
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/cloud/datastore_v1/services/datastore/client.py", line 1354, in reserve_ids
    response = rpc(
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/aartoni/.pyenv/versions/3.9.17/envs/gcloudc39/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None
```

### Emulator logs

Upon receiving this request, the emulator breaks with

```
[firestore] Mar 07, 2024 11:21:46 AM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] WARNING: Operation failed: null
[firestore] java.util.NoSuchElementException
[firestore]     at com.google.common.collect.RegularImmutableSortedSet.last(RegularImmutableSortedSet.java:222)
[firestore]     at com.google.cloud.datastore.emulator.impl.firestore.FirestoreEmulatorHelper.reserveIds(FirestoreEmulatorHelper.java:420)
[firestore]     at com.google.cloud.datastore.emulator.impl.firestore.CloudDatastoreV1.reserveIds(CloudDatastoreV1.java:492)
[firestore]     at com.google.cloud.datastore.emulator.impl.firestore.CloudDatastoreV1Router.reserveIds(CloudDatastoreV1Router.java:108)
[firestore]     at com.google.cloud.datastore.emulator.firestore.cloudv1.CloudDatastoreV1GrpcAdapter$1.lambda$reserveIds$6(CloudDatastoreV1GrpcAdapter.java:98)
[firestore]     at com.google.cloud.datastore.emulator.firestore.cloudv1.CloudDatastoreV1GrpcAdapter.unary(CloudDatastoreV1GrpcAdapter.java:49)
[firestore]     at com.google.cloud.datastore.emulator.firestore.cloudv1.CloudDatastoreV1GrpcAdapter$1.reserveIds(CloudDatastoreV1GrpcAdapter.java:98)
[firestore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:766)
[firestore]     at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
[firestore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
[firestore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
[firestore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[firestore]     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
[firestore]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[firestore]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[firestore]     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by aalej** [comment]
Hey @artoale, thanks for filing a detailed report! I’m able to reproduce the behavior you mentioned using the provided steps. I’ll raise this to our engineering team so they can take a look.

**Comment by harshyyy21** [comment]
Went ahead and fixed this. Should be available in next weeks release!
