### ISSUE TITLE
admin.initializeApp in cloud functions emulation (i.e. local serve) is broken in 3.17.5

### ISSUE THREAD

**Issue by Rulsky** [firebase/firebase-tools#691]
### Version info
3.17.5

### Platform Information
macOS 10.12.6 (16G1212)
node v8.9.3

### Steps to reproduce
when trying to run emulation with 3.17.5 by issuing next command:
`firebase serve --only hosting,functions` I got an error:
```bash
Error from emulator. Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.

Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
```

### Expected behavior
if you run the same command with 3.17.4 - emulation works.
If you deploy code - everything works as expected on the server - both 3.17.4 and 3.17.5

By the way, previously, I did not need to have a service account credential in my functions dir, but now I do.
### Actual behavior

stack trace with debug
```shell
$ /Users/rulsky/dev/freelance/nika-gallery/node_modules/.bin/firebase serve --debug --only hosting,functions
[2018-03-08T19:48:48.804Z] ----------------------------------------------------------------------
[2018-03-08T19:48:48.807Z] Command:       /usr/local/Cellar/node@8/8.9.3/bin/node /Users/rulsky/dev/freelance/nika-gallery/node_modules/.bin/firebase serve --debug --only hosting,functions
[2018-03-08T19:48:48.807Z] CLI Version:   3.17.5
[2018-03-08T19:48:48.807Z] Platform:      darwin
[2018-03-08T19:48:48.807Z] Node Version:  v8.9.3
[2018-03-08T19:48:48.808Z] Time:          Thu Mar 08 2018 21:48:48 GMT+0200 (EET)
[2018-03-08T19:48:48.808Z] ----------------------------------------------------------------------

[2018-03-08T19:48:48.819Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-03-08T19:48:48.819Z] > authorizing via signed-in user
[2018-03-08T19:48:48.821Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/nika-gallery

 Thu Mar 08 2018 21:48:48 GMT+0200 (EET)
[2018-03-08T19:48:49.596Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 08 Mar 2018 19:48:49 GMT, content-type=application/json; charset=utf-8, content-length=111, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-03-08T19:48:49.597Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/nika-gallery/tokens

 Thu Mar 08 2018 21:48:49 GMT+0200 (EET)
[2018-03-08T19:48:50.279Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 08 Mar 2018 19:48:50 GMT, content-type=application/json; charset=utf-8, content-length=260, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-03-08T19:48:50.280Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/nika-gallery

 Thu Mar 08 2018 21:48:50 GMT+0200 (EET)
[2018-03-08T19:48:51.377Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 08 Mar 2018 19:48:51 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35", accept-ranges=none, connection=close

=== Serving from '/Users/rulsky/dev/freelance/nika-gallery'...

i  functions: Preparing to emulate functions.
[2018-03-08T19:48:52.057Z] Fetching environment
[2018-03-08T19:48:52.059Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/430306600714:getServerAppConfig

 Thu Mar 08 2018 21:48:52 GMT+0200 (EET)
[2018-03-08T19:48:52.060Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/430306600714/clients/_:getWebAppConfig

 Thu Mar 08 2018 21:48:52 GMT+0200 (EET)
[2018-03-08T19:48:52.662Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 08 Mar 2018 19:48:52 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35", accept-ranges=none, connection=close
[2018-03-08T19:48:52.663Z] Starting @google-cloud/functions-emulator
Warning: You're using Node.js v8.9.3 but Google Cloud Functions only supports v6.11.5.
[2018-03-08T19:48:52.875Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 08 Mar 2018 19:48:52 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35", accept-ranges=none, connection=close
i  hosting: Serving hosting files from: build
✔  hosting: Local server: http://localhost:5000

[2018-03-08T19:48:54.222Z] Parsing function triggers
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
[2018-03-08T19:48:54.741Z] Error during trigger parsing:  Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.

Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (/Users/rulsky/dev/freelance/nika-gallery/functions/node_modules/firebase-functions/lib/config.js:55:15)
    at config (/Users/rulsky/dev/freelance/nika-gallery/functions/node_modules/firebase-functions/lib/config.js:29:9)
    at Object.<anonymous> (/Users/rulsky/dev/freelance/nika-gallery/functions/server/data/connector.js:16:51)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
⚠  functions: Error from emulator. Error occurred while parsing your function triggers. Please ensure you have the latest firebase-functions SDK by running "npm i --save firebase-functions@latest" inside your functions folder.

Error: Firebase config variables are not available. Please use the latest version of the Firebase CLI to deploy this function.
    at init (/Users/rulsky/dev/freelance/nika-gallery/functions/node_modules/firebase-functions/lib/config.js:55:15)
    at config (/Users/rulsky/dev/freelance/nika-gallery/functions/node_modules/firebase-functions/lib/config.js:29:9)
    at Object.<anonymous> (/Users/rulsky/dev/freelance/nika-gallery/functions/server/data/connector.js:16:51)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
[2018-03-08T19:48:54.742Z]
```

**Comment by laurenzlong** [comment]
Hi @Rulsky what's your firebase-functions version?

**Comment by Rulsky** [comment]
Hello @laurenzlong my dependencies are:
```
"firebase-admin": "^5.9.0",
"firebase-functions": "^0.8.1",
```

**Comment by Jhony0311** [comment]
@laurenzlong Any idea on when this get merged or what can I do in the meantime to keep working?

**Comment by mondul** [comment]
In the meantime I did:

`$ npm uninstall firebase-tools -g && npm install -g https://github.com/firebase/firebase-tools.git#laurenzlong-patch-1`

Then had to:

`$ nano +115 ~/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/lib/functionsEmulator.js`

And add a line with `firebaseConfig = JSON.stringify(result);` before the logger debug.

After that I was able to serve a function locally. Hope gets merged soon.

**Comment by laurenzlong** [comment]
Thanks for tip on the missing line @mondul . We're also waiting for https://github.com/firebase/firebase-tools/pull/692 before making another release. 

In the meanwhile, you can also downgrade to 3.17.4 by running:
` npm install -g firebase-tools@3.17.4`

**Comment by BernalCarlos** [comment]
Thank you @laurenzlong, your PR seems to solve the problem, I was able to make it work after downloading the branch.

`npm uninstall firebase-tools -g && npm install -g https://github.com/firebase/firebase-tools.git#laurenzlong-patch-1`

@mondul The PR was updated with your suggestion, there is no need to do anything else now.

Let's hope this gets merged soon.

**Comment by laurenzlong** [comment]
3.17.6 was just released. Thanks for the patience everyone

**Comment by louggl** [comment]
@laurenzlong, I am having same issues as @Rulsky. 

I saw your [merge](https://github.com/firebase/firebase-tools/pull/693) and installed it. 

It did prevent the 'Failed to load functions source code. Ensure that you have the latest SDK...' message from appearing, but now it just hangs after 'Parsing function triggers'...


```
functions $ firebase --debug serve --only functions
[2018-03-09T22:50:48.564Z] ----------------------------------------------------------------------
[2018-03-09T22:50:48.569Z] Command:       /Users/***/.nvm/versions/node/v6.11.5/bin/node /Users/***/.nvm/versions/node/v6.11.5/bin/firebase --debug serve --only functions
[2018-03-09T22:50:48.570Z] CLI Version:   3.17.6
[2018-03-09T22:50:48.570Z] Platform:      darwin
[2018-03-09T22:50:48.570Z] Node Version:  v6.11.5
[2018-03-09T22:50:48.571Z] Time:          Fri Mar 09 2018 14:50:48 GMT-0800 (PST)
[2018-03-09T22:50:48.571Z] ----------------------------------------------------------------------

[2018-03-09T22:50:48.587Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-03-09T22:50:48.588Z] > authorizing via signed-in user
[2018-03-09T22:50:48.591Z] >>> HTTP REQUEST GET https://***

 Fri Mar 09 2018 14:50:48 GMT-0800 (PST)
[2018-03-09T22:50:50.598Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 09 Mar 2018 22:50:50 GMT, content-type=application/json; charset=utf-8, content-length=154, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-03-09T22:50:50.600Z] >>> HTTP REQUEST GET https://***/tokens

 Fri Mar 09 2018 14:50:50 GMT-0800 (PST)
[2018-03-09T22:50:51.409Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 09 Mar 2018 22:50:51 GMT, content-type=application/json; charset=utf-8, content-length=262, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-03-09T22:50:51.411Z] >>> HTTP REQUEST GET https://***

 Fri Mar 09 2018 14:50:51 GMT-0800 (PST)
[2018-03-09T22:50:51.690Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 09 Mar 2018 22:50:51 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35", accept-ranges=none, connection=close

=== Serving from ***...

i  functions: Preparing to emulate functions.
[2018-03-09T22:50:52.731Z] Fetching environment
[2018-03-09T22:50:52.733Z] >>> HTTP REQUEST GET https://***

 Fri Mar 09 2018 14:50:52 GMT-0800 (PST)
[2018-03-09T22:50:53.144Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 09 Mar 2018 22:50:53 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35", accept-ranges=none, connection=close
[2018-03-09T22:50:53.145Z] Starting @google-cloud/functions-emulator
[2018-03-09T22:50:55.233Z] Parsing function triggers
```

**Comment by MehranJanfeshan** [comment]
@laurenzlong and it broke a lot of things. https://github.com/laurenzlong
