### ISSUE TITLE
firebase deploy: Error: Source and destination must not be the same. - Error: An unexpected error has occurred 

### ISSUE THREAD

**Issue by JohannCornet** [firebase/firebase-tools#7022]
### [REQUIRED] Environment info

firebase --version
13.7.3

**Platform:**
Windows

### [REQUIRED] Test case

Default application created from npx create-next-app@latest --experimental-app.

default option for nextjs (app)

2 page have been modified

app\page.js
```js
// Root page.js
"use client"
import React from 'react';
import { CompareSurfboardsProvider } from '../contexts/CompareSurfboardsContext'

function App() {
  return (
    <CompareSurfboardsProvider>      
      {/* other components */}
    </CompareSurfboardsProvider>
  );
}

export default App;
```
app\layout.js
```js
"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Breadcrumbs from '../components/Breadcrumbs.js'; // Ensure you have this component set up
import Footer from '../components/Footer.js';  // Adjust the path as necessary
import 'bootstrap/dist/css/bootstrap.min.css';
import { CompareSurfboardsProvider } from '../contexts/CompareSurfboardsContext'


const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "The ultimate Surfboards Comparator",
  description: "The ultimate Surfboards Comparator",
};*/


export default function RootLayout({ children }) {

  const breadcrumbItems = [
    { title: 'Home', href: '/' },
    // Add more breadcrumb items as needed
  ];
  

  return (
    <CompareSurfboardsProvider>
      <html lang="en">
        <body className={inter.className}>
          <Container fluid>
            <Row className="align-items-center">
              <Col xs={1}><a href="/main/"> <img id="logo" src="\img\logo.png" alt="logo of a surfboard with a tick"></img> </a> </Col>
              <Col xs={9} ><h1 className="title">The ultimate Surfboards Comparator</h1></Col>
              <Col xs={2}><a href="admin">{//Login 
              }
               </a></Col>
            </Row>
            <Row>
              <Col xs={12}>
                {/* Render Breadcrumbs */}
                <Breadcrumbs items={breadcrumbItems} />
              </Col>
            </Row>
          </Container>

          {children}
          <Footer />  {/* This is where the Footer gets rendered */}

        </body>
      </html>
    </CompareSurfboardsProvider>
  );
}
```
components

components\breadcrumbs.js
```js
'use client';
import React, { useMemo, Suspense } from 'react';
import Link from 'next/link';
import { usePathname, useSearchParams } from 'next/navigation';

// Example array of brand menu items
const brandMenuItems = [
  { title: 'Firewire', href: '/search?brand=Firewire' },
  { title: 'JS Industries', href: '/search?brand=JS Industries' },
  { title: 'Channel Island', href: '/search?brand=Channel Island' },
  // Add more brands as needed
];

const sizeMenuItems = [
    { title: 'Knee', href: '/search?size=knee' },
    { title: 'Waist', href: '/search?size=waist' },
    { title: 'Shoulder', href: '/search?size=shoulder' },
    { title: 'Overhead', href: '/search?size=Overhead' },
    // Add more sizes as needed
  ];

const BreadcrumbsContent = () => {
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const breadcrumbs = useMemo(() => {
    let crumbs = [{ title: 'Home', href: '/main/home' }];

    if (pathname.includes('/search')) {
      crumbs.push({ title: 'Surfboards', href: '/main/search?category=all' });
    }

    const brand = searchParams.get('brand');
    const size = searchParams.get('size');
    
    if (brand) {
      const brandItem = brandMenuItems.find(item => item.href.includes(`brand=${brand}`));
      if (brandItem) {
        crumbs.push({ title: brandItem.title, href: `/main${brandItem.href}` });
      }
    }

    if (size) {
      const sizeItem = sizeMenuItems.find(item => item.href.includes(`size=${size}`));
      if (sizeItem) {
        crumbs.push({ title: sizeItem.title, href: `/main${sizeItem.href}` });
      }
    }

    return crumbs;
  }, [pathname, searchParams]);

  return (
    <ol className="breadcrumb">
      {breadcrumbs.map((crumb, index) => (
        <li key={index} className={`breadcrumb-item ${index === breadcrumbs.length - 1 ? 'active' : ''}`}>
          {index < breadcrumbs.length - 1 ? (
            <Link href={crumb.href}>
              {crumb.title}
            </Link>
          ) : (
            crumb.title
          )}
        </li>
      ))}
    </ol>
  );
};

const Breadcrumbs = () => {
  return (
    <nav aria-label="breadcrumb">
      <Suspense fallback={<div>Loading...</div>}>
        <BreadcrumbsContent />
      </Suspense>
    </nav>
  );
};

export default Breadcrumbs;
```

components\DynamicMenu.js

```js
export default function DynamicMenu({ items }) {
    return (
      <nav>
        {items.map((item) => (
          <a key={item.key} href={item.href}>{item.title}</a>
        ))}
      </nav>
    );
  }
```

components\footer.js
```js  
// components/Footer.js
"use client";

import Link from 'next/link';
import { Container, Row, Col } from 'react-bootstrap';

export default function Footer() {
  return (
    <Container fluid className="bg-light mt-5">
      <Row>
        <Col className="text-center py-3">
          © {new Date().getFullYear()} The Ultimate Surfboards Comparator
        </Col>
        <Col className="text-center py-3">
          <Link href="/main/disclaimer" passHref>
            Disclaimer
          </Link>
        </Col>
      </Row>
    </Container>
  );
}
```

contexts

```js
// /contexts/CompareSurfboardsContext.js
import React, { createContext, useContext, useState } from 'react';

const CompareSurfboardsContext = createContext();

export const CompareSurfboardsProvider = ({ children }) => {
  const [comparedSurfboards, setComparedSurfboards] = useState([]);

  const addSurfboardToCompare = (surfboard) => {
    if (!comparedSurfboards.some(s => s.id === surfboard.id)) {
      setComparedSurfboards([...comparedSurfboards, surfboard]);
    }
  };

  const removeSurfboardFromCompare = (surfboardId) => {
    setComparedSurfboards(comparedSurfboards.filter(s => s.id !== surfboardId));
  };

  return (
    <CompareSurfboardsContext.Provider value={{ comparedSurfboards, addSurfboardToCompare, removeSurfboardFromCompare }}>
      {children}
    </CompareSurfboardsContext.Provider>
  );
};

export const useCompareSurfboards = () => useContext(CompareSurfboardsContext);
```

### [REQUIRED] Steps to reproduce

firebase deploy --debug

firebase deploy --debug

### [REQUIRED] Expected behavior

Deploying the app nextjs, firebase, application in the cloud

### [REQUIRED] Actual behavior

```
c:\DEV\lordsboardsBUG>firebase deploy --debug
(node:6968) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2024-04-19T09:10:38.667Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2024-04-19T09:10:38.669Z] > authorizing via signed-in user (johann.cornet59@gmail.com)
[2024-04-19T09:10:38.672Z] [iam] checking project surfboardpicker-a61a6 for permissions ["cloudconfig.configs.get","cloudconfig.configs.update","cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get","firebasedatabase.instances.update","firebasehosting.sites.update","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create",null]
[2024-04-19T09:10:38.676Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/surfboardpicker-a61a6:testIamPermissions [none]
[surfboard-debug.zip](https://github.com/firebase/firebase-tools/files/15038529/surfboard-debug.zip)

[2024-04-19T09:10:38.676Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/surfboardpicker-a61a6:testIamPermissions x-goog-quota-user=projects/surfboardpicker-a61a6
[2024-04-19T09:10:38.677Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/surfboardpicker-a61a6:testIamPermissions {"permissions":["cloudconfig.configs.get","cloudconfig.configs.update","cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get","firebasedatabase.instances.update","firebasehosting.sites.update","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create",null]}
[2024-04-19T09:10:39.864Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/surfboardpicker-a61a6:testIamPermissions 200
[2024-04-19T09:10:39.865Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/surfboardpicker-a61a6:testIamPermissions {"permissions":["cloudconfig.configs.get","cloudconfig.configs.update","cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get","firebasedatabase.instances.update","firebasehosting.sites.update","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]}
[2024-04-19T09:10:39.868Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project surfboardpicker-a61a6:


[2024-04-19T09:10:39.875Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/surfboardpicker-a61a6/serviceAccounts/surfboardpicker-a61a6@appspot.gserviceaccount.com:testIamPermissions [none]
[2024-04-19T09:10:39.875Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/surfboardpicker-a61a6/serviceAccounts/surfboardpicker-a61a6@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[2024-04-19T09:10:40.323Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/surfboardpicker-a61a6/serviceAccounts/surfboardpicker-a61a6@appspot.gserviceaccount.com:testIamPermissions 200
[2024-04-19T09:10:40.323Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/surfboardpicker-a61a6/serviceAccounts/surfboardpicker-a61a6@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[2024-04-19T09:10:40.326Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 [none]
[2024-04-19T09:10:40.916Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 200
[2024-04-19T09:10:40.917Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 {"projectId":"surfboardpicker-a61a6","projectNumber":"385912847997","displayName":"SurfboardPicker","name":"projects/surfboardpicker-a61a6","resources":{"hostingSite":"surfboardpicker-a61a6","realtimeDatabaseInstance":"surfboardpicker-a61a6-default-rtdb","storageBucket":"surfboardpicker-a61a6.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_e7c8a9f9-2618-4ce0-a9f6-91d88c137326"}
[2024-04-19T09:10:40.922Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 [none]
[2024-04-19T09:10:41.513Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 200
[2024-04-19T09:10:41.515Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/surfboardpicker-a61a6 {"projectId":"surfboardpicker-a61a6","projectNumber":"385912847997","displayName":"SurfboardPicker","name":"projects/surfboardpicker-a61a6","resources":{"hostingSite":"surfboardpicker-a61a6","realtimeDatabaseInstance":"surfboardpicker-a61a6-default-rtdb","storageBucket":"surfboardpicker-a61a6.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_e7c8a9f9-2618-4ce0-a9f6-91d88c137326"}

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.
   The integration is known to work with Next.js version 12 - 14.0. You may encounter errors.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[2024-04-19T09:10:52.508Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 [none]
[2024-04-19T09:10:53.854Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 200
[2024-04-19T09:10:53.855Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 {"name":"projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6","defaultUrl":"https://surfboardpicker-a61a6.web.app","appId":"1:385912847997:web:05936d42a5b94eb42cfb14","type":"DEFAULT_SITE"}
  ▲ Next.js 14.2.2



   Creating an optimized production build ...

 ✓ Compiled successfully

   Linting and checking validity of types ...

   Collecting page data ...

   Generating static pages (0/4) ...

   Generating static pages (1/4)

   Generating static pages (2/4)

   Generating static pages (3/4)

 ✓ Generating static pages (4/4)

   Finalizing page optimization ...

   Collecting build traces ...



Route (app)                              Size     First Load JS
┌ ○ /                                    141 B            87 kB
└ ○ /_not-found                          871 B          87.8 kB
+ First Load JS shared by all            86.9 kB
  ├ chunks/23-b6b066db8b1efede.js        31.4 kB
  ├ chunks/fd9d1056-2821b0f0cabcd8bd.js  53.6 kB
  └ other shared chunks (total)          1.84 kB



○  (Static)  prerendered as static content


Building a Cloud Function to run this application. This is needed due to:
 • non-static component /_not-found/page

[2024-04-19T09:11:11.184Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 [none]
[2024-04-19T09:11:12.527Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 200
[2024-04-19T09:11:12.528Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6 {"name":"projects/surfboardpicker-a61a6/sites/surfboardpicker-a61a6","defaultUrl":"https://surfboardpicker-a61a6.web.app","appId":"1:385912847997:web:05936d42a5b94eb42cfb14","type":"DEFAULT_SITE"}
[2024-04-19T09:11:12.911Z] Error: Source and destination must not be the same.
    at C:\Users\johan\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\util\stat.js:49:19
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```
[surfboard-debug.zip](https://github.com/firebase/firebase-tools/files/15038534/surfboard-debug.zip)

**Comment by aalej** [comment]
Hey @JohannCornet, thanks for reaching out and providing code snippets. I was able to reproduce the error you mentioned. From what I can tell, the issue is only reproducible on Windows. Tried it out on a macOS machine and there were no issues encountered during deployment.

Let me raise this to our engineering team so they can take a look. In case anyone wants to reproduce the issue, I created this [mcve](https://github.com/aalej/issues-7022) using the code snippets provided.

**Comment by jamesdaniels** [comment]
@leoortizz PTAL

**Comment by JwillSDP** [comment]
I am getting this same error. I have create TWO apps that give me the same using Next.js 14

`
[debug] [2024-04-21T15:22:17.208Z] ----------------------------------------------------------------------
[debug] [2024-04-21T15:22:17.211Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Afrosoul4eva\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js hosting:channel:deploy AmalPreview
[debug] [2024-04-21T15:22:17.211Z] CLI Version:   13.7.3
[debug] [2024-04-21T15:22:17.212Z] Platform:      win32
[debug] [2024-04-21T15:22:17.212Z] Node Version:  v21.6.1
[debug] [2024-04-21T15:22:17.212Z] Time:          Sun Apr 21 2024 11:22:17 GMT-0400 (Eastern Daylight Time)
[debug] [2024-04-21T15:22:17.212Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-04-21T15:22:17.291Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-04-21T15:22:17.292Z] > authorizing via signed-in user (jwilliams@souldopepro.com)
[debug] [2024-04-21T15:22:17.292Z] [iam] checking project v12elites for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-04-21T15:22:17.295Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/v12elites:testIamPermissions [none]
[debug] [2024-04-21T15:22:17.295Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/v12elites:testIamPermissions x-goog-quota-user=projects/v12elites
[debug] [2024-04-21T15:22:17.295Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/v12elites:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2024-04-21T15:22:17.604Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/v12elites:testIamPermissions 200
[debug] [2024-04-21T15:22:17.604Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/v12elites:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2024-04-21T15:22:17.605Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/v12elites [none]
[debug] [2024-04-21T15:22:18.071Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/v12elites 200
[debug] [2024-04-21T15:22:18.071Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/v12elites {"projectId":"v12elites","projectNumber":"475077005955","displayName":"V12Elites","name":"projects/v12elites","resources":{"hostingSite":"v12elites"},"state":"ACTIVE","etag":"1_e3a6d158-358a-45e4-a9d6-8a7c81d69064"}
[debug] [2024-04-21T15:22:18.073Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview [none]
[debug] [2024-04-21T15:22:18.391Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:22:18.391Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:20:20.957663814Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:20:20.957663814Z"}
[debug] [2024-04-21T15:22:18.391Z] [hosting] found existing channel for site v12elites {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:20:20.957663814Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:20:20.957663814Z"}
[debug] [2024-04-21T15:22:18.392Z] >>> [apiv2][query] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview updateMask=ttl
[debug] [2024-04-21T15:22:18.392Z] >>> [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"ttl":"604800s"}
[debug] [2024-04-21T15:22:18.530Z] <<< [apiv2][status] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:22:18.530Z] <<< [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:22:22.976109930Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:22:22.976109930Z"}
[debug] [2024-04-21T15:22:18.530Z] [hosting] updated TTL for existing channel for site v12elites {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:22:22.976109930Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:22:22.976109930Z"}
[info] 
   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.
   The integration is known to work with Next.js version 12 - 14.0. You may encounter errors.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[debug] [2024-04-21T15:22:31.547Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview [none]
[debug] [2024-04-21T15:22:31.861Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:22:31.861Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:22:22.976109930Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:22:22.976109930Z"}
[info]   ▲ Next.js 14.2.2

[info] 

[info]    Creating an optimized production build ...

[info]  ✓ Compiled successfully

[info]    Linting and checking validity of types ...

[info]    Collecting page data ...

[info]    Generating static pages (0/4) ...

[info]    Generating static pages (1/4) 

[info]    Generating static pages (2/4) 

[info]    Generating static pages (3/4) 

[info]  ✓ Generating static pages (4/4)

[info]    Finalizing page optimization ...
   Collecting build traces ...

[info] 

[info] Route (app)                              Size     First Load JS
┌ ○ /                                    141 B            87 kB
└ ○ /_not-found                          871 B          87.8 kB
+ First Load JS shared by all            86.9 kB
  ├ chunks/23-b6b066db8b1efede.js        31.4 kB
  ├ chunks/fd9d1056-2821b0f0cabcd8bd.js  53.6 kB
  └ other shared chunks (total)          1.84 kB



[info] ○  (Static)  prerendered as static content


[info] Building a Cloud Function to run this application. This is needed due to:
[info]  • non-static component /_not-found/page
[info] 
[debug] [2024-04-21T15:22:49.669Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview [none]
[debug] [2024-04-21T15:22:49.966Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:22:49.966Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:22:22.976109930Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:22:22.976109930Z"}
[debug] [2024-04-21T15:22:50.092Z] Error: Source and destination must not be the same.
    at C:\Users\Afrosoul4eva\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\util\stat.js:49:19
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.

`

**Comment by JwillSDP** [comment]
@leoortizz Thank you so much. I reinstalled firebase-tools to version 13.6.1

```bash

npm uninstall -g firebase-tools

npm install -g firebase-tools@13.6.1

```
