### ISSUE TITLE
Can't run firebase command on the terminal

### ISSUE THREAD

**Issue by pash90** [firebase/firebase-tools#703]
### Version info
v3.17.4, v3.17.5, v3.17.6

### Platform Information
OS X

### Steps to reproduce
I was on node 6.9.* and wanted to serve functions locally. Due to the lack of support I upgraded to 6.11.5

1. `npm i -g firebase-tools@latest` (same process with other versions)
2. `firebase login`

### Expected behavior
Opens a browser window for logging in and continues the process onwards

### Actual behavior
```
/usr/local/lib/node_modules/firebase-tools/node_modules/sntp/lib/index.js:19
exports.time = async function (options = {}) {
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/hawk/lib/index.js:5:16)
```

**Comment by MehranJanfeshan** [comment]
@pash90 it's similar to this: https://github.com/firebase/firebase-tools/issues/702

**Comment by Rulsky** [comment]
@pash90 async isn't supported in node 6

**Comment by laurenzlong** [comment]
Closing as duplicate of #702.

**Comment by pash90** [comment]
@Rulsky I found it out after a bit of more reading. Thanks @laurenzlong for closing. Turned out to be a node installation issue. Thank you for all the help
