### ISSUE TITLE
Functions config export failing with unexpected error

### ISSUE THREAD

**Issue by tahir606** [firebase/firebase-tools#7036]
### [REQUIRED] Environment info

**firebase-tools:** 13.7.3

**Platform:** macOS

### [REQUIRED] Steps to reproduce

Running the command `firebase functions:config:export` throws the error

### [REQUIRED] Expected behavior

The config variables should be exported

### [REQUIRED] Actual behavior

Error output:
```
[info] i  Importing configs from projects: [teamapps, single-station-364002, teamapps-france, teamapps-uat] 
[debug] [2024-04-23T16:36:25.867Z] TypeError: Cannot read properties of undefined (reading 'replace')
    at escape (/Users/tahirshakir/.nvm/versions/node/v18.16.1/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:128:14)
    at /Users/tahirshakir/.nvm/versions/node/v18.16.1/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:131:65
    at Array.map (<anonymous>)
    at Object.toDotenvFormat (/Users/tahirshakir/.nvm/versions/node/v18.16.1/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:131:24)
    at /Users/tahirshakir/.nvm/versions/node/v18.16.1/lib/node_modules/firebase-tools/lib/commands/functions-config-export.js:110:56
    at Array.map (<anonymous>)
    at Command.actionFn (/Users/tahirshakir/.nvm/versions/node/v18.16.1/lib/node_modules/firebase-tools/lib/commands/functions-config-export.js:110:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.

```

**Comment by aalej** [comment]
Hey @tahir606, thanks for reaching out and sharing your debug logs. I’m able to reproduce the error you mentioned. From what I can gather, it occurs when at least one of your env variables doesn’t have a value set, resulting in it being `undefined`. I’ll raise this to our engineering team to see what we can do here.

**Comment by tahir606** [comment]
Thanks @aalej, That is great to know. What would be the solution here? Setting a value to the env variable? And if so how can I find out which one is it?

Because when I do `firebase:config:get` I get the complete object with all the envs.

**Comment by aalej** [comment]
That's interesting, I was under the assumption that `firebase:config:get` was returning something like:
```json
{
  ...
  "my": {
    "test": {}
  }
  ...
}
```
Got the config above by running `firebase functions:config:set my.test.id=`. Setting the value of the variable should fix the issue. Any chance you could share an overview of the output of running `firebase:config:get`? Please change the string values in the output to remove any personal identifiable information.

**Comment by dominics** [comment]
In my case, there was a value set to `undefined`, but neither `firebase functions:config:get` nor `firebase functions:config:get --json` showed it. Nor did the more specific command `firebase functions:config:get broken.key --json` (which shows the same thing as if the config value did not exist: `true` for success, but no value on the returned object).

In my case, it certainly looks like a typo in a config value someone has tried to set. And `firebase functions:config:unset broken.key` fixed it up

Would be good to fix the exception though
