### ISSUE TITLE
Next.js SSR: "Couldn't find any 'pages' or 'app' directory. Please create one under the project root"

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/firebase-tools#7128]
### [REQUIRED] Environment info

**firebase-tools:** 13.8.0

**Platform:** macOS

### [REQUIRED] Test case

Our docs using Nextra: https://github.com/SharezoneApp/sharezone-app/tree/main/docs

### [REQUIRED] Steps to reproduce

1. Clone our Nextra docs: https://github.com/SharezoneApp/sharezone-app/tree/main/docs
2. Enable web frameworks
3. Update `firebase.json` and `.firebaserc` to use your own Firebase project
4. Run `firebase deploy`

### [REQUIRED] Expected behavior

No errors in the console.

### [REQUIRED] Actual behavior

We are getting a lot of error in our console for our `ssrsharezonedocsprod` cloud function:

![image](https://github.com/firebase/firebase-tools/assets/24459435/d62f705a-c5a0-4d00-8487-a71212fd5ae2)

```

Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (/workspace/node_modules/next/dist/lib/find-pages-dir.js:42:15)
    at findPagesDirectory (/workspace/node_modules/nextra/dist/index.js:169:15)
    at Object.<anonymous> (/workspace/node_modules/nextra/dist/index.js:173:53)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/workspace/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:177:18)
```

The source folder of deployed cloud function (downloaded via GCP console):

![image](https://github.com/firebase/firebase-tools/assets/24459435/36d92277-ca4b-4afc-91d1-c1b6f5ec9bb5)

Local `functions` folder in `.firebase`:

![image](https://github.com/firebase/firebase-tools/assets/24459435/da733372-cafa-4d58-9fa3-63d0e526e97e)

**Comment by aalej** [comment]
Hey @nilsreichardt, thanks for the detailed report. Sorry to hear you encounter this issue. I’m currently unable to reproduce this. I tried following the steps provided, but no errors were raised during deployment or when visiting the site. 

![image](https://github.com/firebase/firebase-tools/assets/118378103/5683b41e-e38e-4950-91a5-3b267a8e5995)

I also tried visiting the other pages on the deployed site but no errors were raised as well. Does the error message occur when visiting a specific page? 

Could you try deploying using firebase-tools 13.8.1? Also, regarding the screenshot of the `function-source` you downloaded, could you try running `ls -a` to see if there are also other files downloaded? I’m guessing there may be some hidden files which are not being shown when using finder.

**Comment by nilsreichardt** [comment]
Sorry, that I wasn't clear about the issue. The deployment is fine. It's running in production at https://docs.sharezone.net. However, our Google Cloud logs are spammed by the SSR cloud function (see screenshot). My goal is to get rid of the error logs in the cloud function.

Here the screenshot with the hidden files:

<img width="852" alt="image" src="https://github.com/firebase/firebase-tools/assets/24459435/b8176343-936e-4a81-9ef9-82cf5a7d6985">

<img width="852" alt="image" src="https://github.com/firebase/firebase-tools/assets/24459435/eadc3c3a-f78c-403c-98eb-8b26dbbb1b37">

**Comment by leoortizz** [comment]
Hey @nilsreichardt are you still having this issue?

**Comment by nilsreichardt** [comment]
Yes, there are still many error logs
