### ISSUE TITLE
Failed to parse app options file: ... no such file or directory, open '[object Object]'

### ISSUE THREAD

**Issue by zgosalvez** [firebase/firebase-tools#722]
### Version info

3.18.1

### Platform Information

OS X

### Steps to reproduce

1. Init functions with TypeScript implementation
2. Initialize firebase using 
```ts
import * as admin from 'firebase-admin';
admin.initializeApp();
```
3. `firebase --project project-id deploy --only functions`

### Expected behavior

Deploy successfully.

### Actual behavior

Deploy fails. Note that `/Users/username/project-id/functions/src/index.ts:10:7` corresponds to `admin.initializeApp();`

```sh
[2018-04-05T23:27:40.068Z] ----------------------------------------------------------------------
[2018-04-05T23:27:40.078Z] Command:       /usr/local/bin/node /Users/username/.npm-global/bin/firebase --project project-id deploy --only functions --debug
[2018-04-05T23:27:40.080Z] CLI Version:   3.18.1
[2018-04-05T23:27:40.080Z] Platform:      darwin
[2018-04-05T23:27:40.080Z] Node Version:  v6.11.5
[2018-04-05T23:27:40.082Z] Time:          Fri Apr 06 2018 07:27:40 GMT+0800 (+08)
[2018-04-05T23:27:40.082Z] ----------------------------------------------------------------------

[2018-04-05T23:27:40.104Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-04-05T23:27:40.105Z] > authorizing via signed-in user
[2018-04-05T23:27:40.111Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/project-id

 Fri Apr 06 2018 07:27:40 GMT+0800 (+08)
[2018-04-05T23:27:41.485Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 05 Apr 2018 23:27:41 GMT, content-type=application/json; charset=utf-8, content-length=117, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-04-05T23:27:41.488Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/project-id/tokens

 Fri Apr 06 2018 07:27:41 GMT+0800 (+08)
[2018-04-05T23:27:42.681Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 05 Apr 2018 23:27:42 GMT, content-type=application/json; charset=utf-8, content-length=263, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'project-id'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" install --silent
Running command: rm -rf "$RESOURCE_DIR/lib"
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@0.0.0 lint /Users/username/project-id/functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@0.0.0 build /Users/username/project-id/functions
> tsc

Running command: npm --prefix "$RESOURCE_DIR" run test

> functions@0.0.0 test /Users/username/project-id/functions
> jasmine JASMINE_CONFIG_PATH=jasmine.json

Started
.


1 spec, 0 failures
Finished in 0.009 seconds
✔  functions: Finished running predeploy script.
[2018-04-05T23:28:01.738Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "version": "0.0.0",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "test": "jasmine JASMINE_CONFIG_PATH=jasmine.json",
    "lint-fix": "tslint --project tsconfig.json --fix"
  },
  "main": "lib/index.js",
  "dependencies": {...},
  "devDependencies": {...},
  "private": true
}
i  functions: ensuring necessary APIs are enabled...
[2018-04-05T23:28:01.744Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/project-id?view=CONSUMER_VIEW

 Fri Apr 06 2018 07:28:01 GMT+0800 (+08)
[2018-04-05T23:28:01.746Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/project-id?view=CONSUMER_VIEW

 Fri Apr 06 2018 07:28:01 GMT+0800 (+08)
[2018-04-05T23:28:03.467Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:03 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:03.584Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:03 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
✔  functions: all necessary APIs are enabled
[2018-04-05T23:28:03.586Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/project-id

 Fri Apr 06 2018 07:28:03 GMT+0800 (+08)
[2018-04-05T23:28:04.759Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:04 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:04.760Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/926397345262:getServerAppConfig

 Fri Apr 06 2018 07:28:04 GMT+0800 (+08)
[2018-04-05T23:28:06.766Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
i  functions: preparing functions directory for uploading...
[2018-04-05T23:28:06.779Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs

 Fri Apr 06 2018 07:28:06 GMT+0800 (+08)
[2018-04-05T23:28:07.186Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.190Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/google/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.191Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/plaid/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.192Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/sendgrid/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.193Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/aloglia/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.194Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/support/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.195Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/taxjar/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.195Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/algolia/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.196Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/stripe/variables

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.563Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.567Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/sendgrid/variables/api_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.572Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.573Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/plaid/variables/secret

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.573Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/plaid/variables/client_id

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.574Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/plaid/variables/public_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.579Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.580Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/taxjar/variables/api_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.584Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.591Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/google/variables/recaptcha

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.594Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.600Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/support/variables/firebase_sender_id

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.600Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/support/variables/firebase_server_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.614Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.616Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.617Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/algolia/variables/app_id

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.618Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/algolia/variables/app_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.619Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.619Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/stripe/variables/secret_key

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.620Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-id/configs/stripe/variables/endpoint_secret

 Fri Apr 06 2018 07:28:07 GMT+0800 (+08)
[2018-04-05T23:28:07.943Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.945Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.951Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.962Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.973Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.974Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.976Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.984Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.985Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:07.999Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:08.007Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close
[2018-04-05T23:28:08.024Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 05 Apr 2018 23:28:07 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35", accept-ranges=none, connection=close

Error: Error occurred while parsing your function triggers.

Error: Failed to parse app options file: Error: ENOENT: no such file or directory, open '[object Object]'
    at FirebaseAppError.Error (native)
    at FirebaseAppError.FirebaseError [as constructor] (/Users/username/project-id/functions/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Users/username/project-id/functions/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/Users/username/project-id/functions/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at FirebaseNamespaceInternals.loadOptionsFromEnvVar (/Users/username/project-id/functions/node_modules/firebase-admin/lib/firebase-namespace.js:214:19)
    at FirebaseNamespaceInternals.initializeApp (/Users/username/project-id/functions/node_modules/firebase-admin/lib/firebase-namespace.js:64:28)
    at FirebaseNamespace.initializeApp (/Users/username/project-id/functions/node_modules/firebase-admin/lib/firebase-namespace.js:362:30)
    at Object.<anonymous> (/Users/username/project-id/functions/src/index.ts:10:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

Having trouble? Try firebase deploy --help
```

**Comment by zgosalvez** [comment]
@laurenzlong That did it. 👌🏼 "Deploy complete!"

**Comment by laurenzlong** [comment]
Thanks for letting me know!

**Comment by blexo** [comment]
should we use the other branch or wait for a fix?

**Comment by blexo** [comment]
Oh I don't have permission - will be fixed tomorrow?

**Comment by dimitri320** [comment]
I can't install this branch, throws an error, from user and admin alike.

**Comment by dimitri320** [comment]
It's a bug with the firebase-tools@3.18.1 version

Downgrading to 3.18.0 allowed me to deploy !

npm uninstall -g firebase-tools
npm i -g firebase-tools@3.18.0

**Comment by jackyq2015** [comment]
Seems the same exception is reoccurring at version 6.3.0

**Comment by bkendall** [comment]
@jackyq2015 if you're still seeing this issue, please open a new bug with the appropriate details and reproduction steps. Thanks!
