### ISSUE TITLE
Firebase Deploy Broken, 1.0 Update, admin.initializeApp()

### ISSUE THREAD

**Issue by grenaudStemulo** [firebase/firebase-tools#726]
### Version info

Firebase version 3.18.1
Node version 9.9.0
firebase-admin version 5.11.0
firebase-functions version 1.0.0

### Platform Information

OS X

### Explanation

An error occurred when i want to deploy code after upgrading to v1.0.0 (firebase deploy)

### My code

```
var request = require('request');
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

const ref = admin.database().ref;

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});

```
### Issue

```
✔  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: Failed to parse app options file: Error: ENOENT: no such file or directory, open '[object Object]'
    at FirebaseAppError.FirebaseError [as constructor] (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at FirebaseNamespaceInternals.loadOptionsFromEnvVar (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-namespace.js:214:19)
    at FirebaseNamespaceInternals.initializeApp (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-namespace.js:64:28)
    at FirebaseNamespace.initializeApp (/Users/grenaud/workspace/cloud-functions/functions/node_modules/firebase-admin/lib/firebase-namespace.js:362:30)
    at Object.<anonymous> (/Users/grenaud/workspace/cloud-functions/functions/index.js:3:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```

If I remove the "admin.initializeApp();" line, there is no error anymore.

Thanks for help !

**Comment by grenaudStemulo** [comment]
Duplication of https://github.com/firebase/firebase-tools/issues/722
