### ISSUE TITLE
Export to dotenv fails if config is specified with empty characters in firebase functions.

### ISSUE THREAD

**Issue by ytetsuro** [firebase/firebase-tools#7460]
Export to dotenv fails if config is specified with empty characters in firebase functions.

### [REQUIRED] Environment info

**firebase-tools:**

13.13.3

**Platform:**

macOS 14.4

### [REQUIRED] Test case

```bash
$ firebase functions:config:set hoo.bar=""
$ firebase functions:config:export
```

### [REQUIRED] Steps to reproduce

```bash
$ firebase functions:config:set hoo.bar=""
$ firebase functions:config:export
```

### [REQUIRED] Expected behavior

Exported in dotenv format.

### [REQUIRED] Actual behavior

Show following error.

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at escape (/Users/yoshikawa/.nodebrew/node/v20.10.0/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:128:14)
    at /Users/yoshikawa/.nodebrew/node/v20.10.0/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:131:100
    at Array.map (<anonymous>)
    at Object.toDotenvFormat (/Users/yoshikawa/.nodebrew/node/v20.10.0/lib/node_modules/firebase-tools/lib/functions/runtimeConfigExport.js:131:24)
    at /Users/yoshikawa/.nodebrew/node/v20.10.0/lib/node_modules/firebase-tools/lib/commands/functions-config-export.js:110:56
    at Array.map (<anonymous>)
    at Command.actionFn (/Users/yoshikawa/.nodebrew/node/v20.10.0/lib/node_modules/firebase-tools/lib/commands/functions-config-export.js:110:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Pull Request

https://github.com/firebase/firebase-tools/pull/7368

**Comment by aalej** [comment]
Hey @ytetsuro, thanks for reaching out to us and for providing a detailed report. I was able to reproduce the issue you mentioned. Also, thanks for submitting a PR! I’ll raise this to our engineering team so they can take a look into this. I think the PR also fixes #7036.
