### ISSUE TITLE
How to import an array of data from json file

### ISSUE THREAD

**Issue by anhtuank7c** [firebase/firebase-tools#750]
### Version info
3.18.4

### Platform Information

OS X 10.13.4

### Steps to reproduce

```
firebase database:set /my/path -d JSON.stringify([{
data: 'me'},
{ data: 'you' }
]) -y
```

### Expected behavior

```
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at generateTrainings (/Users/anhtuank7c/projects/equilab-backend/mockdata/index.js:248:3)
    at Object.<anonymous> (/Users/anhtuank7c/projects/equilab-backend/mockdata/index.js:268:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

### Actual behavior

Unable to set an array of data

**Comment by laurenzlong** [comment]
The way to insert array values through the CLI is to write a JSON object whose keys are numeric, for example:

```
# assuming Linux/Mac, windows would have a different way to specify JSON via command line
firebase database:set /my/path -d '{"0":{"data":"me"}, "1":{"data":"you"}}'
```

**Comment by anhtuank7c** [comment]
I got it.
Now i known i have to use JSON Object instead of Array.
Thank you so much

**Comment by laurenzlong** [comment]
You're welcome!
