### ISSUE TITLE
Firebase deploy throwing unexpected error

### ISSUE THREAD

**Issue by SheikhSajid** [firebase/firebase-tools#756]
### Version info

Firebase Version: 3.18.4

### Platform Information

Windows 10
### Steps to reproduce

firebase deploy --only hosting

### Expected behavior

When I run firebase deploy for my hosting, I expect it to work. I was able to deploy cloud functions and it worked fine. 

##  _This is the output from the **cmd**:_
=== Deploying to 'kpr-chat-42e6a'...

i  deploying hosting
i  hosting: preparing build directory for upload...

Error: An unexpected error has occurred.

## _Here is what I found in the **firebase-debug.log** file:_
[info] === Deploying to 'kpr-chat-42e6a'...
[info] 
[info] i  deploying hosting
[info] i  hosting: preparing build directory for upload...
[debug] [2018-04-27T20:02:38.076Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/kpr-chat-42e6a/uploads/-LB7gpxQGpxwBSBI0HoY?fileCount=7&message=  
  
 Sat Apr 28 2018 02:02:38 GMT+0600 (Bangladesh Standard Time)
[debug] [2018-04-27T20:02:42.131Z] <<< HTTP RESPONSE 404
[debug] [2018-04-27T20:02:42.131Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-04-27T20:02:42.133Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (C:\Users\sheik\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:10:13)
    at Request._callback (C:\Users\sheik\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:47:25)
    at Request.self.callback (C:\Users\sheik\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\sheik\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\sheik\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by mbleigh** [comment]
This was due to [a Firebase Hosting incident](https://status.firebase.google.com/incident/Hosting/18005) that is now closed.

**Comment by filipemir** [comment]
I believe this issue is back. I'm no longer able to deploy:
```
[debug] [2018-10-28T12:01:35.908Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/stonybrook-strings-stg/uploads/-LPuYB9JMFICpnTuZko4?fileCount=597&message=  
  
 Sun Oct 28 2018 08:01:35 GMT-0400 (EDT)
[debug] [2018-10-28T12:01:41.034Z] <<< HTTP RESPONSE 410
[debug] [2018-10-28T12:01:41.034Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-10-28T12:01:41.035Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:47:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by mbleigh** [comment]
Please upgrade to the latest version of the Firebase CLI.

    npm install -g firebase-tools

**Comment by RiChrisMurphy** [comment]
@itsbrianburton I'm having the same problem as you with firebase-tools 3.17.4, but can't seem to remove the path. How did you end up removing all the installations?

**Comment by itsbrianburton** [comment]
@RiChrisMurphy Just repeatedly uninstall firebase-tools until it says that it's no longer installed.
`npm remove -g firebase-tools` 

`firebase -V`
`3.17.6`

`npm remove -g firebase-tools` 

`firebase -V`
`6.0.1`

`npm remove -g firebase-tools` 
`up to date in 4.629s`

`npm i -g firebase-tools@latest`

Alternatively, either run `where firebase` or `which firebase` depending on your OS to find where it's installed and go there to remove the module.

**Comment by RiChrisMurphy** [comment]
Thanks, I ended up having problems with nvm / homebrew node installations which was the problem. Finally fixed it. :)
