### ISSUE TITLE
Error Deploying Cloud Functions

### ISSUE THREAD

**Issue by kalm42** [firebase/firebase-tools#757]
### Version info
3.18.4

### Platform Information
OS X 10.13.4

### Steps to reproduce
`firebase deploy`

I tried to re-deploy my functions after several failed attempts and no idea where to look for solutions.

### Expected behavior
I expected the functions to deploy.

### Actual behavior
```
[2018-04-27T21:31:00.534Z] ----------------------------------------------------------------------
[2018-04-27T21:31:00.537Z] Command:       /Users/kyle/.nvm/versions/node/v8.9.1/bin/node /Users/kyle/.nvm/versions/node/v8.9.1/bin/firebase deploy --debug
[2018-04-27T21:31:00.538Z] CLI Version:   3.18.4
[2018-04-27T21:31:00.538Z] Platform:      darwin
[2018-04-27T21:31:00.538Z] Node Version:  v8.9.1
[2018-04-27T21:31:00.538Z] Time:          Fri Apr 27 2018 14:31:00 GMT-0700 (PDT)
[2018-04-27T21:31:00.538Z] ----------------------------------------------------------------------

[2018-04-27T21:31:00.548Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-04-27T21:31:00.549Z] > authorizing via signed-in user
[2018-04-27T21:31:00.550Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/barbell-ballistics

 Fri Apr 27 2018 14:31:00 GMT-0700 (PDT)
[2018-04-27T21:31:01.124Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 27 Apr 2018 21:31:01 GMT, content-type=application/json; charset=utf-8, content-length=129, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-04-27T21:31:01.125Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/barbell-ballistics/tokens

 Fri Apr 27 2018 14:31:01 GMT-0700 (PDT)
[2018-04-27T21:31:01.485Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 27 Apr 2018 21:31:01 GMT, content-type=application/json; charset=utf-8, content-length=268, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'barbell-ballistics'...

i  deploying functions
[2018-04-27T21:31:04.223Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "@google-cloud/logging": "^0.7.1",
    "firebase": "^4.4.0",
    "firebase-admin": "^5.12.0",
    "firebase-functions": "^1.0.1",
    "stripe": "^5.8.0"
  }
}
i  functions: ensuring necessary APIs are enabled...
[2018-04-27T21:31:04.224Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/barbell-ballistics?view=CONSUMER_VIEW

 Fri Apr 27 2018 14:31:04 GMT-0700 (PDT)
[2018-04-27T21:31:04.225Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/barbell-ballistics?view=CONSUMER_VIEW

 Fri Apr 27 2018 14:31:04 GMT-0700 (PDT)
[2018-04-27T21:31:04.806Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:04 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-04-27T21:31:04.863Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:04 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
✔  functions: all necessary APIs are enabled
[2018-04-27T21:31:04.864Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/barbell-ballistics

 Fri Apr 27 2018 14:31:04 GMT-0700 (PDT)
[2018-04-27T21:31:05.283Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:05 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-04-27T21:31:05.283Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/408577803858:getServerAppConfig

 Fri Apr 27 2018 14:31:05 GMT-0700 (PDT)
[2018-04-27T21:31:05.829Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:05 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
i  functions: preparing functions directory for uploading...
[2018-04-27T21:31:05.831Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/barbell-ballistics/configs

 Fri Apr 27 2018 14:31:05 GMT-0700 (PDT)
[2018-04-27T21:31:06.148Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-04-27T21:31:06.149Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/barbell-ballistics/configs/stripe/variables

 Fri Apr 27 2018 14:31:06 GMT-0700 (PDT)
[2018-04-27T21:31:06.372Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-04-27T21:31:06.373Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/barbell-ballistics/configs/stripe/variables/currency

 Fri Apr 27 2018 14:31:06 GMT-0700 (PDT)
[2018-04-27T21:31:06.373Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/barbell-ballistics/configs/stripe/variables/token

 Fri Apr 27 2018 14:31:06 GMT-0700 (PDT)
[2018-04-27T21:31:06.582Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-04-27T21:31:06.592Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 27 Apr 2018 21:31:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close

Error: Error occurred while parsing your function triggers.

TypeError: Cannot set property auth of #<FirebaseNamespace> which has only a getter
    at FirebaseNamespaceInternals.registerService (/Users/kyle/Documents/Clients/Barbell Balistics/website/functions/functions/node_modules/firebase-admin/lib/firebase-namespace.js:179:37)
    at Object.default_1 [as default] (/Users/kyle/Documents/Clients/Barbell Balistics/website/functions/functions/node_modules/firebase-admin/lib/auth/register-auth.js:46:30)
    at Object.<anonymous> (/Users/kyle/Documents/Clients/Barbell Balistics/website/functions/functions/node_modules/firebase-admin/lib/index.js:30:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

I don't see any reference to my code. I was attempting to deploy code that matches exactly code that is already deployed after a few failed attempts to deploy new code. Please let me know what other information I can provide. Thank you for taking the time to read though this.

**Comment by mbleigh** [comment]
Can you share your functions code?

**Comment by kalm42** [comment]
```
// Connection to Firebase Functions
const functions = require('firebase-functions')

// Connection to Firebase Database
const admin = require('firebase-admin')
admin.initializeApp()

// Logging
const logging = require('@google-cloud/logging')()

// Connection to Stripe
const stripe = require('stripe')(functions.config().stripe.token)

// initializeApp
// Initialize Firebase
var firebase = require('firebase')

const currency = functions.config().stripe.currency || 'USD'

// Creates stripe customer when a new user signs up, and stores the customers
// information in the database so it can be looked up again
exports.createStripeCustomer = functions.auth.user().onCreate((user) => {
  return stripe.customers.create({
    email: user.email
  }).then((customer) => {
    return admin.database().ref(`/users/${user.uid}/customer_id`).set(customer.id)
  })
})

//
// When a user is deleted from the authentication delete that user's stripe customer
//
exports.cleanupUser = functions.auth.user().onDelete((user) => {
  // grab the user record from the databse
  return admin.database().ref(`/users/${user.uid}`).once('value').then((snapshot) => {
    return snapshot.val()
  }).then((customer) => {
    // tell stripe to delete the customer
    return stripe.customers.del(customer.customer_id)
  }).then(() => {
    // finally remove the user record from the database
    return admin.database().ref(`/users/${user.uid}`).remove()
  })
})

//
// Adds a method of payment to their account. All recurring bills will be applied
// to this card.
//
exports.addPaymentSource = functions.database.ref('/users/{userId}/sources/{pushId}/token')
.onCreate((snapshot, context) => {
  const source = snapshot.val()
  // See if data was deleted. if it was then ignore.
  if (source === null) {
    return null
  }
  // get the stripe customer_id
  return admin.database().ref(`/users/${context.params.userId}/customer_id`).once('value').then((snapshot) => {
    return snapshot.val()
  }).then((customer) => {
    // Add source to customer.
    return stripe.customers.createSource(customer, {source})
  }).then((response) => {
    // Set the response in the database.
    return snapshot.ref.parent.set(response)
  }, (error) => {
    // if there was an error, tell the front end.
    return snapshot.ref.parent.child('error').set(userFacingMessage(error))
  }).then((error) => {
    if (error) {
      // report the error.
      return reportError(error, {user: context.params.userId})
    }
    return null
  })
})

//
// Create new product to be sold. Still requires a plan.
//
exports.createStripeProduct = functions.database.ref('/products/{pushId}/name')
.onCreate((snapshot, context) => {
  const name = snapshot.val()
  // See if the data was deleted, if it was then ignore
  if(name === null) {
    return null
  }

  // Make the product in stripe
  return stripe.products.create({
    name,
    type: 'service',
  }).then((stripeProduct) => {
    if (!stripeProduct) {
      // returned null, write failed handle error
    }
    // write product to database
    return admin.database().ref(`/products/${context.params.pushId}`).set(stripeProduct)
  }).catch((err) => {
    // handle error
  })
})

//
// Create new payment plan for a product to be sold
//
exports.createStripeProductPaymentPlan = functions.database.ref('/plans/{productId}/{pushId}')
.onCreate((snapshot, context) => {
  const plan = snapshot.val()
  // See if the data was deleted, if it was then ignore
  if(plan === null) {
    return null
  }

  // Make the product in stripe
  const {amount, interval, product, currency} = plan
  return stripe.plans.create({
    amount,
    interval,
    product,
    currency
  }).then((stripePlan) => {
    if (!stripePlan) {
      // returned null, write failed handle error
    }
    // write product to database
    return admin.database().ref(`/plans/${context.params.productId}/${context.params.pushId}`).set(stripePlan)
  }).catch((err) => {
    // handle error
  })
})

//
// post the subscription id to the database at /users/{userId}/membership/{pushId}/token
//
exports.createStripeSubscription = functions.database.ref('/users/{userId}/membership/{pushId}/token')
.onCreate((change, context) => {
  const plan = change.after.val()
  if (source === null) {
    return null
  }
  // get the stripe customer_id
  return admin.database().ref(`/users/${context.params.userId}/customer_id`).once('value').then((snapshot) => {
    return snapshot.val()
  }).then((customer) => {
    // Add subscription to customer
    return stripe.subscriptions.create({
      cusomter,
      items: [{plan}]
    })
  }).then((response) => {
    return change.after.ref.parent.set(response)
  }, (error) => {
    // if there was an error tell the front end
    return change.after.ref.parent.child('error').set(userFacingMessage(error))
  }).then((error) => {
    if (error) {
      // report error.
      return reportError(error, {user: context.params.userId})
    }
    return null
  })
})

function reportError(err, context = {}) {
  const logName = 'errors'
  const log = logging.log(logName)

  const metadata = {
    resource: {
      type: 'cloud_function',
      labels: { function_name: process.env.FUNCTION_NAME }
    }
  }

  const errorEvent = {
    message: err.stack,
    serviceContext: {
      service: process.env.FUNCTION_NAME,
      resource_type: 'cloud_function'
    },
    context: context
  }

  return new Promise((resolve, reject) => {
    log.write(log.entry(metadata, errorEvent), (error) => {
      if (error) {
        return reject(error)
      }
      return resolve()
    })
  })
}

// Sanatize user facing error message
function userFacingMessage(error) {
  return error.type ? error.message : 'An error occured, developers have been alerted.'
}

```
