### ISSUE TITLE
Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by narry0966** [firebase/firebase-tools#760]
### Steps to reproduce

After do all things until here
https://codelabs.developers.google.com/codelabs/firebase-web/index.html#3
I've typed
firebase serve

### Expected behavior

Error: An unexpected error has occurred.

### Actual behavior
mbp:web-start narry$ firebase serve --debug
[2018-05-03T12:08:31.652Z] ----------------------------------------------------------------------
[2018-05-03T12:08:31.654Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --debug
[2018-05-03T12:08:31.654Z] CLI Version:   3.18.4
[2018-05-03T12:08:31.655Z] Platform:      darwin
[2018-05-03T12:08:31.655Z] Node Version:  v8.11.1
[2018-05-03T12:08:31.655Z] Time:          Thu May 03 2018 21:08:31 GMT+0900 (JST)
[2018-05-03T12:08:31.655Z] ----------------------------------------------------------------------

[2018-05-03T12:08:31.665Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-05-03T12:08:31.665Z] > authorizing via signed-in user
[2018-05-03T12:08:31.667Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/friendlychat-c03c0  
  
 Thu May 03 2018 21:08:31 GMT+0900 (JST)
[2018-05-03T12:08:33.613Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 03 May 2018 12:08:33 GMT, content-type=application/json; charset=utf-8, content-length=123, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-05-03T12:08:33.614Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/friendlychat-c03c0/tokens  
  
 Thu May 03 2018 21:08:33 GMT+0900 (JST)
[2018-05-03T12:08:34.279Z] <<< HTTP RESPONSE 200 server=nginx, date=Thu, 03 May 2018 12:08:34 GMT, content-type=application/json; charset=utf-8, content-length=268, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-05-03T12:08:34.280Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/friendlychat-c03c0  
  
 Thu May 03 2018 21:08:34 GMT+0900 (JST)
[2018-05-03T12:08:35.262Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Thu, 03 May 2018 12:08:35 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close

=== Serving from '/Users/narry/Downloads/friendlychat-web-master/web-start'...

[2018-05-03T12:08:36.871Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:111:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/local/lib/node_modules/firebase-tools/commands/serve.js:48:12)

Error: An unexpected error has occurred.

**Comment by narry0966** [comment]
I've also tried with Ubuntu 14.04 LTS but it become same result. Do I have any way to run?

**Comment by laurenzlong** [comment]
How did you install firebase-tools? Please do not install with "sudo", you can try following these tips when troublehshooting: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by narry0966** [comment]
$ sudo npm install -g firebase-tools

I've installed with this command.
My npm version is 5.6.0.
And I checked that I can deploy it.
