### ISSUE TITLE
Install fails on mac - Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by pliniobarraza** [firebase/firebase-tools#771]
NOTE: I saw a similar issue on Windows here: https://github.com/firebase/firebase-tools/issues/626

### Version info

None Yet
NODE version: v10.1.0
NPM version: 1.3.11

### Platform Information

OS X Sierra 10.12.6

### Steps to reproduce

1. I installed node and npm. NPM had some linking and path issues. The executable npm in the installed directory was a funny script that tried to find the real npm-cli.js but did not. I fixed it manually with:

export PATH="$HOME/.npm/npm/1.3.11/package/bin/:$PATH"
cd $HOME/.npm/npm/1.3.11/package/bin/
mv npm npm.old
ln -s npm-cli.js npm

2. I ran the command npm install -g firebase-tools

### Expected behavior

A successfull installation of the firebase tools

### Actual behavior

The following output :

npm http GET https://registry.npmjs.org/firebase-tools
npm http GET https://registry.npmjs.org/firebase-tools
npm http GET https://registry.npmjs.org/firebase-tools
npm ERR! Error: unable to get local issuer certificate
npm ERR!     at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
npm ERR!     at TLSSocket.emit (events.js:182:13)
npm ERR!     at TLSSocket._finishInit (_tls_wrap.js:635:8)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 16.7.0
npm ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm" "install" "-g" "firebase-tools"
npm ERR! cwd /Users/pliniobarraza/.npm/npm/1.3.11/package/bin
npm ERR! node -v v10.1.0
npm ERR! npm -v 1.3.11
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm-debug.log
npm ERR! not ok code 0

### Here is npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.1.0/bin/node',
1 verbose cli   '/Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'firebase-tools' ]
2 info using npm@1.3.11
3 info using node@v10.1.0
4 verbose cache add [ 'firebase-tools', null ]
5 verbose cache add name=undefined spec="firebase-tools" args=["firebase-tools",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'firebase-tools',
6 verbose parsed url   path: 'firebase-tools',
6 verbose parsed url   href: 'firebase-tools' }
7 silly lockFile 3fa4b23e-firebase-tools firebase-tools
8 verbose lock firebase-tools /Users/pliniobarraza/.npm/3fa4b23e-firebase-tools.lock
9 silly lockFile 3fa4b23e-firebase-tools firebase-tools
10 silly lockFile 3fa4b23e-firebase-tools firebase-tools
11 verbose addNamed [ 'firebase-tools', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 59c4bcc4-firebase-tools firebase-tools@
14 verbose lock firebase-tools@ /Users/pliniobarraza/.npm/59c4bcc4-firebase-tools.lock
15 silly addNameRange { name: 'firebase-tools', range: '*', hasData: false }
16 verbose url raw firebase-tools
17 verbose url resolving [ 'https://registry.npmjs.org/', './firebase-tools' ]
18 verbose url resolved https://registry.npmjs.org/firebase-tools
19 info trying registry request attempt 1 at 10:42:19 AM
20 http GET https://registry.npmjs.org/firebase-tools
21 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
22 info trying registry request attempt 2 at 10:42:43 AM
23 http GET https://registry.npmjs.org/firebase-tools
24 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
25 info trying registry request attempt 3 at 10:43:45 AM
26 http GET https://registry.npmjs.org/firebase-tools
27 silly lockFile 59c4bcc4-firebase-tools firebase-tools@
28 silly lockFile 59c4bcc4-firebase-tools firebase-tools@
29 error Error: unable to get local issuer certificate
29 error     at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
29 error     at TLSSocket.emit (events.js:182:13)
29 error     at TLSSocket._finishInit (_tls_wrap.js:635:8)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Darwin 16.7.0
32 error command "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm" "install" "-g" "firebase-tools"
33 error cwd /Users/pliniobarraza/.npm/npm/1.3.11/package/bin
34 error node -v v10.1.0
35 error npm -v 1.3.11
36 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
37 verbose exit [ 1, true ]

**Comment by pliniobarraza** [comment]
I used the following command to get past the previous error:
npm config set registry http://registry.npmjs.org/

Running 
npm install -g firebase-tools
gives the following output now:

npm http GET http://registry.npmjs.org/firebase-tools
npm http 200 http://registry.npmjs.org/firebase-tools
npm http GET http://registry.npmjs.org/firebase-tools/-/firebase-tools-3.18.4.tgz
npm http 200 http://registry.npmjs.org/firebase-tools/-/firebase-tools-3.18.4.tgz
npm http GET http://registry.npmjs.org/JSONStream
npm http GET http://registry.npmjs.org/archiver
npm http GET http://registry.npmjs.org/chalk
npm http GET http://registry.npmjs.org/cjson
npm http GET http://registry.npmjs.org/cli-table
npm http GET http://registry.npmjs.org/configstore
npm http GET http://registry.npmjs.org/cross-env
npm http GET http://registry.npmjs.org/cross-spawn
npm http GET http://registry.npmjs.org/csv-streamify
npm http GET http://registry.npmjs.org/didyoumean
npm http GET http://registry.npmjs.org/es6-set
npm http GET http://registry.npmjs.org/exit-code
npm http GET http://registry.npmjs.org/filesize
npm http GET http://registry.npmjs.org/firebase
npm http GET http://registry.npmjs.org/fs-extra
npm http GET http://registry.npmjs.org/google-auto-auth
npm http GET http://registry.npmjs.org/inquirer
npm http GET http://registry.npmjs.org/is
npm http GET http://registry.npmjs.org/jsonschema
npm http GET http://registry.npmjs.org/jsonwebtoken
npm http GET http://registry.npmjs.org/lodash
npm http GET http://registry.npmjs.org/ora/0.2.3
npm http GET http://registry.npmjs.org/open
npm http GET http://registry.npmjs.org/progress
npm http GET http://registry.npmjs.org/portfinder
npm http GET http://registry.npmjs.org/superstatic
npm http GET http://registry.npmjs.org/tmp/0.0.33
npm http GET http://registry.npmjs.org/universal-analytics
npm http GET http://registry.npmjs.org/update-notifier
npm http GET http://registry.npmjs.org/user-home
npm http GET http://registry.npmjs.org/uuid
npm http GET http://registry.npmjs.org/google-cloud/functions-emulator
npm http GET http://registry.npmjs.org/tar
npm http GET http://registry.npmjs.org/commander
npm http GET http://registry.npmjs.org/semver
npm http GET http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/winston
npm http GET http://registry.npmjs.org/glob
npm http GET http://registry.npmjs.org/request
npm http 200 http://registry.npmjs.org/cli-table
npm http GET http://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz
npm http 200 http://registry.npmjs.org/exit-code
npm http GET http://registry.npmjs.org/exit-code/-/exit-code-1.0.2.tgz
npm http 200 http://registry.npmjs.org/ora/0.2.3
npm http GET http://registry.npmjs.org/ora/-/ora-0.2.3.tgz
npm http 404 http://registry.npmjs.org/google-cloud/functions-emulator
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/Users/pliniobarraza/.npm/npm/1.3.11/package/lib/cache.js:687:35)
npm ERR!     at /Users/pliniobarraza/.npm/npm/1.3.11/package/lib/cache.js:675:5
npm ERR!     at saved (/Users/pliniobarraza/.npm/npm/1.3.11/package/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /Users/pliniobarraza/.npm/npm/1.3.11/package/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at FSReqWrap.oncomplete (fs.js:152:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 16.7.0
npm ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm" "install" "-g" "firebase-tools"
npm ERR! cwd /Users/pliniobarraza/.npm/npm/1.3.11/package/bin
npm ERR! node -v v10.1.0
npm ERR! npm -v 1.3.11
npm http 200 http://registry.npmjs.org/user-home
npm http GET http://registry.npmjs.org/user-home/-/user-home-2.0.0.tgz
npm http 200 http://registry.npmjs.org/ora/-/ora-0.2.3.tgz
npm http 200 http://registry.npmjs.org/progress
npm http GET http://registry.npmjs.org/progress/-/progress-2.0.0.tgz
npm http 200 http://registry.npmjs.org/tmp/0.0.33
npm http GET http://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz
npm http 200 http://registry.npmjs.org/cjson
npm http GET http://registry.npmjs.org/cjson/-/cjson-0.3.3.tgz
npm http 200 http://registry.npmjs.org/open
npm http GET http://registry.npmjs.org/open/-/open-0.0.5.tgz
npm http 200 http://registry.npmjs.org/universal-analytics
npm http GET http://registry.npmjs.org/universal-analytics/-/universal-analytics-0.4.16.tgz
npm http 200 http://registry.npmjs.org/cjson/-/cjson-0.3.3.tgz
npm http 200 http://registry.npmjs.org/es6-set
npm http GET http://registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz
npm http 200 http://registry.npmjs.org/portfinder
npm http GET http://registry.npmjs.org/portfinder/-/portfinder-1.0.13.tgz
npm http 200 http://registry.npmjs.org/user-home/-/user-home-2.0.0.tgz
npm http 200 http://registry.npmjs.org/cli-table/-/cli-table-0.3.1.tgz
npm http 200 http://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz
npm http 200 http://registry.npmjs.org/portfinder/-/portfinder-1.0.13.tgz
npm http 200 http://registry.npmjs.org/cross-spawn
npm http GET http://registry.npmjs.org/cross-spawn/-/cross-spawn-4.0.2.tgz
npm http 200 http://registry.npmjs.org/google-auto-auth
npm http 200 http://registry.npmjs.org/universal-analytics/-/universal-analytics-0.4.16.tgz
npm http GET http://registry.npmjs.org/google-auto-auth/-/google-auto-auth-0.7.2.tgz
npm http 200 http://registry.npmjs.org/cross-spawn/-/cross-spawn-4.0.2.tgz
npm http 200 http://registry.npmjs.org/didyoumean
npm http GET http://registry.npmjs.org/didyoumean/-/didyoumean-1.2.1.tgz
npm http 200 http://registry.npmjs.org/exit-code/-/exit-code-1.0.2.tgz
npm http 200 http://registry.npmjs.org/csv-streamify
npm http GET http://registry.npmjs.org/csv-streamify/-/csv-streamify-3.0.4.tgz
npm http 200 http://registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz
npm http 200 http://registry.npmjs.org/open/-/open-0.0.5.tgz
npm http 200 http://registry.npmjs.org/uuid
npm http GET http://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz
npm http 200 http://registry.npmjs.org/update-notifier
npm http GET http://registry.npmjs.org/update-notifier/-/update-notifier-0.5.0.tgz
npm http 200 http://registry.npmjs.org/chalk
npm http 200 http://registry.npmjs.org/progress/-/progress-2.0.0.tgz
npm http GET http://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 http://registry.npmjs.org/google-auto-auth/-/google-auto-auth-0.7.2.tgz
npm http 200 http://registry.npmjs.org/semver
npm http GET http://registry.npmjs.org/semver/-/semver-5.5.0.tgz
npm http 200 http://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz
npm http 200 http://registry.npmjs.org/didyoumean/-/didyoumean-1.2.1.tgz
npm http 200 http://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 http://registry.npmjs.org/configstore
npm http GET http://registry.npmjs.org/configstore/-/configstore-1.4.0.tgz
npm http 200 http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz
npm http 200 http://registry.npmjs.org/semver/-/semver-5.5.0.tgz
npm http 200 http://registry.npmjs.org/configstore/-/configstore-1.4.0.tgz
npm http 200 http://registry.npmjs.org/update-notifier/-/update-notifier-0.5.0.tgz
npm http 200 http://registry.npmjs.org/csv-streamify/-/csv-streamify-3.0.4.tgz
npm http 200 http://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz
npm http 200 http://registry.npmjs.org/archiver
npm http GET http://registry.npmjs.org/archiver/-/archiver-2.1.1.tgz
npm http 200 http://registry.npmjs.org/filesize
npm http GET http://registry.npmjs.org/filesize/-/filesize-3.6.1.tgz
npm http 200 http://registry.npmjs.org/archiver/-/archiver-2.1.1.tgz
npm http 200 http://registry.npmjs.org/jsonschema
npm http GET http://registry.npmjs.org/jsonschema/-/jsonschema-1.2.4.tgz
npm http 200 http://registry.npmjs.org/inquirer
npm http GET http://registry.npmjs.org/inquirer/-/inquirer-0.12.0.tgz
npm http 200 http://registry.npmjs.org/is
npm http GET http://registry.npmjs.org/is/-/is-3.2.1.tgz
npm http 200 http://registry.npmjs.org/glob
npm http GET http://registry.npmjs.org/glob/-/glob-7.1.2.tgz
npm http 200 http://registry.npmjs.org/inquirer/-/inquirer-0.12.0.tgz
npm http 200 http://registry.npmjs.org/is/-/is-3.2.1.tgz
npm http 200 http://registry.npmjs.org/winston
npm http GET http://registry.npmjs.org/winston/-/winston-1.1.2.tgz
npm http 200 http://registry.npmjs.org/glob/-/glob-7.1.2.tgz
npm http 200 http://registry.npmjs.org/jsonschema/-/jsonschema-1.2.4.tgz
npm http 200 http://registry.npmjs.org/winston/-/winston-1.1.2.tgz
npm http 200 http://registry.npmjs.org/cross-env
npm http GET http://registry.npmjs.org/cross-env/-/cross-env-5.1.5.tgz
npm http 200 http://registry.npmjs.org/filesize/-/filesize-3.6.1.tgz
npm http 200 http://registry.npmjs.org/cross-env/-/cross-env-5.1.5.tgz
npm http 200 http://registry.npmjs.org/fs-extra
npm http GET http://registry.npmjs.org/fs-extra/-/fs-extra-0.23.1.tgz
npm http 200 http://registry.npmjs.org/tar
npm http GET http://registry.npmjs.org/tar/-/tar-4.4.2.tgz
npm http 200 http://registry.npmjs.org/fs-extra/-/fs-extra-0.23.1.tgz
npm http 200 http://registry.npmjs.org/commander
npm http GET http://registry.npmjs.org/commander/-/commander-2.15.1.tgz
npm http 200 http://registry.npmjs.org/JSONStream
npm http GET http://registry.npmjs.org/JSONStream/-/JSONStream-1.3.2.tgz
npm http 200 http://registry.npmjs.org/commander/-/commander-2.15.1.tgz
npm http 200 http://registry.npmjs.org/tar/-/tar-4.4.2.tgz
npm http 200 http://registry.npmjs.org/JSONStream/-/JSONStream-1.3.2.tgz
npm http 200 http://registry.npmjs.org/request
npm http GET http://registry.npmjs.org/request/-/request-2.86.0.tgz
npm http 200 http://registry.npmjs.org/request/-/request-2.86.0.tgz
npm http 200 http://registry.npmjs.org/lodash
npm http GET http://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz
npm http 200 http://registry.npmjs.org/jsonwebtoken
npm http GET http://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.3.tgz
npm http 200 http://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz
npm http 200 http://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-7.4.3.tgz
npm http 200 http://registry.npmjs.org/superstatic
npm http GET http://registry.npmjs.org/superstatic/-/superstatic-5.0.1.tgz
npm http 200 http://registry.npmjs.org/superstatic/-/superstatic-5.0.1.tgz
npm http 200 http://registry.npmjs.org/firebase
npm http GET http://registry.npmjs.org/firebase/-/firebase-2.4.2.tgz
npm http 200 http://registry.npmjs.org/firebase/-/firebase-2.4.2.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pliniobarraza/.npm/npm/1.3.11/package/bin/npm-debug.log
npm ERR! not ok code 0

**Comment by ChALkeR** [comment]
npm@1.3.11 is very old and it probably doesn't work anymore.
I would suggest using a recent npm version bundled with Node.js distribution.

**Comment by pliniobarraza** [comment]
Thank you @ChALkeR you are absolutely right, even so I will include my solution for others

Solution:
Developing in OS X is a bit of a pain compared to Linux. After a while one ends up with a messy system after installing various command line programs or X11 type applications (Freeware and such). 

So unfortunately the only solution I found was to start on a fresh install of OS X High Sierra. Then I installed the official package from node (https://nodejs.org/en/). 

Then I ran:
sudo npm install -g firebase-tools

Yes, sudo, because the permissions are really messy to work with in node on OS X. I understand this can be avoided by installing nvm, but I have not tried that yet. Anyway, this managed to get me through the installation.
