### ISSUE TITLE
const gzipHeader = Buffer.from([0x1f, 0x8b]) TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by N00bAdrian** [firebase/firebase-tools#772]
### Version info

I am unable to get it.

### Platform Information

Ubuntu

### Steps to reproduce

`firebase login`

### Expected behavior

prompt me to login

### Actual behavior

`/usr/local/lib/node_modules/firebase-tools/node_modules/tar/lib/parse.js:33`
`const gzipHeader = Buffer.from([0x1f, 0x8b])`
 `                         ^`

`TypeError: this is not a typed array.`
`    at Function.from (native)`
`    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/tar/lib/parse.js:33:27)`
`    at Module._compile (module.js:410:26)`
`    at Object.Module._extensions..js (module.js:417:10)`
`    at Module.load (module.js:344:32)`
`    at Function.Module._load (module.js:301:12)`
`    at Module.require (module.js:354:17)`
`    at require (internal/module.js:12:17)`
`    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/tar/lib/list.js:10:16)`
`    at Module._compile (module.js:410:26)`

**Comment by N00bAdrian** [comment]
It worked, thanks so much!
