### ISSUE TITLE
Installation fails missing file: firebase-tools/lib/templates/hosting/init.js

### ISSUE THREAD

**Issue by ufmemo** [firebase/firebase-tools#7851]
### [REQUIRED] Environment info

**firebase-tools:** 13.22.1 and 13.22.0
**Platform:** macOS

### [REQUIRED] Test case

1. Install firebase-tools globally with any of these options:
* npm install -g firebase-tools
* pnpm install -g firebase-tools
* brew install firebase-cli
* curl -sL https://firebase.tools | bash
* download repo, npm install, npm build, npm link

All of these approaches generated a variation of the same error.

### [REQUIRED] Steps to reproduce
1. Install Node.js (v18.19.0 used in this case, but attempted with different versions)
2. Install firebase-tools globally using npm
3. Run `firebase --version` or any other firebase command
4. Observe the error

### [REQUIRED] Expected behavior
The command should execute successfully, displaying the version number or performing the requested action.

### [REQUIRED] Actual behavior

The command fails with the following error:

```
Error: ENOENT: no such file or directory, open '/Users/user/.nvm/versions/node/v18.19.0/lib/node_modules/firebase-tools/lib/templates/hosting/init.js'
at Object.openSync (node:fs:596:3)
at readFileSync (node:fs:464:35)
at readTemplateSync (/Users/user/.nvm/versions/node/v18.19.0/lib/node_modules/firebase-tools/lib/templates.js:17:34)
at Object.<anonymous> (/Users/user/.nvm/versions/node/v18.19.0/lib/node_modules/firebase-tools/lib/hosting/implicitInit.js:12:56)
at Module._compile (node:internal/modules/cjs/loader:1356:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load (node:internal/modules/cjs/loader:1013:12)
at Module.require (node:internal/modules/cjs/loader:1225:19)
at require (node:internal/modules/helpers:177:18) {
errno: -2,
syscall: 'open',
code: 'ENOENT',
path: '/Users/user/.nvm/versions/node/v18.19.0/lib/node_modules/firebase-tools/lib/templates/hosting/init.js'
}
Node.js v18.19.0
```

This error persists across different installation methods (global npm install, local install, manual build from source) and Node.js versions. The file 'init.js' appears to be missing from the expected location, suggesting a possible issue with the build process or package structure of firebase-tools.

Additional troubleshooting steps taken:
- Cleared npm cache
- Manually attempted to create directory structures
- Updated Node.js and npm to latest versions
- Tried using npx to run firebase-tools

None of these steps resolved the issue.

I believe this file is meant to be packaged into this build as it's available:
https://raw.githubusercontent.com/firebase/firebase-tools/master/templates/hosting/init.js

**Comment by ufmemo** [comment]
I don't have an explanation, but for funzies, I started a new terminal session and everything started working for me.
