### ISSUE TITLE
Breakpad symbol generation failed for Unity 6 symbols 

### ISSUE THREAD

**Issue by FrantisekHolubec** [firebase/firebase-tools#7867]
### [REQUIRED] Environment info

**firebase-tools: 13.23.0**

**Platform: Windows 11**

### [REQUIRED] Test case
I tried to upload the symbols for my unity 6 app but it fails. its failing only for symbols made by unity 6
Is this unity problem, am I doing something wrong or is this a bug ?
I tried with 2 different java version and get 2 different errors.

### [REQUIRED] Steps to reproduce

problematic file: https://drive.google.com/file/d/1rR9b9Pt7gwbfvePiUneL-RwRgPj5i39w/view?usp=sharing
attempt to upload symbols
```
firebase crashlytics:symbols:upload --debug --app=1:187029196205:android:e8b5c9e6935cf6bb11a524 ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip

firebase crashlytics:symbols:upload --debug --app=1:187029196205:android:e8b5c9e6935cf6bb11a524 ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip --generator csym
```

### [REQUIRED] Expected behavior

Uploads the symbols

### [REQUIRED] Actual behavior

Java 8 Breakpad:
```
[2024-10-24T08:25:41.192Z] Buildtools Jar already downloaded at C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar
i  Generating symbols for ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Extracting dump_syms from dump_syms/windows/dump_syms.bin to N:\Projects\TankSurvivor\Builds\Android\develop\Release\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Extracting object file to .crashlytics
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Zipped input file detected: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.\TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip; unzipping to temp location: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache; writing output to: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad
[CRASHLYTICS LOG DEBUG] 36 native libraries found at C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\libcrashlytics-trampoline.so5347859241832512873.tmp
[CRASHLYTICS LOG DEBUG] GNU Build Id for C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so: acf6365f1a57d0513d7e78424b14f07c579aa5fc
[CRASHLYTICS LOG DEBUG] Renaming Breakpad symbol file to: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\crashlytics-trampoline-arm64-acf6365f1a57d0513d7e78424b14f07c579aa5fc.sym
[CRASHLYTICS LOG DEBUG] Generated symbol file: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\crashlytics-trampoline-arm64-acf6365f1a57d0513d7e78424b14f07c579aa5fc.sym (839 bytes)
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libFirebaseCppAnalytics.so
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\libFirebaseCppAnalytics.so1969445296118415733.tmp
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG ERROR] Crashlytics execution failed.
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
        at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:129)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:306)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:280)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:193)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:125)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:72)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:114)

Error: java command failed with args: -jar,C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,C:\Users\Franta\AppData\Local\Temp\crashlytics-3f81189c-e4f4-481c-8e65-de4e4110c8c0\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools
```

Java 8 csym:
```
[2024-10-24T08:26:23.729Z] Buildtools Jar already downloaded at C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar
i  Generating symbols for ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Zipped input file detected: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.\TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip; unzipping to temp location: C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache; writing output to: C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym
[CRASHLYTICS LOG DEBUG] 36 native libraries found at C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol file from: C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at com.google.firebase.crashlytics.buildtools.utils.io.ByteReader.readInt(ByteReader.java:120)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.readElfFileHeader(ElfDataParser.java:475)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parseElf(ElfDataParser.java:118)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parse(ElfDataParser.java:97)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.elf.ElfDataParser.parse(ElfDataParser.java:42)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.ElfCSymFactory.createCSymFromFile(ElfCSymFactory.java:90)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.NdkCSymGenerator.generateSymbolFileFromFile(NdkCSymGenerator.java:39)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.NdkCSymGenerator.generateSymbols(NdkCSymGenerator.java:24)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:306)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:280)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:193)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:125)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:72)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:114)

Error: java command failed with args: -jar,C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar,-symbolGenerator,csym,-symbolFileCacheDir,C:\Users\Franta\AppData\Local\Temp\crashlytics-e5978618-d132-4c47-bb0b-8f8ee69ed1ba\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym,-verbose,-generateNativeSymbols,-unstrippedLibrary,./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools
```

Java 17 Breakpad:
```
[2024-10-24T08:03:09.761Z] Buildtools Jar already downloaded at C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar
i  Generating symbols for ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Extracting dump_syms from dump_syms/windows/dump_syms.bin to N:\Projects\TankSurvivor\Builds\Android\develop\Release\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Extracting object file to .crashlytics
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Zipped input file detected: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.\TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip; unzipping to temp location: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache; writing output to: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad
[CRASHLYTICS LOG DEBUG] 36 native libraries found at C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\libcrashlytics-trampoline.so15350546551661262856.tmp
[CRASHLYTICS LOG DEBUG] GNU Build Id for C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so: acf6365f1a57d0513d7e78424b14f07c579aa5fc
[CRASHLYTICS LOG DEBUG] Renaming Breakpad symbol file to: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\crashlytics-trampoline-arm64-acf6365f1a57d0513d7e78424b14f07c579aa5fc.sym
[CRASHLYTICS LOG DEBUG] Generated symbol file: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\crashlytics-trampoline-arm64-acf6365f1a57d0513d7e78424b14f07c579aa5fc.sym (839 bytes)
[CRASHLYTICS LOG DEBUG] Crashlytics generating Breakpad Symbol file for: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache\arm64-v8a\libFirebaseCppAnalytics.so
[CRASHLYTICS LOG DEBUG] Extracting Breakpad symbols to temp file: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\libFirebaseCppAnalytics.so12064853055665658732.tmp
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad\unzippedLibsCache
[CRASHLYTICS LOG ERROR] Crashlytics execution failed.
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
        at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:129)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:306)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:280)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:193)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:125)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:72)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:114)

Error: java command failed with args: -jar,C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,C:\Users\Franta\AppData\Local\Temp\crashlytics-f01d0685-7e28-4ec0-8b72-17e99b0323bc\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools
```
Java 17 csym:
```
[2024-10-24T08:01:59.261Z] Buildtools Jar already downloaded at C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar
i  Generating symbols for ./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Zipped input file detected: N:\Projects\TankSurvivor\Builds\Android\develop\Release\.\TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip; unzipping to temp location: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache; writing output to: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym
[CRASHLYTICS LOG DEBUG] 36 native libraries found at C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol file from: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache\arm64-v8a\libcrashlytics-trampoline.so
[CRASHLYTICS LOG DEBUG] Using DWARF data for cSYM generation.
[CRASHLYTICS LOG DEBUG] Generated symbol file: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\crashlytics-trampoline-aarch64-acf6365f1a57d0513d7e78424b14f07c579aa5fc.cSYM (478 bytes)
[CRASHLYTICS LOG DEBUG] Generating native symbol file from: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache\arm64-v8a\libFirebaseCppAnalytics.so
[CRASHLYTICS LOG DEBUG] Crashlytics could not find a build ID.
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym\unzippedLibsCache
[CRASHLYTICS LOG ERROR] Crashlytics execution failed.
java.lang.NullPointerException: Cannot invoke "com.google.firebase.crashlytics.buildtools.ndk.internal.csym.CSym$Builder.build()" because the return value of "com.google.firebase.crashlytics.buildtools.ndk.internal.csym.ElfCSymFactory$CSymFactoryHandler.getBuilder()" is null
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.ElfCSymFactory.createCSymFromFile(ElfCSymFactory.java:92)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.NdkCSymGenerator.generateSymbolFileFromFile(NdkCSymGenerator.java:39)
        at com.google.firebase.crashlytics.buildtools.ndk.internal.csym.NdkCSymGenerator.generateSymbols(NdkCSymGenerator.java:24)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:306)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:280)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:193)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:125)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:72)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:114)

Error: java command failed with args: -jar,C:\Users\Franta\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-3.0.2.jar,-symbolGenerator,csym,-symbolFileCacheDir,C:\Users\Franta\AppData\Local\Temp\crashlytics-f1692580-ff14-447b-9382-19c5b55d533e\nativeSymbols\1-187029196205-android-e8b5c9e6935cf6bb11a524\csym,-verbose,-generateNativeSymbols,-unstrippedLibrary,./TA_TankSurvivor_Release_v.0.02.01.506-0.02.01-v201-IL2CPP.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools
```

**Comment by FrantisekHolubec** [comment]
Any info about this? Its currently holding back our releases as we have no debugging symbols to detect problems

**Comment by FrantisekHolubec** [comment]
Any info about this?

**Comment by mrober** [comment]
Thanks for reporting this @FrantisekHolubec. I am able to reproduce this.

For now, you can work around this by manually unzipping the symbols, and removing all `libFirebaseCpp*` files from each arch.

I think this behaviour might be new, I don't remember Unity including Firebase libs in the output. I will update our build tools to handle it, but it will likely not get released until next year. If this workaround does not work for you, I can build you a prerelease of the build tools binaries.

**Comment by FrantisekHolubec** [comment]
Thank you @mrober removing libFirebaseCpp* files worked, I integrated it into our pipeline until the new version gets released.

**Comment by UnwindGamesDeveloper** [comment]
Any ETA for this fix ?

**Comment by shokarta** [comment]
also experiencing this... any update?

**Comment by FrantisekHolubec** [comment]
I am using TeamCity for building so I made a simple Python script to fix the symbols, sharing until the fix comes out:
```py
def fixFirebaseSymbols(zip_path):
    prefix = "libFirebaseCpp"
    temp_zip_path = zip_path + ".tmp"

    # Temporary storage for files to keep
    files_to_keep = []
    skip_fix = True

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        compression_method = zip_ref.getinfo(zip_ref.namelist()[0]).compress_type
        for file_name in zip_ref.namelist():
            if not os.path.basename(file_name).startswith(prefix):
                files_to_keep.append((file_name, zip_ref.read(file_name)))
            else:
                skip_fix = False

    if skip_fix:
        print("No need for fixing symbols.")
        return

    # Write the filtered files into a temporary ZIP file with the original compression method
    with zipfile.ZipFile(temp_zip_path, 'w', compression=compression_method) as zip_ref:
        for file_name, file_data in files_to_keep:
            zip_ref.writestr(file_name, file_data)

    # Replace the original ZIP file with the modified one
    shutil.move(temp_zip_path, zip_path)
```

**Comment by mrober** [comment]
I have a fix for this in the latest Crashlytics buildtools, it will be included in the next version of the Firebase CLI tool. For now you can manually tell it to use the latest buildtools by:

1. Download [firebase-crashlytics-buildtools-3.0.3.jar](https://dl.google.com/android/maven2/com/google/firebase/firebase-crashlytics-buildtools/3.0.3/firebase-crashlytics-buildtools-3.0.3.jar).

2. Tell the Firebase CLI tool to use the downloaded jar by setting the environment variable:

    ```bash
    export CRASHLYTICS_LOCAL_JAR=/path/to/firebase-crashlytics-buildtools-3.0.3.jar
    ```

3. Run the Firebase CLI tool in debug mode to verify it's using the downloaded jar:

    ```bash
    firebase crashlytics:symbols:upload --debug --app=FIREBASE_APP_ID /path/to/symbols
    ```

**Comment by shokarta** [comment]
hello @mrober Im not sure if this also fixes https://github.com/firebase/firebase-android-sdk/issues/6633,
should it also fix?

**Comment by joehan** [comment]
Closing this since the PR is merged - it will be included in the next firebase-tools release sometime next week.
