### ISSUE TITLE
Count does not work in emulator

### ISSUE THREAD

**Issue by erayerdin** [firebase/firebase-tools#7872]
### [REQUIRED] Environment info

- firebase-tools 13.22.1 (installed globally via npm, npm installed system-wide)
- PopOS 22.04

### [REQUIRED] Test case

```
export const initAdminUser = functions.auth.user().onCreate(async () => {
  const listUsersResult = await auth.listUsers(10);
  const user = listUsersResult.users.find((u) => u.email !== undefined);

  if (user) {
    const { data: getAdminUserCount } = await firestore
      .collection("profiles")
      .where("roles", "array-contains", "admin")
      .limit(1)
      .count()
      .get();
    const { count: adminUserCount } = getAdminUserCount();
    const adminUserExists = adminUserCount > 0;

    if (!adminUserExists) {
      warn("Creating admin user...", user);
      await firestore
        .collection("profiles")
        .doc(user.uid)
        .set({
          roles: ["admin"],
        });

      log("Removing sign-up request for admin user...");
      const qSnapshot = await firestore
        .collection("signupRequests")
        .where("email", "==", user.email)
        .get();
      const docs = qSnapshot.docs;

      for (const doc of docs) {
        await doc.ref.delete();
      }
    }
  }
});
```

### [REQUIRED] Expected behavior

It should create a `/profiles/{user.uid}` document with content `{ 'roles': ['admin'] }` and delete the related document (our app's requirements) under `/signupRequests`.

### [REQUIRED] Actual behavior

```
W
function[us-central1-initAdminUser]
TypeError: Cannot read properties of undefined (reading '_data')
    at data (functions/node_modules/@google-cloud/firestore/build/src/reference/aggregate-query-snapshot.js:57:21)
    at functions/lib/triggers.js:29:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runFunction (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)
    at async runBackground (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:517:5)
    at async processBackground (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:501:5)
    at async /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:690:21
01:04:35
W
function[us-central1-initAdminUser]
Your function was killed because it raised an unhandled error.
01:04:35
I
function[us-central1-initAdminUser]
Finished "us-central1-initAdminUser" in 224.505194ms
```

# Extras

Coming from [this SO question](https://stackoverflow.com/a/79123695/2926992) (the answerer is me).

**Comment by aalej** [comment]
Hey @erayerdin, thanks for sharing code snippets and the error you encountered. I was able to reproduce the error using the code snippet you provided. However, I tried deploying the function and I encountered the same error. This makes me think that the issue might not be related to the emulators.

It looks like like the error was raised along these lines:
```js
    const { data: getAdminUserCount } = await firestore
          .collection("profiles")
          .where("roles", "array-contains", "admin")
          .limit(1)
          .count()
          .get();
    const { count: adminUserCount } = getAdminUserCount();
```

I tried updating this code snippet, and I was able to get the function working. When a new user is created, a new Firestore document under `/profiles` is also created. The updated code looks something like:
```js
export const initAdminUser = functions.auth.user().onCreate(async () => {
   const listUsersResult = await auth.listUsers(10);
   const user = listUsersResult.users.find((u) => u.email !== undefined);

   if (user) {
       const adminUserCountSnapshot = await firestore
           .collection("profiles")
           .where("roles", "array-contains", "admin")
           .limit(1)
           .count()
           .get();
       const { count: adminUserCount } = adminUserCountSnapshot.data();
       const adminUserExists = adminUserCount > 0;

       if (!adminUserExists) {
           console.warn("Creating admin user...", user);
           await firestore
               .collection("profiles")
               .doc(user.uid)
               .set({
                   roles: ["admin"],
               });

           console.log("Removing sign-up request for admin user...");
           const qSnapshot = await firestore
               .collection("signupRequests")
               .where("email", "==", user.email)
               .get();
           const docs = qSnapshot.docs;

           for (const doc of docs) {
               await doc.ref.delete();
           }
       }
   }
});
```

Could you give this a try? Also, I created this [mcve](https://github.com/aalej/issues-7872) to replicate the issue, let me know in case I may have made a mistake or missed anything here.
