### ISSUE TITLE
Hosting init: "Could not load dependency vite in ./"

### ISSUE THREAD

**Issue by inorganik** [firebase/firebase-tools#7874]
### [REQUIRED] Environment info

**firebase-tools:** 13.23.0

**Platform:** macOS

### [REQUIRED] Test case

I new'd up an angular 17 app, added angularfire, and it deploys hosting perfectly. But I have an older ionic/capacitor app that I have upgraded to angular 17 (originally 14), and this is where the error occurs. I have compared their package.json and angular.json files, and I can't find any key differences. I deleted the .firebaserc and firebase.json files in the ionic project to start fresh, because I have successfully deployed firebase hosting in the past before I upgraded.

I have already tried blowing away node modules and reinstalling everything, and not sure what else to try.

I searched "vite" in both project's package-lock.json, and it's there. 

### [REQUIRED] Steps to reproduce

1. `firebase init hosting`

### [REQUIRED] Expected behavior

Initializes hosting

### [REQUIRED] Actual behavior

firebase-debug.log:

```
=== Hosting Setup
[debug] [2024-10-25T12:56:41.959Z] Checked if tokens are valid: true, expires at: 1729863264694
[debug] [2024-10-25T12:56:41.959Z] Checked if tokens are valid: true, expires at: 1729863264694
[debug] [2024-10-25T12:56:41.959Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/whats-for-dinner-98674 [none]
[debug] [2024-10-25T12:56:42.058Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/whats-for-dinner-98674 200
[debug] [2024-10-25T12:56:42.058Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/whats-for-dinner-98674 {"projectId":"whats-for-dinner-98674","projectNumber":"1057105872167","displayName":"Nomaste","name":"projects/whats-for-dinner-98674","resources":{"hostingSite":"whats-for-dinner-98674","storageBucket":"whats-for-dinner-98674.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_e5822b66-bd35-45ef-a958-d159674301f9"}
[debug] [2024-10-25T12:56:45.425Z] Error: Cannot find module 'vite'
Require stack:
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/utils.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/index.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/emulator/controller.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/emulator/commandUtils.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/commands/database-get.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/commands/index.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/index.js
- /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/bin/firebase.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at relativeRequire (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/utils.js:195:34)
    at getConfig (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/vite/index.js:111:65)
    at discover (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/vite/index.js:60:68)
    at async /Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/vite/index.js:38:55
    at async discover (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/frameworks/index.js:47:32)
    at async doSetup (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/init/features/hosting/index.js:54:11)
    at async init (/Users/jamie/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/init/index.js:41:9)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by inorganik** [comment]
I was able to resolve this by installing vite as a dev dependency... but it was a puzzling error because my new angular 17 project did not have it in package.json as a dependency.

**Comment by Ishan-pro** [comment]
I faced the same error and I solved it by updating "vite dev" in my package.json to "yarn vite dev" since I was using yarn instead of npm and specifying pacakgeManager in package.json as yarn.

```json
"scripts": {
    "dev": "yarn vite",
    "build": "tsc -b && yarn vite build",
    "lint": "eslint .",
    "preview": "yarn vite preview"
  },
```
