### ISSUE TITLE
Firebase Serve fails on with Parse Error

### ISSUE THREAD

**Issue by ikhatri** [firebase/firebase-tools#797]
### Version info
```
> firebase --version
3.18.6
> node -v
v6.11.5
> npm -v
3.10.10
```

### Platform Information
Windows 10 x64

### Steps to reproduce
``` JavaScript
// index.js
var functions = require('firebase-functions');

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});
```
1. Run `firebase serve --only functions --debug` or `firebase serve --debug` or `firebase functions:shell --debug` all three aforementioned commands fail with the same error.

### Expected behavior
The function is emulated locally.

### Actual behavior
``` log
[debug] [2018-06-12T19:03:30.039Z] ----------------------------------------------------------------------
[debug] [2018-06-12T19:03:30.055Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\bin\firebase serve --only functions --debug
[debug] [2018-06-12T19:03:30.055Z] CLI Version:   3.18.6
[debug] [2018-06-12T19:03:30.055Z] Platform:      win32
[debug] [2018-06-12T19:03:30.055Z] Node Version:  v6.11.5
[debug] [2018-06-12T19:03:30.055Z] Time:          Tue Jun 12 2018 15:03:30 GMT-0400 (Eastern Daylight Time)
[debug] [2018-06-12T19:03:30.055Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-06-12T19:03:30.077Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-06-12T19:03:30.077Z] > authorizing via signed-in user
[debug] [2018-06-12T19:03:30.077Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/sleepy-sue  
  
 Tue Jun 12 2018 15:03:30 GMT-0400 (Eastern Daylight Time)
[debug] [2018-06-12T19:03:30.420Z] <<< HTTP RESPONSE 200
[debug] [2018-06-12T19:03:30.422Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/sleepy-sue/tokens  
  
 Tue Jun 12 2018 15:03:30 GMT-0400 (Eastern Daylight Time)
[debug] [2018-06-12T19:03:30.760Z] <<< HTTP RESPONSE 200
[debug] [2018-06-12T19:03:30.760Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/sleepy-sue  
  
 Tue Jun 12 2018 15:03:30 GMT-0400 (Eastern Daylight Time)
[debug] [2018-06-12T19:03:31.077Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from 'C:\Users\320025505\Documents\SleepCoach-Demo'...
[info] 
[info] i  functions: Preparing to emulate functions.
[debug] [2018-06-12T19:03:33.181Z] Fetching environment
[debug] [2018-06-12T19:03:33.181Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/414768550018:getServerAppConfig  
  
 Tue Jun 12 2018 15:03:33 GMT-0400 (Eastern Daylight Time)
[debug] [2018-06-12T19:03:33.512Z] <<< HTTP RESPONSE 200
[debug] [2018-06-12T19:03:33.512Z] Starting @google-cloud/functions-emulator
[debug] [2018-06-12T19:03:33.589Z] Parsing function triggers
[debug] [2018-06-12T19:03:34.019Z] Error while deploying to emulator: Error: Parse Error
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[warn] !  functions: Failed to emulate helloWorld
[info] i  functions: No HTTPS functions found. Use firebase functions:shell if you would like to emulate other types of functions.
[info] Shutting down...
```

**Comment by gerhardcit** [comment]
There seems to be many "Error parsing triggers: Cannot find module './package.json'" like errors going around. 
Is there any suggestion on how we get passed it. Function deployments are completely broken. We are stuck with parse errors which seems to come from something beyond the parsing. @laurenzlong ?

**Comment by gerhardcit** [comment]
Node: v6.11.5
Npm: 3.10.10
firebase --version: 5.1.1

The parsing seems to work:

```
✔  functions: Finished running predeploy script.
[2018-10-22T04:51:35.334Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.5",
    "request": "^2.88.0",
    "request-promise": "^4.2.2"
  },
  "devDependencies": {
    "tslint": "~5.8.0",
    "typescript": "~2.8.3"
  },
  "private": true
}
```

But then this at the end
```

[2018-10-22T04:51:43.287Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 22 Oct 2018 04:51:43 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close

Error: Error parsing triggers: Cannot find module './package.json'

Try running "npm install" in your functions directory before deploying.
```

I've even tried removing any prebuild actions in  the root folder: firebase.json
```
{
  "functions": {
    "predeploy": []
  }
}
```

This is from the basic typescript starter project. 

This message seems wrong anywway `Error parsing triggers: Cannot find module './package.json'`
There is something else that goes wrong and it not caught properly.
When can we get this fixed please?

**Comment by gerhardcit** [comment]
@laurenzlong , 
My stupidity it seems after all.
After moving project structure to typescript: 
`const appPackage = require('./package.json');`
is suppose to be
`const appPackage = require('../package.json');` 

Compiler does not pick that up. Only at runtime does it fails.

**Comment by thechenky** [comment]
Thanks @gerhardcit for posting your updates! @ikhatri can you update your CLI to the latest version and try again? If the issue is still occurring, please file another issue. Thanks everyone!
