### ISSUE TITLE
it keep telling me the port is already used

### ISSUE THREAD

**Issue by Motekema** [firebase/firebase-tools#8013]
Error: listen EADDRINUSE: address already in use :::8625
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Function.listen (C:\Users\DISS_PC\Loan_Manager_P2\backend\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\DISS_PC\Loan_Manager_P2\backend\dist\app.js:44:5)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8625
}

Node.js v18.20.5

**Comment by aalej** [comment]
Hey @Motekema. My best guess here is that you're trying to start the emulators and the port configured for one of the emulators in `firebase.json` is already in use.  If so, try terminating the process running on port `8625` or change the port number to a free port.  This [documentation](https://firebase.google.com/docs/emulator-suite/install_and_configure#security_rules_configuration) shows an example on how you can specify the port.

If you're still encountering an issue after trying the above, could you file a new issue and provide the details using the specified template? This is because we would need additional information to investigate this further. Please include the version of firebase-tools you're using, steps to reproduce the issue, etc. Thanks!
