### ISSUE TITLE
RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304 using Emulator suite

### ISSUE THREAD

**Issue by fiindl** [firebase/firebase-tools#8081]
13.29.1
**Platform:** Windows

### [REQUIRED] Test case

Trying to insert bulks data using NodeJS and batch.

### [REQUIRED] Steps to reproduce

Setup an emulator suite environment
Add a function that insert "important" amount of data (30mb in my case)

Example script : 

```
export const initDb = onRequest({
    timeoutSeconds: 300,
    memory: "8GiB",
  }, async (request, response) => {
    const db = await getFirestore();

    logger.info("Init - Downloading fresh data from " + INIT_URI);

    const result = await axios.get(INIT_URI);

    logger.info("Init - Download done, processing: " + result.data.length);

    const colRef = await db.collection('recalls');

    if(result.data) {
        let batchNum = 0;
        let batches: any[] = [];

        let index = 0;

        for(const recall of result.data) {

            batches.push(recall);
            batchNum++;

            if(batchNum > 10 || result.data.length - 1 === index) {

                if(result.data.length - 1 === index) {
                    console.log('Last batch');
                }

                console.log('commiting, current index: ' + index);

                var batch = db.batch();

                batches.forEach(i => {
                    batch.set(colRef.doc(i.id.toString()), i)
                });

                // await new Promise(resolve => setTimeout(resolve, 1000));

                try {
                    await batch.commit();
                } catch(e) {
                    console.error(e)
                }
                

                console.log('Done');
                batchNum = 0;
            }

            index++;
        }
    } else {
        logger.error("No data retreived");
    }

    response.send('OK');
});
```

### [REQUIRED] Expected behavior

Works well? Not triggering error

### [REQUIRED] Actual behavior

When insert the ~1700 row, the consol trigger this error and stops the script run:

```
Dec 26, 2024 1:18:55 PM io.grpc.netty.NettyServerStream$TransportState deframeFailed
WARNING: Exception processing message
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4200838
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:392)
        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:272)
        at io.grpc.internal.MessageDeframer.request(MessageDeframer.java:162)
        at io.grpc.internal.AbstractStream$TransportState$1RequestRunnable.run(AbstractStream.java:264)
        at io.grpc.netty.NettyServerStream$TransportState$1.run(NettyServerStream.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1575)

```

**Comment by fiindl** [comment]
Nevermind, I forgot to clear the "batches" array after each commit...
