### ISSUE TITLE
firebase login error

### ISSUE THREAD

**Issue by buu700** [firebase/firebase-tools#809]
### Version info

3.19.1

### Platform Information

Debian 9.4

### Steps to reproduce

`firebase login`

### Expected behavior

No errors.

### Actual behavior

Command appears to work as expected, but with an error.

```
[2018-06-27T04:45:37.004Z] ----------------------------------------------------------------------
[2018-06-27T04:45:37.016Z] Command:       /usr/bin/node /node_modules/.bin/firebase login --debug
[2018-06-27T04:45:37.016Z] CLI Version:   3.19.1
[2018-06-27T04:45:37.017Z] Platform:      linux
[2018-06-27T04:45:37.018Z] Node Version:  v8.11.3
[2018-06-27T04:45:37.019Z] Time:          Wed Jun 27 2018 04:45:37 GMT+0000 (UTC)
[2018-06-27T04:45:37.020Z] ----------------------------------------------------------------------

? Allow Firebase to collect anonymous CLI usage and error reporting information? No

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=268733292&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
(node:108) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-06-27T04:46:37.589Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token
 { code: '4/AAAFAJvPRkZClLOcS9a1Z5Hobz6nsd0VikPBAidWbBp1v3AuP2p1cyYRJy7Yii68x6EFyedzN7NTJJsKcdJYfUc',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' }
 Wed Jun 27 2018 04:46:37 GMT+0000 (UTC)
[2018-06-27T04:46:38.015Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, x-content-type-options=nosniff, cache-control=no-cache, no-store, max-age=0, must-revalidate, pragma=no-cache, expires=Mon, 01 Jan 1990 00:00:00 GMT, date=Wed, 27 Jun 2018 04:46:36 GMT, content-disposition=attachment; filename="json.txt"; filename*=UTF-8''json.txt, server=ESF, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, alt-svc=quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, vary=Accept-Encoding, connection=close

✔  Success! Logged in as jerusalem.duvet@gmail.com
```

**Comment by grundid** [comment]
I have the same problem. 

As a workaround I downgraded to 3.18.6, logged in and then upgraded back to 3.19.1

**Comment by paolomainardi** [comment]
Same here running 3.19.3
