### ISSUE TITLE
Emulator crashes on hot reload when using param decorator

### ISSUE THREAD

**Issue by dpkshrma** [firebase/firebase-tools#823]
### Version info
3.18.4

### Platform Information
macOS High Sierra

### Steps to reproduce
I am using [typescript-rest](https://github.com/thiagobustamante/typescript-rest) to host an api.

When I use `PathParam` decorator like below, it works correctly for the first time while serving using `tsc && firebase serve --only functions`

### UserController.ts
```ts
import { GET, Path, PathParam } from 'typescript-rest'
import User from '../models/User';

@Path('/users')
export class UserController {
  @GET
  @Path(':id')
  async getById(@PathParam('id') id: string) {
    return await User.findOne(id)
  }
}
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "newLine": "LF",
    "noFallthroughCasesInSwitch": true,
    "outDir": "lib",
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": false,
    "target": "es2016"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

But on hot reload (due to code change), it throws the following error when the API is called:

```
error: /Users/deepak/firetest/functions/node_modules/typescript-rest/dist/decorators.js:981
        serviceMethod.parameters[parameterIndex] = new metadata.MethodParam(name, paramTypes[parameterIndex], paramType);
                                                                                            ^
TypeError: Cannot read property '0' of undefined
    at processDecoratedParameter (/Users/deepak/firetest/functions/node_modules/typescript-rest/dist/decorators.js:981:93)
    at /Users/deepak/firetest/functions/node_modules/typescript-rest/dist/decorators.js:594:46
    at /Users/deepak/firetest/functions/lib/controllers/UserController.js:9:37
    at DecorateProperty (/Users/deepak/firetest/functions/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/Users/deepak/firetest/functions/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/Users/deepak/firetest/functions/lib/controllers/UserController.js:4:92)
    at Object.<anonymous> (/Users/deepak/firetest/functions/lib/controllers/UserController.js:39:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error: Function worker crashed with exit code: 1
```

I need to know if there are some configuration options available to force `firebase serve` to rebuild using `tsc`

### Expected behavior
Should rebuild using same ts configuration (which probably seems to be root cause of the issue)

### Actual behavior

Throws error on API call as described above. No debug logs were produced on API call when the error occured.

**Comment by laurenzlong** [comment]
Hi, this issue is the same as https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/207, please follow along there.
