### ISSUE TITLE
firebase serve unable to serve https function

### ISSUE THREAD

**Issue by hectorlee** [firebase/firebase-tools#827]
### Version info

firebase v3.19.3
node v6.11.5
npm v3.10.10
nvm v0.33.2

firebase-admin 5.12.1 and 
firebase-functions 1.0.3 and 1.1.0

### Platform Information

Mac OS 10.12.6

### Steps to reproduce

firebase serve fails to emulate functions even with the example function in index.js. 

```
const functions = require('firebase-functions');

// Create and Deploy Your First Cloud Functions
// https://firebase.google.com/docs/functions/write-firebase-functions

exports.helloWorld = functions.https.onRequest((request, response) => {
 response.send("Hello from Firebase!");
});
```

### Expected behavior

Expected to serve functions.

### Actual behavior

```
➜  functionsTest firebase serve --only functions --debug
[2018-07-13T05:31:30.253Z] ----------------------------------------------------------------------
[2018-07-13T05:31:30.257Z] Command:       /Users/hectorlee/.nvm/versions/node/v6.11.5/bin/node /Users/hectorlee/.nvm/versions/node/v6.11.5/bin/firebase serve --only functions --debug
[2018-07-13T05:31:30.258Z] CLI Version:   3.19.3
[2018-07-13T05:31:30.258Z] Platform:      darwin
[2018-07-13T05:31:30.258Z] Node Version:  v6.11.5
[2018-07-13T05:31:30.258Z] Time:          Fri Jul 13 2018 13:31:30 GMT+0800 (+08)
[2018-07-13T05:31:30.259Z] ----------------------------------------------------------------------

[2018-07-13T05:31:30.268Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-07-13T05:31:30.268Z] > authorizing via signed-in user
[2018-07-13T05:31:30.272Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/firecast-caaa6

 Fri Jul 13 2018 13:31:30 GMT+0800 (+08)
[2018-07-13T05:31:31.132Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 13 Jul 2018 05:31:31 GMT, content-type=application/json; charset=utf-8, content-length=111, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-07-13T05:31:31.133Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/firecast-caaa6/tokens

 Fri Jul 13 2018 13:31:31 GMT+0800 (+08)
[2018-07-13T05:31:31.887Z] <<< HTTP RESPONSE 200 server=nginx, date=Fri, 13 Jul 2018 05:31:31 GMT, content-type=application/json; charset=utf-8, content-length=263, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-07-13T05:31:31.888Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/firecast-caaa6

 Fri Jul 13 2018 13:31:31 GMT+0800 (+08)
[2018-07-13T05:31:33.071Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 13 Jul 2018 05:31:33 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close

=== Serving from '/Users/hectorlee/code/functionsTest'...

i  functions: Preparing to emulate functions.
[2018-07-13T05:31:33.531Z] Fetching environment
[2018-07-13T05:31:33.533Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/11896845545:getServerAppConfig

 Fri Jul 13 2018 13:31:33 GMT+0800 (+08)
[2018-07-13T05:31:34.187Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 13 Jul 2018 05:31:34 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="43,42,41,39,35", accept-ranges=none, connection=close
[2018-07-13T05:31:34.188Z] Starting @google-cloud/functions-emulator
[2018-07-13T05:31:34.209Z] Parsing function triggers
[2018-07-13T05:31:34.341Z] Error while deploying to emulator: TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at Promise (/Users/hectorlee/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:34:42)
    at getService.then (/Users/hectorlee/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:33:16)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
⚠  functions: Failed to emulate helloWorld
i  functions: No HTTPS functions found. Use firebase functions:shell if you would like to emulate other types of functions.
```

**Comment by laurenzlong** [comment]
Seems like the important part of the log is:

[2018-07-13T05:31:34.341Z] Error while deploying to emulator: TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at Promise (/Users/hectorlee/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:34:42)
    at getService.then (/Users/hectorlee/.nvm/versions/node/v6.11.5/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:33:16)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)


Which comes from https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/master/src/client/rest-client.js#L34. Can you file an issue in https://github.com/GoogleCloudPlatform/cloud-functions-emulator?

**Comment by hectorlee** [comment]
I've filed an issue in the repo you suggested. Hope someone can fix this. Haven't been able to use functions locally at all.

**Comment by archebyte** [comment]
Same/similar issue currently running Node8, commented here.
[firebase serve unable to serve https function #254](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/254)
