### ISSUE TITLE
firebase deploy (functions): TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by dark-swordsman** [firebase/firebase-tools#833]
### Version info
3.19.3

### Platform Information
Windows 10 64-bit 1803 17134.165

### Steps to reproduce
After compiling ES6 code down to ES5 with babel into a `functions` folder, `firebase deploy` is run.

### Expected behavior
Functions app is deployed.

### Actual behavior

Shell:
```
$ firebase deploy

=== Deploying to 'miatadb'...

i  deploying functions

Error: An unexpected error has occurred.
```
Debug:
```
[info] 
[info] === Deploying to 'miatadb'...
[info] 
[info] i  deploying functions
[debug] [2018-07-22T22:25:11.385Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:168:7)
    at module.exports (C:\Users\DarkSwordsman\AppData\Roaming\npm\node_modules\firebase-tools\lib\resolveProjectPath.js:7:15)
    at module.exports (C:\Users\DarkSwordsman\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\prepare.js:25:30)
    at _chain (C:\Users\DarkSwordsman\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:26:38)
    at C:\Users\DarkSwordsman\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:83:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by dark-swordsman** [comment]
It turns out that I forgot to specify a `source` parameter in my `firebase.json`, and the error is a Node error from `path.resolve()` in `detectProjectRoot.js`.

I really recommend that a fix be added, and I will even do it myself, to that file, such as this:

```JavaScript
"use strict";

var fsutils = require("./fsutils");
var path = require("path");

module.exports = function(cwd) {
  var projectRootDir = cwd || process.cwd();
  while (!fsutils.fileExistsSync(path.resolve(projectRootDir, "./firebase.json"))) {
    var parentDir = path.dirname(projectRootDir);
    if (parentDir === projectRootDir) {
      return null;
    }
    projectRootDir = parentDir;
  }
  return projectRootDir;
};
```

**Comment by Christilut** [comment]
Thanks for this. Better error message would be nice here indeed.
