### ISSUE TITLE
Created new project -- Already failure -- Useless error message

### ISSUE THREAD

**Issue by fxfactorial** [firebase/firebase-tools#843]
```
npm i -g firebase-tools@4.0.0
/Users/qz1llg/.nvm/versions/node/v8.10.0/bin/firebase -> /Users/qz1llg/.nvm/versions/node/v8.10.0/lib/node_modules/firebase-tools/bin/firebase
+ firebase-tools@4.0.0
updated 1 package in 3.759s
```

And got: 

```
firebase init cloud-functions

     🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥     🔥🔥🔥     🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥
     🔥🔥        🔥🔥  🔥🔥     🔥🔥 🔥🔥       🔥🔥     🔥🔥  🔥🔥   🔥🔥  🔥🔥       🔥🔥
     🔥🔥🔥🔥🔥🔥    🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥   🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥
     🔥🔥        🔥🔥  🔥🔥    🔥🔥  🔥🔥       🔥🔥     🔥🔥 🔥🔥     🔥🔥       🔥🔥 🔥🔥
     🔥🔥       🔥🔥🔥🔥 🔥🔥     🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥     🔥🔥  🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥

You're about to initialize a Firebase project in this directory:

  /Users/qz1llg/Repos/hack


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Select a default Firebase project for this directory: hack-for-humanity (hack-for-humanity-3cc30)

=== Cloud-functions Setup

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```

With an debug log of:

```
~/R/hack ❯❯❯ cat firebase-debug.log
    1 [debug] [2018-07-28T21:19:49.312Z] ----------------------------------------------------------------------
    2 [debug] [2018-07-28T21:19:49.314Z] Command:       /Users/qz1llg/.nvm/versions/node/v8.10.0/bin/node /Users/qz1llg/.nvm/versions/node/v8.10.0/bin/firebase init cloud-functions
    3 [debug] [2018-07-28T21:19:49.314Z] CLI Version:   3.19.3
    4 [debug] [2018-07-28T21:19:49.314Z] Platform:      darwin
    5 [debug] [2018-07-28T21:19:49.314Z] Node Version:  v8.10.0
    6 [debug] [2018-07-28T21:19:49.315Z] Time:          Sat Jul 28 2018 14:19:49 GMT-0700 (PDT)
    7 [debug] [2018-07-28T21:19:49.315Z] ----------------------------------------------------------------------
    8 [debug]
    9 [debug] [2018-07-28T21:19:49.321Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
   10 [debug] [2018-07-28T21:19:49.321Z] > authorizing via signed-in user
   11 [info]
   12      🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥     🔥🔥🔥     🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥
   13      🔥🔥        🔥🔥  🔥🔥     🔥🔥 🔥🔥       🔥🔥     🔥🔥  🔥🔥   🔥🔥  🔥🔥       🔥🔥
   14      🔥🔥🔥🔥🔥🔥    🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥   🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥
   15      🔥🔥        🔥🔥  🔥🔥    🔥🔥  🔥🔥       🔥🔥     🔥🔥 🔥🔥     🔥🔥       🔥🔥 🔥🔥
   16      🔥🔥       🔥🔥🔥🔥 🔥🔥     🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥 🔥🔥🔥🔥🔥🔥🔥🔥  🔥🔥     🔥🔥  🔥🔥🔥🔥🔥🔥  🔥🔥🔥🔥🔥🔥🔥🔥
   17
   18 You're about to initialize a Firebase project in this directory:
   19
   20   /Users/qz1llg/Repos/hack
   21
   22 [info]
   23 === Project Setup
   24 [info]
   25 [info] First, let's associate this project directory with a Firebase project.
   26 [info] You can create multiple project aliases by running firebase use --add,
   27 [info] but for now we'll just set up a default project.
   28 [info]
   29 [debug] [2018-07-28T21:19:49.326Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects
   30
   31  Sat Jul 28 2018 14:19:49 GMT-0700 (PDT)
   32 [debug] [2018-07-28T21:19:49.867Z] <<< HTTP RESPONSE 200
   33 [info]
   34 === Cloud-functions Setup
   35 [debug] [2018-07-28T21:19:52.133Z] TypeError: features[nextFeature] is not a function
   36     at init (/Users/qz1llg/.nvm/versions/node/v8.10.0/lib/node_modules/firebase-tools/lib/init/index.js:13:49)
   37     at /Users/qz1llg/.nvm/versions/node/v8.10.0/lib/node_modules/firebase-tools/lib/init/index.js:14:14
   38     at <anonymous>
   39     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
   40 [error]
   41 [error] Error: An unexpected error has occurred.
```

I understand that all software has bugs but it is surprising when a hundred million dollar project gives error messages of  ` An unexpected error has occurred.` which are not helpful on just trying to start a project.

**Comment by mbleigh** [comment]
Try just

firebase init functions

It's not cloud- functions -- did you see it as such in documentation
somewhere?

**Comment by fxfactorial** [comment]
@mbleigh You're right, that works thank you. 

I thought I read it on a tutorial somewhere that I could start it with whatever name. Please make the CLI more robust to errors like this.
