### ISSUE TITLE
functions: Failed to emulate No HTTPS functions found

### ISSUE THREAD

**Issue by ilearnio** [firebase/firebase-tools#844]
### Version info

firebase-tools 4.0.0
yarn 1.7.0
Node 6.11.5 (couldn't make it work with Node 8 after many tries)

### Platform Information

OS X

### Steps to reproduce

It happens to me every time when I do:

```
firebase init
cd functions
yarn
yarn build && firebase serve --only functions --debug
```

### Expected behavior

Should start `helloWorld` https function

### Actual behavior

```
firebase serve --only functions --debug
[2018-07-30T10:20:30.650Z] ----------------------------------------------------------------------
[2018-07-30T10:20:30.655Z] Command:       /Users/Admin/.nvm/versions/node/v6.11.5/bin/node /usr/local/bin/firebase serve --only functions --project commerce-co --debug
[2018-07-30T10:20:30.657Z] CLI Version:   4.0.0
[2018-07-30T10:20:30.657Z] Platform:      darwin
[2018-07-30T10:20:30.657Z] Node Version:  v6.11.5
[2018-07-30T10:20:30.658Z] Time:          Mon Jul 30 2018 13:20:30 GMT+0300 (EEST)
[2018-07-30T10:20:30.659Z] ----------------------------------------------------------------------

[2018-07-30T10:20:30.680Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-07-30T10:20:30.681Z] > authorizing via signed-in user
[2018-07-30T10:20:30.685Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/commerce-co

 Mon Jul 30 2018 13:20:30 GMT+0300 (EEST)
!!!! make request https://admin.firebase.com/v1/projects/commerce-co
[2018-07-30T10:20:31.489Z] <<< HTTP RESPONSE 200 server=nginx, date=Mon, 30 Jul 2018 10:19:55 GMT, content-type=application/json; charset=utf-8, content-length=108, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-07-30T10:20:31.492Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/commerce-co/tokens

 Mon Jul 30 2018 13:20:31 GMT+0300 (EEST)
!!!! make request https://admin.firebase.com/v1/database/commerce-co/tokens
[2018-07-30T10:20:32.317Z] <<< HTTP RESPONSE 200 server=nginx, date=Mon, 30 Jul 2018 10:19:56 GMT, content-type=application/json; charset=utf-8, content-length=259, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-07-30T10:20:32.319Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/commerce-co

 Mon Jul 30 2018 13:20:32 GMT+0300 (EEST)
!!!! make request https://cloudresourcemanager.googleapis.com/v1/projects/commerce-co
[2018-07-30T10:20:33.330Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 30 Jul 2018 10:19:57 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close

=== Serving from '/Users/Admin/Code/boxes/commerceco'...

i  functions: Preparing to emulate functions.
[2018-07-30T10:20:34.692Z] Fetching environment
[2018-07-30T10:20:34.697Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/770563601143:getServerAppConfig

 Mon Jul 30 2018 13:20:34 GMT+0300 (EEST)
!!!! make request https://mobilesdk-pa.googleapis.com/v1/projects/770563601143:getServerAppConfig
[2018-07-30T10:20:35.225Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 30 Jul 2018 10:19:59 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-07-30T10:20:35.227Z] Starting @google-cloud/functions-emulator
[2018-07-30T10:20:35.324Z] Parsing function triggers
!!!! make request http://localhost:5001/$discovery/rest?version=v1
!!!! body.error.errors [ '/$discovery/rest is not a recognized path.' ]
!!!! make request http://localhost:5001/$discovery/rest?version=v1
!!!! body.error.errors [ '/$discovery/rest is not a recognized path.' ]
[2018-07-30T10:20:35.725Z] Error while deploying to emulator: Error
Error
    at RequestError.Error (native)
    at new RequestError (/Users/Admin/.config/yarn/global/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/Users/Admin/.config/yarn/global/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:97:27)
    at Request.self.callback (/Users/Admin/.config/yarn/global/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Admin/.config/yarn/global/node_modules/request/request.js:1164:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Admin/.config/yarn/global/node_modules/request/request.js:1086:12)
⚠  functions: Failed to emulate helloWorld
i  functions: No HTTPS functions found. Use firebase functions:shell if you would like to emulate other types of functions.
```

I've been debugging this for a while and as you can see, I added some custom logs that are starting with `!!!` and it turns out that `@google-cloud/functions-emulator` is calling a wrong URL `http://localhost:5001/$discovery/rest?version=v1`. This is the place:

![image](https://user-images.githubusercontent.com/14331216/43392258-d5ddfbae-93fb-11e8-8587-502dfcd59c3f.png)

**Comment by ilearnio** [comment]
Ah, so much time wasted on this. It appears that I had another firebase process running. Please add some more detailed error messages so we know what's happening!

**Comment by laurenzlong** [comment]
Hi could you post this as an issue on https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues?
