### ISSUE TITLE
Unexpected error has occured - trying to deploy

### ISSUE THREAD

**Issue by bcook12345** [firebase/firebase-tools#862]
### Version info
4.0.3
node v8.10.0
### Platform Information
Windows 10 Pro

### Steps to reproduce
https://github.com/firebase/firebase-tools/issues/654#issuecomment-368329077, https://github.com/firebase/firebase-tools/issues/654#issuecomment-373859801,
https://github.com/firebase/firebase-tools/issues/654#issuecomment-376788540 then `firebase deploy`. (3 Different comments, please read all of them)

### Expected behavior
Deploy my app to my project domain - ProjectIDHere.firebaseapp.com

### Actual behavior
[2018-08-08T18:32:43.256Z] ----------------------------------------------------------------------
[2018-08-08T18:32:43.259Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\braythor\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase deploy --debug
[2018-08-08T18:32:43.259Z] CLI Version:   4.0.3
[2018-08-08T18:32:43.259Z] Platform:      win32
[2018-08-08T18:32:43.260Z] Node Version:  v8.10.0
[2018-08-08T18:32:43.260Z] Time:          Wed Aug 08 2018 14:32:43 GMT-0400 (Eastern Daylight Time)
[2018-08-08T18:32:43.261Z] ----------------------------------------------------------------------

[2018-08-08T18:32:43.268Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-08-08T18:32:43.268Z] > authorizing via signed-in user
[2018-08-08T18:32:43.270Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2018-08-08T18:32:43.270Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token
 { refresh_token: 'XXX',
  client_id: 'XXX.apps.googleusercontent.com',
  client_secret: 'XXX',
  grant_type: 'refresh_token',
  scope: 'email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/firebase openid' }
 Wed Aug 08 2018 14:32:43 GMT-0400 (Eastern Daylight Time)
[2018-08-08T18:32:43.820Z] <<< HTTP RESPONSE 200 cache-control=no-cache, no-store, max-age=0, must-revalidate, pragma=no-cache, expires=Mon, 01 Jan 1990 00:00:00 GMT, date=Wed, 08 Aug 2018 18:32:46 GMT, vary=X-Origin, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, x-content-type-options=nosniff, x-frame-options=SAMEORIGIN, x-xss-protection=1; mode=block, server=GSE, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-08-08T18:32:43.841Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/ProjectIDHere

 Wed Aug 08 2018 14:32:43 GMT-0400 (Eastern Daylight Time)
[2018-08-08T18:32:44.233Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 08 Aug 2018 18:32:47 GMT, content-type=application/json; charset=utf-8, content-length=108, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-08-08T18:32:44.238Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/ProjectIDHere/tokens

 Wed Aug 08 2018 14:32:44 GMT-0400 (Eastern Daylight Time)
[2018-08-08T18:32:44.619Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 08 Aug 2018 18:32:47 GMT, content-type=application/json; charset=utf-8, content-length=260, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store

=== Deploying to 'ProjectIDHere'...

i  deploying database, storage, firestore, functions, hosting
[2018-08-08T18:32:45.107Z] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Config.path (C:\Users\braythor\AppData\Roaming\npm\node_modules\firebase-tools\lib\config.js:166:37)
    at C:\Users\braythor\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\lifecycleHooks.js:68:38
    at _chain (C:\Users\braythor\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:26:38)
    at C:\Users\braythor\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:29:14
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Error: An unexpected error has occurred.

Thanks for the help
-bcook12345

**Comment by laurenzlong** [comment]
Hi, we need to improve our error messaging, but ensure that your firebase.json has "source" in the "functions" object, and it indicates the source directory for your functions code.

e.g.
```
{
....
"functions": {
   "source": "functions"
},
...
}
```

**Comment by bcook12345** [comment]
@laurenzlong Now it gives me this error: `Error: There was an error loading firebase.json:

Unexpected token 'p' at 11:6
    "predeploy": [
     ^
File: "C:\Users\braythor\firebase-init\firebase.json"
`

the part it is referencing looks like this:
`  "functions": {
		"source": "functions"
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },`

**Comment by laurenzlong** [comment]
you're missing a comma after `"source": "functions"`
