### ISSUE TITLE
Emulating functions fails (possibly due to something regarding google-auth-library?)

### ISSUE THREAD

**Issue by ppannuto** [firebase/firebase-tools#863]
### Version info

```
$ firebase --version
4.0.3
```

### Platform Information

OS X

### Steps to reproduce

```bash
nvm use v6.11
# node --version  --> v6.11.5
mkdir -p /tmp/test && cd /tmp/test
firebase init
# ... enable Functions, choose TypeScript, otherwise defaults
```

Add to `src/index.ts`

```typescript
export const onUserCreate =
  functions.database.ref('/users/{uid}').onCreate(event => {
    return event.ref.update({ createdAt: Date.now() })
})
```

Now try to emulate the function:

```bash
npm run build && firebase functions:shell
```

```
> functions@ build /private/tmp/test/functions
> tsc

i  functions: Preparing to emulate functions.
⚠  functions: Failed to emulate onUserCreate
i  functions: No functions to emulate.
No functions emulated.
```

### Expected behavior

Drop into a function shell.

### Actual behavior

```
$ npm run build && firebase functions:shell --project paymenttoy --debug

> functions@ build /private/tmp/test/functions
> tsc

[2018-08-08T22:15:00.886Z] ----------------------------------------------------------------------
[2018-08-08T22:15:00.889Z] Command:       /Users/ppannuto/.nvm/versions/v6.11.5/bin/node /Users/ppannuto/.nvm/versions/v6.11.5/bin/firebase functions:shell --project paymenttoy --debug
[2018-08-08T22:15:00.889Z] CLI Version:   4.0.3
[2018-08-08T22:15:00.890Z] Platform:      darwin
[2018-08-08T22:15:00.890Z] Node Version:  v6.11.5
[2018-08-08T22:15:00.890Z] Time:          Wed Aug 08 2018 15:15:00 GMT-0700 (PDT)
[2018-08-08T22:15:00.890Z] ----------------------------------------------------------------------

[2018-08-08T22:15:00.900Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-08-08T22:15:00.900Z] > authorizing via signed-in user
[2018-08-08T22:15:00.902Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/paymenttoy

 Wed Aug 08 2018 15:15:00 GMT-0700 (PDT)
[2018-08-08T22:15:01.195Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 08 Aug 2018 22:15:01 GMT, content-type=application/json; charset=utf-8, content-length=105, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-08-08T22:15:01.196Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/paymenttoy/tokens

 Wed Aug 08 2018 15:15:01 GMT-0700 (PDT)
[2018-08-08T22:15:01.628Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 08 Aug 2018 22:15:01 GMT, content-type=application/json; charset=utf-8, content-length=258, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
i  functions: Preparing to emulate functions.
[2018-08-08T22:15:02.007Z] Fetching environment
[2018-08-08T22:15:02.008Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/paymenttoy

 Wed Aug 08 2018 15:15:02 GMT-0700 (PDT)
[2018-08-08T22:15:02.404Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Wed, 08 Aug 2018 22:15:02 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-08-08T22:15:02.405Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/473127682708:getServerAppConfig

 Wed Aug 08 2018 15:15:02 GMT-0700 (PDT)
[2018-08-08T22:15:02.699Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Wed, 08 Aug 2018 22:15:02 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-08-08T22:15:02.699Z] Starting @google-cloud/functions-emulator
[2018-08-08T22:15:02.736Z] Parsing function triggers
[2018-08-08T22:15:02.836Z] Deploying functions locally
[2018-08-08T22:15:02.877Z] Error while deploying to emulator: Error
Error
    at RequestError.Error (native)
    at new RequestError (/Users/ppannuto/.nvm/versions/v6.11.5/lib/node_modules/firebase-tools/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/Users/ppannuto/.nvm/versions/v6.11.5/lib/node_modules/firebase-tools/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:96:27)
    at Request.self.callback (/Users/ppannuto/.nvm/versions/v6.11.5/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ppannuto/.nvm/versions/v6.11.5/lib/node_modules/firebase-tools/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ppannuto/.nvm/versions/v6.11.5/lib/node_modules/firebase-tools/node_modules/request/request.js:1079:12)
⚠  functions: Failed to emulate onUserCreate
i  functions: No functions to emulate.
No functions emulated.
```

----

n.b. This is a reduced MWE. I am unable to emulate any functions from any projects, but the error is always the same.

This environment works fine for `firebase serve --only functions` or `firebase deploy` or any other firebase methods.

**Comment by laurenzlong** [comment]
Hi this sounds like the same issue as https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/179. It seems like may be caused by being behind a proxy? Please follow along on that issue.
