### ISSUE TITLE
cannot use firebase-tools in cloud function

### ISSUE THREAD

**Issue by wwwy3y3** [firebase/firebase-tools#884]
### Version info
4.0.2

### Platform Information
on Firebase cloud function

### Steps to reproduce
I use `firebase-tools` in cloud function to automatically deploy my hosting files.
```js
const client = require('firebase-tools');
client.deploy({
      project: process.env.GCLOUD_PROJECT,
      token: <firebase token>,
      cwd: <path to hosting folder>
    });
```

I encountered following error. Does it mean `admin.firebase.com` is considered external network and I have to use paid plan to use `firebase-tools` in cloud function?
```
{ Error
    at Error.FirebaseError (/user_code/node_modules/firebase-tools/lib/error.js:11:16)
    at Request._callback (/user_code/node_modules/firebase-tools/lib/api.js:34:11)
    at self.callback (/user_code/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1040:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'FirebaseError',
  message: 'Server Error. getaddrinfo ENOTFOUND admin.firebase.com admin.firebase.com:443',
  children: [],
  status: 500,
  exit: 2,
  stack: 'Error\n    at Error.FirebaseError (/user_code/node_modules/firebase-tools/lib/error.js:11:16)\n    at Request._callback (/user_code/node_modules/firebase-tools/lib/api.js:34:11)\n    at self.callback (/user_code/node_modules/firebase-tools/node_modules/request/request.js:185:22)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at Request.onRequestError (/user_code/node_modules/firebase-tools/node_modules/request/request.js:881:8)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at TLSSocket.socketErrorListener (_http_client.js:310:9)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1040:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)',
  original: 
   { Error: getaddrinfo ENOTFOUND admin.firebase.com admin.firebase.com:443
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'admin.firebase.com',
     host: 'admin.firebase.com',
     port: 443 },
  context: undefined }
```

**Comment by laurenzlong** [comment]
Yes that is correct, only URLs that are xxx.googleapis.com are considered within the Google network.

**Comment by laurenzlong** [comment]
`admin.firebase.com` is a legacy endpoint, and we are going to be removing it as a dependency for the CLI in the future.

**Comment by wwwy3y3** [comment]
@laurenzlong Is there any workaround I can deploy hosting files within the Google network?

**Comment by mbleigh** [comment]
You can upgrade your plan to blaze, which will unrestrict the network.

**Comment by wwwy3y3** [comment]
@mbleigh I mean other than upgrading my plan, is there endpoint in Google network I can deploy my hosting files to?

**Comment by laurenzlong** [comment]
@wwwy3y3 No, there's no other way. Upgrading your plan does not mean that you will get charged, if you keep outbound data transfer under 5 GB per month it's still free. See the pricing calculator: https://firebase.google.com/pricing/
