### ISSUE TITLE
Suddenly unable to deploy function due to missing dependency

### ISSUE THREAD

**Issue by codmajik** [firebase/firebase-tools#920]
I am not able to deploy update to my cloud functions. its complaining of not being able to load a dependency (pdfkit2) which was in the earlier version and was working fine.

```
Function load error: Code in file lib/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'pdfkit2'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/lib/index.js:16:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

### Version info
4.2.1

Microsoft Linux (WSL)

**Comment by laurenzlong** [comment]
To confirm, is "pdfkit2" listed in your package.json?

**Comment by codmajik** [comment]
yes

**Comment by laurenzlong** [comment]
Can you also run "npm install" inside your functions folder?

If that  fails to work, could you share the 'dependencies' part of functions/package.json, and also the part in the code where you are importing "pdfkit2"?

**Comment by laurenzlong** [comment]
Also, the package.json file has to be in your functions folder, having it in a directory above won't work.

**Comment by codmajik** [comment]
closing this. I switched to `pdfmake`

**Comment by laurenzlong** [comment]
Thanks for the update!
