### ISSUE TITLE
Problems when trying to init a project

### ISSUE THREAD

**Issue by paulogr** [firebase/firebase-tools#952]
Hi, I've just created a new firebase project and when trying to init using firebase-tools I have the following error:

```
[debug] [2018-10-15T21:31:35.519Z] <<< HTTP RESPONSE 200
[debug] [2018-10-15T21:31:37.896Z] TypeError: Cannot read property 'instances' of undefined
    at /Users/paulogr/.nvm/versions/node/v10.12.0/lib/node_modules/firebase-tools/lib/init/features/project.js:88:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
```

As you can see I'm using the latest node version.

Thanks

**Comment by mbleigh** [comment]
Will be fixed by #953, sorry about that!
