### ISSUE TITLE
Error on Deploy

### ISSUE THREAD

**Issue by woniel123mx** [firebase/firebase-tools#972]
### Version info
3.19.1

### Platform Information
Windows

### Steps to reproduce
 Firebase deploy

### Actual behavior
Crash jaja

**Comment by mbleigh** [comment]
Please upgrade to the latest version of `firebase-tools`.

**Comment by woniel123mx** [comment]
this is log.

[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2018-10-25T23:56:15.384Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/project-6998102911132998759?view=CONSUMER_VIEW  
  
 Thu Oct 25 2018 18:56:15 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:15.385Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/project-6998102911132998759?view=CONSUMER_VIEW  
  
 Thu Oct 25 2018 18:56:15 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:16.384Z] <<< HTTP RESPONSE 200
[debug] [2018-10-25T23:56:16.531Z] <<< HTTP RESPONSE 200
[info] +  functions: all necessary APIs are enabled
[debug] [2018-10-25T23:56:16.533Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/project-6998102911132998759  
  
 Thu Oct 25 2018 18:56:16 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:17.228Z] <<< HTTP RESPONSE 200
[debug] [2018-10-25T23:56:17.229Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/294805556905:getServerAppConfig  
  
 Thu Oct 25 2018 18:56:17 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:17.758Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2018-10-25T23:56:17.764Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-6998102911132998759/configs  
  
 Thu Oct 25 2018 18:56:17 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:18.503Z] <<< HTTP RESPONSE 200
[info] i  hosting: preparing dist directory for upload...
[debug] [2018-10-25T23:56:19.577Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/project-6998102911132998759/uploads/-LPhe2urtx4J9w8bipR4?fileCount=71&message=  
  
 Thu Oct 25 2018 18:56:19 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:27.573Z] <<< HTTP RESPONSE 410
[debug] [2018-10-25T23:56:27.573Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-10-25T23:56:27.575Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:10:13)
    at Request._callback (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:47:25)
    at Request.self.callback (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.

**Comment by woniel123mx** [comment]
i  functions: ensuring necessary APIs are enabled...
[debug] [2018-10-25T23:56:15.384Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/project-6998102911132998759?view=CONSUMER_VIEW  
  
 Thu Oct 25 2018 18:56:15 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:15.385Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/project-6998102911132998759?view=CONSUMER_VIEW  
  
 Thu Oct 25 2018 18:56:15 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:16.384Z] <<< HTTP RESPONSE 200
[debug] [2018-10-25T23:56:16.531Z] <<< HTTP RESPONSE 200
[info] +  functions: all necessary APIs are enabled
[debug] [2018-10-25T23:56:16.533Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/project-6998102911132998759  
  
 Thu Oct 25 2018 18:56:16 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:17.228Z] <<< HTTP RESPONSE 200
[debug] [2018-10-25T23:56:17.229Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/294805556905:getServerAppConfig  
  
 Thu Oct 25 2018 18:56:17 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:17.758Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2018-10-25T23:56:17.764Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/project-6998102911132998759/configs  
  
 Thu Oct 25 2018 18:56:17 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:18.503Z] <<< HTTP RESPONSE 200
[info] i  hosting: preparing dist directory for upload...
[debug] [2018-10-25T23:56:19.577Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/project-6998102911132998759/uploads/-LPhe2urtx4J9w8bipR4?fileCount=71&message=  
  
 Thu Oct 25 2018 18:56:19 GMT-0500 (Hora de verano central (México))
[debug] [2018-10-25T23:56:27.573Z] <<< HTTP RESPONSE 410
[debug] [2018-10-25T23:56:27.573Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-10-25T23:56:27.575Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:10:13)
    at Request._callback (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:47:25)
    at Request.self.callback (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\woniel123mx\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.
