### ISSUE TITLE
Firebase hosting deploy resulting in 410

### ISSUE THREAD

**Issue by filipemir** [firebase/firebase-tools#979]
### Version info
3.18.4

### Platform Information
OSX

### Steps to reproduce
Just ran the `firebase deploy` command as I've done before

### Expected behavior
It should deploy my build

### Actual behavior
```
[debug] [2018-10-28T12:11:19.828Z] ----------------------------------------------------------------------
[debug] [2018-10-28T12:11:19.829Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --only hosting -P stg
[debug] [2018-10-28T12:11:19.830Z] CLI Version:   3.18.4
[debug] [2018-10-28T12:11:19.830Z] Platform:      darwin
[debug] [2018-10-28T12:11:19.830Z] Node Version:  v8.9.1
[debug] [2018-10-28T12:11:19.830Z] Time:          Sun Oct 28 2018 08:11:19 GMT-0400 (EDT)
[debug] [2018-10-28T12:11:19.830Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-10-28T12:11:19.840Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-10-28T12:11:19.840Z] > authorizing via signed-in user
[debug] [2018-10-28T12:11:19.842Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/stonybrook-strings-stg  
  
 Sun Oct 28 2018 08:11:19 GMT-0400 (EDT)
[debug] [2018-10-28T12:11:20.208Z] <<< HTTP RESPONSE 200
[debug] [2018-10-28T12:11:20.209Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/stonybrook-strings-stg/tokens  
  
 Sun Oct 28 2018 08:11:20 GMT-0400 (EDT)
[debug] [2018-10-28T12:11:20.463Z] <<< HTTP RESPONSE 200
[warn] ⚠  functions: package.json indicates an outdated version of firebase-functions.
 Please upgrade using npm install --save firebase-functions@latest in your functions directory.
[info] 
[info] === Deploying to 'stonybrook-strings-stg'...
[info] 
[info] i  deploying hosting
[info] i  hosting: preparing public directory for upload...
[debug] [2018-10-28T12:11:26.446Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/stonybrook-strings-stg/uploads/-LPu_S164jBi7I-7BGIL?fileCount=597&message=  
  
 Sun Oct 28 2018 08:11:26 GMT-0400 (EDT)
[debug] [2018-10-28T12:11:31.470Z] <<< HTTP RESPONSE 410
[debug] [2018-10-28T12:11:31.471Z] <<< HTTP RESPONSE BODY undefined
[debug] [2018-10-28T12:11:31.472Z] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:47:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
[error] 
[error] Error: An unexpected error has occurred.

```

**Comment by mbleigh** [comment]
Please upgrade to the latest version of the Firebase CLI.

    npm install -g firebase-tools

**Comment by filipemir** [comment]
I'm so sorry. I thought I had done so already but turns out I had just accidentally upgraded `firebase-functions`. Works fine now. Thanks for the quick response.
