### ISSUE TITLE
Functions did not deploy properly - Cannot find module './clone.js'

### ISSUE THREAD

**Issue by 39ro** [firebase/firebase-tools#994]
Not really able to identify this error. My cloud functions are not anymore deploying!
Cannot find module './clone.js'

```
⚠  functions[healthcheck(us-central1)]: Deployment error.
Function load error: Code in file build/src/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._resolveFilename (/user_code/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

```

### Version info
6.0.1

### Platform Information
Linux 
### Steps to reproduce

1. tsc
2. firebase deploy --only functions:healthcheck 

### Expected behavior
Successfully deploy my cloud function.

### Actual behavior
Fail to deploy my cloud function.

```
[2018-11-02T23:12:04.398Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 02 Nov 2018 23:12:04 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-02T23:12:06.403Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/operations/YnVua2FwcHRlc3QvdXMtY2VudHJhbDEvaGVhbHRoY2hlY2sveDZfMzdBak15eE0  
 
[2018-11-02T23:12:06.646Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 02 Nov 2018 23:12:06 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-02T23:12:08.650Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/operations/YnVua2FwcHRlc3QvdXMtY2VudHJhbDEvaGVhbHRoY2hlY2sveDZfMzdBak15eE0  
 
[2018-11-02T23:12:08.863Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 02 Nov 2018 23:12:08 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
⚠  functions[healthcheck(us-central1)]: Deployment error.
Function load error: Code in file build/src/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._resolveFilename (/user_code/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

```

**Comment by mbleigh** [comment]
See https://github.com/isaacs/node-graceful-fs/issues/139

A very common Node.js dependency pushed a bad version.
